### ISSUE TITLE
I have somehow now 3 organizations from Github in my Snyk.io dashboard

### ISSUE THREAD

**Issue by SeppPenner** [snyk/snyk#1003]
I have linked snyk to my github profile. Afterwards, I wanted to remove some projects (And didn't want to do that manually one by one). Therefore, I removed the snyk integration and added it again. Now I have 3 different profiles in the snyk dashboard:

![image](https://user-images.githubusercontent.com/9639361/74442019-0cb9de00-4e71-11ea-8af4-b902ac69737d.png)

It seems that the organization is not deleted when you remove the integration from Github and add it again but a new organization is created.

@lili2311: I don't know if this is a bug or desired, but is there a possibility for you guys (or some admin) to delete my organization(s) except the one with id `642dfd66-af3d-4728-a9fd-1f72007c09ac`?

**Comment by lili2311** [comment]
Hi @SeppPenner did you receive a support case for this? It would be best handled via email with engineers on call

**Comment by SeppPenner** [comment]
Hi @lili2311. Actually not. How do I even get one? :D

**Comment by SeppPenner** [comment]
Hi @lili2311. I have now created a support case / taken contact via your form under https://snyk.io/contact-us/. Let's see if they can fix it :)
