### ISSUE TITLE
[🐛] --all-projects ignores snyk policy files in individual project directories.

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#1014]
- `node -v`: v13.3.0
- `npm -v`:6.13.1
- `snyk -v`:1.294.1
- OS: (e.g. OSX, Linux, Windows, ...) windows
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)

```
snyk test --all-projects
```

### Expected behaviour
for each project snyk will use the snyk policy file in the project directory, not the one in the current workingdirectory. Or, even better, snyk combines the policies.

### Actual behaviour
when the layout is as follows:

```
root
+ src
  + projectA
      .snyk
  + projectB
     .snyk
```

and snyk is called as follows:

```
.\root > snyk test --all-projects
```

the snyk policy files are ignored.

**Comment by dkontorovskyy** [comment]
Hello @jessehouwing! Thanks for submitting the issue. We are looking in it now and will update you ASAP.
Best Daniel

**Comment by lili2311** [comment]
This has been fixed & is releasing now. Please confirm this works as expected for you.

**Comment by lili2311** [comment]
Released :) Let me know if I can close this

**Comment by lili2311** [comment]
Closing the issue, please re-open if needed.
