### ISSUE TITLE
display Snyk findings in Jenkins 

### ISSUE THREAD

**Issue by ennef** [snyk/snyk#102]
- `node -v`: `v6.7.0`
- `npm -v`: `3.10.3`
- `snyk -v`: `1.40.0`
- Command run: `snyk test --outputFormat json --outputFile snyk.json`

### Expected behaviour
In a CI pipeline, I would like to display the Snyk findings on the Jenkins job. This could be possible with the Warnings plugin, a custom warnings parser and Snyk reporting the findings to a structured file.

Is it possible to generate the Snyk report as `json`? Are there plans to support this use-case?

### Actual behaviour
N/A

### Steps to reproduce
N/A

**Comment by darscan** [comment]
Hi. You can use `snyk test --json` to get JSON output.

Or, to dump that into a file: `snyk test --json > snyk.json`

**Comment by ennef** [comment]
Thanks, that is what I was looking for!
