### ISSUE TITLE
[🐛] json log can't be parsed when an exception happens during `snyk test`

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#1027]
+ snyk-to-html@1.7.2
+ snyk@1.297.1

- OS: (e.g. OSX, Linux, Windows, ...) Windows 
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)

```
snyk test --all-projects --exclude=project.json --json
```
The project has both .NET Core and NPM files, at this time we're only interested in the .NET Core ones and are explicitly ignoring `project.json`.

### Expected behaviour
json log is actually of type JSON and can be parsed as such

### Actual behaviour

The report includes a stack trace and can't be parsed. See below:

![image](https://user-images.githubusercontent.com/4173387/75362630-5535ba80-58b9-11ea-849c-2a25d4f3914b.png)

[report-2020-02-26T15-12-45.zip](https://github.com/snyk/snyk/files/4256723/report-2020-02-26T15-12-45.zip)

**Comment by jessehouwing** [comment]
I'm guessing the issue is due to the fact that only output is redirected and error isn't. err follows output if not explicitly redirected:

![image](https://user-images.githubusercontent.com/4173387/75364338-de4df100-58bb-11ea-8f0b-8ab619e5989a.png)

**Comment by jessehouwing** [comment]
It also fails when `--debug` is enabled, since all debug data is added to the json as plain text.

**Comment by jessehouwing** [comment]
It's probably useful to just redirect the err stream explicitly to `console.err` or `console.out`.

**Comment by lili2311** [comment]
👋 We should we redirecting errors to err stream, will check why this is not happening in this case

**Comment by jessehouwing** [comment]
Cause it's not specified explicitly. The Task SDK has a "useful" feature to redirect that to stdOut if not specified and stdOut *is* redirected.

**Comment by maxjeffos** [comment]
Thanks @jessehouwing . The errors and debug info from the Snyk CLI are indeed being redirected  to stderr so this is a thing we will tackle in the Azure extension (as opposed to here in the Snyk CLI). I'll follow up with you there with a PR and then close the loop here once that's done.

**Comment by lili2311** [comment]
Is this still an issue?

**Comment by jessehouwing** [comment]
Yeah. The --json-file-output will fix this for sure.

**Comment by maxjeffos** [comment]
I merged https://github.com/snyk/snyk/pull/1107 which adds the `--json-file-output=<file>` option. 
Will create a PR for the Azure Extension to use it @jessehouwing.

**Comment by maxjeffos** [comment]
Fixed with https://github.com/snyk/snyk/pull/1107 and https://github.com/snyk/snyk-azure-pipelines-task/issues/30
