### ISSUE TITLE
[🐛] `snyk monitor` error

### ISSUE THREAD

**Issue by theonewolf** [snyk/snyk#1040]
- `node -v`: v10.15.2
- `npm -v`: 6.13.4
- `snyk -v`: 1.298.1
- OS: Ubuntu 19.10 Server
- Command run: `snyk monitor`

### Expected behaviour

I expect to get a URL to view my report.

### Actual behaviour

```
> snyk monitor

Monitoring /home/wolf/........

undefined
```

### Steps to reproduce

`snyk auth ....`
`snyk monitor`

### Debug log

```
> snyk -d monitor
  snyk monitor { _: [ [Circular] ], debug: true } +0ms
  snyk Processing /home/wolf/......... +0ms
  snyk getDepsFromPlugin ... +9ms
Error: 
Monitoring /home/wolf/........

undefined
    at /usr/local/lib/node_modules/snyk/src/cli/commands/monitor/index.ts:226:9
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/snyk/dist/cli/commands/monitor/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  snyk analytics { args: [ { debug: true } ],
  command: 'bad-command',
  org: undefined,
  metadata:
   { pluginOptions: { debug: true },
     'error-message': '\nMonitoring /home/.......\n\nundefined',
     error:
      'Error: \nMonitoring /home/...........\n\nundefined\n    at /usr/local/lib/node_modules/snyk/src/cli/commands/monitor/index.ts:226:9\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/local/lib/node_modules/snyk/dist/cli/commands/monitor/index.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     'error-code': undefined,
     command: 'monitor' },
  version: '1.298.1',
  os: 'Linux 5.3',
  nodeVersion: 'v10.15.2',
  id: '500b732e07ca9f46b08a80e427d94a5748252e49',
  ci: false,
  durationMs: 193 } +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 685 +0ms
  snyk gzipped request body size: 409 +0ms
  snyk not using proxy +0ms
```

**Comment by lili2311** [comment]
👋 could you please share steps to replicate? What is in the folder you are running `snyk monitor` in? Can you share a stripped down version to replicate. Also could you please try with Node 8? We no longer support Node 6 actively

**Comment by johsim** [comment]
I am seeing this issue as well, but only for our python (pip) projects.

**Comment by theonewolf** [comment]
I may have had this issue because the VM I executed on didn't have enough
memory (0.5 GiB).

**Comment by firecode9** [comment]
@theonewolf 
Hi, 
1. Are you still seeing this issue ?
2. Can you share with us the manifest files?

**Comment by theonewolf** [comment]
Not when I gave the system more RAM, something like 2-4 GiB.

**Comment by theonewolf** [comment]
I didn't destroy that VM, so I may be able to share manifest files.  How do I do that?  Any specific command to run to dump them?

**Comment by dkontorovskyy** [comment]
This issue is related to low RAM memory. I assume as you said that bumping your RAM size fixes the issue. Can I close the issue now?

**Comment by theonewolf** [comment]
@dkontorovskyy I'm fine with closing.

**Comment by dkontorovskyy** [comment]
@theonewolf glad this worked for you 🤗
