### ISSUE TITLE
[🐛]

### ISSUE THREAD

**Issue by Alfian878787** [snyk/snyk#1058]
- `node -v`:
- `npm -v`:
- `snyk -v`:
- OS: (e.g. OSX, Linux, Windows, ...)
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)

### Expected behaviour
Please share _expected_ behaviour.

### Actual behaviour
Please share _problematic_ behaviour you are seeing.

### Steps to reproduce
Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testsing.

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

### Screenshots
.github/CONTRIBUTING.md

**Comment by Alfian878787** [comment]
@edwardgeorge @remy @gablaxian @https://github.com/snyk/snyk/issues/1058#issue-588489567

**Comment by dkontorovskyy** [comment]
@Alfian878787 can you please add the info so we can look into your issue. Please use the template above. Thanks

**Comment by dkontorovskyy** [comment]
Closing this ticket, cos there is no information about the issue. Can reopen if @Alfian878787 files the template.
