### ISSUE TITLE
scripts/postinstall: "npm run snyk-protect" resulting in "missing node_modules folder" error

### ISSUE THREAD

**Issue by ryan-kimber** [snyk/snyk#106]
- `node -v`: 6.11.1
- `npm -v`:  3.10.10 & 5.4.2 (tried both)
- `snyk -v`: 1.41.1
- Command run: npm install @formhero/fh-build-reporter (private module with .snyk file and post-install command

### Expected behaviour
I expect that Snyk will read the .snyk file in the module's folder and apply the patches during the post-install step

### Actual behaviour
Post install step fails with:
![screen shot 2017-10-01 at 10 23 16 pm](https://user-images.githubusercontent.com/1018189/31062247-26e7e692-a6f7-11e7-8266-381bf87ef05b.png)

Perhaps I'm doing something wrong. Here's the scripts section of my package.json for the fh-build-reporter:

![screen shot 2017-10-01 at 10 23 45 pm](https://user-images.githubusercontent.com/1018189/31062265-4a46f740-a6f7-11e7-9b78-8bac539e0103.png)

#################

Any guidance would be tremendously appreciated! Thanks.

**Comment by ryan-kimber** [comment]
Another illustration:

![screen shot 2017-10-01 at 11 36 20 pm](https://user-images.githubusercontent.com/1018189/31063495-6418d4cc-a701-11e7-8cd3-8fb81d7d64ae.png)

**Comment by adrukh** [comment]
@ryan-kimber having `npm run snyk-protect` as a `prepublish` target is sufficient. Please remove the `postinstall` target you have.

See https://docs.npmjs.com/misc/scripts for more details, this gets a bit messy.

Short story:
- `prepublish` also runs after `npm install`, and will apply Snyk patches to any relevant dependencies.
- with npm@5, `prepublish` changes its behaviour, and the right target for `snyk protect` becomes `prepare`. Our CLI detects this - if npm@5 is used, `snyk protect` will run on `prepare`.

Let me know if this helps!

**Comment by ryan-kimber** [comment]
Thanks! This fixed my issue.

If the documentation at https://snyk.io/docs/using-snyk/ (search for
postinstall) had a link to how npm scripts should be configured for the
different versions of NPM, it would be really helpful. I took the current
documentation literally, expecting that it's 'postinstall' that should be
executing the hook.

Thanks again!

**Comment by adrukh** [comment]
Great suggestion, thanks!
