### ISSUE TITLE
[🐛] Cannot install with yarn on node 8 - says min. required is node 10

### ISSUE THREAD

**Issue by Asvarox** [snyk/snyk#1060]
- `node -v`: v8.17.0
- `npm -v`: 6.13.4
- `snyk -v`: 1.305.0
- `yarn -v`: 1.22.0
- OS: OSX
- Command run: `yarn add snyk`

### Expected behaviour
snyk should install just fine (I presume so since `package.json` says it requires node >= 8)

### Actual behaviour
Following error occurs:
```
yarn add v1.22.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @snyk/ruby-semver@2.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Steps to reproduce
1. Make sure you're on Node 8
2. `yarn init -y`
3. `yarn add snyk`

It's possible to mitigate the problem by adding `--ignore-engines` flag. 

Wasn't sure if I should post it here or direcrly to snyk/ruby-semver though the other repo has no issues reported (opened nor closed)

**Comment by lili2311** [comment]
👋 This should be fixed from version `1.310.1`
