### ISSUE TITLE
Snyk Web Console unaware of over-ridden dependencies for pom.xml (local snyk test passes, but web shows 7 vulnerabilities)

### ISSUE THREAD

**Issue by ryan-kimber** [snyk/snyk#107]
- `node -v`: 6.11.1
- `npm -v`: 3.10.10
- `snyk -v`: 1.41.1
- Command run:  'snyk test' against Java project / pom.xml

### Expected behaviour
We have a dependency on Google Cloud Storage, version 1.6.0, which has a transitive dependency on the Apache Commons HttpClient 4.0.1 and other out of date libraries. 

By over-riding adding an explicit dependency on HttpClient 4.5 (and similarly overriding the XML bindings libraries) I am effectively patching the vulnerability, and 'snyk test' passes. 

I expect that the web console would also recognize that we have removed the vulnerability.

### Actual behaviour
The web console still shows 7 'medium' vulnerabilities.

### Steps to reproduce
1) Create a pom.xml with the following dependencies in it: 

```xml
      <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.7</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.8.9</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
            <version>1.6.0</version>
        </dependency>
```
---

2) Try 'snyk test' locally, and it should be happy that the installed .jars have not issues.
3) Check out what the Snyk Web Console shows for the git repo: it should show several vulnerabilities related to httpclient:4.0.1 and an earlier version of com.fasterxml.jackson.core.

**Comment by adrukh** [comment]
@ryan-kimber thanks for raising this!

There is an inherent difference between our dependency processing with the CLI (relies directly on `mvn`) and our web offering. We will handle this via the support ticket you opened and try to bring our web results to the ones shown by the CLI.

I'll post an update here once we have a resolution or a clear statement about feasibility for this issue on our web offering.

**Comment by adrukh** [comment]
Sorry, I wasn't seeing straight and thought you already opened a support ticket for this. :)
Can you please email support@snyk.io mentioning this issue, we'll take it from there.

**Comment by ksclarke** [comment]
Hi, are Snyk support tickets open? I'm trying out Snyk and noticed this discrepancy and am wondering the best place to track its resolution. Here? By following a Snyk support ticket?

The support link on the Snyk website is a mailto link and it wasn't obvious to me where the tickets would be if they are openly tracked. Thanks!

**Comment by adrukh** [comment]
@ksclarke we are using a combination of GH issues and an internal tracking tool for support cases.

GH issues on snyk/snyk are best used for issues with specific reference to our CLI, discussing PRs and such.

A discrepancy such as the one you describe is best handled with support@snyk.io where you can be more specific about the related project etc. Please email support@snyk.io and we'll take it from there.

I'll also add that we are constantly working on minimizing the gaps between dependencies detected by our CLI and by our back-end processing. A support ticket on every such issue will be very helpful!

**Comment by ksclarke** [comment]
I'm curious about this being closed. I see the issue still (which is why I responded to this ticket). I will submit an additional ticket to support@snyk since I can't tell whether ryan-kimber ever did, but it seems like this should stay open until the issue is resolved?

**Comment by maban** [comment]
@ksclarke my mistake, reopening.

**Comment by GuiSim** [comment]
We are facing a similar problem but with Gradle instead of Maven.

Any progress on this issue in the last months?

**Comment by ksclarke** [comment]
It does seem fixed for Maven. Thanks!
