### ISSUE TITLE
vuln.upgradePath.some is not a function

### ISSUE THREAD

**Issue by IanVS** [Snyk/snyk#11]
Using: 
snyk@dev (1.9.0-alpha3) 
npm@3.5.3
node@5.3.0

I get the following after running through the wizard and choosing `upgrade` for each vulnerability:

```
vuln.upgradePath.some is not a function
```

There is no stack trace.

Subsequently, if I run `snyk test`, I see just as many vulnerabilities detected as before running the wizard.

**Comment by remy** [comment]
Can you run with `-d` as an argument in the wizard and paste the output? It'll give us the stack trace plus some of the data being sent. If you're worried about any private details being leaked (or package names, etc) you can email me at support@snyk.io and I can follow up there.

– Remy

**Comment by IanVS** [comment]
OK, email sent.  Thanks.

**Comment by remy** [comment]
Hi @IanVS we actually found that this specific error was related to the server and not the alpha version of the snyk cli. As a result, the fix has been deployed to live, and you should be able to re-run the wizard without an update and it _should_ work.

If you could let me know how you get on I'd appreciate it.

Cheers,

– Remy
