### ISSUE TITLE
Better support and badges for polyglot repositories

### ISSUE THREAD

**Issue by scottohara** [snyk/snyk#111]
I have a repository that include both Rails code (backend API) and Javascript code (frontend UI).

The repo has both a `Gemfile` and a `package.json`.

After setting up Github integration, I added the project to Synk, which defaulted to monitoring only the `package.json` file.

I was able to manually add the `Gemfile` by adding the project a second time, and choosing the "Add custom file location..." option, specifying `Gemfile.lock` for the file path.

This works fine, however it would be awesome if Snyk could auto-detect & monitor both manifest files as part of a single "project".

I'm now adding a badge to my README, but it seems that I can only add a badge for the `package.json`.

The image at `https://snyk.io/test/github/{username}/{repo}/badge.svg`  displays `[Vulnerabilities][4]` (which is the current number of npm vulnerabilities).

For the `Gemfile` vulnerabilities, I attempted `https://snyk.io/test/github/{username}/{repo}:Gemfile.lock/badge.svg` (matching the format of the name for the project on the dashboard), but that doesn't seem to work.

Is there a way to generate a Github badge for projects that use a custom manifest file location?

**Comment by adrukh** [comment]
@scottohara we need to do a better job documenting this, as this already exists with the help of a query param. Try `https://snyk.io/test/github/{username}/{repo}/badge.svg?targetFile={path-to-target-file}`, for example:

https://snyk.io/test/github/snyk-fixtures/monorepo-simple/badge.svg would be identical to https://snyk.io/test/github/snyk-fixtures/monorepo-simple/badge.svg?targetFile=package.json, but different from https://snyk.io/test/github/snyk-fixtures/monorepo-simple/badge.svg?targetFile=Gemfile.lock

Hope this helps!

**Comment by scottohara** [comment]
Fantastic.  Works perfectly.

Thanks @adrukh !
