### ISSUE TITLE
[🙏] snyk test shouldn't be dependent from source code

### ISSUE THREAD

**Issue by goemon07** [snyk/snyk#1127]
- `Language / Project Type:` GoLang
- `Package Manager / Build Tool:` Go Modules

**Describe the user need**

I want to be able to run `snyk test` without being dependent on the source code (actually the `import` section ) but only from the `go.mod` file. 

**Describe expected behaviour**

If I'm in a folder with just a `go.mod` file, the scan will go smoothly as it happens for `snyk monitor`, which takes into consideration only the module file. 

**Additional context**

Testing only the `go.mod` file without source code contained in the same directory always gives back a useless result:
![image](https://user-images.githubusercontent.com/17404386/82316555-a5fb1200-99d5-11ea-9ca2-02f3e5c569c2.png)

**Comment by lili2311** [comment]
👋 Unfortunately `go.mod` is not enough information to understand the dependencies. The vulnerabilities exists in packages not modules, so we have to understand what packages are used by your project. To do that we would need a combination of understanding what is in each module that you require and what is being used. We also need to understand what transitive dependencies are being pulled in by each dependency to give an accurate representation of your dependencies.

**Comment by lili2311** [comment]
Does the above answer your question?

**Comment by goemon07** [comment]
Yes. Thanks and sorry for the late reply.
