### ISSUE TITLE
CLI error when testing multiple projects

### ISSUE THREAD

**Issue by mhh** [snyk/snyk#113]
- `node -v`: `v8.9.0`
- `npm -v`: `3.10.10`
- `snyk -v`: `1.53.0`
- Command run: `snyk test a b`

### Expected behaviour

snyk should test 2 projects, `a` and `b`, and print the results of each test and a summary:

```
Testing a...
✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

Testing b...
✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

Tested 2 projects, no vulnerable paths were found.
```

### Actual behaviour

snyk prints: `Cannot read property 'length' of undefined` and exits with error code 1.

### Steps to reproduce

1. `mkdir a b`
1. `cd a`
1. `npm init` (take defaults to get a basic `package.json`)
1. `npm install`
1. `cd ../b`
1. `npm init` (take defaults to get a basic `package.json`)
1. `npm install`
1. `cd ..`
1. `snyk test a b`

---

### Further details

Here's the relevant bit of debug output + stack trace:

```
  snyk:spinner clearing Querying vulnerabilities database... (0) +2ms
  snyk add +0ms error-message Cannot read property 'length' of undefined
  snyk add +0ms error TypeError: Cannot read property 'length' of undefined
    at ...\node_modules\snyk\cli\commands\test.js:131:42
```

It looks like this is happening because when testing multiple projects, there is a code path which [produces a summary string](https://github.com/snyk/snyk/blob/633ecd123d8297d1bdf1e29baf3fde9fa562cbef/cli/commands/test.js#L36-L87) from each individual test result object.  However, further along in the promise chain, there is a handler which [still expects to be dealing with a test result object](https://github.com/snyk/snyk/blob/633ecd123d8297d1bdf1e29baf3fde9fa562cbef/cli/commands/test.js#L95-L254).

**Comment by maban** [comment]
Hi @mhh, thanks for reporting this, and for all the useful information. We're going to have a look into this and get back to you.

**Comment by mhh** [comment]
Sounds good.  Thanks, @maban! 👍

**Comment by maban** [comment]
Ok, I've done some investigating and ran this all locally. I think the problem is to do with the format of one of the package.json files, because I was able to run the multiple project test with my own projects.

I followed your instructions and was able to reproduce the error when testing a and b together. They both passed individually. However, if I then added a dependency to one of the packages, they were both able to run at the same time.

Does one of these packages not contain any dependencies? Perhaps only dev dependencies?

**Comment by mhh** [comment]
Ah, yes, that is indeed the case.  One of them has 0 dependencies and multiple devDependencies; the other has several of both types.

**Comment by mhh** [comment]
Yep, easy enough to work around for now.

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.

Please re-try with the latest version of CLI and let us know if this is still a problem.
