### ISSUE TITLE
[🙏] Separate exit code when no project has been found

### ISSUE THREAD

**Issue by defsprite** [snyk/snyk#1135]
- `Language / Project Type: all/none` 
- `Package Manager / Build Tool: n/a`

**Describe the user need**
For easier use of snyk CLI in generic CI pipelines it would be a great addition to have a separate exit code for "no project found" from an actual error running snyk. At this point there is extra output parsing required to tell whether there is an actual error or no manifest files have been found. 

**Describe expected behaviour**

When there are no manifest files found that are parseable by snyk, exit with any other exit code higher than `2`.

**Comment by lili2311** [comment]
👋 @defsprite Could you please expand on "No projects found", are you referring to `Could not detect supported target files....` message? In what situation does your configured pipeline have no projects?

**Comment by defsprite** [comment]
We run the snyk CLI as part of generic security tooling against every repository.
For some repositories, there are no target files detectable. snyk then bails out with the same error as it does with an actual error running. 

It would be easier for our "wrapper script" if we could tell the two cases apart by the exit code of snyk.

**Comment by lili2311** [comment]
@defsprite we have a releases a new CLI version `1.389.0` that will use exit code `3` when no supported projects/manifests are detected.

**Comment by defsprite** [comment]
🎉 Excellent! Thank you very much! Pinging @marklechner that this has been implemented.
