### ISSUE TITLE
[🐛] snyk-docker: Failed to test undefined project (distroless image)

### ISSUE THREAD

**Issue by HannesBBR** [snyk/snyk#1144]
- `node -v`: v13.10.1
- `npm -v`: 6.13.7
- `snyk -v`: 1.328.0
- OS: (e.g. OSX, Linux, Windows, ...) Mac + Linux
- Command run: `snyk test -d --docker <image-url> --file=Dockerfile`

Docker base image used: 
`gcr.io/distroless/java:11-debug`

### Expected behaviour
No error returned. Container-scanning results returned.

### Actual behaviour
Error message `Failed to test undefined project`. This started happening 4 days ago, presumable something in the baseimage `gcr.io/distroless/java:11-debug` changed, but this should imo not result in snyk crashing without context.

### Steps to reproduce
Do `snyk test -d --docker gcr.io/distroless/java:11-debug`
Note that the same command works as expected for `gcr.io/distroless/java:11`

### Debug log
``` snyk test <ref *1> {
  _: [
    'gcr.io/distroless/java:11-debug',
    [Circular *1]
  ],
  debug: true,
  docker: true,
  file: 'Dockerfile'
} +0ms
  snyk Error running test {
  error: {
    stdout: '',
    stderr: 'rpm: unrecognized option: -\n' +
      'BusyBox v1.31.0 (2019-06-10 15:54:54 CEST) multi-call binary.\n' +
      '\n' +
      'Usage: rpm -i PACKAGE.rpm; rpm -qp[ildc] PACKAGE.rpm\n' +
      '\n' +
      'Manipulate RPM packages\n' +
      '\n' +
      'Commands:\n' +
      '\t-i\tInstall package\n' +
      '\t-qp\tQuery package\n' +
      '\t-qpi\tShow information\n' +
      '\t-qpl\tList contents\n' +
      '\t-qpd\tList documents\n' +
      '\t-qpc\tList config files\n'```

**Comment by karniwl** [comment]
Hi @HannesBBR, thanks for raising this issue. This is not a solution yet for this error, but either way I'd like to suggest you to use a beta version of Snyk Container CLI, which will allow vulnerabilities to be found in Distroless based images (which in the default version we don't crash but also don't provide vulnerabilities) both in `gcr.io/distroless/java:11` and in `gcr.io/distroless/java:11`. To use this please add `--experimental` flag to the command: `snyk test -d --docker <image-url> --file=Dockerfile --experimental`. Please note, this is still in beta so take it into account you may run into more issues here, but we'd love to hear your feedback and any issues raised by you!

**Comment by lili2311** [comment]
👋 @HannesBBR is your issue now resolved?

**Comment by karniwl** [comment]
Hi @HannesBBR, latest update on this is that we now fully support `snyk container test` command which supports distroless scanning. You can run `snyk container test --help` to see all options.
I'll now close the issue but please reopen if you encounter any issues. Thanks!
