### ISSUE TITLE
[🐛] snyk.io: Not fixing gunicorn dependency

### ISSUE THREAD

**Issue by Demacr** [snyk/snyk#1152]
Snyk writes that it update gunicorn 19.6.0 -> 19.10.0, but not doing it.

### Expected behaviour
Snyk makes PR with gunicorn update.

### Actual behaviour
Snyk made PR with empty commit.

### Steps to reproduce
- Have repo consisting gunicorn requirements that have version 19.6.0
- Make fix PR from snyk.io dashboard

### Example PR
`https://github.com/Demacr/syncserver/pull/4`

**Comment by lili2311** [comment]
hi @Demacr apologies for the slow response here, is this still occuring for you? Are you able to replicate this to generate fresh logs for me to check?

**Comment by Demacr** [comment]
@lili2311 Hello, yeah, problem still occure. I ran new update, but it still opens PR with empty commit: https://github.com/Demacr/syncserver/pull/5. Where can I make logs? I cannot see it at snyk.io

**Comment by lili2311** [comment]
thanks @Demacr I can replicate this, will see what is causing this & issue a fix.

**Comment by lili2311** [comment]
@Demacr found the issue and have a fix https://github.com/lili2311/syncserver/pull/2/files, I will raise it and deploy. Will update here once it is released.

The issue was: we were looking for the full resolved version `19.6.0` in a file but of course the original spec is partial `19.6` so we could not find the right place to apply the change.

**Comment by Demacr** [comment]
@lili2311 Nice, thank you!

**Comment by lili2311** [comment]
@Demacr changes have been released, please could close the bad PR, delete the branch & try opening new PR?

**Comment by Demacr** [comment]
@lili2311 [Awesome](https://github.com/Demacr/syncserver/pull/6/commits/5008c75193a740c2c38f8df59a411e77fca64faf) :)
