### ISSUE TITLE
[🐛]

### ISSUE THREAD

**Issue by zohaib85** [snyk/snyk#1168]
- `node -v`: v11.9.0
- `npm -v`: 6.4.1
- `snyk -v`:1.336.0
- OS: (e.g. OSX, Linux, Windows, ...) Windows
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)
**snyk.cmd test <src>/<code directory>/packages.config**
### Expected behaviour
Please share _expected_ behaviour.
.json report should create at the root of the project i.e. <src> folder instead of where packages.config is located.
JSON file should produce at the root of the 
### Actual behaviour
.json report gets created where packages.config file is.
Please share _problematic_ behaviour you are seeing.

### Steps to reproduce
Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testsing.

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.
It's happening in Azure DevOps builds where we are integration snyk during build. Now after build we don't see any report as json file from where report gets generated located where packages.config file is.

### Screenshots
![image](https://user-images.githubusercontent.com/13233663/83885595-9dd1ff00-a757-11ea-83c4-d9871928ef30.png)

**Comment by zohaib85** [comment]
JSON file gets generated what we select as "test working directory" path
![image](https://user-images.githubusercontent.com/13233663/83886134-09b46780-a758-11ea-95ba-cb9c091a9b0f.png)

but snyk report is not getting generated because it could not find json file at root directory of the project.

Kindly advise

**Comment by JackuB** [comment]
Hi, thanks for the report. From what I understand:

- you are using Azure DevOps Pipelines
- you change the working directory in settings
- snyk test is run and JSON is created in the specified working directory
- when trying to view the report after test, it ends with an error, because it expects the report in a different directory

**Comment by maxjeffos** [comment]
I'm working on generating the reports (both json and html) in the `Agent.TempDirectory` (an Azure thing https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)... see https://github.com/snyk/snyk-azure-pipelines-task/issues/54
I think that doing that should also solve for this.

What do you think @zohaib85 @JackuB @jessehouwing ?

**Comment by JackuB** [comment]
@zohaib85 hi, since the PR mentioned above was merged and released, the issue should be solved. Is everything working for you now?
