### ISSUE TITLE
undefined error when using snyk monitor on a maven project

### ISSUE THREAD

**Issue by Lucas-C** [snyk/snyk#117]
Hi

I witness the following error in my Jenkins pipeline:
```
$ mvn -s ./settings.xml clean install -Dmaven.test.skip=true
...
[INFO] BUILD SUCCESS
...
$ snyk monitor --debug
Thu, 14 Dec 2017 14:10:37 GMT snyk monitor { _: [ [Circular] ], debug: true }
Thu, 14 Dec 2017 14:10:37 GMT snyk checking for cli updates
Thu, 14 Dec 2017 14:10:54 GMT snyk add error-message undefined
Thu, 14 Dec 2017 14:10:54 GMT snyk add error undefined
Thu, 14 Dec 2017 14:10:54 GMT snyk add error-code undefined
Thu, 14 Dec 2017 14:10:54 GMT snyk add command monitor
undefined
Thu, 14 Dec 2017 14:10:54 GMT snyk { command: 'bad-command',
  args: [ { debug: true } ],
  metadata: 
   { 'error-message': undefined,
     error: undefined,
     'error-code': undefined,
     command: 'monitor' },
  version: '1.59.1',
  os: 'Linux 3.10',
  nodeVersion: 'v6.9.2',
  id: '1731e95c2a3dce8517dd2fdb15ddc2ef3e4e0fc1',
  ci: true }
```

The relevant Jenkins pipeline code:

    build_image.inside("-u root --env HTTP_PROXY=${env.HTTP_PROXY} --env https_proxy=${env.HTTPS_PROXY} --env no_proxy=${env.NO_PROXY} -v ${pwd()}/docker-volumes/m2-repository:/appl/usljksu1/m2repo") {
        env.M2_HOME = ''
        env.JAVA_HOME = ''
        sh('npm --version')
        sh('npm install -g snyk')
        maven('clean install -Dmaven.test.skip=true')
        withCredentials([string(credentialsId: 'SnykTokenId', variable: 'SNYK_TOKEN')]) {
            sh('snyk --version')
            sh('snyk monitor --debug')
        }
    }

I miss to see what bit of environment context is breaking `snyk` execution here.

I reproduced those steps manually in a `docker run -it` session, and it worked perfectly well.

Would you have any idea on what could be failing here ?

**Comment by Lucas-C** [comment]
I was able to reproduce it with `snyk test`, in a `docker run -it` session this time:
```
# snyk test --debug
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk checking for cli updates +462ms
  snyk add local true +56ms
  snyk add packageManager maven +0ms
  snyk add error-message undefined +27s
  snyk add error undefined +1ms
  snyk add error-code undefined +0ms
  snyk add command test +0ms
undefined
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true, packageManager: 'maven', file: 'pom.xml' } ],
  snyk   metadata:
  snyk    { local: true,
  snyk      packageManager: 'maven',
  snyk      'error-message': undefined,
  snyk      error: undefined,
  snyk      'error-code': undefined,
  snyk      command: 'test' },
  snyk   version: '1.59.1',
  snyk   os: 'Linux 3.10',
  snyk   nodeVersion: 'v6.9.2',
  snyk   id: '0728e8c6943ce964327cf313422fb91ac3f0e779',
  snyk   ci: false } +3ms
```

**Comment by joshje** [comment]
Are you able to share the `pom.xml` with us for this test? If so please send it to support@snyk.io.

We will take a look and see why this is happening.

**Comment by darmalovan** [comment]
Hey @Lucas-C I'm trying to run `mvn install` on your `pom.xml` without any luck.
I'm getting:
```
   The project com.vsct.vsc.catalog:offers-xsell-engine:1.46-SNAPSHOT (/Users/darmalovani/Downloads/offers-xsell-engine/pom.xml) has 1 error
[ERROR]     Child module /Users/darmalovani/Downloads/offers-xsell-engine/engine-api-perf of /Users/darmalovani/Downloads/offers-xsell-engine/pom.xml does not exist
```

**Comment by darmalovan** [comment]
There are some private dependencies that I cannot download inside the submodule:
 `engine-api`. 
After excluding it I was able to run `snyk test`,
Is it possible to remove the module in your `pom.xml` and see if the problem persists? It will help us to narrow down the root cause.

**Comment by Lucas-C** [comment]
Indeeed the `engine-api` module has 4 dependencies to internal `com.vsct` packages.

I removed it from the root `pom.xml` and re-ran the pipeline. There is the result:
```
+ snyk monitor --debug
Mon, 18 Dec 2017 10:39:20 GMT snyk monitor { _: [ [Circular] ], debug: true }
Mon, 18 Dec 2017 10:39:20 GMT snyk checking for cli updates
Mon, 18 Dec 2017 10:39:35 GMT snyk add error-message undefined
Mon, 18 Dec 2017 10:39:35 GMT snyk add error undefined
Mon, 18 Dec 2017 10:39:35 GMT snyk add error-code undefined
Mon, 18 Dec 2017 10:39:35 GMT snyk add command monitor
undefined
Mon, 18 Dec 2017 10:39:35 GMT snyk { command: 'bad-command',
  args: [ { debug: true } ],
  metadata: 
   { 'error-message': undefined,
     error: undefined,
     'error-code': undefined,
     command: 'monitor' },
  version: '1.59.1',
  os: 'Linux 3.10',
  nodeVersion: 'v6.9.2',
  id: '793fba63fd1f33204fea551c185a183d48977b70',
  ci: true }
```

**Comment by darmalovan** [comment]
@Lucas-C Can you update `snyk` and run it again? the error should be logged properly now.

**Comment by Lucas-C** [comment]
I retried with npm 3.10.9 and snyk 1.61.1 and got the following log:
[snyk.log](https://github.com/snyk/snyk/files/1575245/snyk.log)

**Comment by darmalovan** [comment]
Great, seems like a progress.
Can you tell me:
- Which version of `mvn` you are running inside the container?
- What happen when you run `mvn dependency:tree -Doutput=dot`

**Comment by Lucas-C** [comment]
```
+ mvn -s ./settings.xml --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
```
With Java version 1.8

`mvn -s ./settings.xml dependency:tree -Doutput=dot` completed successfully and generated 5 files:
```
engine-api/dot
engine-api-perf/dot
engine-api-tests/dot
engine-common/dot
engine-rules/dot
```

I renamed them and made a zip archive: -> 
[offers-xsell-engine.dot.zip](https://github.com/snyk/snyk/files/1575604/offers-xsell-engine.dot.zip)

**Comment by darmalovan** [comment]
I assume that the `settings.xml` is missing for `snyk monitor`
You should able to run it like that:
`snyk monitor -- -s ./settings.xml`

**Comment by Lucas-C** [comment]
Yes !! This was the solution !
Thank you very much !
