### ISSUE TITLE
[🙏] Snyk CLI support for K8s

### ISSUE THREAD

**Issue by jonrau1** [snyk/snyk#1190]
- `Language / Project Type:` Kubernetes

**Describe the user need**
As a DevSecOps engineer I want to use the Snyk CLI to scan my k8s config files and helm charts in CI/CD so that I can ensure there are no security deficiencies 

**Describe expected behaviour**
Preferably I would not have to configure k8s IAC support at the org level and the CLI will attempt it on any .yml or .json files it find
```bash
npm install -g snyk
snyk auth <key>
snyk test --all-projects
```

**Additional context**

N/A

**Comment by orkamara** [comment]
:wave: @jonrau1 !

Nice to meet you - I'm Or from the team that owns the Kubernetes config support.
You have a perfect timing! We're working on the CLI support (starting with K8s) now - https://github.com/snyk/snyk/pull/1140.

Would you like to be part of the beta users?

BTW - have you tried our SaaS integration for K8s / Helm configs? it would be great to get a feedback from you!

Thanks,
or

**Comment by lili2311** [comment]
@jonrau1 does the new CLI release solve your request?

**Comment by jonrau1** [comment]
@lili2311 @orkamara sorry for the delays folks, was caught up.

I pulled the latest (`npm i snyk@1.350.0`) and tried running it on a very basic k8s deployment.yaml and was unable to do it.

I tried both `snyk test .` and `snyk test file=deployment.yaml` and received the usual error.

```
snyk test .

Testing ....

CustomError: Could not detect supported target files in ..
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.
```

```
snyk test --file=./deployment.yaml

Testing /home/ubuntu/environment/k8stest...

Error: Could not detect package manager for file: ./deployment.yaml
```

110% possible I am messing this up somewhere. Can you folks kindly advise and set me aright?

**Comment by jonrau1** [comment]
Upgraded to `1.360.0` and still running into those same issues

**Comment by orkamara** [comment]
:wave: @jonrau1 !!
Missed your reply somehow - sorry for that.
The reason you you cannot use the feature is that it's still behind a feature flag.
If you could send me your Snyk org, I'll enable that for you..

Thanks,
Or

**Comment by lili2311** [comment]
@jonrau1 is this resolved for you now?

**Comment by lili2311** [comment]
@jonrau1 closing this issue since we have not heard back from you in a while, please re-open if you need anything further.
