### ISSUE TITLE
Tunneling socket could not be established

### ISSUE THREAD

**Issue by jezhalford** [Snyk/snyk#12]
Hi,

I get the following message when running Snyk behind a particularly restrictive firewall. Is there a list somewhere of the ports / hosts / etc that I need to open for Snyk to work?

Thanks

    tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)

**Comment by remy** [comment]
Hi @jezhalford,

You'll want to whitelist https://snyk.io as it's `GET`'ing and `POST`ing to that URL. 

I take it that error is coming out of the snyk CLI tool?

**Comment by jezhalford** [comment]
Hi, yes from the CLI. I thought https://synk.io was on my whitelist, but it seems it might not be. Thanks for clarifying.
