### ISSUE TITLE
When snyk policy has expires date without quotes in YML, it is ignored

### ISSUE THREAD

**Issue by dominykas** [snyk/snyk#120]
- `node -v`:`8.9.4`
- `npm -v`: `5.6.0`
- `snyk -v`: `1.64.0`
- Command run: `snyk test --dev`

### Expected behaviour

All dates treated equally.

### Actual behaviour

When `.snyk` has `expires: 2017-12-30T12:00:00.000Z`, the ignore does not expire.
When `.snyk` has `expires: '2017-12-30T12:00:00.000Z'`, the ignore expires correctly.

---

This happens, I think, because `js-yaml` automatically tries to interpret the `expires` as a date when it has no quotes - at least it seems to be the case that `expires` is an instance of `Date` [here](https://github.com/snyk/policy/blob/master/lib/filter/ignore.js#L37) and [here](https://github.com/snyk/policy/blob/master/lib/filter/notes.js#L23)

I think the fix is to `if (expires.toJSON) { expires = expires.toJSON(); }` right after the lines I pasted - I'm happy to PR and add tests for this, if you agree.

**Comment by dominykas** [comment]
Oh, and I have no idea how did our `expires` ended up without quotes - possibly ignored by some older version of snyk or maybe a bad copy/paste from some example.

**Comment by odinn1984** [comment]
@dominykas Hi! thanks for the bug report. We are looking into it and will give you an answer as soon as we can.

**Comment by odinn1984** [comment]
@dominykas we would be happy to review the PR if you open it. Thanks a lot! :)

**Comment by dominykas** [comment]
Opened https://github.com/snyk/policy/pull/19 - I can continue on it tomorrow, if the missing tests/cleanup are necessary, although you probably have a better idea on how things should work internally?

**Comment by dominykas** [comment]
Figured out how I got the bug in the first place - just had to run this:
```
snyk ignore --id='npm:lodash:20180130' --expiry='2018-02-23' --reason='Ignoring to make the build green, while we investigate further - the upgrade on elasticsearch-js is by far non-trivial and will take time; must assess the exposure/impact'
```

So this is actually quite serious and out in the wild? Using snyk `1.69.7`.

**Comment by adrukh** [comment]
@dominykas I just merged https://github.com/snyk/snyk/issues/120, will update here once this is released in the CLI.

**Comment by dominykas** [comment]
Thanks!

**Comment by dominykas** [comment]
Looks good!
