### ISSUE TITLE
CLI connecting to unkown host

### ISSUE THREAD

**Issue by RRMoelker** [snyk/snyk#123]
- `node -v`: v8.9.1
- `npm -v`: 5.6.0
- `snyk -v`: 1.1.1
- Command run: `snyk test` and `snyk auth`

### Expected behaviour
Testing or authentication

### Actual behaviour
Connection problem to `app.snyk.io`:

```
getaddrinfo ENOTFOUND app.snyk.io app.snyk.io:443
```

### Steps to reproduce
```
$ snyk test
getaddrinfo ENOTFOUND app.snyk.io app.snyk.io:443
```
The host doesn't appear to exist: http://downforeveryoneorjustme.com/app.snyk.io

**Comment by adrukh** [comment]
Yikes, we really killed this host a while ago!
But 1.1.1 is such an old release... Please update with `npm i -g snyk`, you are in for a ride!

**Comment by RRMoelker** [comment]
Hmm, I was under the illusion that I was using the latest version. Updating to `1.68.0` indeed solves this problem. Thank you!

Problem for me personally was that `npm i -g snyk` was updating the wrong binary. If anyone else encounters this on OS X using nvm, try:

```
nvm use system
npm i -g snyk
```

Suggest closing the issue.

**Comment by adrukh** [comment]
Thanks for updating!
