### ISSUE TITLE
[🙏]

### ISSUE THREAD

**Issue by Barkole** [snyk/snyk#1238]
- `Language / Project Type:` [typescript
- `Package Manager / Build Tool:` yarn

**Describe the user need**
I want to install snyk without deprecation warnings

**Describe expected behaviour**

No deprecation warnings

**Additional context**

```txt
 warning snyk > @snyk/snyk-cocoapods-plugin > @snyk/dep-graph > @snyk/graphlib > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
```

**Comment by JackuB** [comment]
Thank you for bringing this up 🎉 - we will be removing that package from the CLI dependencies
