### ISSUE TITLE
snyk test reports a "direct dependency" that seems indirect

### ISSUE THREAD

**Issue by hakanson** [snyk/snyk#124]
I was evaluating `snyk test` (version 1.68.1) on a project and the was part of my results:

```
Testing /Users/hakanson/VSCodeProjects/redacted ...
✗ Low severity vulnerability found on hawk@1.0.0
- desc: Regular Expression Denial of Service (DoS)
- info: https://snyk.io/vuln/npm:hawk:20160119
- from: redacted@0.1.0 > update-notifier@0.1.7 > request@2.27.0 > hawk@1.0.0
Upgrade direct dependency update-notifier@0.1.7 to update-notifier@0.1.9 (triggers upgrades to request@2.59.0 > hawk@3.1.3)
```

I was confused this being labeled as a "direct dependency" since I didn't see it listed in my `package.json` and the report doesn’t seem to show where this dependency is coming from. I did a “find in files” and it was in `yarn.lock` as a dependency for `tsd` which was a dependency of `grunt-tsd` from my `package.json`.

Should the report look more like:
```
- from: redacted@0.1.0 > grunt-tsd@0.1.0 > tsd@0.5.6 > update-notifier@0.1.7 > request@2.27.0 > hawk@1.0.0
```
or even:
```
- from: redacted@0.1.0 > grunt-tsd@0.1.0 (package.json) > tsd@0.5.6 (yarn.lock) > update-notifier@0.1.7 > request@2.27.0 > hawk@1.0.0
```

Or doesn't that change the outcome since I still run `snyk wizard` to resolve and patch.

**Comment by adrukh** [comment]
> I was confused this being labeled as a "direct dependency"
Are you referring to `update-notifier`? Please share the output of `yarn why update-notifier` on this project, I'd like to confirm the `find in files` finding you shared.

**Comment by hakanson** [comment]
Hmm - this seems to imply `snyk` depends on it.
```
$ yarn why update-notifier
yarn why v1.3.2
warning package.json: No license field
[1/4] 🤔  Why do we have the module "update-notifier"...?
[2/4] 🚚  Initialising dependency graph...
warning redacted@0.1.0: No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info This module exists because "snyk" depends on it.
info Disk size without dependencies: "1.25GB"
info Disk size with unique dependencies: "1.25GB"
info Disk size with transitive dependencies: "1.25GB"
info Number of shared dependencies: 49
✨  Done in 1.50s.
```

But, here is the `npm ls update-notifier` output:
```
redacted@0.1.0 /Users/hakanson/VSCodeProjects/redacted
└─┬ grunt-tsd@0.1.0
  └─┬ tsd@0.5.7
    └── update-notifier@0.1.7  (git://github.com/Bartvds/update-notifier.git#0706121db6a6b6c47faeec87b18090cc9a10b6a7)
```

From `package.json`:
```
  "devDependencies": {
    ...
    "grunt-tsd": "0.1.0",
```

From `yarn.lock`:
```
grunt-tsd@0.1.0:
  version "0.1.0"
  resolved "http://redacted.example.com/artifactory/api/npm/default.npm.global/grunt-tsd/-/grunt-tsd-0.1.0.tgz#d5528fa9e3ea63007ab740736b0aa488940460d7"
  dependencies:
    tsd "~0.5.6"


tsd@~0.5.6:
  version "0.5.7"
  resolved "http://redacted.example.com/artifactory/api/npm/default.npm.global/tsd/-/tsd-0.5.7.tgz#524bfb437b541467b5cb6111f40744a7538042d1"
  dependencies:
    ...
    update-notifier "git://github.com/Bartvds/update-notifier/#fix/fork"
"
```

**Comment by adrukh** [comment]
@hakanson this is based on a known difference between how `npm` and `yarn` keep track of the 'parent' for each installed dependency. Our CLI follows the `npm` way, and can cause misdetection of paths as a result. It was documented in https://github.com/snyk/snyk/issues/86#issuecomment-306291454

We have better `yarn` support on the roadmap and plan on solving this gap. I cannot comment on a specific timeline yet.

**Comment by karniwl** [comment]
@hakanson some time has passed and we have improved since our `yarn` support :) would you like to check if this detects the dependency as indirect now?

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.
