### ISSUE TITLE
Confusing testing with empty node_modules

### ISSUE THREAD

**Issue by jehy** [snyk/snyk#126]
- `node -v`: 8.9.1
- `npm -v`: 5.5.1
- `snyk -v`: 1.69.1
- Command run:
snyk test
### Expected behaviour
When node_modules is empty, snyk should display an error like when there is no node_modules:
```
Missing node_modules folder: we can't test without dependencies.
Please run `npm install` first.
```

### Actual behaviour
snyk does not test anything and does not produce error:
```
Testing /web/project...
Organisation: jehy
Package manager: npm
Target file: package.json
Open source: no

✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.
```
### Steps to reproduce
remove contents of node_modules from any package and get same results.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by jehy** [comment]
This really makes me doubt - does snyk really check and use package.json? If it does - why it does not tell that module from package.json is not installed locally? Seems like a crytical issue to me.

**Comment by adrukh** [comment]
@jehy I think I understand what you mean, please read below and let me know what you think.

There's an assumption in our CLI with regards to npm projects that `snyk test` runs after `npm install` was already executed. If your `node_modules` folder exists, and is empty, we assume no dependencies, hence no vulnerabilities via dependencies, hence return code `0`.

Your expectation that an empty `node_modules` folder would be an invalid state to run `snyk test` sent me on a quick investigation of interoperability with several package managers:
- When using `npm@3` on a project with no dependencies, running `npm i` generates an empty `node_modules` folder.
- When using `npm@5` on a project with no dependencies, running `npm i` *does not* generate a `node_modules` folder.
- When using `yarn@1.3.2` on a project with no dependencies, running `yarn` *does not* generate a `node_modules` folder.

So I think our current implementation is ok for the `npm@3` case, while your expectation fits the `npm@5` and `yarn` cases.

Would you be interested in submitting a PR that adds this distinction and acts accordingly? The relevant area in code is https://github.com/snyk/snyk/blob/f6e3ae9ae405a659557ac36e0d22ae6df3218e8f/lib/snyk-test/npm/index.js#L21

**Comment by jehy** [comment]
Hi! I don't think that relying on npm version is a good idea. We can't tell if npm or yarn was used, and also:

* What if user used npm of one version and runs snyk from another? That's not rare case, I switch node (and npm) version about 10 times a day.
* What if user manually made `rm node_modules/*` which is a common advice in many situations?
* What if user manually removed or updated packages from `node_modules`?
* What if user has only insides of `node modules` ignored in git and so he checks out and empty `node_modules` dir?
* What if user interrupted `npm install` or it exited because of some error and not all modules were installed?

I think that the only reliable solution is to get all used modules from `package.json` and check if all of them exist in `node_modules`. Or to run `npm install` before actually analyzing anything.

**Comment by lili2311** [comment]
👋 I believe this is now resolved? We do show a warning if `node_modules` are empty  && if there is a lockfile present we don't look in the node_modules at all since the lockfile gives us all we need.

**Comment by jehy** [comment]
Yup, this issue is no longer present.

**Comment by chesterm8** [comment]
This is still an issue with snyk monitor - you get no warning about the missing node_modules folder

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/pull/1372 PR merged that will in the future not throw if package.json has no dependencies
