### ISSUE TITLE
[🐛] web tool shows vulnerability that cli tool does not in build.gradle

### ISSUE THREAD

**Issue by jason-upchurch** [snyk/snyk#1265]
- `node -v`: v10.16.0
- `npm -v`: 6.14.4
- `snyk -v`: 1.300.0
- OS: OSX
- Command run: `snyk test --file=build.gradle`

### Expected behaviour
Our related issue https://github.com/fecgov/openFEC/pull/4430 shows that no vulnerabilities exist. We expect the web interface to also report that no vulnerabilities exist.

### Actual behaviour
The web interface shows that this vulnerability still exists even thought the CLI tool shows it is resolved.

```
  ✗ XML External Entity (XXE) Injection [High Severity][https://snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-571481] in org.postgresql:postgresql@42.2.5.jre6
    introduced by org.flywaydb:flyway-commandline@5.2.4 > org.postgresql:postgresql@42.2.5.jre6
  This issue was fixed in versions: 42.2.13
```

### Steps to reproduce
https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3?action=ignore-delete&success=true

### Debug log
n/a

### Screenshots
n/a

**Comment by lili2311** [comment]
Hi @jason-upchurch please reference this support article https://support.snyk.io/hc/en-us/articles/360002615737-Snyk-CLI-shows-no-vulnerabilities-but-Snyk-UI-does, I hope this answers your question?

**Comment by jason-upchurch** [comment]
> Hi @jason-upchurch please reference this support article https://support.snyk.io/hc/en-us/articles/360002615737-Snyk-CLI-shows-no-vulnerabilities-but-Snyk-UI-does, I hope this answers your question?

thank you @lili2311! Yes this answers my question--much appreciated!
