### ISSUE TITLE
[🐛] Snyk fails to install with yarn on Node 8 despite Node Engine support

### ISSUE THREAD

**Issue by asos-craigmorten** [snyk/snyk#1270]
- `node -v`: `v8.17.0`
- `npm -v`: `6.13.4`
- `yarn -v`: `1.22.4`
- `snyk -v`: `^1.319.1`
- OS: MacOS
- Command run: `yarn add snyk`

Low priority! 😄 Raising more for visibility in case anyone else sees this, and also to flag as something needing consideration going forward for `yarn` users (as we progress to Node 12.x and beyond).

### Expected behaviour

Yarn should be reporting `snyk` as incompatible with Node `8.x`.

### Actual behaviour

Snyk currently lists in it's [package.json that it supports Node >=8](https://github.com/snyk/snyk/blob/master/package.json#L21) so Yarn will attempt to install `snyk` on Node `8.x` only to then fall over when trying to install the sub-dependency `semver` (among others) which requires Node >=10.

This is particularly painful due to the way Snyk is versioned as allowing minor version upgrades (commonly denoted by `^`) results in this problem for any project on Node `8.x` as the breaking change (in supported Node version) in Snyk was published as a minor change.

### Steps to reproduce

1. Install Node `8.x`, this is easiest done using NVM. See [here](https://github.com/nvm-sh/nvm#installing-and-updating) on how to install NVM. One can then run `nvm use lts/carbon` to use the latest Node `8.x` version.
1. In any project attempt to add any version past `snyk@^1.319.1` to your dependencies. For example:

    ```console
    $ yarn add snyk@1.319.1
    ```

1. Notice that you will receive an error similar to the one below (may vary depending on exact `snyk` version) installed.

### Debug log

```console
$ yarn add snyk@1.319.1
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Notes:

- Consider updating the listed engine for Node in the [`package.json`](https://github.com/snyk/snyk/blob/master/package.json#L21) so it is reflective of it's Node support matrix of it's dependencies going forward:

    ```
    {
      ...
      "engines": {
        "node": ">=10"
      },
      ...
    }
    ```

- It is likely that such a change requires updates to your CI e.g. https://github.com/snyk/snyk/blob/master/.circleci/config.yml#L287

- Likely worth considering because Node `8.x` went end of life last December (REF: https://github.com/nodejs/Release#end-of-life-releases).

- Engine error path:

    `snyk@1.319.1` > `@snyk/dep-graph@1.18.3` > `semver@^7.3.2`.

- Minor tag upgrade that introduced the breaking Node engine version: https://github.com/snyk/snyk/compare/v1.319.0...v1.319.1

- PR that introduced the breaking Node engine version: https://github.com/snyk/snyk/pull/1103

- `semver` Node engine version: https://github.com/npm/node-semver/blob/v7.3.2/package.json#L36

- This does not impact `npm` because (1) it only warns if the top-level Node engine rule isn't met and (2) it doesn't appear to report at all on sub-dependency Node engine rules.

- Can be mitigated by using the `--ignore-engines` flag, e.g. `yarn install --ignore-engines`. This somewhat defeats the purpose of packages providing `engine`s however.

### Screenshots

N/A

**Comment by yqrashawn** [comment]
similar problem with `@yarnpkg/core` error
```
error @yarnpkg/core@2.1.1: The engine "node" is incompatible with this module. Expected version ">=10.19.0". Got "10.16.3"
```

**Comment by dkontorovskyy** [comment]
@asos-craigmorten, @yqrashawn can you try updating `snyk` to the latest version (v1.361.3) and see if this helps, please?

**Comment by asos-craigmorten** [comment]
This issue impacts all versions of Snyk from `1.319.1` through to the latest version `1.361.3` which I have also confirmed. The problem is these newer versions of `snyk` pulled in upgraded dependencies which are now incompatible with the Node engine set in the [current package.json](https://github.com/snyk/snyk/blob/master/package.json#L21).

**Comment by orsagie** [comment]
@asos-craigmorten, @yqrashawn I suggest using version snyk@1.358.0 for now, the `incompatible node` issue is affecting version 1.359.0 and up (since yarn2 support was added). We are working on fixing the issue.

**Comment by asos-craigmorten** [comment]
Hi @orsagie, the incompatible node issue impacts version `1.319.1` and up as per the description. I recopy the terminal output below:

```
$ yarn add snyk@1.319.1
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by orsagie** [comment]
@asos-craigmorten the fix reverting yarn2 has been merged. Can you check that you are able to install snyk with the latest version?

**Comment by asos-craigmorten** [comment]
@orsagie apologies for the slow reply! Will check it out now for you and confirm 😄

**Comment by asos-craigmorten** [comment]
Hi @orsagie, this appears that we still face the same error installing the latest `snyk` while using Node 8:

```console
$ nvm use
Found '~/test-snyk/.nvmrc' with version <8>
Now using node v8.17.0 (npm v6.13.4)

$ yarn add snyk
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

This time the error coming from the `chalk@4.1.0` package (unsure of the dependency chain) which requires Node >=10 and therefore makes latest Snyk incompatible with Node 8.

It is possible to install latest `snyk` with the `--ignore-engines` flag and then we can run the CLI on Node 8 and can see the various warning messages about EOL, but generally it is ill-advised to ignore the `engines` settings as they are put there to ensure full compatibility, and ignore them can result in unexpected behaviour.

**Comment by JackuB** [comment]
Snyk CLI will be dropping the Node 8 support after Feb 15th. This means we won't be testing CLI against Node 8 anymore and `engines` field in package.json will get bumped as well.

We highly recommend upgrading if possible. Alternatively, brew/scoop & standalone builds of the CLI are available https://github.com/snyk/snyk/releases

https://updates.snyk.io/ending-snyk-cli-support-for-node-js-8-x-183304

**Comment by Spown** [comment]
My understanding of the problem (which has the same root as #1699) is that you've explicitly removed [package-lock.json](https://github.com/snyk/snyk/blob/master/.gitignore#L10) and there is no yarn.lock either. So all these modules, that were not requiring Node@10 at the time of inclusion started "traveling back to the future", because they were added with semver ranges (``@^XXX``) and forcing all those Snyk versions, that were perfectly fine with Node@8 also demanding Node@10.

It's too late to do anything about it now, apart from finding a definitive latest possible Snyk version, that those module versions won't seep through and inform about it in the Readme.

**Comment by asos-craigmorten** [comment]
Given support for Node 8 was dropped 2 months ago, the `package.json` has an updated `engines` field for Node 10 onwards, and there is a workaround of `--ignore-engines` for older versions that are impacted, happy to close.
