### ISSUE TITLE
[🐛] Bitbucket cloud integration reports incorrect transitive (vulnerable) dependencies in maven project

### ISSUE THREAD

**Issue by martinvisser** [snyk/snyk#1280]
### Expected behaviour
Projects imported through Bitbucket cloud should report no vulnerabilities just like the Snyk CLI does.

### Actual behaviour
When importing a project through Bitbucket cloud Snyk reports vulnerabilities on dependencies which are not in the dependency tree. If I run a local `snyk monitor` Snyk reports zero vulnerabilities, but the automatic scan based on the project import reports 4. All of them are transitive dependencies, but these are not found on a `mvn dependency:tree` call.

### Steps to reproduce
Import a project from Bitbucket cloud with this pom: [pom.xml.zip](https://github.com/snyk/snyk/files/4962015/pom.xml.zip)
Also run `snyk test` to check the results:
`✓ Tested 164 dependencies for known issues, no vulnerable paths found.`

### Screenshots
This is one of the four incorrectly found vulnerabilities:
![import](https://user-images.githubusercontent.com/3170236/88218608-8d6ed880-cc60-11ea-9be5-95fa1bc07e82.png)

**Comment by lili2311** [comment]
👍 @martinvisser Please take a look at this [help article](https://support.snyk.io/hc/en-us/articles/360000920998-Why-did-the-Snyk-CLI-discover-different-dependencies-and-vulnerabilities-than-through-the-integration-in-the-app-) that explains the differences.

**Comment by martinvisser** [comment]
Okay, that indeed helps. I don't like it, but it does explain why it happens.
