### ISSUE TITLE
Different reports between CLI and web

### ISSUE THREAD

**Issue by daniele-occhipinti** [snyk/snyk#129]
Hi.

I often get different results between reports on CLI and web - e.g. I don't get any vulns from the CLI, but the web report highlights some.

Sorry I don't include more details about the vulnerabilities but I don't want to expose my project. I would be happy to provide more details privately.

Why that may be?

```
dan@test.local:~/projects/gds/pay-connector$ node -v
v7.10.0
dan@test.local:~/projects/gds/pay-connector$ npm -v
4.2.0
dan@test.local:~/projects/gds/pay-connector$ snyk -v
1.69.5
```

**Comment by joshje** [comment]
Hey @daniele-occhipinti, there's a few key differences between how our CLI works and how our online integrations work. These differences also differ per language & package manager, so it'd be good to get more information about the project you are testing.

You can contact us privately at support@snyk.io and we can chat.

**Comment by joshje** [comment]
Here's an updated status of this issue.

We've discovered the cause of this. Our online tool reads package manifest files and determines which dependencies would be installed if it were run, whereas our CLI tool has access to the actual environment and can determine the actual packages used by the codebase.

Sometimes we encounter scenarios where our online tool has a different conclusion to the CLI, and in this case this resulted in an optional dependency being included in the online results where it isn't included via the project.

We will be working to improve our online offering, and this insight will help us do that. In the meantime I suggest you ignore the vulnerability. You can do this from our UI by clicking the "ignore" button on the project page at the bottom of the vulnerability.

**Comment by daniele-occhipinti** [comment]
Glad you told me you were able to reproduce the issue.

**Comment by azuk-bread** [comment]
Still seems to be an issue, and it's incredibly frustrating.
