### ISSUE TITLE
[🐛] ./snyk-mac.sh reports unknown version

### ISSUE THREAD

**Issue by mat007** [snyk/snyk#1296]
- `node -v`: n/a
- `npm -v`: n/a
- `snyk -v`: n/a
- OS: OSX
- Command run: `./snyk-mac.sh version`

### Expected behaviour

```
./snyk-mac.sh version
1.365.0 (standalone)
```

or maybe not `(standalone)`, not sure?

### Actual behaviour

```
$ ./snyk-mac.sh version
unknown
```

### Steps to reproduce

Download and extract https://github.com/snyk/snyk/releases/download/v1.365.0/docker-mac-signed-bundle.tar.gzhttps://github.com/snyk/snyk/releases/download/v1.365.0/docker-mac-signed-bundle.tar.gz

### Debug log

```
$ ./snyk-mac.sh version --debug
  snyk version { _: [], debug: true, callGraphBuilderTimeout: '300' } +0ms
unknown
  snyk analytics {
  args: [],
  command: 'version',
  org: undefined,
  metadata: { integrationName: '', integrationVersion: '' },
  version: 'unknown',
  os: 'macOS Catalina',
  nodeVersion: 'v14.6.0',
  standalone: false,
  id: '86abbd6926f0c0eaf16b632a084fafc31d489f53',
  ci: false,
  durationMs: 94
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 258 +0ms
  snyk gzipped request body size: 193 +0ms
  snyk not using proxy +1ms
```

**Comment by JackuB** [comment]
Hey, this should've been solved with the release 1.369.0 https://github.com/snyk/snyk/releases/tag/v1.369.0, as we switched to a different packaging step. We'll verify that and get back to you

**Comment by mat007** [comment]
Thanks, I just started a build on our CI with 1.369.2, I’ll let you know!

**Comment by JackuB** [comment]
<img width="295" alt="screenshot_2020-07-31_at_16 51 03" src="https://user-images.githubusercontent.com/1788727/89067550-cb11e680-d36f-11ea-8edc-cc352caaf583.png">

Should be working as expected now 👌

**Comment by mat007** [comment]
This is indeed fixed now!
