### ISSUE TITLE
Update to package.json can result in incorrect `exit 1`

### ISSUE THREAD

**Issue by adam-moss** [Snyk/snyk#13]
When you `npm init` a new package.json it defaults the `scripts` element as follows:

```"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },```

If you then `snyk wizard` and accept the update to package.json you end up with:

```"scripts": {
    "test": "snyk test && echo \"Error: no test specified\" && exit 1"
  },```

This results in an exit code of 1, irrespective of whether the `synk test` was successful.

**Comment by remy** [comment]
Sorry, I meant to post a reply to this - essentially: good shout.

I'll add this into the upcoming releases of Snyk, and test for the `&& exit 1` in the current `scripts.test` value.

**Comment by adam-moss** [comment]
Cool.

I've actually moved sync to a separate `snyk` script now:

`"snyk": "snyk test --dev"`

And moved `snyk` itself to a dev dependency with the rest of the testing toolchain.
