### ISSUE TITLE
snyk behind company proxy

### ISSUE THREAD

**Issue by m-handy** [snyk/snyk#132]
- `node -v `: 6.12.3
- `npm -v`: 3.10.10
- `snyk -v`: 1.69.7
- Command run: `snyk auth token`

### Expected behaviour
Your account has been authenticated. Snyk is now ready to be used.

### Actual behaviour
Authentication failed. Please check the API token on https://snyk.io

### Steps to reproduce
Use docker container `node:6.12.3` and install snyk `npm install -g snyk` 

Call `snyk auth $SNYK_TOKEN` 
where `SNYK_TOKEN` was my token - I checked it twice. I tried call API with this token directly via `curl:`
```
curl --include \
     --header "Content-Type: application/json" \
     --header "Authorization: token $SNYK_TOKEN" \
  'https://snyk.io/api/v1/'
```
and the response was OK:
```
HTTP/1.0 200 Connection established
....
{"what orgs can the current token access?":"https://snyk.io/api/v1/orgs","what projects are owned by this org?":"https://snyk.io/api/v1/org/:id/projects","test a package for issues":"https://snyk.io/api/v1/:packageManager/"}
```
---
debug output: [snyk_error.txt](https://github.com/snyk/snyk/files/1719941/snyk_error.txt)

errors from proxy server: [snyk_proxy_anonym.txt](https://github.com/snyk/snyk/files/1719944/snyk_proxy_anonym.txt)

**Comment by darmalovan** [comment]
Hello,
Can you try to remove the call to snyk auth and use an environment variable instead for the snyk api token?
You can do so by doing: `export SNYK_TOKEN=<your-api-key>`

**Comment by darmalovan** [comment]
In addition, please try the following:
1) `openssl s_client -connect snyk.io:443`
2) ```
HTTPS_PROXY=<your-proxy> curl --include \
     --header "Content-Type: application/json" \
     --header "Authorization: token $SNYK_TOKEN" \
  'https://snyk.io/api/v1/'
```
Please let us know what are the results.

**Comment by m-handy** [comment]
Hi, I tried set token as environment variable but without success.
My results with your points are following:

1. 
```
connect: Connection timed out
connect:errno=22
```

2.
```
connect: Connection timed out
connect:errno=22
```

3.
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   224  100   224    0     0   1067      0 --:--:-- --:--:-- --:--:--  1071
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
x-snyk-version: undefined
x-frame-options: DENY
snyk-request-id: 65cb7ffb-eb6b-4cd9-875b-500188ef8c63
Content-Type: application/json; charset=utf-8
Content-Length: 224
ETag: W/"e0-t834H5YfTMN+2NnwoSoL6suLhNY"
Date: Fri, 16 Feb 2018 11:58:44 GMT
Connection: keep-alive
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
X-Frame-Options: deny
Strict-Transport-Security: max-age=31536000; preload

{"what orgs can the current token access?":"https://snyk.io/api/v1/orgs","what projects are owned by this org?":"https://snyk.io/api/v1/org/:id/projects","test a package for issues":"https://snyk.io/api/v1/:packageManager/"
```

**Comment by darmalovan** [comment]
Could it be a cert issue on the HTTPS proxy on your side ? The first/second command shouldn't fail

**Comment by m-handy** [comment]
It could, but I have to investigate all possibilities since I have very limited access to information from this proxy. Im not sure if `openssl` is going through the proxy, because our firewall is dropping direct comunication with the internet.

**Comment by adrukh** [comment]
When authenticating with a token, the CLI is making a POST call. Maybe these get treated differently with your proxy?

Can you please try `curl -X POST https://snyk.io/api/v1/verify/token`? You should see `{"error":"Not authorised"}` if the response comes back from snyk.io.

**Comment by m-handy** [comment]
I looks like there is a problem only when this is calling directly with node.js. The command you suggested ended as expected:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    26  100    26    0     0    113      0 --:--:-- --:--:-- --:--:--   113
{"error":"Not authorised"}
```

**Comment by adrukh** [comment]
Interesting!

Our CLI uses proxy detection like so - https://github.com/snyk/snyk/blob/master/lib/request/request.js#L73

If you run `snyk auth -d` and do not see the `proxy` debug message, it means the CLI is not using your proxy settings. Can this be the issue? Easily resolved by making sure that your `HTTPS_PROXY` env var is set properly.

**Comment by m-handy** [comment]
I tried `echo $SNYK_TOKEN` and `echo $HTTPS_PROXY` just to be sure and the results are `***-***-***-***-***` and `http://proxy.****.***:3128` (real values masked). And here is the result of your command:

```
2018-02-26T09:24:37.708Z snyk auth { _: [], debug: true }
2018-02-26T09:24:38.019Z snyk checking for cli updates
2018-02-26T09:24:38.051Z snyk add error-message noAuthInCI
2018-02-26T09:24:38.051Z snyk add error Error: noAuthInCI
    at githubAuth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:46:17)
    at auth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:150:15)
    at /usr/local/lib/node_modules/snyk/lib/hotload.js:16:21
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/cli/index.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
2018-02-26T09:24:38.051Z snyk add error-code AUTH_IN_CI
2018-02-26T09:24:38.051Z snyk add command auth
Error: noAuthInCI
    at githubAuth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:46:17)
    at auth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:150:15)
    at /usr/local/lib/node_modules/snyk/lib/hotload.js:16:21
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/cli/index.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
2018-02-26T09:24:38.055Z snyk { command: 'bad-command',
  args: [],
  metadata: 
   { 'error-message': 'noAuthInCI',
     error: 'Error: noAuthInCI\n    at githubAuth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:46:17)\n    at auth (/usr/local/lib/node_modules/snyk/cli/commands/auth.js:150:15)\n    at /usr/local/lib/node_modules/snyk/lib/hotload.js:16:21\n    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/cli/index.js:15:23)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.runMain (module.js:604:10)',
     'error-code': 'AUTH_IN_CI',
     command: 'auth' },
  version: '1.69.9',
  os: 'Linux 4.4',
  nodeVersion: 'v6.12.3',
  id: '2d601f7b724359a822eda42945a966a79ca161cc',
   ci: true }
```

**Comment by adrukh** [comment]
Please update to the latest `snyk@1.69.10`, we now show proxy related info in debug output.

I didn't realise you were running in a CI env, where we do not allow `snyk auth` as self-authentication requires user interaction via a browser.

Having `$SNYK_TOKEN` defined actually makes `snyk auth` non-mandatory, as this env var will be used to authenticate the CLI requests.

Can you go ahead and see if the expected `snyk test` works in this scenario? With `$SNYK_TOKEN` and `$HTTPS_PROXY` properly configured, that is.

If not, please provide the output of `snyk test -d`.

**Comment by m-handy** [comment]
Thanks, it looks like there is a issue on company proxy, because debug message contains this:
```
2018-02-28T14:53:58.743Z snyk sending request to: https://snyk.io/api/v1/analytics/cli
2018-02-28T14:53:58.743Z snyk request body size: 979
2018-02-28T14:53:58.743Z snyk Using proxy:  http://proxy.****.***:3128
```

**Comment by m-handy** [comment]
My company's proxy guy told me we are using old version of squid, but it should be transparent proxy, so version of SSL/TLS shouldn't be affected, when there is CONNECT in the begining od https communication. Is it possible somehow implement such a feature?

**Comment by m-handy** [comment]
Hi I would like to ask - do you think about rework of establishing HTTPS connection in your agent or can you suggest me different aproach how can I connect to your service from my CI? Thanks

**Comment by MichaelRVelasco** [comment]
I'm also having an issue with my companies proxy.  I have the HTTP_PROXY and HTTPS_PROXY environmental variables set, along with the SNYK_TOKEN variable.  Below is the redacted output from the debug.  It may or may not be important to know that my companies proxy for HTTPS still uses port 83 (not 443), e.g. the secure proxy server is still running over HTTP protocol, (but not port 80).

```
C:\Projects\git\testProj>snyk test -d > error.txt
  snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder C:\Projects\git\testProj +0ms
  snyk trying to autodetect for yarn.lock +0ms
  snyk trying to autodetect for package.json +0ms
  snyk analytics add local true +0ms
  snyk policies found [ 'C:\\Projects\\git\\testProj' ] +0ms
  snyk analytics add policies 1 +4s
  snyk analytics add packageManager npm +23ms
  snyk analytics add packageName test-project +0ms
  snyk analytics add packageVersion 1.3.1 +1ms
  snyk analytics add package test-project@1.3.1 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 278872 +2ms
  snyk Using proxy:  http://proxy.redactedcompany.com:83 +1ms
  snyk analytics add error-message socket hang up +72ms
  snyk analytics add error Error: socket hang up
    at C:\Program Files\nodejs\node_modules\snyk\cli\commands\test.js:135:21
    at tryCatch (C:\Program Files\nodejs\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\Program Files\nodejs\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\Program Files\nodejs\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\Program Files\nodejs\node_modules\snyk\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) +0ms
  snyk analytics add error-code ECONNRESET +1ms
  snyk analytics add command test +0ms
  snyk analytics { command: 'bad-command',
  args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     policies: 1,
     packageManager: 'npm',
     packageName: 'test-project',
     packageVersion: '1.3.1',
     package: 'test-project@1.3.1',
     'error-message': 'socket hang up',
     error: 'Error: socket hang up\n    at C:\\Program Files\\nodejs\\node_modules\\snyk\\cli\\commands\\test.js:135:21\n    at tryCatch (C:\\Program Files\\nodejs\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:410:12)\n    at invokeCallback (C:\\Program Files\\nodejs\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:425:13)\n    at publish (C:\\Program Files\\nodejs\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:393:7)\n    at flush (C:\\Program Files\\nodejs\\node_modules\\snyk\\node_modules\\es6-promise\\dist\\es6-promise.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
     'error-code': 'ECONNRESET',
     command: 'test' },
  version: '1.73.0',
  os: 'Windows 10',
  nodeVersion: 'v8.11.1',
  id: 'bed2181aa3ef16eddee7c33986e8a0c44c77b0b0',
  ci: false,
  durationMs: 4008 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +68ms
  snyk request body size: 1203 +0ms
  snyk Using proxy:  http://proxy.redactedcompany.com:83 +0ms
  snyk analytics { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' } +122ms
```

**Comment by adrukh** [comment]
@m-handy 
> Hi I would like to ask - do you think about rework of establishing HTTPS connection in your agent or can you suggest me different aproach how can I connect to your service from my CI? Thanks

Our CLI connects to snyk.io over HTTPS for security purposes. We have no plans to allow plain HTTP access to our servers. See bottom of message for troubleshooting advice.

@MichaelRVelasco 
> I'm also having an issue with my company's proxy.
From your debug output I see that the connection to our server is being hung up after 72 milliseconds from the moment the first request is made. The same fate awaits the analytics API call (this time after 122 milliseconds). Could it be that your proxy does not approve POST requests to snyk.io, expecting GET requests and such? I'm just guessing here..

My suggestion on how to debug this would be to see how a plain POST request can be made against https://snyk.io. You can attempt to hit the `/api/v1/verify/token` endpoint, posting an empty JSON body such as `{}` like so:
```
curl -i -X POST -H "content-type: application/json" -d '{}' https://snyk.io/api/v1/verify/token
```

A proper result would be similar to the following:
```
HTTP/2 401
x-snyk-version: undefined
x-frame-options: DENY
snyk-request-id: 0de9b38f-73b0-4912-a4a5-3999ed97c0a2
content-type: application/json; charset=utf-8
content-length: 26
etag: W/"1a-iCzAwKdSkIcBZlSRaGZFUtGWl0Q"
date: Sun, 22 Apr 2018 11:23:20 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: deny
strict-transport-security: max-age=31536000; preload

{"error":"Not authorised"}
```

Anything other than that would probably not be coming from our server.

We'd love to assist further - please email us at support@snyk.io with the exact output of your debug attempts and we'll take it from there.

**Comment by m-handy** [comment]
@adrukh With `curl` I got proper output - same as yours. And I agree with usage of secured connection. I'm not JS developer, so I can't tell you where, but it looks like CLI tool is establishing connection in different way - from our proxy logs it looks like it does directly `POST` request before establishing HTTPS connection with `CONNECT` method.

**Comment by adrukh** [comment]
@m-handy thanks for this input! Very insightful, as it makes me think our use of [needle](https://github.com/tomas/needle) does not fully support proxying for HTTPS - https://github.com/tomas/needle/issues/176.

Our use is quite simple, you can see it [here](https://github.com/snyk/snyk/blob/master/lib/request/request.js#L75-L81). I'll add this to the list of issues we can investigate, but don't have a specific timeline yet.

Would appreciate any effort the community can apply here 🙏  :)

**Comment by adrukh** [comment]
@m-handy good news! We've revamped our proxy support with https://github.com/snyk/snyk/releases/tag/v1.76.0, can you please give this a go and confirm?

**Comment by MichaelRVelasco** [comment]
@adrukh I test with version 1.78.0 and it works perfect behind the proxy now! Thank you!

**Comment by m-handy** [comment]
@adrukh I agree, it works now. Good job, thanks!
