### ISSUE TITLE
[🐛] Golang 2nd-level vunerabilities not flagged up with Snyk

### ISSUE THREAD

**Issue by axsaucedo** [snyk/snyk#1330]
- `node -v`: v13.1.0
- `npm -v`: 6.12.1
- `snyk -v`: 1.369.1 (standalone)
- OS: Linux
- Command run: `snyk test --all-projects`

### Overview

When running `snyk test` on a golang project with go.mod, only the 1st level vulnarabilities are checked. This is sub-optimal as this results in projects with 2nd level vulnerabilities from the projects that are imported - given that go is a static language, it actually compiles with all 2nd+ level versions, and vulnerabilities would still be present. 

Ideally the vulnerability checks should be performed with the output <s> of `go list -m all`</s> of `go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}' | sort -u`, as that lists all the 1st and 2nd+ level versions included in the project (also taking into account replace functions).

### Expected behaviour
Please share _expected_ behaviour.

Vulnerabilities from 2nd level dependencies in golang should be flagged

### Actual behaviour

Vulnerabilities from 2nd level dependencies in golang are currently not flagged.

### Steps to reproduce
This can be tested on our current repository:
1. Run `snyk test --all-projects` in https://github.com/SeldonIO/seldon-core/tree/master/operator
2. Confirm that none of the CVEs will flag up, these are the CVEs that should be flagged up from 2nd level deps https://github.com/SeldonIO/seldon-core/pull/2211

**Comment by axsaucedo** [comment]
Following up with this issue, we've done some experiments on golang package manaer (https://gitlab.com/rskolasinski/test-go-deps/final-progr) and it seems that the best way to find the exact packages the project is using is with the command `go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}' | sort -u` or viaa the `vendor/modules.txt`.

**Comment by anthogez** [comment]
Hi @axsaucedo, thanks for reporting this issue, we will check it and keep you updated, thanks! :)

**Comment by RafalSkolasinski** [comment]
Small variation of the above snippet that also seems to respect module replacement rules is
```bash
go list -deps -f '{{with .Module}}{{with .Replace}}{{.Path}} {{.Version}}{{else}}{{.Path}} {{.Version}}{{end}}{{end}}' | sort -u
```
this is however starting to be looking more and more obscure.

**Comment by axsaucedo** [comment]
Thank you @lili2311 - just wanted to follow up if there were any updates?

**Comment by lili2311** [comment]
hi @axsaucedo is the issue still occurring for you?

**Comment by lili2311** [comment]
@axsaucedo did you get a chance to confirm?

**Comment by lili2311** [comment]
@axsaucedo closing this issue, please re-open if the issue is still occurring and provide some fresh information. Thanks!
