### ISSUE TITLE
Feature Request: support lock files

### ISSUE THREAD

**Issue by cdanielsen** [snyk/snyk#134]
Been experimenting with integrating snyk into a CI chain, but if I understand correctly, the current version does not support lock files like `package-lock.json`? [Basing off of this](https://support.snyk.io/frequently-asked-questions/finding-vulnerabilities/does-snyk-work-with-shrinkwrap) and observed behavior.

This is problematic as I use the lock file and pinned dependencies to enforce a frozen dependency tree in a known state that can be upgraded intentionally over time. Not using this configuration, IMO, substantially weakens the value of a given `snyk test` report, as it's almost certain the resulting dependency tree will change on the next `npm install` even with the exact same `package.json` manifest of dependencies. Thanks for considering!

**Comment by adrukh** [comment]
@cdanielsen 
As far as the CLI goes, lockfiles are supported. When running `snyk wizard`, we detect the presence of a lockfile (`yarn.lock` or `package-lock.json`). If you choose to upgrade a dependency, the CLI will use the package manager to uninstall the existing dependencies and then install the upgraded version. 
This should update both `package.json` and `package-lock.json` in case of `npm@5`.
See https://github.com/snyk/snyk/blob/master/lib/protect/update.js#L71 for more details.

Please give it a try and let us know if something is not working as I described!

PS
The support article refers to lockfile support on our source-control integration which is in the works, but no exact timeframe just yet :)

**Comment by cdanielsen** [comment]
Ah, good to know about the CLI, but I mostly use snyk by integrating with my CI system and Github as I want to (as much as possible) automate the process of keeping my dependency tree in a good state re: vulnerabilities.

So is it accurate to say that running `synk test` locally in a project with a package-lock.json and the test that's generated via pull requests will likely produce different results?  If so, I'd probably want to remove the source control intergration and just have my CI run `snyk test` until they're in sync...

**Comment by adrukh** [comment]
A very valid point re comparison of CLI and PR test results. In the CLI case we have access to the dependencies as they were installed by the package manager, and generate objectively accurate results. In the PR test case, we extrapolate the dependencies from the manifest file at 'best effort' (for example, a privately scoped dependency won't be available for us, and we won't detect its vulnerable sub-dependencies).

I will generally say that CI/CD oriented customers tend to use our CLI, while dev-lifecycle oriented customers rely on our GitHub/GitLab/Bitbucket integration. The main question here is what is the best point in time to detect a vulnerability, and what it is that you are trying to prevent. If you don't want to deploy a vulnerable version of your app, CLI on CI/CD is the way to go. If you don't want to introduce a vulnerability to the codebase (observe some 'security watermark'), PR tests is the way to go.

Hope this helps!

**Comment by cdanielsen** [comment]
Definitely; thanks for the explanation!
