### ISSUE TITLE
[🐛] Could not detect supported target files

### ISSUE THREAD

**Issue by Drjacky** [snyk/snyk#1347]
- `node -v`: v14.7.0
- `npm -v`: 6.4.7
- `snyk -v`: 1.370.1 (standalone)
- OS: OSX macOS Catalina 10.15.6
- Command run: import projetc from Github in dashboard/web

### Expected behaviour
I expect I could import this project: https://github.com/Drjacky/OMDbMultiplatform

### Actual behaviour
It shows an error:
> - Could not detect supported target files. Please see our documentation for supported languages and target files.

### Steps to reproduce
Try to import https://github.com/Drjacky/OMDbMultiplatform.
It contains swift and kotlin languages

### Screenshots
![image](https://user-images.githubusercontent.com/2296754/90545689-4c97b000-e189-11ea-9ac0-792e19079a5f.png)

**Comment by lili2311** [comment]
hi @Drjacky unfortunately the message you are seeing is correct neither `*.swift` or `build.gradle.kts` are supported via Github import in UI.

You can use the CLI to scan Kotlin applications and for Swift we only at the moment support CocoaPods lock files.

Please have a look at our documentation for [Java](https://support.snyk.io/hc/en-us/articles/360003817357-Snyk-for-Java-Gradle-Maven-) & [Swift](https://support.snyk.io/hc/en-us/articles/360004701658-Snyk-for-Swift-and-Objective-C-CocoaPods-).

**Comment by realhuseynov** [comment]
> hi @Drjacky unfortunately the message you are seeing is correct neither `*.swift` or `build.gradle.kts` are supported via Github import in UI.
> 
> You can use the CLI to scan Kotlin applications and for Swift we only at the moment support CocoaPods lock files.
> 
> Please have a look at our documentation for [Java](https://support.snyk.io/hc/en-us/articles/360003817357-Snyk-for-Java-Gradle-Maven-) & [Swift](https://support.snyk.io/hc/en-us/articles/360004701658-Snyk-for-Swift-and-Objective-C-CocoaPods-).

why had not you supported "build.gradle.kts" files in Github import to UI yet?

**Comment by Drjacky** [comment]
@realhuseynov Sorry, I didn't get your question/solution!

**Comment by lili2311** [comment]
Kotlin projects are still not supported in Snyk UI (Git), you can review support here: https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-java-gradle-maven#git-services-for-maven-projects broken down by CLI vs Git.

For Swift we only support Podfile scanning in Git https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-swift-and-objective-c-cocoapods#git-services-for-cocoapods-projects
