### ISSUE TITLE
Snyk tries to run yarn remove on subdependencies

### ISSUE THREAD

**Issue by edrpls** [snyk/snyk#135]
- `node -v`: v9.5.0
- `npm -v`: 5.6.0
- `snyk -v`: 1.69.7
- Command run: snyk wizard

### Expected behaviour
Snyk should run the wizard and install the subdependencies without failing. It probably should not run `yarn remove` on subdependencies, just run yarn add on them.

### Actual behaviour
Snyk runs the `yarn remove` command including subdependencies, which gives a yarn error:

```
Applying updates using yarn...
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: Command failed: yarn remove  aws-sdk boom cryptiles epilogue hawk lodash request s3-uploader snyk
warning package.json: No license field
error This module isn't specified in a manifest.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

```
In this case, the subdependencies are `boom`, `cryptiles`, `hawk` and `request`.

### Steps to reproduce
Run `snek wizard` on a project with vulnerable subdependencies, like lodash on versions prior to  4.17.5, this will run y`arn remove lodash` which will give an error similar to the one above.

**Comment by adrukh** [comment]
@edrpls can I ask you for an example `package.json` and `yarn.lock` to reproduce this issue?
Also, version of `yarn` just to be precise?

**Comment by edrpls** [comment]
Sorry about the delay, my yarn version is:
yarn version v1.3.2

I will create tomorrow a demo project with the failing deps.

**Comment by adrukh** [comment]
I believe the culprit is here: https://github.com/snyk/snyk/blob/master/lib/protect/update.js#L71

We are eagerly trying to remove all dependencies that need to be updated (all dependencies along the path from the direct dependency to the vulnerable dependency), without acknowledging the fact that `yarn` only wants to remove direct deps, and will take care of the rest of the 'path'.

Just sharing for context, a demo project that fails on this will be very helpful!

**Comment by edrpls** [comment]
@adrukh I created a demo repo here:

https://github.com/edrpls/snyk-issue-135

But what I found is that I cannot reproduce the issues with the same dependency that is breaking our other projects. Now I believe that this has nothing to do with snek but instead with the build process we use for the failing library, since we build it on each client when yarn install is run, instead of building it on the publication step.

I will address that problem with our library and update this ticket just to confirm that the problem was on our side or if there is something else still happening.

**Comment by adrukh** [comment]
I believe the culprit is in additional constraints from your other project deps applied to the demo project dep, introducing a vuln by downgrading some transitive dependency. Please update here if you get a working replication of the issue.

**Comment by edrpls** [comment]
We refactored our library to compile on publish instead of on install and the issues are gone.
