### ISSUE TITLE
[🐛] Yarn Workspaces monorepo missing license for workspace package

### ISSUE THREAD

**Issue by SigurdMW** [snyk/snyk#1359]
- `node -v`: 12.13.1
- `npm -v`: 6.13.6
- `snyk -v`: 1.381.2
- OS: (e.g. OSX, Linux, Windows, ...) Windows
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...) snyk test --strict-out-of-sync=false --yarn-workspaces --detection-depth=4

### Expected behaviour
No license error

### Actual behaviour
so I have a Yarn Workspace with the following workspace folders:
* webapp
* shared
* dynamic-router 

These are **not**  NPM packages (we don't have them installed anywhere in the repo). However, I get this error message for all three of these:

 ✗ Unknown license (new) [High Severity][https://snyk.io/vuln/snyk:lic:npm:webapp:Unknown] in webapp@1.0.0
    Legal instructions:
    ○ for Unknown: Please report unrecognized open source licenses to Snyk support.

  ✗ Unknown license (new) [High Severity][https://snyk.io/vuln/snyk:lic:npm:shared:Unknown] in shared@1.0.0
    Legal instructions:
    ○ for Unknown: Please report unrecognized open source licenses to Snyk support.

  ✗ Unknown license (new) [High Severity][https://snyk.io/vuln/snyk:lic:npm:dynamic-router:Unknown] in dynamic-router@1.0.0
    Legal instructions:
    ○ for Unknown: Please report unrecognized open source licenses to Snyk support.

### Steps to reproduce
Create a new monorepo with Yarn, add in package.json:
`"workspaces": [
    "packages/*"
  ],`
create a folder `packages/webapp` and add a minimal `package.json` in it
run `yarn` and then run `snyk test --strict-out-of-sync=false --yarn-workspaces --detection-depth=4`

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 Hi @SigurdMW I see my colleague is helping you via our issue management tracker, so could we close this issue here and stick to all communication on the issue thread?

**Comment by SigurdMW** [comment]
Sure, lets close it

**Comment by SigurdMW** [comment]
This does seem like a bug to me. Could some of you test the repro steps I have written and see if you are able to reproduce? I currently had to turn off all Snyk testing in my project and it's less than ideal.

**Comment by lili2311** [comment]
hi @SigurdMW I can still see my colleagues are helping you on the internal issue tracker, let's chat there. I can respond there as well.

**Comment by lili2311** [comment]
I have responded directly there :)

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/issues/350

**Comment by lili2311** [comment]
Following our in person chat, closing this issue.
