### ISSUE TITLE
Invalid string length when attempting to snyk-protect package with symlinked dependencies

### ISSUE THREAD

**Issue by b-smets** [snyk/snyk#136]
- `node -v`: v8.9.4
- `npm -v`: 5.6.0
- `snyk -v`: 1.69.10

I have a lerna mono repo with a couple of packages. Each package has a number of dependencies and certain packages depend on other packages as well. Lerna ensures that these dependencies are symlinked together for ease of development. 
I ran `snyk wizard` in every package to generate the .snyk file and add the `snyk protect` targets where necessary. When running lerna bootstrap, dependencies are installed and local dependencies are replaced with symlinks. Afterwards, npm triggers the prepare phase which attempts to run `snyk protect` in one of my modules. This hangs for a while before resulting in an `Invalid string length` error. I assume this may be caused due to the large number of dependencies or the symlinks themselves.

To be clear: I do not have any circular dependencies.

### Expected behaviour
Snyk protect applies patches after running lerna bootstrap

### Actual behaviour
Snyk protect runs for a while before resulting in the Invalid String length error.

### Steps to reproduce
- Create a lerna monorepo containing a couple of packages
- Let each package include a number of dependencies 
- Let one package depend on another package 
- Run snyk wizard to generate the .snyk file (This will also add a snyk-protect script to the module, which can apply patches which will run in the prepare phase after installation)
- Run lerna bootstrap to establish a symlink between the package and the dependent package
=> This will trigger the prepare phase which will trigger `snyk protect` which results in the error below.
---

The output of snyk protect with the debug flag can be found here:
https://gist.github.com/b-smets/e9f247bd395f64504cfd77ed3671a3f2

Please let me know if there is any additional information I can provide to help diagnose this problem.

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, is this an issue for you?

**Comment by lili2311** [comment]
Closing, please re-open if needed.
