### ISSUE TITLE
Intermittent failure to produce report ("undefined vulnerabilities, undefined vulnerable paths")

### ISSUE THREAD

**Issue by dominykas** [snyk/snyk#138]
- `node -v`: v6.11.5
- `npm -v`: 3.10.10
- `snyk -v`: 1.69.6
- Command run: `snyk test --dev`

### Expected behaviour

Snyk reports results

### Actual behaviour

Snyk report:
```

Testing /var/lib/jenkins/jobs/wa2.pentest.master.export/workspace...


Organisation: undefined
Package manager: npm
Target file: package.json
Open source: yes

Tested /var/lib/jenkins/jobs/wa2.pentest.master.export/workspace for known vulnerabilities, found undefined vulnerabilities, undefined vulnerable paths.

Run `snyk wizard` to address these issues.
```

### Steps to reproduce

Unsure - this is completely intermittent, happens maybe once in ~100 runs. A re-run has so far been always successful.

We used to get some 5xx errors from the snyk service - we no longer seem to have those - could that be related to 5xx handling in the CLI?

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@dominykas please update to the latest release, we improved error reporting that used to cause this problem in https://github.com/snyk/snyk/releases/tag/v1.69.8

Please update with the exact error you see, we’d like to resolve it!

**Comment by dominykas** [comment]
Hmmm. This is odd. I thought we're running latest. Thanks, will check.

**Comment by adrukh** [comment]
@dominykas any updates on this one? Can you confirm the v1.69.8 or higher has this resolved?

**Comment by dominykas** [comment]
Haven't had any failures yet. Happy to reopen if I spot it again.
