### ISSUE TITLE
[🐛] 'gomodules' doesn't support graphs.

### ISSUE THREAD

**Issue by pohly** [snyk/snyk#1382]
- `node -v`: v10.21.0
- `npm -v`: 5.8.0
- `snyk -v`: 1.385.0
- OS: (e.g. OSX, Linux, Windows, ...) Linux
- Command run: `snyk monitor` in a Go project

### Expected behaviour

I expect this to create a new project in the web app. 

### Actual behaviour

It analyzes go dependencies, then fails with `'gomodules' doesn't support graphs.` Exit code is 2.

### Steps to reproduce

```
cd /tmp
git clone git@github.com:intel/pmem-csi.git
cd pmem-csi/
snyk monitor
```

### Debug log

```
Using a custom API endpoint from `snyk config` (tip: it should contain path to `/api`): https://xxxx/api
  snyk monitor { _: [ [Circular] ],
  debug: true,
  callGraphBuilderTimeout: '300' } +0ms
  snyk Processing /tmp/pmem-csi... +0ms
  snyk getDepsFromPlugin ... +2ms
Error: 
Monitoring /tmp/pmem-csi...

'gomodules' doesn't support graphs.
    at monitor (/usr/local/lib/node_modules/snyk/src/cli/commands/monitor/index.ts:298:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Implications

This blocks me from creating a project. Setting up a new project via the web interface does not work either because the web app (behind a company firewall) can't access the public GitHub repo (authentication fails because GitHub can't reach the web app).

**Comment by pohly** [comment]
`snyk test` works. But then I can't collaborate with others on scan results, right? I'm new to Snyk, so I am not sure how findings are supposed to be tracked and dealt with.

**Comment by aarlaud** [comment]
Hi, the issue has been identified and is specific to your environment. Your account team and the support team are working towards remediation and as such will reach out to apply the fix in your setup. James will reach out shortly.

**Comment by huornlmj** [comment]
@lili2311 Do you mind me asking what the issue was and the resolution?  Facing the same issue here.  Thanks.
