### ISSUE TITLE
"snyk test" with file on subdirectory [Gradle]

### ISSUE THREAD

**Issue by lbalmaceda** [snyk/snyk#139]
- `node -v`: 8.7.0
- `npm -v`:  5.6.0
- `snyk -v`: 1.70.2
- Command run: `snyk test --file lib/build.gradle`

### Expected behaviour
Tests run against Gradle using the `build.gradle` file of the module `lib`.

### Actual behaviour
Fails with the following stacktrace.
 
```sh
~/Android/Lock.Android  master ✔                                                                                         
▶ snyk test --file lib/build.gradle 
/Users/me/.nvm/versions/node/v8.7.0/lib/node_modules/snyk/cli/index.js:12
if (args.options.file && args.options.file.match(/\.sln$/)) {
                                           ^

TypeError: args.options.file.match is not a function
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v8.7.0/lib/node_modules/snyk/cli/index.js:12:44)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

### Steps to reproduce
1. Clone a repository with a Gradle project structure, such as [Lock.Android](https://github.com/auth0/lock.android).
1. `cd` into that directory
1.  run `snyk test --file lib/build.gradle`
---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
Yikes! We should be failing more gracefully here, sorry.

The solution is quite simple - please use the `=` sign like so: `--file=lib/build.gradle`

**Comment by lbalmaceda** [comment]
Yes! that works. Thanks @adrukh :)
