### ISSUE TITLE
Support for Visual Studio 2017 <packagereference> elements in project file

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#143]
In Visual Studio 2017 and dotnet core a new format for specifying nuget dependencies has been added it uses the new syntax to put references to packages in the project files themselves. This means that any `*.*proj` or `*.targets` or `*.props` file in a .NET solution is now a possible location where dependencies are specified:

Example of reference in project file:
https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.ServerPlugin/Aggregator.ServerPlugin.csproj#L139-L144

Example of reference in targets file:
https://github.com/tfsaggregator/tfsaggregator/blob/master/References/2018/config.targets#L5-L18
auto included through:
https://github.com/tfsaggregator/tfsaggregator/blob/master/Directory.Build.targets#L5

Other options to include extra targets:
```
before.{YourSolution}.sln.targets
after.{YourSolution}.sln.targets
```

This new format adds a couple of really powerful new behaviours, but I suppose it makes it harder for you to find the right references. Especially since reference inclusion can be made conditional through the `<choose><when>` and `<itemgroup condition="">` constructs and conditional targets inclusion..

**Comment by adrukh** [comment]
Thanks @jessehouwing really interesting and relevant. We'll touch base once improving .NET scanning is on our roadmap!

**Comment by tomkerkhove** [comment]
I would like to use this as well.

**Comment by bruno-garcia** [comment]
Right now at the root of the repo, I run:

` snyk test`

> Could not autodetect package manager for C:\Users\bruno\git\sentry-dotnet-platform-abstractions

And with:

`snyk test --packageManager=nuget`
> Could not determine manifest type for sentry-dotnet-platform-abstractions

The project is built, so under src\*\obj, `snyk` should find the `project.assets.json`.

**Comment by lili2311** [comment]
👋 Just an update that we know support `<PackageReference>` in our Web UI, please try this out and let us know if it helps your use case. On the CLI today we are relying on the project to be build to analyse it, so this should not affect which way you are specifying dependencies as we are able to process from whatever Nuget returns. 

Let me know if I can close this issue.
