### ISSUE TITLE
npm vulnerability failed with error [error]Bash exited with code '1' in azure devops pipeline

### ISSUE THREAD

**Issue by KiranManaguli-git1** [snyk/snyk#1436]
- `Language / Project Type:` [e.g angular 10...]
- `Package Manager / Build Tool:` [e.g.  npm, ...]

I am new to Devops and we have a existing pipeline that was working till today but suddenly pipeline failed with error below please help me on the same..

found 322 vulnerabilities (321 low, 1 high) in 1667 scanned packages
run `npm audit fix` to fix 322 of them.
[debug]Exit code 1 received from tool '/bin/bash'
[debug]STDIO streams have closed for tool '/bin/bash'
[error]Bash exited with code '1'.
[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
[debug]task result: Failed
[debug]Processed: ##vso[task.complete result=Failed;done=true;]
[section]Finishing: npm install and build

**Comment by JackuB** [comment]
Hi, is this the full log? It seems like something is missing. Could you also share your azure pipeline settings?

**Comment by JackuB** [comment]
I'm closing this issue as we haven't heard back. Feel free to open a new one or contact our support.
