### ISSUE TITLE
Update Snyk docs to include TFS and VSTS as possible targets

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#144]
Simplest docs would be to run `npm install snyk@latest` followed by running snyk from a `run command` task. Which is supported out of the box on VSTS as well as TFS 2015 - 2018.

The more complex doc would include the extension I wrote last year:
https://marketplace.visualstudio.com/items?itemName=jessehouwing.vsts-snyk

**Comment by lili2311** [comment]
Can this be closed as the plugin is deprecated?

**Comment by jessehouwing** [comment]
Should now point to: https://marketplace.visualstudio.com/items?itemName=Snyk.snyk-security-scan. And by now be called `Azure DevOps` and `Azure DevOps Server`.
