### ISSUE TITLE
Error with Travis & snyk-protect

### ISSUE THREAD

**Issue by Aarbel** [snyk/snyk#145]
- `node -v`: 8.9.3
- `yarn -v`: 1.3.2
- `snyk -v`: 1.70.3
- Command run : npm run snyk protect

![image](https://user-images.githubusercontent.com/25119847/38164878-77585aec-350b-11e8-9e44-b89b21e9495b.png)

Hi Snyk teams, i've got this error running my tests with Travis (my tests run inside docker container), what could be the best way to debug it ? Thanks a lot ! 

Note : lines 723 and 724 are just warnings, nothing linked with Snyk

**Comment by adrukh** [comment]
@aarbel this error indicates that the snyk policy file `.snyk` is missing.

Could it be that you are running `npm install` after copying the manifest files into the docker image? Just make sure you also copy `.snyk` into the image.

**Comment by Aarbel** [comment]
@adrukh Perfect that solved the problem ! 

in my Dockerfile.dev : 
```
…
COPY api-server/.snyk ./
…
```
