### ISSUE TITLE
[🙏] configure commit message

### ISSUE THREAD

**Issue by cyberhck** [snyk/snyk#1472]
- `Language / Project Type:` npm / but applies to all language
- `Package Manager / Build Tool:` npm / but applies everywhere

**Describe the user need**
Snyk is doing a good job sending PRs to update dependency, everything's well, but it's using invalid commit message. If it's a security fix then yes, a commit message with `fix` is appropriate, but if it's just updating typescript or any devDependency from one version to another, then why would you use `fix` on a commit message? This triggers a release in our case without any meaningful update for the user.

Snyk should use `chore` for devDependency updates, not `fix` as for dependency updates, if it's a security update, then fix would be okay, but not if just a normal update without vulnerability being fixed.

**Describe expected behaviour**

```
if (devDependency || !update.fixedSecurityIssue) {
  return `chore: ....`;
}
return `fix: ...`;
```

**Additional context**
Need to think which upgrade is worth creating a new release over, fixing a security issue? Yes, upgrading jest to a newer version? No!

If there's an option available already, please let me know, because I couldn't find it on the UI. I'm using the github app integration, no cli, no configuration, nothing.

**Comment by JackuB** [comment]
Hi, thanks a lot for this. We are discussing this change internally.

**Comment by JackuB** [comment]
Hi, we are planning to improve the commit messages in Upgrade & Fix PRs. We are thinking about making them follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Don't have any timeline at this point.
Again, thank you for the suggestion!

I'm closing this issue now, as we don't want to use GitHub issues as a feature tracker. You can follow https://updates.snyk.io for new features and improvements.
