### ISSUE TITLE
Snyk monitor undefined error

### ISSUE THREAD

**Issue by melinmedicalutvikling** [snyk/snyk#148]
- `node -v`: v9.11.1
- `npm -v`: 5.6.0
- `snyk -v`: 1.70.3
- Command run: snyk monitor

### Expected behaviour
Normal snyk monitor behaviour (create the project and run vulnerability test in platform.)

### Actual behaviour
Command takes forever and then error occurs. 
/Users/user/Development/project`, unexpected error: undefined

Snyk test command works just find. 
This is happening to some of our php projects with composer.lock

For path `/Users/user/Development/project`, unexpected error: undefined
  snyk analytics { command: 'monitor',
  args: [ { debug: true } ],
  metadata: { packageManager: 'composer' },
  version: '1.70.3',
  os: 'OS X',
  nodeVersion: 'v9.11.1',
  id: '',
  ci: false,
  durationMs: 301673 } +5m
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +5m
  snyk request body size: 229 +0ms
  snyk Not using proxy +0ms

**Comment by melinmedicalutvikling** [comment]
Yes, I will contact you there. Thank you very much.

**Comment by m-handy** [comment]
Hi,
I'm facing similar issue:

C:\__GIT\project>snyk monitor -d
  snyk monitor { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder C:\__GIT\project +0ms
  snyk trying to autodetect for yarn.lock +0ms
  snyk trying to autodetect for package.json +1ms
  snyk trying to autodetect for Gemfile +0ms
  snyk trying to autodetect for Gemfile.lock +1ms
  snyk trying to autodetect for pom.xml +0ms
  snyk trying to autodetect for yarn.lock +0ms
  snyk trying to autodetect for package.json +1ms
  snyk trying to autodetect for Gemfile +16ms
  snyk trying to autodetect for Gemfile.lock +1ms
  snyk trying to autodetect for pom.xml +0ms
  snyk analytics add packageManager maven +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/maven +0ms
  snyk request body size: 623695 +0ms
  snyk analytics add payloadSize 623695 +12ms
  snyk not using proxy +1ms
For path `C:\__GIT\project`, unexpected error: undefined
  snyk analytics { command: 'monitor',
  args: [ { debug: true } ],
  metadata: { packageManager: 'maven', payloadSize: 623695 },
  version: '1.82.0',
  os: 'Windows 10',
  nodeVersion: 'v10.2.1',
  id: '*censored*',
  ci: false,
  durationMs: 325526 } +5m
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +5m
  snyk request body size: 253 +0ms
  snyk not using proxy +1ms
/ Posting monitor snapshot for pom.xml ...

**Comment by adrukh** [comment]
@melinmedicalutvikling we've improved a lot since version 1.70.3, can you give this a try on our latest CLI version and see if the problem is now resolved?

**Comment by lili2311** [comment]
Closing this issue, please re-open if the issue persists.

**Comment by alterEgo123** [comment]
This issue persists.
Using:
Snyk 1.323.0
npm 3.5.2
node v12.16.3
