### ISSUE TITLE
Pipfile: test should not update Pipfile.lock? 

### ISSUE THREAD

**Issue by damycra** [snyk/snyk#1487]
I run snyk manually\* from time to time in dev using the python-3 Docker image (lightly modified to allow psycopg2 to install, as I recall) but recently I was surprised to see my _Pipfile.lock_ being updated by the process. Therefore the test runs against an updated _Pipfile.lock_ and **not** the _Pipfile.lock_ that's committed (and is probably being built by Jenkins). 

Should it be
~~pipenv lock~~
`pipenv install --system --deploy`
https://github.com/snyk/snyk/blob/f35f39e96ef7aa69b22a846315dda015b12a4564/docker/docker-python-entrypoint.sh#L25

See also [Using pipenv for deployments](https://pipenv.pypa.io/en/latest/advanced/#using-pipenv-for-deployments).

Of course, my assumption is that _Pipfile.lock_ is always committed. Perhaps it should indeed run `pipenv lock` if one does not exist although this reduces the accuracy of the result. 

Happy to submit PR if desirable.

\* I appreciate that this is not how I should be doing it, so feel free to ignore me entirely! I `pipenv update` in dev then run tests locally before committing the _Pipfile.lock_ — then Jenkins takes over. If I run snyk at the beginning of this process, all is well; but if snyk was running in CI the problem recurs (with a small but definitely finite chance that libs will have updated between my local `pipenv update` and `snyk test`).

**Comment by lili2311** [comment]
hi @damycra I can't think of any reason why it is doing that and I added it 🤔 If you are able to raise the PR to remove this, I can check with the relevant team to make sure they can review and are happy with this change.

**Comment by damycra** [comment]
Thanks @lili2311 — 
the only reason I could see was if there was no Pipfile.lock, but I am conscious that I spend very little time on `pipenv` and only as an _end-user_ i.e. not a library maintainer or anything. So there may be something else hiding in there and I would hate to break everyone's scans! No worries if the risk/reward case for this chance can't be made, I am happy with my workflow for now.  

It seems like a `pipenv` bug that a harmless Mac only dependency is dropped by `pipenv lock`, so perhaps I should raise that with them, too.

**Comment by lili2311** [comment]
@damycra your contribution has now been merged 🎉 Did that solve your issue? Can we close this?

**Comment by damycra** [comment]
Thanks @lili2311 yes that fixes my issue. (While I'm here, are there any plans to push the Dockerfile.python-3.8 artefact to DockerHub?)

**Comment by lili2311** [comment]
This was released a few weeks ago: https://github.com/snyk/snyk/commit/dfa7565774256804dee1228c4326371b62ebeebf but I can't see the tag in docker hub, I'll check with the team.

**Comment by lili2311** [comment]
@damycra You can grab it here: https://hub.docker.com/layers/snyk/snyk/python-3.8
