### ISSUE TITLE
 Snyk under a corporate proxy: Check your network connection, failed to connect to Snyk API

### ISSUE THREAD

**Issue by remojansen** [Snyk/snyk#15]
- `node -v`: v4.2.1
- `npm -v`: 2.14.7
- `snyk -v`: 1.11.0
- Command run:
```
$ snyk test
```

### Expected behaviour
Show results

### Actual behaviour
```
Check your network connection, failed to connect to Snyk API
```
### Steps to reproduce
Run Snyk under a corporate proxy.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensistive/personal details or tokens.

```
$  snyk test --debug
Mon, 22 Feb 2016 11:29:22 GMT snyk test { _: [ [Circular] ], debug: true }
Mon, 22 Feb 2016 11:29:23 GMT snyk checking for cli updates
Mon, 22 Feb 2016 11:29:23 GMT snyk add local true
Mon, 22 Feb 2016 11:29:28 GMT snyk add package cpic-ui-web@1.0.0
Mon, 22 Feb 2016 11:29:28 GMT snyk policies found [ 'C:\\Dev\\CPIC.SPA\\trunk\\CPIC.SPA' ]
Mon, 22 Feb 2016 11:29:28 GMT snyk add policies 1
Mon, 22 Feb 2016 11:29:29 GMT snyk add error Error: connect ECONNREFUSED 104.101.180.69:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
Error: connect ECONNREFUSED 104.101.180.69:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
Mon, 22 Feb 2016 11:29:29 GMT snyk { command: 'test', args: [ { debug: true } ], metadata: { local: true, package: 'cpic-ui-web@1.0.0', policies: 1, error: 'Error: connect ECONNREFUSED 104.101.180.69:443\n    at Object.exports._errnoException (util.js:874:11)\n    at exports._exceptionWithHostPort (util.js:897:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)' }, version: '1.11.0', os: 'Windows 7', id: '08c85b01a17019b0e91821b0efe081afd6658dc5', ci: false }
Mon, 22 Feb 2016 11:29:30 GMT snyk Error: connect ECONNREFUSED 104.101.180.69:443
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

```

I couldn't find anything online about configuring proxy settings.

**Comment by remojansen** [comment]
Hi I just got an answer via the support chat:

> We use request internally for the API calls which should support environment variables to control proxy usage. See the documentation here for more information: https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables
We use SSL for all api requests so HTTPS_PROXY should be the environment variable that you need.
Let me know if this doesn't work for you or if it doesn't satisfy your use-case.

I'm documenting it here so when others have the same issue can find a solution online.

**Comment by remy** [comment]
This is great - thanks for digging into it. I'll raise an internal issue and see if we can make this a configuration that you set once and snyk will reuse it when running the `request` calls.

**Comment by remojansen** [comment]
Hi guys I followed [this](http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows) to set up environment variables  with no luck:
```
$  set http_proxy=http://xx.x.xxx.xxx:8080 && https_proxy=http://xx.x.xxx.xxx:8080 && snyk test
```
In other node tools like npm I use `.rc` files like:

```
proxy=http://xx.x.xxx.xxx:8080
strict-ssl=false
```
Maybe my problem is that our proxy don't work under strict-ssl?

**Comment by remy** [comment]
@remojansen thanks for the update. I'm going to take a look at the npm source code to see how they're making their requests. My gut feeling it's with `request` also, but maybe the `strict-ssl` is being handled specifically.

**Comment by remy** [comment]
@remojansen I appreciate this reply is a long time waiting, but I'm testing this locally and getting very different results.

Can you try the following (where `$` is the prompt)?

```
$ https_proxy=http://x.x.x.x:8080/ snyk test
```

When I test it using Charles as a test proxy, I get messages about self signed certs (probably because I've not set my proxy up correctly). What do you see when you try this?

**Comment by remy** [comment]
Hi @remojansen any chance you could take a look at my last comment and let me know if this works for you? https://github.com/Snyk/snyk/issues/15#issuecomment-204361292

**Comment by remojansen** [comment]
Hi @remy sorry but I don't work anymore in the network where I was experiencing the issues so I won't be able to test it. I'm using Snyk on my home network and an open-source project and works great :)

**Comment by lirantal** [comment]
I can confirm that working in an enterprise where we have proxies I had no issues to run snyk CLI.
So at least for my network configuration it works well.

**Comment by remy** [comment]
@lirantal thank you so much for your comment! 👍 it means I can strike off a jira ticket that's been staring at me for nearly a month 😄

**Comment by remojansen** [comment]
@remy thanks for taking a look, sorry I could not help more...

**Comment by getglad** [comment]
I am having a similar, but slightly different issue. I'm getting `self signed certificate in certificate chain` when I run `snyk wizard`.

I am assuming somewhere in the process snyk invokes NPM? I have my system NPM setup to use our firewall network `npm -g config set ca=”-----BEGIN CERTIFICATE----- … -----END CERTIFICATE-----“` - but in my experience each node process needs to be given the certificate. _SO_ if `snyk` creates it's own node process then invokes NPM from inside that, I think there needs to be a way to pass the certificate to `snyk`.

(Full disclosure: I am not a network guy, and do not have a super deep knowledge of NPM, but that is what my team has done to be able to work with NPM and Node processes running on the same machine)
