### ISSUE TITLE
Unknown error while running snyk wizard

### ISSUE THREAD

**Issue by karthiknvlr** [snyk/snyk#150]
- `node -v`: v8.11.1
- `npm -v`:  5.8.0
- `snyk -v`: 1.72.0

- Command run:
snyk wizard

### Expected behaviour
Suggestions to mitigate the found vulnerability in node project.

### Actual behaviour
thrown some unkown error

### Steps to reproduce
snyk auth
snyk ionic
snyk wizard

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

snyk analytics add error-message 413 +2s
  snyk analytics add error Error: 413
    at /usr/lib/node_modules/snyk/lib/snyk-test/npm/index.js:127:23
    at /usr/lib/node_modules/snyk/lib/request/index.js:12:7
    at tryCatch (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) +0ms
  snyk analytics add error-code 413 +0ms
  snyk analytics add command wizard +0ms
Error: 413
    at /usr/lib/node_modules/snyk/lib/snyk-test/npm/index.js:127:23
    at /usr/lib/node_modules/snyk/lib/request/index.js:12:7
    at tryCatch (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  snyk analytics { command: 'bad-command',
  args: 
   [ { debug: true,
       packageManager: 'npm',
       newPolicy: true,
       ignoreDisabled: false,
       file: 'package.json' } ],
  metadata: 
   { 'inline-auth': false,
     local: true,
     policies: 1,
     packageManager: 'npm',
     packageName: 'nodestarter',
     packageVersion: '1.0.0',
     package: 'nodestarter@1.0.0',
     'error-message': '413',
     error: 'Error: 413\n    at /usr/lib/node_modules/snyk/lib/snyk-test/npm/index.js:127:23\n    at /usr/lib/node_modules/snyk/lib/request/index.js:12:7\n    at tryCatch (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)\n    at invokeCallback (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)\n    at publish (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)\n    at flush (/usr/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
     'error-code': 413,
     command: 'wizard' },
  version: '1.72.0',
  os: 'Linux 4.13',
  nodeVersion: 'v8.11.1',
  id: 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  ci: false,
  durationMs: 14854 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +1s
  snyk request body size: 1184 +0ms
  snyk Not using proxy +0ms

**Comment by adrukh** [comment]
@karthiknvlr error 413 most likely means that the request body was too large for our servers to handle. Can you share the whole output of the debug command? Perhaps do so with support@snyk.io so we can keep better track of the issue?

**Comment by karthiknvlr** [comment]
@adrukh  I have sent a mail to you with debug output.

**Comment by adrukh** [comment]
@karthiknvlr thanks for your patience here!

We improved quite a few things relating to payload sizes, please try out the latest CLI release (1.89.0 right now) and see if the issue is resolved.

**Comment by lili2311** [comment]
@karthiknvlr is this now resolved for you?

**Comment by karthiknvlr** [comment]
Yes It's been resolved
