### ISSUE TITLE
[🐛]High severity vulnerability found in Snyk itself

### ISSUE THREAD

**Issue by jaffersadhique** [snyk/snyk#1522]
- `node -v`: 12.19.0
- `npm -v`:6.14.8
- `snyk -v`: 1.425.2
- OS: (e.g. OSX, Linux, Windows, ...) OSX
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...) snyk test .

### Expected behaviour
Snyk test should pass when we run the command snyk test command. But it's failed due to one of its dependencies.

### Actual behaviour
Snyk test command is failing due to one of its dependencies.

```
Issues with no direct upgrade or patch:
--
120 | ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-Y18N-1021887] in y18n@3.2.1
121 | introduced by snyk@1.425.2 > snyk-config@3.1.1 > nconf@0.10.0 > yargs@3.32.0 > y18n@3.2.1 and 4 other path(s)
122 | This issue was fixed in versions: 5.0.5

```

### Steps to reproduce
Run snyk test command after installing SNYK. Due to the referring the outdated y18n dependency, it's failing.

**Comment by JackuB** [comment]
Hi, you are right, we are looking into our options of updating or removing the vulnerable package.

**Comment by JackuB** [comment]
We've removed the affected module `y18n` in CLI in v1.425.4 https://github.com/snyk/snyk/releases/tag/v1.425.4

Thank you for bringing this up! I'm closing this issue now.
