### ISSUE TITLE
[🙏] Support configurable (or semantic) PR titles

### ISSUE THREAD

**Issue by lshadler** [snyk/snyk#1547]
- `Language / Project Type:` Javascript
- `Package Manager / Build Tool:` Yarn/NPM

**Describe the user need**

My team uses [semantic-release](https://github.com/semantic-release/semantic-release) in our project and are looking to automate some of our Snyk patches. We are confident in our unit and automation testing, but `semantic-release` and projects like it rely on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), meaning that the structure of the commit message is important.

**Describe expected behaviour**

We would like to configure a conventional commit from Snyk, likely based on the mergeability score. If the score is above 900 (out of 1000), we would have the format be

```
fix(snyk): {{ normal Snyk message here }}
```

The above will trigger a patch release of our project. For other changes that may require additional work to merge, we would like to trigger a minor bump like:

```
feat(snyk): {{ normal Snyk message here }}
```

**Additional context**

In our current state, we should be able to just change the PR title, but automating this would allow us to use Snyk at scale across our projects!

**Comment by JackuB** [comment]
Hi! Similar to the issue https://github.com/snyk/snyk/issues/1472, we are planning to improve our commit messages in Fix & Upgrade PRs. We are thinking about making them follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) first. Don't have any timeline at this point. Rule-based customization like yours suggestion is not planned at this point.

I'm closing this issue now, as we don't want to use GitHub issues as a feature tracker. You can follow https://updates.snyk.io for new features and improvements.
