### ISSUE TITLE
[🐛] Snyk doesn't detect vulnerabilities in workspaces when --yarn-workspaces is used

### ISSUE THREAD

**Issue by ebickle** [snyk/snyk#1560]
- `node -v`: v14.15.1
- `npm -v`: 6.14.9
- `yarn -v`: 1.22.4
- `snyk -v`: 1.434.4
- OS: Windows 10 Version 2004
- Command run: `snyk test --yarn-workspaces`

### Expected behaviour
Snyk should report vulnerabilities in workspace packages.

### Actual behaviour
Snyk does not find vulnerabilities that exist in workspace packages when `--yarn-workspaces` is used. Snyk's debug output reports that the workspace package.json "is not part of any detected workspace, skipping".

### Steps to reproduce
* Create a package.json file in the working directory. Add `"workspaces": ["packages/component1"]` to it.
* Create a package.json file in the subdirectory "packages/component1". 
* `cd` into `packages/component1` and type `yarn add underscore.string@3.3.4`.
* `cd` back to original parent working directory.
* Type `yarn install`. Note that it installs the dependency in the child workspace and generates a `yarn.lock` file in the parent working directory with underscore.string 3.3.4 in it. This library has a vulnerability.
* Type `snyk test --yarn-workspaces -d`.

Note that Snyk incorrectly reports there are "no vulnerable paths" despite the yarn.lock file and workspace package.json file containing a vulnerability. Review the debug output and note that the packages/component1/package.json file is incorrectly skipped/ignored. No errors or warnings are displayed.

This issue appears to be independent of the related https://github.com/snyk/snyk/issues/1559 bug.

It's worth noting that this issue appears to be a catastrophic bug in `--yarn-workspaces` making that specific Snyk feature inoperable. Snyk dangerously reports zero vulnerabilities without any warnings or other indication something might have gone wrong.

### Debug log
```
PS C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2> snyk test -d --yarn-workspaces
  snyk test <ref *1> {
  _: [ [Circular *1] ],
  debug: true,
  yarnWorkspaces: true,
  callGraphBuilderTimeout: '300'
} +0ms
  snyk-test auto detect manifest files, found 2 [
  'C:\\Users\\username\\Desktop\\snyk-test\\sample-yarn-lock-2\\package.json',
  'C:\\Users\\username\\Desktop\\snyk-test\\sample-yarn-lock-2\\packages\\component1\\package.json'
] +0ms
  snyk-yarn-workspaces Processing potential Yarn workspaces (2) +0ms
  snyk-yarn-workspaces C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2\packages\component1\package.json is not part of any detected workspace, skipping +11ms
  snyk-test Found 1 projects from 2 detected manifests +13ms
  snyk Potential policy locations found: [ 'C:\\Users\\username\\Desktop\\snyk-test\\sample-yarn-lock-2' ] +0ms
  snyk:find-files Encountered multiple node lockfiles files, defaulting to C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2\yarn.lock +0ms
  snyk:run-test converting dep-tree to dep-graph { name: 'sample', targetFile: 'package.json' } +0ms
  snyk:run-test done converting dep-tree to dep-graph { uniquePkgsCount: 1 } +3ms
  snyk:prune rootPkg { name: 'sample', version: '1.0.0' } +0ms
  snyk:prune prePrunePathsCount: 1 +0ms
  snyk:prune isDenseGraph false +1ms
  snyk sending request to: https://snyk.io/api/v1/test-dep-graph +0ms
  snyk request body size: 473 +0ms
  snyk gzipped request body size: 296 +0ms
  snyk not using proxy +1ms

Testing C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2...

Organization:      asurion
Package manager:   yarn
Target file:       package.json
Project name:      sample
Open source:       no
Project path:      C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2
Licenses:          enabled

✓ Tested C:\Users\username\Desktop\snyk-test\sample-yarn-lock-2 for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
  snyk analytics {
  args: [
    {
      debug: true,
      yarnWorkspaces: true,
      callGraphBuilderTimeout: '300',
      org: undefined,
      showVulnPaths: 'some'
    }
  ],
  command: 'test',
  org: undefined,
  metadata: {
    local: true,
    yarnWorkspaces: {
      scannedProjects: 1,
      targetFiles: [Array],
      packageManagers: [Array],
      levelsDeep: undefined,
      ignore: [Array]
    },
    pluginName: 'snyk-nodejs-yarn-workspaces',
    policies: 1,
    policyLocations: [
      'C:\\Users\\username\\Desktop\\snyk-test\\sample-yarn-lock-2'
    ],
    packageManager: 'yarn',
    packageName: 'sample',
    packageVersion: '1.0.0',
    package: 'sample@1.0.0',
    prePrunedPathsCount: 1,
    payloadSize: 473,
    gzippedPayloadSize: 296,
    depGraph: true,
    isDocker: false,
    'vulns-pre-policy': 0,
    vulns: 0
  },
  version: '1.434.4',
  os: 'Windows 10',
  nodeVersion: 'v14.15.1',
  standalone: false,
  integrationName: '',
  integrationVersion: '',
  integrationEnvironment: '',
  integrationEnvironmentVersion: '',
  id: 'bb9595d2f9f7ddbbc46cd1f7eedbc7d8d76770b4',
  ci: false,
  durationMs: 2783,
  metrics: {
    network_time: { type: 'timer', values: [Array], total: 2312 },
    cpu_time: { type: 'synthetic', values: [Array], total: 471 }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +3s
  snyk request body size: 1215 +45ms
  snyk gzipped request body size: 592 +1ms
  snyk not using proxy +1ms
```

**Comment by candrews** [comment]
What is the latest news on this issue?

**Comment by lili2311** [comment]
Hi @ebickle we found a bug with Windows + `--yarn-workspaces` support. Once the fix is merged I expect your scan to correctly match the `package.json` files of the workspaces as belonging to a Yarn workspace. This means each test will correctly detect and report on every package.json not just the root package.json. I will let you know once you can try again

**Comment by lili2311** [comment]
@ebickle a fix has been released for a bug that was preventing matching a package.json to a workspace on Windows, please could you try again with the latest CLI version? https://github.com/snyk/snyk/releases/tag/v1.750.0

**Comment by ebickle** [comment]
@lili2311 Confirmed that the fix works on my machine. Snyk 1.749.0 reported no vulnerabilities in my test project, Snyk 1.750.0 worked correctly and showed the vulnerabilities.

Thanks to you and the team! Appreciate the help.
