### ISSUE TITLE
[🙏] Remove --yarn-workspaces and make it the default behavior of Snyk

### ISSUE THREAD

**Issue by ebickle** [snyk/snyk#1561]
- `Language / Project Type:`JavaScript
- `Package Manager / Build Tool:` npm and/or yarn

**Describe the user need**
NPM 7.0 added native support for Workspaces, a feature that was previously limited to yarn. Now that workspaces is a core, standardized feature of package.json files, Snyk has a number of UI/UX deficiencies:
* The `--yarn-workspaces` argument is named after "Yarn", even though it's an NPM feature as well now.
* There is no warning, error, or informational message alerting users of "workspace packages" that Snyk will not detect vulnerabilities if `--yarn-workspaces` is not supplied as a CLI argument.

I propose that the `--yarn-workspaces` CLI argument be removed and instead have Snyk automatically analyze all `package.json` workspaces. Failing to do this by default means that users will always miss vulnerabilities - currently this happens with **zero warning**, making the use of workspaces and Snyk very risky. In our own situation we've found dozens of repositories where Snyk is completely missing hundreds of vulnerabilities that exist in them due to the use of workspaces.

**Describe expected behaviour**
Snyk should support core NPM / package.json features by default. If that is not possible, Snyk should fail with an error code by default when scanning a package.json file with workspaces. (e.g. `--ignore-workspaces` could be added to continue without exiting with an error). There is no scenario where a user would expect Snyk to silently continue and miss vulnerabilities by default.

**Comment by lili2311** [comment]
Hi @ebickle thanks for raising this! do you have an example npm workspaces repository we can use to 👀 at. There is possibility to bring in `--yarn-workspaces` as part of `--all-projects` scanning we still need to review how it can work if no arguments are passed in. Example repository will really help us do some research thanks!

**Comment by ebickle** [comment]
Thanks @lili2311! As I mentioned over at https://github.com/snyk/snyk/issues/1561 I should be able to send a complex repository structure over your way that would make a useful "real world" example for the Snyk team. Will be sometime the first week of January, if that's okay.

The big thing for me is making sure there aren't any "traps" users can fall into - what's happening with us is that we have a lot of teams wanting to try out new and fun things (large mono repos) and they have no idea that Snyk isn't properly finding their vulnerabilities. Most people don't know they should use `--yarn-workspaces` and even if we do, it's hard for our automated tooling to use it because it's difficult to determine in advance if it's needed in a sort of generic scripting sort of way.

Same goes for APIs - many of our tools cal your APIs directly and pass in a package file and lockfile - there's no equivalent option in the API similar to yarn-workspaces which makes me wonder if we're missing things there. My hope is that it can either be completely seamless or at least give an error of some sort to notify users they need to do something different.

**Comment by ebickle** [comment]
Just a quick heads up that I haven't forgotten this and I'm working through some email blocking issues. Should have the files over to you in the next few days.

**Comment by ebickle** [comment]
The sample repository structure should now be attached to internal ticket #8157.

**Comment by candrews** [comment]
What's the latest news on this issue?

We really need `--all-projects` to imply `--yarn-workspaces` as described at https://github.com/snyk/snyk/issues/1561#issuecomment-750354789

**Comment by candrews** [comment]
I've reported this issue at https://support.snyk.io/hc/en-us/requests/14135

**Comment by nyanshak** [comment]
I have also submitted a request to support: https://support.snyk.io/hc/en-us/requests/14887.

**Comment by lili2311** [comment]
Hi all! We are in the process of spiking what support will look like https://github.com/snyk/snyk/pull/2341 will keep you updated on further developments and if this is something we can release soon.

**Comment by candrews** [comment]
> `--all-projects` now automatically detects and scans Yarn workspaces projects too. The original command `--yan-workspaces` remains the same and staying for now at least.

Could you please update the documentation at https://docs.snyk.io/features/snyk-cli/guides-for-our-cli/cli-reference#options accordingly?

**Comment by ebickle** [comment]
Documentation appears to be updated as well, and an issue I had with multiple Yarn lockfiles in the same repo was just resolved. Appreciate all the help fixing these issues!
