### ISSUE TITLE
Add support for organization env var

### ISSUE THREAD

**Issue by omerlh** [snyk/snyk#157]
Currently, you need to specify organization on each command by using `--org=`. 
Can this be configured with env var?

**Comment by michael-go** [comment]
Hi @omerlh.

TL;DR yes: 
```
$ export SNYK_org=<my-org>
$ snyk test
```

`snyk` uses the `snyk-config` package to manage it's config options, and it allows also setting all options via env vars as see here: https://github.com/snyk/config#cli

**Comment by omerlh** [comment]
thanks! worth also adding it to the readme, if you want I can create a PR.

**Comment by michael-go** [comment]
Thanks @omerlh. I think we should add it across all our docs (https://snyk.io/docs/using-snyk too), and we should make sure it indeed works for all available options, so we'll just do that as part of that.
Cheers 🤗
