### ISSUE TITLE
Add support for build.gradle.kts files for Gradle projects

### ISSUE THREAD

**Issue by tbroyer** [snyk/snyk#158]
Gradle builds can use Kotlin instead of Groovy for their build scripts; the Kotlin build scripts are written in `build.gradle.kts` files.

This would allow such projects to be checked through the GitHub integration, as currently I believe (haven't tested yet) you'd have to use the Snyk CLI with `--file=build.gradle.kts --package-manager=gradle` (or possibly only `--package-manager=gradle`, but still)

**Comment by adrukh** [comment]
@tbroyer thanks for this suggestion! Indeed the `--file` and `--package-manager` flags allow for some 'hidden' flexibility of the CLI.

Not being too familiar with Kotlin, I wonder whether the basic Gradle dependency parsing logic works the same way for `build.gradle.kts` files. Consider the command we construct at https://github.com/snyk/snyk-gradle-plugin/blob/master/lib/index.js#L67-L70 (the generic case would yield `gradle dependencies -q`, would you say it is expected to work if added with `--build-file build.gradle.kts`?

**Comment by tbroyer** [comment]
It **will** work exactly the same, yes. It's almost as if you were using TypeScript vs. CoffeeScript: under the hood it's a JS engine exposing the same objects; here Kotlin and Groovy both run a JVM and call the same Gradle APIs.

**Comment by adrukh** [comment]
Ok, in that case, `snyk test --file=build.gradle.kts --package-manager=gradle` is the way to go for now.

Once we move towards Kotlin support, we may want to make it more straightforward.

**Comment by tbroyer** [comment]
Correct me if I'm wrong but wouldn't adding `build.gradle.kts` to `DETECTABLE_FILES` and `DETECTABLE_PACKAGE_MANAGERS` be enough? (modulo tests, of course… and assuming the GitHub integration uses that code)
https://github.com/snyk/snyk/blob/ba9ad07d4426a2b8483d515812edccf307cfa968/lib/detect.js#L10-L44

**Comment by Bluexin** [comment]
:+1: on this
Any progress? I have a few open-source projects I'd love to be able to test on snyk.io :smile:

**Comment by lili2311** [comment]
@Bluexin 👋  We might have a work around for you, please try: `snyk test --file=build.gradle.kts --package-manager=gradle -- --configuration compileClasspath`

**Comment by Bluexin** [comment]
Thanks for the reply.
I was talking specifically about enabling it on snyk.io with the Github integration for all the fancyness this brings. However, I'm not very familiar with Snyk yet. Does the CLI actually let you enable this?

**Comment by pastjean** [comment]
Hey i've built it here :D just need someone from snyk's go https://github.com/snyk/snyk/pull/277

**Comment by lili2311** [comment]
👋 Update: We are working on adding support in CLI for `gradle.kts` files in the next few sprints, will update once this is in. We need to make some changes internally to make the awesome PR contribution mergeable.

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/pull/395 🎉 Support now available in latest CLI version @tbroyer, closing issue please re-open if needed.

**Comment by martintreurnicht** [comment]
Having it in the CLI is great, but it would be great if we could run this as part of our PRs on github. Right now it doesn't seem to support github, when importing from github it just says:
```console
Could not detect supported target files
```
Bit of a dealbreaker for us
