### ISSUE TITLE
Error 504

### ISSUE THREAD

**Issue by m-handy** [snyk/snyk#159]
- `snyk mvn docker image` : 1.80.0
- Command run:
`docker run -i -v "%env.M2_PATH%:/home/node/.m2" -v "%teamcity.maven.local.repository.path%:/home/node/maven/repository" -v "%teamcity.build.checkoutDir%:/project" -v "/usr/java/jdk1.8.0_144/jre/lib/security:/usr/lib/jvm/java-8-oracle/jre/lib/security" -e "SNYK_TOKEN=%env.SNYK_TOKEN%" -e ENV_FLAGS="-s /home/node/.m2/settings.xml -Dmaven.repo.local=/home/node/maven/repository" -e HTTPS_PROXY=http://proxy.company.net:3128 -e HTTP_PROXY=http://proxy.company.net:3128 snyk/snyk-cli:%env.SNYK_VERSION%-maven-3.5.2 test -d`

### Expected behaviour
✓ Tested

### Actual behaviour
[17:09:36][Step 2/2] Status: Downloaded newer image for snyk/snyk-cli:1.80.0-maven-3.5.2
[17:14:55][Step 2/2] parse error: Invalid numeric literal at line 1, column 6
[17:14:55][Step 2/2] Failed to run the process ...
[17:14:55][Step 2/2] Error: 504
[17:14:55][Step 2/2]     at /usr/local/lib/node_modules/snyk/cli/commands/test.js:134:21
[17:14:55][Step 2/2]     at <anonymous>
[17:14:55][Step 2/2]     at process._tickCallback (internal/process/next_tick.js:188:7)
[17:14:55][Step 2/2] 
[17:14:55][Step 2/2] ==Stoping docker wrapper==

### Steps to reproduce
I just run `mvn clean install` on my project and than I passed mvn repository inside docker image. This approach (and exact the same snyk command) is working on my other project very well and I can't find why is not working with this second project. When I run `snyk test` locally from cmd it is working, but when I try `snyk monitor` it will produce same error as mentioned in #148 

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@m-handy we just released an updated docker image (based on maven 3.5.4), please try it out and see if the problem persists. Note that the image tag is `maven-3.5.4` without the Snyk CLI version.

If the problem persists, I'd like to ask you to compare the output of `mvn dependency:tree -DoutputType=dot` running on your project locally versus inside the docker image. Perhaps the dependency graph differs to the point that can explain this result.

The 504 response means that the processing on our end took too long, and timed out.

**Comment by lili2311** [comment]
Closing this, please re-open if it is still an issue
