### ISSUE TITLE
Queries regarding how Snyk maintains its vulnerability database

### ISSUE THREAD

**Issue by nasifimtiazohi** [snyk/snyk#1590]
Hi,

As part of our research, we are trying to understand how different advisory databases maintain and curate their vulnerability data. It'd be greatly helpful if we had some comments on the below questions:

1. What are your sources for vulnerability data, e.g. NVD, OSS Index?
2. Do you have any process to discover open source vulnerabilities by yourselves, e.g. through monitoring bug repositories? If yes, is it possible to share with us a high level explanation of what you do?
3. When collecting vulnerability data from third-party databases (e.g. NVD), do you perform any curation and/or correction, e.g. discarding debated CVEs or correcting the affected version range? If yes, is it possible to share with us a high level explanation of what you do?

Sorry for the template questions. We're trying to reach out to different parties with the same set of questions so that we can study the answers systematically. Any insight would be greatly helpful. Also, sorry if it is not the right place to ask these questions. I was trying to reach Snyk maintainers but was unable to find a better way. 

Nasif

**Comment by JackuB** [comment]
Hey @nasifimtiazohi, I raised this to our security team

**Comment by JackuB** [comment]
Our security team actually wrote a blog post with details about our approach. It should cover your questions: https://snyk.io/blog/why-snyk-wins-open-source-security-battle/

Hope this helps!

**Comment by nasifimtiazohi** [comment]
Thanks. That's more or less exactly what I was looking for!
