### ISSUE TITLE
[🐛] Impossible to install npm snyk 1.441.0, if git command is not available

### ISSUE THREAD

**Issue by CompartMSL** [snyk/snyk#1614]
- `node -v`: v10.21.0
- `npm -v`: 6.14.4
- `snyk -v`: 1.441.0
- OS: Docker + GNU/Linux
- Command run: npm install snyk

### Expected behaviour

    + snyk@1.441.0
    updated 1 package in 6.098s

### Actual behaviour

    npm ERR! code ENOENT
    npm ERR! syscall spawn git
    npm ERR! path git
    npm ERR! errno ENOENT
    npm ERR! enoent Error while executing:
    npm ERR! enoent undefined ls-remote -h -t https://github.com/open-policy-agent/npm-opa-wasm.git
    npm ERR! enoent 
    npm ERR! enoent 
    npm ERR! enoent spawn git ENOENT
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent 
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-02-04T15_45_16_194Z-debug.log

- The new dependency `"@open-policy-agent/opa-wasm": "git+https://github.com/open-policy-agent/npm-opa-wasm.git#f4a21fe6f4d70706f85106dc6ea867983747e040",` could not installed, because the git command is not available on the system. 
- IMHO it is very common that there are less commands available inside a container. And git is typically not needed inside a container.
- The dependency with `git+https` was introduced via the branch `feat/iac-experimental-local-exec`

### Steps to reproduce

 - System without git
 - But with npm, nodejs, ...
 - Call `npm install snyk`

### Debug log
N/A

### Screenshots
N/A

**Comment by JackuB** [comment]
Yes, you are right, we are reverting that change

**Comment by JackuB** [comment]
Hi, sorry for this! Is the issue solved for you in the latest `snyk@1.443.0`?

We'll be adding more checks to prevent this in the future
