### ISSUE TITLE
Snyk wizard cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by gostaffer** [snyk/snyk#165]
- `node -v`: 8.9.4
- `npm -v`: 6.0.1
- `snyk -v`: 1.88.0
- Command run: `snyk wizard --debug`

### Expected behaviour
Expected the Snyk wizard to complete successfully.

### Actual behaviour
It threw the following error: `Cannot read property 'id' of undefined`

### Steps to reproduce
Run `snyk wizard`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

> snyk wizard --debug

  snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /Users/andrewaponte/Projects/active/gostaffer/website +0ms
  snyk found package file package.json in /Users/andrewaponte/Projects/active/gostaffer/website +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk sending request to: https://snyk.io/api/v1/verify/token +0ms
  snyk request body size: 46 +0ms
  snyk analytics add payloadSize 46 +0ms
  snyk not using proxy +0ms
  snyk analytics add inline-auth false +528ms
  snyk not using proxy +528ms

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

  snyk analytics add local true +224ms
  snyk policies found [ '/Users/andrewaponte/Projects/active/gostaffer/website' ] +0ms
  snyk analytics add policies 1 +10s
Analyzing npm dependencies for package.json
  snyk analytics add packageManager npm +32ms
  snyk analytics add packageName gostaffer-website +0ms
  snyk analytics add packageVersion 1.0.0 +0ms
  snyk analytics add package gostaffer-website@1.0.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +11s
  snyk request body size: 4310862 +0ms
  snyk analytics add payloadSize 4310862 +42ms
  snyk not using proxy +0ms
  snyk analytics add vulns-pre-policy 139 +586ms
  snyk analytics add vulns 139 +3ms
Querying vulnerabilities database...
Tested 1149 dependencies for known vulnerabilities, found 15 vulnerabilities, 139 vulnerable paths.
  snyk starting questions +12s
  snyk getUpdatePrompts +0ms
  snyk + adding juice-resources-promise@0.0.2 to upgrades +16ms
  snyk + adding stringstream@0.0.6 to upgrades +0ms
  snyk + adding is-url@1.2.4 to upgrades +0ms
  snyk + adding deep-extend@0.5.1 to upgrades +0ms
  snyk + adding is-url@1.2.4 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding react-prop-types@0.4.0 to upgrades +0ms
  snyk + adding react-overlays@0.7.4 to upgrades +1ms
  snyk + adding prop-types-extra@1.1.0 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding uncontrollable@4.1.0 to upgrades +0ms
  snyk + adding react-onclickoutside@6.7.1 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding react-popper@0.8.3 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding react-side-effect@1.1.5 to upgrades +0ms
  snyk + adding react-transition-group@2.3.1 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding prop-types-extra@1.1.0 to upgrades +0ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +1ms
  snyk + adding ua-parser-js@0.7.18 to upgrades +0ms
  snyk + adding react-router@4.2.0 to upgrades +0ms

  snyk final show npm:sshpk:20180409 when true +17ms
? 4 vulnerabilities introduced via email-templates@3.5.2
- info: https://snyk.io/package/npm/email-templates/3.5.2
  Remediation options Re-install email-templates@3.5.2
  snyk no group answer: show npm:sshpk:20180409 when false +1s
  snyk no group answer: show npm:sshpk:20180409 when false +1ms
  snyk no group answer: show npm:stringstream:20180511 when false +0ms
  snyk no group answer: show npm:stringstream:20180511 when false +0ms

  snyk final show npm:is-url:20180319 when true +1ms
? 4 vulnerabilities introduced via imagemin-jpegtran@5.0.2
- info: https://snyk.io/package/npm/imagemin-jpegtran/5.0.2
  Remediation options Re-install imagemin-jpegtran@5.0.2
  snyk no group answer: show npm:is-url:20180319 when false +98ms
  snyk no group answer: show npm:is-url:20180319 when false +0ms
  snyk no group answer: show npm:deep-extend:20180409 when false +1ms
  snyk no group answer: show npm:deep-extend:20180409 when false +0ms

  snyk final show npm:deep-extend:20180409 when true +0ms
? 2 vulnerabilities introduced via imagemin-pngquant@5.1.0
- info: https://snyk.io/package/npm/imagemin-pngquant/5.1.0
  Remediation options Re-install imagemin-pngquant@5.1.0
  snyk no group answer: show npm:deep-extend:20180409 when false +152ms
  snyk no group answer: show npm:is-url:20180319 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +1ms
? Medium severity vuln found in ua-parser-js@0.7.17, introduced via prop-types@15.6.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:ua-parser-js:20180227
- from: prop-types@15.6.0 > fbjs@0.8.16 > ua-parser-js@0.7.17
  Remediation options Re-install prop-types@15.6.0

  snyk final show npm:ua-parser-js:20180227 when true +543ms
? 2 vulnerabilities introduced via react@16.2.0
- info: https://snyk.io/package/npm/react/16.2.0
  Remediation options Re-install react@16.2.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +128ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 20 vulnerabilities introduced via react-big-calendar@0.18.0
- info: https://snyk.io/package/npm/react-big-calendar/0.18.0
  Remediation options Re-install react-big-calendar@0.18.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +143ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 20 vulnerabilities introduced via react-datepicker@1.2.2
- info: https://snyk.io/package/npm/react-datepicker/1.2.2
  Remediation options Re-install react-datepicker@1.2.2
  snyk no group answer: show npm:ua-parser-js:20180227 when false +123ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 4 vulnerabilities introduced via react-dom@16.2.0
- info: https://snyk.io/package/npm/react-dom/16.2.0
  Remediation options Re-install react-dom@16.2.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +146ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +1ms
? 5 vulnerabilities introduced via react-helmet@5.2.0
- info: https://snyk.io/package/npm/react-helmet/5.2.0
  Remediation options Re-install react-helmet@5.2.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +150ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +1ms
? 16 vulnerabilities introduced via react-overlays@0.8.3
- info: https://snyk.io/package/npm/react-overlays/0.8.3
  Remediation options Re-install react-overlays@0.8.3
  snyk no group answer: show npm:ua-parser-js:20180227 when false +150ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 3 vulnerabilities introduced via react-redux@5.0.7
- info: https://snyk.io/package/npm/react-redux/5.0.7
  Remediation options Re-install react-redux@5.0.7
  snyk no group answer: show npm:ua-parser-js:20180227 when false +147ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +1ms
? 3 vulnerabilities introduced via react-router@4.2.0
- info: https://snyk.io/package/npm/react-router/4.2.0
  Remediation options Re-install react-router@4.2.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +166ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 6 vulnerabilities introduced via react-router-dom@4.2.2
- info: https://snyk.io/package/npm/react-router-dom/4.2.2
  Remediation options Re-install react-router-dom@4.2.2
  snyk no group answer: show npm:ua-parser-js:20180227 when false +175ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms

  snyk final show npm:ua-parser-js:20180227 when true +0ms
? 6 vulnerabilities introduced via redux-form@7.3.0
- info: https://snyk.io/package/npm/redux-form/7.3.0
  Remediation options Re-install redux-form@7.3.0
  snyk no group answer: show npm:ua-parser-js:20180227 when false +158ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +0ms
  snyk no group answer: show npm:ua-parser-js:20180227 when false +1ms

  snyk final show npm:deep-extend:20180409 when true +0ms
? Low severity vuln found in deep-extend@0.4.2, introduced via sharp@0.20.0
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:deep-extend:20180409
- from: sharp@0.20.0 > prebuild-install@2.5.3 > rc@1.2.5 > deep-extend@0.4.2
  Remediation options Re-install sharp@0.20.0

  snyk final show npm:macaddress:20180511 when true +174ms
? High severity vuln found in macaddress@0.2.8, introduced via uniqid@4.1.1
- desc: Arbitrary Command Injection
- info: https://snyk.io/vuln/npm:macaddress:20180511
- from: uniqid@4.1.1 > macaddress@0.2.8
  Remediation options Re-install uniqid@4.1.1

  snyk final show npm:atob:20180429 when true +176ms
? 11 vulnerabilities introduced via universal-webpack@0.6.1
- info: https://snyk.io/package/npm/universal-webpack/0.6.1
  Remediation options Re-install universal-webpack@0.6.1
  snyk no group answer: show npm:atob:20180429 when false +176ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +1ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +1ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +1ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk no group answer: show npm:atob:20180429 when false +0ms
  snyk getPatchPrompts +2ms

  snyk final show npm:debug:20170905 when true +10ms
? Low severity vuln found in debug@2.6.8, introduced via universal-webpack@0.6.1
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:debug:20170905
- from: universal-webpack@0.6.1 > webpack@4.1.0 > watchpack@1.5.0 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > tar-pack@3.4.0 > debug@2.6.8
  Remediation options Patch

  snyk final show npm:hoek:20180212 when true +168ms
? 8 vulnerabilities introduced in hoek
- info: https://snyk.io/package/npm/hoek/2.16.3
  Remediation options Patch
  snyk no group answer: show npm:hoek:20180212 when false +209ms
  snyk no group answer: show npm:hoek:20180212 when false +0ms
  snyk no group answer: show npm:hoek:20180212 when false +1ms
  snyk no group answer: show npm:hoek:20180212 when false +0ms
  snyk no group answer: show npm:hoek:20180212 when false +0ms
  snyk no group answer: show npm:hoek:20180212 when false +1ms
  snyk no group answer: show npm:hoek:20180212 when false +0ms
  snyk no group answer: show npm:hoek:20180212 when false +0ms

  snyk final show npm:tough-cookie:20170905 when true +0ms
? Medium severity vuln found in tough-cookie@2.3.2, introduced via universal-webpack@0.6.1
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:tough-cookie:20170905
- from: universal-webpack@0.6.1 > webpack@4.1.0 > watchpack@1.5.0 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > request@2.81.0 > tough-cookie@2.3.2
  Remediation options Patch

  snyk final show npm:tunnel-agent:20170305 when true +151ms
? 3 vulnerabilities introduced in tunnel-agent
- info: https://snyk.io/package/npm/tunnel-agent/0.4.3
  Remediation options Patch
  snyk no group answer: show npm:tunnel-agent:20170305 when false +175ms
  snyk no group answer: show npm:tunnel-agent:20170305 when false +0ms
  snyk no group answer: show npm:tunnel-agent:20170305 when false +0ms
  snyk getIgnorePrompts +1ms

  snyk final show npm:braces:20180219 when true +9ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +358ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +520ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-build@2.2.0 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromat
ch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +327ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-wrapper@3.0.2 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +296ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-jpegtran@5.0.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-jpegtran@5.0.2 > jpegtran-bin@3.2.0 > bin-wrapper@3.0.2 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > microm
atch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +297ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-pngquant@5.1.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-pngquant@5.1.0 > pngquant-bin@4.0.0 > bin-wrapper@3.0.2 > download@4.4.3 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > micromatch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:braces:20180219 when true +600ms
? Low severity vuln found in braces@1.8.5, introduced via imagemin-pngquant@5.1.0
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: imagemin-pngquant@5.1.0 > pngquant-bin@4.0.0 > bin-wrapper@3.0.2 > download@4.4.3 > gulp-decompress@1.2.0 > decompress@3.0.0 > vinyl-fs@2.4.4 > glob-stream@5.3.5 > microm
atch@2.3.11 > braces@1.8.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:deep-extend:20180409 when true +2s
? Low severity vuln found in deep-extend@0.4.2, introduced via mem-fs-editor@3.0.2
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:deep-extend:20180409
- from: mem-fs-editor@3.0.2 > deep-extend@0.4.2
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:deep-extend:20180409 when true +607ms
? Low severity vuln found in deep-extend@0.4.2, introduced via universal-webpack@0.6.1
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:deep-extend:20180409
- from: universal-webpack@0.6.1 > webpack@4.1.0 > watchpack@1.5.0 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > rc@1.2.1 > deep-extend@0.4.2
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:deep-extend:20180409 when true +912ms
? Low severity vuln found in deep-extend@0.4.2, introduced via yeoman-generator@1.1.1
- desc: Prototype Pollution
- info: https://snyk.io/vuln/npm:deep-extend:20180409
- from: yeoman-generator@1.1.1 > mem-fs-editor@3.0.2 > deep-extend@0.4.2
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:shelljs:20140723 when true +880ms
? High severity vuln found in shelljs@0.7.8, introduced via shelljs@0.7.8
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:shelljs:20140723 when true +6s
? High severity vuln found in shelljs@0.7.8, introduced via yeoman-generator@1.1.1
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
- from: yeoman-generator@1.1.1 > shelljs@0.7.8
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:sshpk:20180409 when true +1s
? High severity vuln found in sshpk@1.13.0, introduced via universal-webpack@0.6.1
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:sshpk:20180409
- from: universal-webpack@0.6.1 > webpack@4.1.0 > watchpack@1.5.0 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > request@2.81.0 > http-signature@1.1.1 > sshpk@1.13.0
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:string:20170907 when true +728ms
? Medium severity vuln found in string@3.3.3, introduced via string@3.3.3
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:string:20170907
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:stringstream:20180511 when true +969ms
? Medium severity vuln found in stringstream@0.0.5, introduced via universal-webpack@0.6.1
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:stringstream:20180511
- from: universal-webpack@0.6.1 > webpack@4.1.0 > watchpack@1.5.0 > chokidar@2.0.2 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > request@2.81.0 > stringstream@0.0.5
  Remediation options Ignore
? [audit] Reason for ignoring vulnerability? None given

  snyk final show npm:underscore.string:20170908 when true +839ms
? High severity vuln found in underscore.string@3.3.4, introduced via email-templates@3.5.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:underscore.string:20170908
- from: email-templates@3.5.2 > html-to-text@3.3.0 > underscore.string@3.3.4
  Remediation options Ignore

  snyk final show npm:underscore.string:20170908 when true +538ms
? High severity vuln found in underscore.string@3.3.4, introduced via email-templates@3.5.2
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:underscore.string:20170908
- from: email-templates@3.5.2 > @ladjs/i18n@0.2.0 > underscore.string@3.3.4
  Remediation options Ignore
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
This will require authentication via `snyk auth` when running tests. Yes
? Add `snyk protect` as a package.json installation hook to apply chosen patches on install? Yes
  snyk analytics add error-message Cannot read property 'id' of undefined +24s
  snyk analytics add error TypeError: Cannot read property 'id' of undefined
    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:301:27
    at Array.map (<anonymous>)
    at processAnswers (/Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:288:49)
    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:174:24
    at <anonymous> +0ms
  snyk analytics add error-code undefined +0ms
  snyk analytics add command wizard +0ms
TypeError: Cannot read property 'id' of undefined
    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:301:27
    at Array.map (<anonymous>)
    at processAnswers (/Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:288:49)
    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:174:24
    at <anonymous>
  snyk analytics { command: 'bad-command',
  args: 
   [ { debug: true,
       packageManager: 'npm',
       newPolicy: true,
       ignoreDisabled: false,
       file: 'package.json',
       packageLeading: '',
       packageTrailing: '' } ],
  metadata: 
   { payloadSize: [ 46, 4310862 ],
     'inline-auth': false,
     local: true,
     policies: 1,
     packageManager: 'npm',
     packageName: 'gostaffer-website',
     packageVersion: '1.0.0',
     package: 'gostaffer-website@1.0.0',
     'vulns-pre-policy': 139,
     vulns: 139,
     'error-message': 'Cannot read property \'id\' of undefined',
     error: 'TypeError: Cannot read property \'id\' of undefined\n    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:301:27\n    at Array.map (<anonymous>)\n    at processAnswers (/Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:288:49)\n    at /Users/andrewaponte/Projects/active/gostaffer/website/node_modules/snyk/cli/commands/protect/wizard.js:174:24\n    at <anonymous>',
     'error-code': undefined,
     command: 'wizard' },
  version: '1.88.0',
  os: 'macOS High Sierra',
  nodeVersion: 'v8.9.4',
  id: '4104270d9690546c9eaed27913e65be90dc49942',
  ci: false,
  durationMs: 35770 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +24s
  snyk request body size: 1127 +1ms
  snyk not using proxy +0ms

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gostaffer-website@1.0.0 snyk: `snyk wizard --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gostaffer-website@1.0.0 snyk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrewaponte/.npm/_logs/2018-07-01T01_13_43_349Z-debug.log

**Comment by adrukh** [comment]
Thanks for reporting this issue! The culprit lies in the `underscore.string` package being vulnerable. We are using `inquirer` to manage the user interaction and collect answers. Vulnerability IDs are used as names for the questions we ask. The presence of a full stop (`.`) in the name of the question is triggering a feature in `inquirer` which we did not account for, allowing for nested questions.

We will address this issue shortly and update here, thanks for your patience!

**Comment by orsagie** [comment]
@gostaffer, Please install `snyk v1.81.1`. This version handles dots in package names. 

Thanks for reporting!

**Comment by nrxsmith** [comment]
I'm still seeing this precise issue (and with that particular dependency, underscore.string), and I've installed snyk v1.81.1. Are we certain this was actually fixed?

**Comment by orsagie** [comment]
@nrxsmith I had a typo! edited version to `1.88.1` (https://github.com/snyk/snyk/releases)

**Comment by nrxsmith** [comment]
@orsagie Huh....I tried both 1.88.1 and 1.88.2, and I still get the `Cannot read property 'id' of undefined` error, and I have the underscrore.string package.

**Comment by orsagie** [comment]
Can you provide the command you are running and your package.json contents?
