### ISSUE TITLE
Is there a public API to fetch all advisory informations from snyk vulnerability database?

### ISSUE THREAD

**Issue by nasifimtiazohi** [snyk/snyk#1651]
Hi,

As part of my research, I am interested in investigating the lifecycle of a security advisory (e.g., when first introduced in code, first discovered, first reported in an advisory database, when reported as a CVE; and the time lag between these phases). I am interested in working with the data in Snyk's [vulnerability database](https://snyk.io/vuln?type=any).

Is there any public API where I can fetch the data for all advisories in Snyk's database that is present on the web interface?

Thanks, 
Nasif

**Comment by JackuB** [comment]
No, sorry, we don't make this data available in bulk.
