### ISSUE TITLE
snyk test fails after upgrading babel

### ISSUE THREAD

**Issue by joselcc** [snyk/snyk#168]
- `node -v`: v9.10.1
- `npm -v`: 5.8.0
- `snyk -v`: 1.88.1
- Command run: `snyk test`

### Expected behaviour
Get the vulnerability report after upgrading babel packages

### Actual behaviour
I'm getting the following vulnerability report when running `snyk test`

```sh
✗ Low severity vulnerability found in braces
  Description: Regular Expression Denial of Service (ReDoS)
  Info: https://snyk.io/vuln/npm:braces:20180219
  Introduced through: @babel/core@7.0.0-beta.34, @babel/cli@7.0.0-beta.34, @babel/preset-flow@7.0.0-beta.34, @abcaustralia/stylelint-config-abc@0.2.0, @babel/preset-react@7.0.0-beta.34, @abcaustralia/postcss-config@1.9.0, @babel/register@7.0.0-beta.34, @babel/preset-stage-0@7.0.0-beta.34, babel-loader@8.0.0-beta.0, @babel/preset-stage-1@7.0.0-beta.34, @babel/preset-es2015@7.0.0-beta.34, babel7-jest@1.0.1, @babel/preset-env@7.0.0-beta.34, stylelint@9.3.0
  From: @babel/core@7.0.0-beta.34 > micromatch@2.3.11 > braces@1.8.5
  From: @babel/cli@7.0.0-beta.34 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5
  From: @babel/cli@7.0.0-beta.34 > @babel/core@7.0.0-beta.34 > micromatch@2.3.11 > braces@1.8.5
  and 154 more...
  Remediation:
    Your dependencies are out of date, otherwise you would be using a newer version of braces. 
    Try deleting node_modules, reinstalling and running `snyk test` again. If the problem persists, one of your dependencies may be bundling outdated modules.
```
After **upgrading babel** packages from version `7.0.0-beta.34` to `7.0.0-beta.51` running `snyk test` fails with an **unknown error**:

```sh
$ snyk test
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 
Testing /Users/some-user/project/my-private-package...

413
    at /Users/some-user/.nvm/versions/node/v9.10.1/lib/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

### Steps to reproduce

**Upgrade** the following babel packages from version `7.0.0-beta.34` to `7.0.0-beta.51`:
* @babel/cli
* @babel/core
* @babel/polyfill
* @babel/preset-env
* @babel/preset-es2015
* @babel/preset-flow
* @babel/preset-react
* @babel/preset-stage-0
* @babel/preset-stage-1
* @babel/register

---

output for `snyk test --debug` is attached
[debug.log](https://github.com/snyk/snyk/files/2161593/debug.log)

**Comment by tierra** [comment]
Just want to confirm I'm running into the same thing (or at least what looks like the same issue).

Node: 8.11.3
Yarn: 1.7.0 (same with 1.5.1 as well)
Snyk: 1.88.2

```
$ node --max-old-space-size=4096 node_modules/.bin/snyk test --file=yarn.lock --project-name=project-name
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 
Testing /usr/src/app...

413
    at /usr/src/app/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

error An unexpected error occurred: "Command failed.
Exit code: 1
```

I think this is an unrelated issue (or maybe semi-related), but note that I'm forced to use ` --max-old-space-size=4096` to get around "JavaScript heap out of memory" errors (possibly also related to #156):

```
yarn run v1.7.0
$ snyk monitor --file=yarn.lock --project-name=project-name

<--- Last few GCs --->

[21375:0x3664d40]   124669 ms: Scavenge 1270.0 (1439.9) -> 1265.7 (1445.4) MB, 7.5 / 0.0 ms  (average mu = 0.212, current mu = 0.063) allocation failure 
[21375:0x3664d40]   124854 ms: Mark-sweep 1275.0 (1445.4) -> 1274.7 (1442.9) MB, 166.9 / 0.0 ms  (average mu = 0.219, current mu = 0.226) allocation failure scavenge might not succeed
```

Obviously not ideal that, for a tool that's just collecting a list of packages and their versions, that it requires > 2GB of memory to run. :(

**Comment by adrukh** [comment]
@tierra you are hitting two issues here:

1. CLI allocates too much memory when trying to build the dependency graph for your project. We are working on improving our memory footprint. I can offer https://nodejs.org/api/cli.html#cli_node_options_options as a workaround, where you can specify a higher limit to adjust `old space` max size to 4GB or so.

2. 413 status code from our servers indicates a payload that is too large for us to process. Please try the latest CLI release, as we reduced the occurrence of such errors with snyk@1.88.4.

**Comment by tierra** [comment]
I upgraded to 1.89.0, but I'm still seeing 413 response.

**Comment by tierra** [comment]
I'm not using `--dev` option either, for what it's worth.

**Comment by adrukh** [comment]
Can you share the output of `snyk test -d`?

**Comment by tierra** [comment]
I scrubbed this a bit, but...

```  snyk test { _: [ [Circular] ],
  debug: true,
  org: 'myorg',
  file: 'yarn.lock',
  'project-name': 'myproject:node' } +0ms
  snyk analytics add local true +0ms
  snyk policies found [ '/home/project' ] +0ms
  snyk analytics add policies 1 +2m
  snyk analytics add packageManager npm +3ms
  snyk analytics add packageName myproject +0ms
  snyk analytics add packageVersion 1.0.0 +0ms
  snyk analytics add package myproject@1.0.0 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 364914771 +1ms
  snyk gzipped request body size: 5778806 +0ms
  snyk analytics add payloadSize 364914771 +8s
  snyk analytics add gzippedPayloadSize 5778806 +0ms
  snyk not using proxy +1ms
  snyk analytics add error-message 
Testing /home/project...

413 +5s
  snyk analytics add error Error: 
Testing /home/project...

413
    at /home/project/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +1ms
  snyk analytics add error-code 413 +0ms
  snyk analytics add command test +0ms
Error: 
Testing /home/project...

413
    at /home/project/node_modules/snyk/cli/commands/test.js:142:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { command: 'bad-command',
  args: 
   [ { debug: true,
       org: 'myorg',
       file: 'yarn.lock',
       'project-name': 'myproject:node',
       showVulnPaths: true } ],
  metadata: 
   { local: true,
     policies: 1,
     packageManager: 'npm',
     packageName: 'myproject',
     packageVersion: '1.0.0',
     package: 'myproject@1.0.0',
     payloadSize: 364914771,
     gzippedPayloadSize: 5778806,
     'error-message': '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /home/project...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m413',
     error: 'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting /home/project...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m413\n    at /home/project/node_modules/snyk/cli/commands/test.js:142:21\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': 413,
     command: 'test' },
  version: '1.89.0',
  os: 'Linux 4.15',
  nodeVersion: 'v8.11.3',
  id: '31db42d03562b6be55df70352c7d140720951d02',
  ci: false,
  durationMs: 132160 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +5s
  snyk request body size: 1197 +0ms
  snyk gzipped request body size: 533 +0ms
  snyk not using proxy +0ms
```

I see what you mean by payload sizes now... looks like my project has something blowing that all the way up to 350MB?

**Comment by michael-go** [comment]
@tierra thank you for reporting this and sharing your debug output.
The payload reaches the boggling 350MB size 🙈 because the CLI tries to capture the full and accurate dependency tree that is needed for correct remediation suggestions, however it represents the data in a non efficient, recursive tree structure that contains mostly redundant information. We are aware of this issue and are now working on fixing it, by improving the backend to efficiently handle such larger trees, and by introducing a new payload format that will be drastically smaller without losing the needed information. Sorry for the inconvenience :pray:
If possible, it will really help us if you could send your `package.json` and `yarn.lock` to support@snyk.io (linking to this issue and mentioning my name 😄)

**Comment by lili2311** [comment]
👋 Please try out our latest CLI `snyk test --prune-repeated-subdependencies` and see if this is now working better for you? https://github.com/snyk/snyk/pull/706

**Comment by lili2311** [comment]
@joselcc @tierra please give ^^ a try when you have a chance and let me know how it is working out :)

**Comment by aogata-inst** [comment]
FWIW, I am encountering the same error as the above users, and `--prune-repeated-subdependencies` did not work for me. I had to revert to using the `--max-old-space-size=4096` trick.

**Comment by lili2311** [comment]
Thanks for letting me know @aogata-inst we are looking at what we can change here to help.

**Comment by joselcc** [comment]
> @joselcc @tierra please give ^^ a try when you have a chance and let me know how it is working out :)

@lili2311 Thanks for following the issue, I just tried running `snyk test` and `snyk test --prune-repeated-subdependencies` when upgrading babel deps to version 7.0.0-beta.51 or latest ones.  It seems to be working ok with the current version of **snyk**. 

```sh
$ snyk test

Testing /Users/xxx/snyk-test...

Organization:      joselcc
Package manager:   npm
Target file:       package-lock.json
Project name:      snyk-test
Open source:       no
Project path:      /Users/xxx/snyk-test
Licenses:          enabled

✓ Tested 339 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
\ Analyzing npm dependencies for /Users/xxx/snyk-test/package-lock.json
```
