### ISSUE TITLE
[🙏] Support for pnpm lockfile (pnpm-lock.yaml)

### ISSUE THREAD

**Issue by jtraulle** [snyk/snyk#1696]
- `Language / Project Type:` Javascript
- `Package Manager / Build Tool:` pnpm

**Describe the user need**
I want Snyk to scan my Javascript project that uses pnpm package manager.

**Additional context**

As of now, Snyk does only support Yarn or npm but pnpm is also a popular option (10.3k stars on Github).
https://github.com/pnpm/pnpm
https://pnpm.js.org/

Lock file use the yaml file format.

**Comment by JackuB** [comment]
Is pnpm using `dependencies` field in the `package.json`? As in, `snyk test` will test it, but resolves different versions because of a different/unsupported lockfile format?

**Comment by JackuB** [comment]
You might give this GitHub Action a try - https://github.com/snyk-tech-services/github-actions-pnpm-snyk
It'll use Snyk CLI and on background parses pnpm lockfile.

Other than that, I have no news regarding a wider pnpm support.

**Comment by jtraulle** [comment]
Thanks for your detailed answer :+1: 

Unfortunately, I am using a self hosted instance of Gitlab and I will not be able to use this Github Action but this is a good solution for people on Github :slightly\_smiling\_face: 

For now I have switched to npm (and not pmpm) and will reconsider if snyk got wider pnpm support at some point :wink:
