### ISSUE TITLE
How to check a package from github

### ISSUE THREAD

**Issue by albertosantini** [Snyk/snyk#17]
- `node -v`: v5.7.1
- `npm -v`: 3.6.0
- `snyk -v`: 1.11.3
- Command run: snyk --dev test

### Expected behaviour

No error. A package installed from GitHub.

### Actual behaviour

`invalid package name: angular/ngSocket, errors: name can no longer contain capital letters`

### Steps to reproduce

In package.json: "angular/ngSocket": "~0.2.0",

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by remy** [comment]
Hi @albertosantini 

I just tried to install the `angular/ngSocket` package into a test `package.json`, but it installed as this:
```json
"dependencies": {
  "ngSocket": "angular/ngSocket"
},
```

Note that where you've got the version `~0.2.0`, I've got the git package name (this was just via `npm i -S angular/ngSocket`).

Can you walk me through how I can replicate how you've got the ngSocket module installed into your package (so I can replicate here)?

**Comment by albertosantini** [comment]
What a misunderstanding on my side.

I inserted the dep like:
```
"dependencies": {
  "angular/ngSocket": "~0.2.0"
}
```

The correct configuration is the yours.

Sorry for the noise.

**Comment by remy** [comment]
No problem at all ☺
