### ISSUE TITLE
Windows incompatibility due to `patch`

### ISSUE THREAD

**Issue by Pomax** [snyk/snyk#170]
Trying to install Snyk on windows will crash with the notice "Snyk couldn't patch the specified vulnerabilities because GNU's patch is not available. Please install 'patch' and try again." which is not a straight forward thing to do on a windows machine, given that unlike linux distros there is no way to get the right thing.

Ideally, Snyk would be able to use a cross-platform patching tool (and even ideally-er, use a node based tool so that there is no need to even download anything beyond what npm install already takes care of). However, barring that, could this error be change to inform people what the authoritative location for `patch` is?

(And not something along the lines of "install msys" or something, which is total overkill. We've reached a point where most tools are finally reasonably cross-platform in the node/npm ecosystem, it would be fantastic if Snyk also "just worked" regardless of OS)

**Comment by Pomax** [comment]
What is the closest node.js candidate and what's missing from it? I would imagine they'd be interested in adding the missing bits if it meant being the library of choice for Snyk.

**Comment by saschanaz** [comment]
BTW this is a duplicate of #48.

**Comment by adrukh** [comment]
Version 1.131.0 includes the fix (use `jsdiff` instead of the `patch` binary), please give it a try.
