### ISSUE TITLE
how to ignore until change in "Introduced through"

### ISSUE THREAD

**Issue by helios1138** [snyk/snyk#171]
Hi. Is there a way to ignore vulnerability until "Introduced through" changes?

For example, I don't care if there is a vulnerability in some module deep down the dependency tree of some CLI tool that nobody would be able to call anyway, but if the same module would be added directly to application's package.json, I would very much like to know about it.

Currently, if I ignore the issue and "Introduced through" changes later, the issue will remain ignored.

**Comment by joshje** [comment]
Hey @helios1138 

Whilst our UI offers no way to do this, it is possible via the API.

The endpoint you'll want to use is documented here:
https://snyk.docs.apiary.io/#reference/projects/project-ignores-by-issue/add-ignore

One of the attributes available in the `body` of the request is `ignorePath` (string).

An example of such a path is `browser-sync > connect > finalhandler > debug`.

Let me know how you get on with this, and if you have any suggestions for how we could improve this.

**Comment by joshje** [comment]
I also realised you may be ignoring things through the CLI. In which case the wizard ignores _only_ specific paths by default, so a new path would not get ignored.

**Comment by joshje** [comment]
1. Yes, it would automatically update to take into account any issues that were ignored through the UI, and would additionally display which path(s) were ignored.
2. Thanks for bringing this up. We always plan our features based on our customers needs, so you're bumping the priority on this. We need to maintain a simple, easy to use product, so sometimes have advanced functionality available via the API only, but if enough people ask for it to be made available we will look into ways we can provide this functionality in an intuitive way. I'll let you know what decisions are made with this.

**Comment by helios1138** [comment]
@joshje thank you!

**Comment by helios1138** [comment]
@joshje the reason I didn't try to ignore it using the wizard was https://github.com/snyk/snyk/issues/172 :)
