### ISSUE TITLE
Invalid NO_PROXY pattern since 1.518

### ISSUE THREAD

**Issue by prog99** [snyk/snyk#1787]
Hi there, our engineers have been getting this today in their builds. We rolled back to 1.517 and all is well again.
Only thing I can possible think of is that the NO_PROXY variable has the hosts specified with a comma and a space - “localhost, someotherhost, etc”

**Comment by JackuB** [comment]
Thank you, we'll take a look right away

**Comment by JackuB** [comment]
In 1.518.0 we've swapped a dependency called `proxy-agent` for a `global-agent`

```js
    const ruleMatch = rule
      .replace(/^(?<leadingDot>\.)/, '*')
      .match(/^(?<hostname>.+?)(?::(?<port>\d+))?$/);

    if (!ruleMatch || !ruleMatch.groups) {
      throw new UnexpectedStateError('Invalid NO_PROXY pattern.');
    }
```

https://github.com/gajus/global-agent/blob/f89883c39e7053bcc0d31b12c9c61d04961779df/src/utilities/isUrlMatchingNoProxy.js#L17-L23

Which uses this fairly permissive regexp `/^(?<hostname>.+?)(?::(?<port>\d+))?$/`

But the issue stems few lines above:
```js
const rules = noProxy.split(/[\s,]/);
```
https://github.com/gajus/global-agent/blob/f89883c39e7053bcc0d31b12c9c61d04961779df/src/utilities/isUrlMatchingNoProxy.js#L14

The split regex is not greedy, so in case of a comma-space, it'll pick up only the comma. I'll open a PR on global-agent to fix this

**Comment by JackuB** [comment]
[Global-agent v2.0.0](https://github.com/gajus/global-agent/releases/tag/v2.2.0) was released with a fixed behavior for `NO_PROXY`. It'll get installed with latest Snyk CLI, so you can upgrade now.
