### ISSUE TITLE
11.0.0-pre is an unsupported nodejs runtime! Supported runtime range is '>= 4'

### ISSUE THREAD

**Issue by hktalent** [snyk/snyk#180]
- `node -v`:
v11.0.0-pre
- `npm -v`:
6.2.0
- `snyk -v`:
11.0.0-pre is an unsupported nodejs runtime! Supported runtime range is '>= 4'
Please upgrade your nodejs runtime version and try again.
- Command run:
docker kali linux

**Comment by darscan** [comment]
@hktalent Thank you for reporting this. We will fix it very soon.

**Comment by adrukh** [comment]
@hktalent please use `1.90.0`, the issue has been fixed in https://github.com/snyk/snyk/commit/bd4843f

Thanks for pointing it out!

**Comment by robcresswell** [comment]
Closing this; seems to be fixed, and no further comments from the issue author :smile:
