### ISSUE TITLE
Difference with Node Security Project?

### ISSUE THREAD

**Issue by jedrichards** [Snyk/snyk#19]
I had a look through the readme and noted that you use data from Node Security Project, but I couldn't find any discussion of why I should use this tool instead of `nsp check`? Is your tool superior in someway? Does it currently, or will it in future have a larger database of vulnerabilities?

**Comment by johannakoll** [comment]
Right now the key difference is in remediation. Node security project/requireSafe only find issues, while Snyk proceeds to offer you a detailed upgrade path (telling you what direct dep upgrade to do to trigger the relevant downstream upgrade). In addition, we create patches for the (common) case where you cannot upgrade the vulnerability away.

While that’s the primary difference, there are various implementation differences between us, notably in how we address bundled or shrinkwrapped dependencies, and currently not all the advisories in our DB (https://snyk.io/vuln/) are included in the nsp DB.

**Comment by jedrichards** [comment]
Ah great, thanks for the info! Sounds like a meaningful distinction. I'd be tempted to put that somewhere prominently/clearer on your readme because I'm sure it's one of the first questions people will be asking themselves.
