### ISSUE TITLE
feature request: check Node.js version

### ISSUE THREAD

**Issue by DanielRuf** [snyk/snyk#190]
### Expected behaviour
The Node.js version of the project should be checked for vulnerabilities.
Currently only auditjs checks the node version for vulnerabilities.

### Actual behaviour
Node.js is not checked for known vulns.

**Comment by lili2311** [comment]
👋 This is a an excellent point, we were just chatting about this today. Would it make sense to you for this to be shown as a dependency or some separate result instead?

**Comment by DanielRuf** [comment]
👋 thanks for the feedback and to answer your question:
I would show this as a separate result (architecture / platform) since these are often global dependencies / binaries and you can extend this to other checks in the future (vulnerable OS version, vulnerable npm / yarn / pnpm version, ...).

Otherwise it would be hard to see this distinct from normal dependencies as these are normally easy to update but you do not update / upgrade the global setup so often and so easily as this may affect other projects on the same system (rebuilding compiled dependencies aganst the new ABI).
