### ISSUE TITLE
[🐛] `--all-sub-projects` doesn't pick up root-level `.snyk` file

### ISSUE THREAD

**Issue by jsfr** [snyk/snyk#1908]
- `node -v`: `v14.16.1`
- `npm -v`: `v7.12.0`
- `snyk -v`: `v1.592.0`
- OS: MacOS
- Command run: `snyk test --all-sub-projects`

### Expected behaviour
Running the test command, it should respect the top-level `.snyk` file in the root directory. However this doesn't seem to be the case.

### Actual behaviour
The command seems not to pick up the `.snyk` file when using `--all-sub-projects` but works fine when testing each sub-project using `--sub-project=...`

### Steps to reproduce

* Set up a Gradle project (using Kotlin DSL, I'm unsure if that is important) with sub-projects
* Make sure there's a vulnerable dependency. The specific vulnerability I ran into is this one `SNYK-JAVA-ORGGLASSFISHJERSEYCORE-1255637` coming from `io.dropwizard:dropwizard-core@2.0.21`

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by lili2311** [comment]
Please see https://github.com/snyk/snyk/issues/1237

**Comment by lili2311** [comment]
@jsfr does the linked issue help you resolve your issue?

**Comment by lili2311** [comment]
@jsfr closing this issue, the linked issue https://github.com/snyk/snyk/issues/1237 which will suggest you use `--policy-path=.snyk` is you want the same root level `.snyk` file to be applied to all scanned projects. By default the `.snyk` file next to manifest applies.
