### ISSUE TITLE
Enhancement: Publish SHA256 hashes for release artifacts in description

### ISSUE THREAD

**Issue by bbandelgar-lv** [snyk/snyk#194]
### Expected behaviour
SHA256 digest or digital signature of artifacts included with each release description. For example, the kubernetes project includes SHA256 hashes of the tar.gz release artifact in their description https://github.com/kubernetes/kubernetes/releases/tag/v1.11.2 .

### Actual behaviour
Release descriptions do not have any way of verifying the authenticity of the release artifacts.

### Steps to reproduce
1. Access https://github.com/snyk/snyk/releases
2. Read the release description
3. Note that there are no hashes or digital signatures for the release artifacts.
---

**Comment by darmalovan** [comment]
Hey, thanks for the good suggestion - we will figure out how to incorporate it in our release process and will update here.

**Comment by michael-go** [comment]
:wave: @bbandelgar-lv -  https://github.com/snyk/snyk/pull/293 that was just merged implements what you suggested (see .sha256 assets on https://github.com/snyk/snyk/releases) - so I'm closing it. thanks!
