### ISSUE TITLE
[🐛] 404 error upon installing through npm: `@snyk/cloud-config-parser@^1.9.2' is not in the npm registry`

### ISSUE THREAD

**Issue by KissBalazs** [snyk/snyk#2064]
- `node -v`: v14.17.1
- `npm -v`: 6.14.13
- `snyk -v`: na
- OS: Ubuntu 20.04.2 LTS
- Command run: `npm install -g snyk`

### Expected behaviour
Install properly.

### Actual behaviour
```
$ npm install -g snyk
npm ERR! code E404
npm ERR! 404 Object Not Found - GET https://skimdb.npmjs.com/registry/@snyk%2fcloud-config-parser - not_found
npm ERR! 404 
npm ERR! 404  '@snyk/cloud-config-parser@^1.9.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'snyk'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forest/.npm/_logs/2021-06-29T07_47_52_200Z-debug.log
```

### Steps to reproduce

run `npm install -g snyk`

### Debug log
--

### Screenshots
--

**Comment by JackuB** [comment]
Hey, we can’t replicate it locally or in the testing Action yet https://github.com/snyk/snyk/actions/runs/981881568

We’ll try to take a closer look

**Comment by JackuB** [comment]
Hi, we are still not sure what's happening.
The package "@snyk/cloud-config-parser" is part of the CLI for 3 months and we haven't saw anything like this before.
It gets installed on my machine, even when switchin npm account between snyk un/related. It is also installed anonymously in the CI pipeline.

It is available on the npm https://www.npmjs.com/package/@snyk/cloud-config-parser
Its settings are marked as public. However, it won't show up on search results - regardless whether searching for an exact match or a partial string from the package name. It doesn't show up on my Google or DuckDuckGo results either.

Can you visit the npmjs page? 
Are you able to install the package on its own in an empty package.json project for example?

**Comment by JackuB** [comment]
One more thing, could you try running 

```
npm show @snyk/cloud-config-parser
```

**Comment by KissBalazs** [comment]
I think I found the source of the error.

After looking into your tests, I noticed that my laptop `.npmrc` `registry` was set to `registry="https://skimdb.npmjs.com/registry"`. Switching it back to `registry="https://registry.npmjs.org` solved the issue.  (both commands run without any 404 error)

Sorry for not noticing this sooner.  The problem is with the mirror registry not being updated properly maybe?

**Comment by ipapast** [comment]
> I think I found the source of the error.
> 
> After looking into your tests, I noticed that my laptop `.npmrc` `registry` was set to `registry="https://skimdb.npmjs.com/registry"`. Switching it back to `registry="https://registry.npmjs.org` solved the issue. (both commands run without any 404 error)
> 
> Sorry for not noticing this sooner. The problem is with the mirror registry not being updated properly maybe?

Hi @KissBalazs, thanks for flagging this to us. There was an issue of the npm package not getting picked up by the mirrors of npm registry as public, we have now re-triggered a release and this looks like it has solved the problem.

You should be able to see it on the skimdb mirror too, e.g. if you visit https://skimdb.npmjs.com/registry/@snyk%2fcloud-config-parser, it will now show up.

Let us know if there is anything else, thanks.

**Comment by KissBalazs** [comment]
Thank you for the reply. The issue seems to be solved with the mirror. Thank you for looking into this!
