### ISSUE TITLE
Future plans for snyk

### ISSUE THREAD

**Issue by jedrichards** [Snyk/snyk#21]
I've recently enabled snyk on a few projects, and been very impressed. It feels really polished already, despite the beta badge on the website. Good job!

Now having inserted snyk into my CI builds, I'm left wondering about the future of snyk. Is it always going to be free to use like this, is it fully open source and community driven, or do you have plans to introducing payment plans of some kind? I'm curious because now I assume I have a dependency on snyk servers being online in my build ... ?

Thanks again.

**Comment by johannakoll** [comment]
Thanks for the positive feedback! 

Regarding future plans, we are committed to securing the open source landscape, and have open source projects use Snyk as much as possible. Our test and protect functionality are meant to remain free. Monitoring your projects for vulnerabilities will at some point have a premium component (additionally to a limited free plan). We are currently working out the details, so I hope you understand that we can't provide more specific information just yet.

**Comment by jedrichards** [comment]
That sounds fair enough. The projects I'm using snyk with at the moment are private, so was slightly concerned that you might move to the typical "free for open source, paid for private" model in future. But if the plan at the moment is to at least keep `snyk test` free then that's good enough for me for now :+1:
