### ISSUE TITLE
Missing patch files should be reported explicitly.

### ISSUE THREAD

**Issue by dwaynebailey** [snyk/snyk#211]
- `node -v`: v10.9.0
- `npm -v`: 6.2.0
- `snyk -v`: 1.90.2
- Command run:
snyk protect (via npm run within package.json)

### Expected behaviour

It completes without failure or reports what patch is failing.  It was only when I added `--debug` that it expose the fact that it was trying to apply a patch mentioned in `.snyk`.  The error should report that it can't find a patch listed in the `.snyk` file.

### Actual behaviour

```
> snyk protect

Failed to fetch patch file

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccd-case-print-service@1.2.0 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccd-case-print-service@1.2.0 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Steps to reproduce

package.json setup as Snyk bot wanted it https://github.com/hmcts/ccd-case-print-service/commit/d04d49a031a32f88ee383d353d99b26bb25a29b6
yarn install
npm run snyk-protect

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by dwaynebailey** [comment]
With `--debug` I'm also seeing the same 403 that @fekle reports.

**Comment by miiila** [comment]
Hi @dwaynebailey and @fekle. I am sorry, but we had some temporary hiccup in patch avaialability. It shouldbe gone now and everything should behave as usual.

I am going to close this issue. Feel  free to reopen if you would still experience any problems.
