### ISSUE TITLE
[🐛] The engine "node" is incompatible with this module (snyk installation node v < 16.7.0) 

### ISSUE THREAD

**Issue by yarinvak** [snyk/snyk#2176]
- `node -v`: 12.8.2
- `npm -v`: 6.14.14
- `snyk -v`: latest
- OS: (e.g. OSX, Linux, Windows, ...): Linux
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...): `yarn global add snyk`

### Expected behaviour

Snyk should be installed

### Actual behaviour

errors are received:
```
error boolean@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 16.7.0". Got "12.22.4"
error Found incompatible module.
```

### Steps to reproduce

run `yarn global add snyk`

---

It's related to this issue in the `boolean` package you use: https://github.com/thenativeweb/boolean/issues/317
right now snyk cannot be installed when node version is lower than 16.7.0

**Comment by yarinvak** [comment]
if you can use version 3.1.2 of boolean specificely until they solve the issue in a further release

**Comment by JackuB** [comment]
Hey, yup we saw this in [our smoke tests](https://github.com/snyk/snyk/runs/3373238935?check_suite_focus=true) as well and we are monitoring it.
Waiting for the Boolean@3.1.4
