### ISSUE TITLE
Error "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by jurgi** [snyk/snyk#219]
- `node -v`: 8.11.2
- `npm -v`: 6.41
- `snyk -v`: 1.95.3
- Command run (Windows 10):
set https_proxy=http://XXX.YY.ZZZ.2:11 && set http_proxy=http://XXX.YY.ZZZ.2:11 && set NODE_TLS_REJECT_UNAUTHORIZED=0 && snyk test

### Actual behaviour
I am behind a company proxy and with the above command I receive the error `self signed certificate in certificate chain`
I have npm / yarn configured with `strict-ssl false` but it does not seem to work.

Is there any way to prevent the command checks the certificates?

---
snyk test { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder XXXXXXXXXXXXXXXXXX +0ms
  snyk found package file yarn.lock in XXXXXXXXXXXXXXXXXX +0ms
  snyk analytics add local true +0ms
  snyk analytics add using node_modules to get dependency tree true +0ms
  snyk policies found [ 'XXXXXXXXXXXXXXXXXX' ] +0ms
  snyk analytics add policies 1 +30s
  snyk analytics add packageManager npm +0ms
  snyk analytics add packageName lk-app +0ms
  snyk analytics add packageVersion 5.9.10 +0ms
  snyk analytics add package lk-app@5.9.10 +0ms
  snyk sending request to: https://snyk.io/api/v1/vuln/npm +0ms
  snyk request body size: 42664609 +0ms
  snyk gzipped request body size: 1675679 +0ms
  snyk analytics add payloadSize 42664609 +2s
  snyk analytics add gzippedPayloadSize 1675679 +0ms
  snyk using proxy: http://XXX.YY.ZZZ.2:11  +0ms
  snyk Failed to test 1 projects, errors: +0ms
  snyk error: Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) +0ms
  snyk analytics add error-message
Testing XXXXXXXXXXXXXXXXXX...

self signed certificate in certificate chain +308ms
  snyk analytics add error Error:
Testing XXXXXXXXXXXXXXXXXX...

self signed certificate in certificate chain
    at C:\Users\XXXXX\AppData\Local\Yarn\Data\global\node_modules\snyk\cli\commands\test.js:153:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +1ms
  snyk analytics add error-code SELF_SIGNED_CERT_IN_CHAIN +0ms
  snyk analytics add command test +1ms
Error:
Testing XXXXXXXXXXXXXXXXXX...

self signed certificate in certificate chain
    at C:\Users\XXXXX\AppData\Local\Yarn\Data\global\node_modules\snyk\cli\commands\test.js:153:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { command: 'bad-command',
  args: [ { debug: true, org: undefined, showVulnPaths: true } ],
  metadata:
   { local: true,
     'using node_modules to get dependency tree': true,
     policies: 1,
     packageManager: 'npm',
     packageName: 'lk-app',
     packageVersion: '5.9.10',
     package: 'lk-app@5.9.10',
     payloadSize: 42664609,
     gzippedPayloadSize: 1675679,
     'error-message': '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting XXXXXXXXXXXXXXXXXX...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mself signed certificate in certificate chain',
     error: 'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mTesting XXXXXXXXXXXXXXXXXX...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22mself signed certificate in certificate chain\n    at C:\\Users\\xxxxxx\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\snyk\\cli\\commands\\test.js:153:23\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': 'SELF_SIGNED_CERT_IN_CHAIN',
     command: 'test' },
  version: '1.95.3',
  os: 'Windows 10',
  nodeVersion: 'v8.11.2',
  id: '0d2221f32d6e6dfcaca4feacfdb3b935a7be7a0a',
  ci: false,
  durationMs: 32400 } +4ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +316ms
  snyk request body size: 1252 +1ms
  snyk gzipped request body size: 578 +1ms
  snyk using proxy: http://XXX.YY.ZZZ.2:11  +0ms
  snyk analytics { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }

**Comment by darscan** [comment]
Hello @jurgi 

You can try the `--insecure` option

**Comment by jurgi** [comment]
> Hello @jurgi
> 
> You can try the `--insecure` option

I had not seen that option. Now it works perfectly. Thank you very much @darscan

**Comment by darscan** [comment]
My please, happy it's working 😄

**Comment by ygonzalezo** [comment]
Hello

I would like to know in which node.jks file this property is added. I appreciate your help, since I am having the same error with an application that works with node.js

Regards
MilenaG
