### ISSUE TITLE
Unpublished package list no longer included in npm module, so "snyk test-unpublished" no longer works

### ISSUE THREAD

**Issue by brownjava** [snyk/snyk#225]
- `node -v`: v8.9.3
- `npm -v`: 6.4.0
- `snyk -v`: 1.99.0
- Command run:

./node_modules/snyk/dist/cli/index.js test-unpublished
Error: ENOENT: no such file or directory, open '/Volumes/classy/projects/classypay_email/node_modules/snyk/dist/cli/commands/unpublished/package-list.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/Volumes/classy/projects/classypay_email/node_modules/snyk/src/cli/commands/unpublished/index.js:14:21)
    at /Volumes/classy/projects/classypay_email/node_modules/snyk/src/lib/hotload.js:16:21
    at Object.<anonymous> (/Volumes/classy/projects/classypay_email/node_modules/snyk/src/cli/index.ts:32:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

### Expected behaviour

This command should check for unpublished packages as it did in previous versions of snyk.

### Actual behaviour

It doesn't, because package-list.txt is missing:

Here's the source:

jeremy@bookers ~/p/snyk (master)> ls -l src/cli/commands/unpublished/package-list.txt
-rw-r--r--  1 jeremy  staff  3185 Sep 26 15:34 src/cli/commands/unpublished/package-list.txt
jeremy@bookers ~/p/snyk (master *)> yarn build
yarn run v1.9.4
$ tsc
✨  Done in 3.70s.
jeremy@bookers ~/p/snyk (master *)> npm pack

> snyk@1.99.1 prepare /Volumes/classy/projects/snyk
> npm run build

> snyk@1.99.1 build /Volumes/classy/projects/snyk
> tsc

npm notice
npm notice 📦  snyk@1.99.1
npm notice === Tarball Contents ===
npm notice 3.0kB  package.json
npm notice 511B   .snyk
npm notice 58B    config.default.json
npm notice 5.2kB  Contributor-Agreement.md
npm notice 550B   LICENSE
npm notice 10.1kB README.md
npm notice 2.0kB  SECURITY.md
npm notice 4.5kB  dist/cli/args.js
npm notice 3.9kB  dist/cli/args.js.map
npm notice 4.8kB  dist/cli/commands/auth.js
npm notice 4.5kB  dist/cli/commands/auth.js.map
npm notice 2.0kB  dist/cli/commands/config.js
npm notice 2.0kB  dist/cli/commands/config.js.map
npm notice 598B   dist/cli/commands/help.js
npm notice 687B   dist/cli/commands/help.js.map
npm notice 2.0kB  dist/cli/commands/ignore.js
npm notice 2.0kB  dist/cli/commands/ignore.js.map
npm notice 866B   dist/cli/commands/index.js
npm notice 968B   dist/cli/commands/index.js.map
npm notice 607B   dist/cli/commands/modules.js
npm notice 801B   dist/cli/commands/modules.js.map
npm notice 7.7kB  dist/cli/commands/monitor.js
npm notice 6.5kB  dist/cli/commands/monitor.js.map
npm notice 410B   dist/cli/commands/policy.js
npm notice 530B   dist/cli/commands/policy.js.map
npm notice 2.5kB  dist/cli/commands/protect/index.js
npm notice 2.5kB  dist/cli/commands/protect/index.js.map
npm notice 29.1kB dist/cli/commands/protect/prompts.js
npm notice 24.3kB dist/cli/commands/protect/prompts.js.map
npm notice 2.1kB  dist/cli/commands/protect/tasks.js
npm notice 2.0kB  dist/cli/commands/protect/tasks.js.map
npm notice 20.1kB dist/cli/commands/protect/wizard.js
npm notice 16.9kB dist/cli/commands/protect/wizard.js.map
npm notice 12.8kB dist/cli/commands/scenario.js
npm notice 13.1kB dist/cli/commands/scenario.js.map
npm notice 19.9kB dist/cli/commands/test.js
npm notice 17.3kB dist/cli/commands/test.js.map
npm notice 2.0kB  dist/cli/commands/unpublished/index.js
npm notice 2.1kB  dist/cli/commands/unpublished/index.js.map
npm notice 574B   dist/cli/commands/unpublished/prune.js
npm notice 738B   dist/cli/commands/unpublished/prune.js.map
npm notice 725B   dist/cli/commands/unpublished/walk.js
npm notice 911B   dist/cli/commands/unpublished/walk.js.map
npm notice 96B    dist/cli/commands/version.js
npm notice 177B   dist/cli/commands/version.js.map
npm notice 295B   dist/cli/copy.js
npm notice 420B   dist/cli/copy.js.map
npm notice 3.5kB  dist/cli/index.js
npm notice 3.3kB  dist/cli/index.js.map
npm notice 336B   dist/cli/runtime.js
npm notice 394B   dist/cli/runtime.js.map
npm notice 1.0kB  dist/lib/alerts.js
npm notice 1.2kB  dist/lib/alerts.js.map
npm notice 2.5kB  dist/lib/analytics.js
npm notice 2.8kB  dist/lib/analytics.js.map
npm notice 531B   dist/lib/api-token.js
npm notice 700B   dist/lib/api-token.js.map
npm notice 832B   dist/lib/authorization.js
npm notice 918B   dist/lib/authorization.js.map
npm notice 229B   dist/lib/bus.js
npm notice 379B   dist/lib/bus.js.map
npm notice 1.3kB  dist/lib/capture.js
npm notice 1.4kB  dist/lib/capture.js.map
npm notice 997B   dist/lib/config.js
npm notice 1.1kB  dist/lib/config.js.map
npm notice 4.0kB  dist/lib/detect.js
npm notice 3.1kB  dist/lib/detect.js.map
npm notice 1.3kB  dist/lib/display-policy.js
npm notice 1.6kB  dist/lib/display-policy.js.map
npm notice 4.6kB  dist/lib/error.js
npm notice 2.7kB  dist/lib/error.js.map
npm notice 475B   dist/lib/exec.js
npm notice 646B   dist/lib/exec.js.map
npm notice 1.4kB  dist/lib/hook.js
npm notice 1.5kB  dist/lib/hook.js.map
npm notice 592B   dist/lib/hotload.js
npm notice 566B   dist/lib/hotload.js.map
npm notice 1.5kB  dist/lib/index.js
npm notice 1.6kB  dist/lib/index.js.map
npm notice 458B   dist/lib/is-ci.js
npm notice 493B   dist/lib/is-ci.js.map
npm notice 2.6kB  dist/lib/isolate.js
npm notice 2.9kB  dist/lib/isolate.js.map
npm notice 705B   dist/lib/module-info/index.js
npm notice 695B   dist/lib/module-info/index.js.map
npm notice 96B    dist/lib/modules.js
npm notice 165B   dist/lib/modules.js.map
npm notice 3.6kB  dist/lib/monitor.js
npm notice 3.3kB  dist/lib/monitor.js.map
npm notice 1.7kB  dist/lib/npm.js
npm notice 1.9kB  dist/lib/npm.js.map
npm notice 1.2kB  dist/lib/plugins/index.js
npm notice 1.1kB  dist/lib/plugins/index.js.map
npm notice 474B   dist/lib/plugins/npm/index.js
npm notice 564B   dist/lib/plugins/npm/index.js.map
npm notice 898B   dist/lib/plugins/rubygems/index.js
npm notice 944B   dist/lib/plugins/rubygems/index.js.map
npm notice 1.1kB  dist/lib/plugins/rubygems/inspectors/gemfile.js
npm notice 1.2kB  dist/lib/plugins/rubygems/inspectors/gemfile.js.map
npm notice 1.1kB  dist/lib/plugins/rubygems/inspectors/gemspec.js
npm notice 1.3kB  dist/lib/plugins/rubygems/inspectors/gemspec.js.map
npm notice 121B   dist/lib/plugins/rubygems/inspectors/index.js
npm notice 233B   dist/lib/plugins/rubygems/inspectors/index.js.map
npm notice 386B   dist/lib/plugins/rubygems/inspectors/try-get-spec.js
npm notice 591B   dist/lib/plugins/rubygems/inspectors/try-get-spec.js.map
npm notice 474B   dist/lib/plugins/yarn/index.js
npm notice 565B   dist/lib/plugins/yarn/index.js.map
npm notice 4.1kB  dist/lib/protect/apply-patch.js
npm notice 3.5kB  dist/lib/protect/apply-patch.js.map
npm notice 1.2kB  dist/lib/protect/dedupe-patches.js
npm notice 1.3kB  dist/lib/protect/dedupe-patches.js.map
npm notice 1.0kB  dist/lib/protect/ensure-patch.js
npm notice 808B   dist/lib/protect/ensure-patch.js.map
npm notice 1.7kB  dist/lib/protect/fetch-patch.js
npm notice 1.7kB  dist/lib/protect/fetch-patch.js.map
npm notice 1.7kB  dist/lib/protect/get-vuln-source.js
npm notice 1.5kB  dist/lib/protect/get-vuln-source.js.map
npm notice 1.1kB  dist/lib/protect/ignore.js
npm notice 1.4kB  dist/lib/protect/ignore.js.map
npm notice 1.1kB  dist/lib/protect/index.js
npm notice 1.2kB  dist/lib/protect/index.js.map
npm notice 7.7kB  dist/lib/protect/patch.js
npm notice 6.5kB  dist/lib/protect/patch.js.map
npm notice 390B   dist/lib/protect/patches-for-package.js
npm notice 569B   dist/lib/protect/patches-for-package.js.map
npm notice 260B   dist/lib/protect/strip-versions.js
npm notice 363B   dist/lib/protect/strip-versions.js.map
npm notice 5.2kB  dist/lib/protect/update.js
npm notice 5.1kB  dist/lib/protect/update.js.map
npm notice 1.3kB  dist/lib/protect/write-patch-flag.js
npm notice 1.6kB  dist/lib/protect/write-patch-flag.js.map
npm notice 624B   dist/lib/request/index.js
npm notice 709B   dist/lib/request/index.js.map
npm notice 3.3kB  dist/lib/request/request.js
npm notice 3.3kB  dist/lib/request/request.js.map
npm notice 2.6kB  dist/lib/sln/index.js
npm notice 2.4kB  dist/lib/sln/index.js.map
npm notice 608B   dist/lib/snyk-test/common.js
npm notice 758B   dist/lib/snyk-test/common.js.map
npm notice 1.6kB  dist/lib/snyk-test/index.js
npm notice 1.7kB  dist/lib/snyk-test/index.js.map
npm notice 11.6kB dist/lib/snyk-test/npm/index.js
npm notice 9.7kB  dist/lib/snyk-test/npm/index.js.map
npm notice 7.2kB  dist/lib/snyk-test/run-test.js
npm notice 6.8kB  dist/lib/snyk-test/run-test.js.map
npm notice 3.2kB  dist/lib/spinner.js
npm notice 3.9kB  dist/lib/spinner.js.map
npm notice 841B   dist/lib/sub-process.js
npm notice 1.0kB  dist/lib/sub-process.js.map
npm notice 214B   dist/lib/user-config.js
npm notice 321B   dist/lib/user-config.js.map
npm notice 1.5kB  dist/lib/version.js
npm notice 1.4kB  dist/lib/version.js.map
npm notice 1.2kB  dist/lib/yarn.js
npm notice 1.4kB  dist/lib/yarn.js.map
npm notice 165B   help/api-license.txt
npm notice 550B   help/config.txt
npm notice 653B   help/file.txt
npm notice 2.9kB  help/help.txt
npm notice 495B   help/ignore.txt
npm notice 732B   help/orgs.txt
npm notice 51B    help/usage.txt
npm notice 322B   help/wizard-intro.txt
npm notice === Tarball Details ===
npm notice name:          snyk
npm notice version:       1.99.1
npm notice filename:      snyk-1.99.1.tgz
npm notice package size:  109.1 kB
npm notice unpacked size: 443.7 kB
npm notice shasum:        eaf05d8cb44ca861b11c95318a74c8b6ea3fc8fb
npm notice integrity:     sha512-JyCfTP5c097zr[...]iadzbZPPSUWng==
npm notice total files:   163
npm notice
snyk-1.99.1.tgz
jeremy@bookers ~/p/snyk (master *)> tar tzvf snyk-1.99.1.tgz | grep package-list.txt
jeremy@bookers ~/p/snyk (master *) [1]>

### Steps to reproduce

1. Create a project with package.json referencing snyk.
2. Run snyk from within node modules doing "test-unpublished"

**Comment by Kirill89** [comment]
Fixed in v1.100.1.
