### ISSUE TITLE
snyk test --file cannot traverse nested subdirectories

### ISSUE THREAD

**Issue by fillyD** [snyk/snyk#244]
- `node -v`: v8.11.3
- `npm -v`: 5.6.0
- `snyk -v`: 1.103.4
- Command run:

### Expected behaviour
To be able to pick up dependency files wherever they are located

### Actual behaviour
Not able to pick up a package.json found in a second level directory x/y/package.json

### Steps to reproduce
snyk test --file=x/y/package.json --json --dev 

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by darmalovan** [comment]
Can you share the command output with `--debug`?
I wasn't able to reproduce it locally.

**Comment by fillyD** [comment]
you are right, using --debug led on to the actual issue. It is my fault for not telling the whole story.

I use snyk-to-html to generate reports, basically it found the json to be invalid and ended up breaking the report. I assumed it wasn't able to find the file. Sorry.

I was able to fix this with a jq tweak

**Comment by mathiasconradt** [comment]
This does not work when scanning remote public github repos. Compare local scan (left) vs. remote scan (right). Or am I missing something?

On the right, it also defaults to maven as the package manager, even when I add `--package-manager=npm` (not shown in screen).

![Screen Shot 2020-10-23 at 09 22 33](https://user-images.githubusercontent.com/295122/96969164-52579c00-1512-11eb-9107-142757e53030.png)
