### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by DanielRuf** [snyk/snyk#247]
- `node -v`: 10.12.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.100.1
- Command run:

### Expected behaviour
`snyk test --file=bower.json` should check the bower dependencies (which are also on npmjs)

### Actual behaviour
`Error: Could not detect package manager for file: bower.json`

### Steps to reproduce
Create a bower project with a bower.json and run `snyk test --file=bower.json`

**Comment by DanielRuf** [comment]
https://github.com/snyk/snyk/blob/master/src/lib/detect.ts#L29-L47

Also there is the shrinkwrap file missing from npm (and we can still use `npm shrinkwrap`), the shrinkwrap.yml of pnpm and the new pnp config file of Yarn PnP.

**Comment by robcresswell** [comment]
Hey Daniel,

We have no plans to support bower given it has been deprecated for some time. I'm unsure about pnpm or Yarn PnP however; it would be helpful if you could post these as distinct issues for others to search for 😄

**Comment by NicolasCARPi** [comment]
IMHO it's useless to spend time on anything bower related… It's a thing of the past, like horses for transportation :p

**Comment by DanielRuf** [comment]
> IMHO it's useless to spend time on anything bower related… It's a thing of the past, like horses for transportation :p

Sorry but Bower is still used (in current but not new projects) and still gets updates ;-)

**Comment by JackuB** [comment]
Hi, we are currently not planning to support Bower in Snyk CLI and I'll be closing this issue. Bower announced end-of-life in mid 2017. We are focusing on supporting npm and yarn.
