### ISSUE TITLE
Snyk does not install globally when in subdirectory.

### ISSUE THREAD

**Issue by adam-moss** [Snyk/snyk#25]
- `node -v`:
5.11.0

- `npm -v`:
3.8.7

- `snyk -v`:
N/A

- Command run:
`npm install -g snyk --production`

### Expected behaviour
snyk gets installed.

### Actual behaviour
npm ERR! addLocal Could not install /Users/user.name/projects/snyk
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/user.name/.nvm/versions/node/v5.11.0/bin/node" "/Users/user.name/.nvm/versions/node/v5.11.0/bin/npm" "install" "-g" "snyk" "--production"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.7

npm ERR! No version provided in package.json

### Steps to reproduce
mkdir ~/projects
cd ~/projects
npm install -g snyk --production

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by remy** [comment]
I can't replicate this at all... I strongly suspect there's something else at play - the error `npm ERR! No version provided in package.json` seems suspicious to me.

Here's what I've tested with (I note that a fresh install of node 5.11.0 comes with npm@3.8.6, not npm@3.8.7 - which you have, but note that I also manually installed npm@3.8.7 and had the same result as below):

```bash
 ~/Sites/snyk-tests/g-inst ⮀
❯ cat package.json
{
  "name": "g-inst",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
 ~/Sites/snyk-tests/g-inst ⮀
❯ npm install -g snyk --production
/Users/remy/.nvm/versions/node/v5.11.0/bin/snyk -> /Users/remy/.nvm/versions/node/v5.11.0/lib/node_modules/snyk/cli/index.js
/Users/remy/.nvm/versions/node/v5.11.0/lib
└─┬ snyk@1.14.1
  ├── abbrev@1.0.7
  ├── ansi-escapes@1.4.0
  ... snipped
  │ ├── semver-diff@2.1.0
  │ └── string-length@1.0.1
  └─┬ url@0.11.0
    ├── punycode@1.3.2
    └── querystring@0.2.0

 ~/Sites/snyk-tests/g-inst ⮀
❯ snyk -v         
1.14.1
 ~/Sites/snyk-tests/g-inst ⮀
❯ npm -v          
3.8.6
 ~/Sites/snyk-tests/g-inst ⮀
❯ node -v         
v5.11.0
```

**Comment by adam-moss** [comment]
Ahhh... I've realised what it is!

In ~/projects/ I have a snyk folder for the PR I submitted.  So npm is failing to install from there but does from other locations.  So more appropriately a bug in npm.

**Comment by remy** [comment]
I assume you will, but if not, I'd definitely recommend filing on the https://github.com/npm/npm repo - they'll be able to extact some logs (I think) to help diagnose the issue.

Closing here as I _suspect_ it's indeed an npm thing (happy to reopen if needs be).
