### ISSUE TITLE
Outdated dep socks triggers warning on install

### ISSUE THREAD

**Issue by Ryuno-Ki** [snyk/snyk#259]
- `node -v`: v11.0.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.105.1
- Command run: `npm install snyk --save-dev`

### Expected behaviour

All dependencies up-to-date.

### Actual behaviour

> npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

### Steps to reproduce

Execute the above command in a new repo.

--- 

See also:

```
$ npm ls socks@1.1.10
lobsang.js@0.1.0 $HOME/src/$REPONAME
└─┬ snyk@1.105.1
  └─┬ proxy-agent@2.3.1
    ├─┬ pac-proxy-agent@2.0.2
    │ └─┬ socks-proxy-agent@3.0.1
    │   └── socks@1.1.10 
    └─┬ socks-proxy-agent@3.0.1
      └── socks@1.1.10 
```

**Comment by weyusi** [comment]
proxy-agent 3 drops support for node <6 https://github.com/TooTallNate/node-proxy-agent/commit/65fcf7af73fb1324c7e29ff7dee63b962951b457

**Comment by adrukh** [comment]
Yes indeed! We plan on dropping node4 support soon, and will perform the upgrade then.

**Comment by Berkmann18** [comment]
I get the same issue with:
- node -v: `v11.0.0`
- npm -v: `6.4.1`
- snyk -v: `1.111.1`

**Comment by karniwl** [comment]
@Berkmann18 we dropped node4 support and performed the upgrade, do you still get the issue?

**Comment by Berkmann18** [comment]
@karniwl I don't think so.

**Comment by karniwl** [comment]
@Berkmann18 thanks for the update, I'm closing the issue then. Please re-open it if it happens again. Thank you!
