### ISSUE TITLE
snyk test

### ISSUE THREAD

**Issue by antoligy** [snyk/snyk#28]
Hey,

In many workflows it's possible to have separate branches in which different dependencies or different versions of dependencies are being worked on in parallel.

Currently hooking up `snyk test` in this style of workflow is quite disruptive as using it the recommended way (`snyk test` in the main test suite) causes tests to fail, meaning for example that the same upgrade might be performed multiple times in separate branches (a better case scenario) or more likely that these failures will just be ignored in order to get unrelated additions merged in (therefore in my mind compromising the main purpose of snyk).

Does using `snyk test` in tests result in a dangerous level of noise, where its inconvenience might outweigh its benefits?

I was wondering if it is worth a conversation about possible ways around this, whether they should be in snyk or should be applied at workflow or test level?

As a possible solution I have been toying with the idea that it might be potentially worth introducing a new `--branch-deps-only` parameter to `snyk test` which would only perform tests on `package.json` entries modified within the current branch (git specific - so I guess this starts to introduce levels of complexity that probably shouldn't be in Snyk?  Putting out there anyway)

Cheers!
Alex

**Comment by remy** [comment]
Cutting through this, maybe what would suit your workflow (since *all* your branches carry the same vulns), is that `snyk test` is only run on `master` (or some single branch that all branches lead to).

For this,  I'd recommend moving the `snyk test` out of the `package.json` and into your CI config to only run when branch is master.

If you're using Travis for instance this is pretty simple to move it to your `before_script `. 

Really the point is you don't want to ship with vulns, but I also understand how you could have many branches that all share the same vuln and upgrading them all would then cause the same merge conflicts over and over.

What do you think?

**Comment by antoligy** [comment]
I think that makes sense - Potentially then, `snyk monitor` should be recommended for "feature" branches, while `snyk test` should be recommended for `stable` branches?

I'll give that a go for the meantime, though it might be nice to find that this new dependency I'm introducing is vulnerable (for dev workflows it might make sense to say "run snyk test first!")

**Comment by remy** [comment]
Equally it would be good clean out those vulns across all your branches too - that'll probably allow you to re-introduce `snyk test` to your dev workflow properly again.

**Comment by adrukh** [comment]
@antoligy we are thinking about introducing branch support for watched GitHub repositories. That is, you will be able to monitor a specific repo _on a specific branch_, having:
1 - PRs against this branch tested for vulnerabilities
2 - Pushes to this branch will create updated snapshots of the Snyk project

Let me know if this is relevant, I'd like to exchange further ideas about our approach.

Closing this issue as I believe the original question was answered (cli support of branches).

**Comment by madchap** [comment]
@adrukh do you already have an enhancement request to introduce branch support in Github? If so, can you please provide the link? To this date, it does not seem to be in there yet.

Thank you.

**Comment by maban** [comment]
@madchap Hi! This feature is still in beta as we're still ironing out some kinks. We can enable this for your org if you'd like to try it out.

**Comment by madchap** [comment]
Hey @maban,

If stable enough, please go ahead. If you can enable that for org 'cloudbees' and 'codeship', it would be great.

Thanks,
