### ISSUE TITLE
`Missing node_modules` error complicates testing repository with multiple packages.

### ISSUE THREAD

**Issue by nemreid** [snyk/snyk#289]
- `node -v`: v8.11.1
- `npm -v`: 6.4.1
- `snyk -v`: 1.112.0
- Command run: `lerna exec 'snyk test --dev --severity-priority=high' --parallel --no-sort`

First, thank you for this fantastic product! It's been very helpful in quickly and conveniently testing our packages.
I'm testing Snyk for possible integration with our CI, but our monorepo project has a lot of packages, and one in particular has no dependencies, which means there is no `node_modules` folder to test, causing Snyk to always throw an error, which is problematic for CI. Rather than assume that the tested repository has to have a node_modules folder, it might be better if it checked the `package.json` for any dependencies at all first, or at least has a configurable option (e.g. `--ignore-no-dependencies`) to suppress errors with no dependencies.

### Expected behaviour
Snyk does not act on packages with no dependencies.

### Actual behaviour
Throws error: `Missing node_modules folder: we can't test without dependencies. Please run 'npm install' first.`
Seems to have been introduced in https://github.com/snyk/snyk/issues/126. Useful feature, would be more useful if configurable.

### Steps to reproduce
`snyk test` on a package with no dependencies.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by mennovandiermen** [comment]
Thanks @miiila, it is an acceptable workaround.

**Comment by lili2311** [comment]
@mennovandiermen is this still an issue for you in the latest version of the CLI?

**Comment by mennovandiermen** [comment]
@lili2311 I just tested it on our no-dependency package, and got the output:
`✓ Tested 0 dependencies for known vulnerabilities , no vulnerable paths found.`
Looks great, thank you for fixing this!

**Comment by lili2311** [comment]
yay 🎉

**Comment by mennovandiermen** [comment]
Hm, I'm testing snyk again and I'm seeing that it is not, in fact, fixed. It is possible that last time I tested and closed this issue I did have a `package-lock.json`. Now, without a lockfile, and no dependencies listed in `package.json`, I do still get the error:
`Missing node_modules folder: we can't test without dependencies.`.

**Comment by lili2311** [comment]
This is intended behaviour, we can't determine any transitive dependencies without `node_modules` present if no lockfile is present either.  We prefer to traverse `node_modules` vs using npm js registry API to determine all transitive dependencies on the CLI as this is a project you have on your machine and at the time of testing it would be best we test the actual installed dependencies.

Snyk CLI is often used in CI like Travis where testing exactly what was just installed is preferred. What is the behaviour you would expect in this situation?

**Comment by mennovandiermen** [comment]
I should clarify this is a nested package in a monorepo with no dependencies. I understand that in normal circumstances I would at least have `snyk` as a dependency.  I guess this is a consequence of using a monorepo, as I do not intend to add `snyk` as a dependency of every nested package, but to use the executable installed at the root for all nested packages. It does seem like monorepo support in snyk is technically possible, but not exactly first-class?

**Comment by mennovandiermen** [comment]
To illustrate with a use case:
If I create an empty folder, run `npm init`, accept all the default options with no changes, then run snyk which is globally installed (`npm install -g snyk`)  as per the docs, I will run into this error. I understand that it is best to test any transitive dependencies that may exist, but some kind of flag to disable that behavior if no dependencies are defined would be nice.

Thanks for replying so quickly, by the way!

**Comment by lili2311** [comment]
Ah I see, missed the Lerna part, this makes more sense now 😅. So you have a monorepo and a `node_modules` AND `package-lock.json` in the root? Or just one of these?

We are working on supporting Yarn workspaces which will pave the way to first class support for this as well.  The intended behaviour being able to scan from the root of the monorepo and get multiple test results back via an opt-in flag.

I think we can do an improvement and check the length of packages in `package.json` before complaining about `node_modules` which should help here as you say there are no dependencies in the `package.json` under the dependencies property.

**Comment by mennovandiermen** [comment]
The root would have `node_modules`, yes.
Right, there are is no `dependencies` property at all in `package.json` (because none are needed), so it would be nice if snyk could ignore missing `node_modules` if there are no dependencies.

The suggested improvement sounds like exactly what I need for my use case in the short term, I've managed to figure out the rest of the issues I had.

**Comment by lili2311** [comment]
👋 Hi there! Are you able to share an example repo/project we are currently working on Yarn workspaces support and would like to see what else is needed on our end to support Lerna projects too.

**Comment by tedconn** [comment]
@lili2311 do you still need an example project?

**Comment by lili2311** [comment]
@tedconn if you have one that would be amazing! I was just discussing creating a fixture with the team :)

**Comment by lili2311** [comment]
We have shipped Yarn workspaces support https://github.com/snyk/snyk/issues/350 if the lerna project is using the same syntax in the package.json the `yarn` project should be scannable using the same commands.

For `npm` more work would be needed here still.

**Comment by lili2311** [comment]
@nemreid does the recent release satisfy your usecase?

**Comment by lili2311** [comment]
@nemreid did you get a chance to confirm?

**Comment by nemreid** [comment]
@lili2311 Sorry for the delay, it's been a busy couple weeks. I did test it out again. I did not use yarn, as npm is our use case, and I'm still seeing the failure.
To help illustrate, I did set up an example repo at https://github.com/nemreid/snyk-lerna-failure.
Please let me know if you have any questions. Thanks!

**Comment by lili2311** [comment]
Thanks @nemreid I was able to do a spike and get these scanning. Will look at validating some assumptions made here and work on scheduling this in.
<img width="654" alt="Screen Shot 2020-08-21 at 18 21 33" src="https://user-images.githubusercontent.com/2911613/91058482-69683380-e620-11ea-90e0-ebabea940cb9.png">

**Comment by lili2311** [comment]
@tedconn @nemreid could you please confirm:
- lerna has a lockfile in the *root* next to lerna.json for you projects?

I am trying to generate some test fixtures but it automatically creates a lockfile next to each package for me, is there a particular command to get the lockfile in the root? Are both root level lock and individual lock supported? Thanks!

**Comment by tedconn** [comment]
@lili2311 we use a root level lock file but we do _not_ use a package level lock file. If I run `yarn install` from a package, no lock file is generated. This looks like it might be related to the `workspaces` node in the root package.json. If I create a new folder under `src/packages` but which is not listed in workspaces, then the yarn.lock file is created.

**Comment by lili2311** [comment]
@nemreid there is no root lockfile in your example is that correct? I created one, but I want to make sure what is your use-case here? What is your expectation that snyk scans in order to resolve the dependency versions installed?

**Comment by nemreid** [comment]
@lili2311 When following the commands in my example's README:

```
  $ npm install
  $ npm run bootstrap
  $ npm run snyk
```

You will find that there is a root lockfile next to `lerna.json`, created by the initial `npm install`. My concern is not with Snyk scans in the root. 

My concern is with scanning the `packages/subpkg` directory using `$ lerna exec 'snyk test --dev'`. This package has no dependencies in `package.json`.

The scan blows up because there is no lockfile in the `subpkg` dir. `lerna bootstrap` does not create one.
My desirement is for `snyk` to look at `package.json`, see that there are no dependencies, and skip checking for a lockfile and end the scan attempt, as there is *nothing to resolve*.

**Comment by lili2311** [comment]
Thanks for a quick reply @nemreid `lerna` project structures is exactly what we are working on supporting :)

After following your instructions + using the CLI build on [linked PR]() I get:
<img width="1252" alt="Screen Shot 2020-08-27 at 17 02 17" src="https://user-images.githubusercontent.com/2911613/91466449-117f3600-e887-11ea-80ea-cbd21b3aa00a.png">


However when adding a dependency to `subpkg` so that I can show it scanning that correctly `npm run bootstrap` ends up adding a lockfile to the `subpkg` folder which is different to what you would have if you used `yarn` with `lerna` where there is only 1 root lockfile.

Could you share how you would normally add packages to the `subpkg`? Would the dependencies of that be in the *root* lockfile just like `yarn`? 

>My desirement is for snyk to look at package.json, see that there are no dependencies, and skip checking for a lockfile and end the scan attempt, as there is nothing to resolve.

I will look if we can do a separate small check for this and skip going further if there are no deps.

**Comment by nemreid** [comment]
> After following your instructions + using the CLI build on linked PR I get:

That looks promising! I suspect merger of the PR will close this issue.

> Could you share how you would normally add packages to the subpkg? Would the dependencies of that be in the root lockfile just like yarn?

This might be weird, in our case we typically have dependencies in the package lockfile, and devDependencies in the root lockfile. However, I'm pretty sure it all works fine when dependencies exist, and I'm not worried about that.

Moreso, having a package, private or otherwise, to hold common code shared between multiple other sibling packages has become useful in our process, and these internal dependency packages don't always have dependencies, so they fail on the scan. For example, packages holding common schemas or type definitions. As they still need to be linked into other packages, we do include them with `lerna.json` for bootstrapping, and this causes them to hiccup on the `snyk test`.

> I will look if we can do a separate small check for this and skip going further if there are no deps.

Thank you. My 30-seconds-of-thought implementation is probably not optimal, so I'm sure whatever you decide will be for the best.

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/pull/1372 merged that will in the future not throw if package.json has no dependencies. @nemreid in your case there is no need for any special Lerna handling as with the fix merged you can use: `snyk test --all-projects` which will scan all `package.json & package-lock.json` combinations it finds and will not throw if any package.json files are found with no dependencies.
This is available in CLI version 1.386.0

**Comment by nemreid** [comment]
@lili2311 Can confirm that this has resolved my use case. I will close the issue. Thanks for the resolution!!

**Comment by arcanis** [comment]
@lili2311 We have a Yarn 2 lockfile, and this error message appears when there's no `node_modules` (which is annoying, since we use PnP installs and thus having no node_modules is a feature) - is it expected? I've tried updating the `snyk` package to no avail.

**Comment by samarara** [comment]
Hi,
I'm currently experiencing some issues with the `snyk test --all-projects` flag in a lerna monorepo. We're using the hoisted approach so all or our node_modules are hoisted at the root level. As a result one of our packages does not have node_modules (within the context of that package). And on another package, the dependency is added to the root package-lock as opposed to the local paclage-lock.
```bash
  snyk-test Analyzing npm dependencies for /Users/desisan/Workspace/enrolment-react/package-lock.json +0ms
  snyk-test Analyzing npm dependencies for /Users/desisan/Workspace/enrolment-react/client/package-lock.json +265ms
  snyk-test 
  snyk-test ✗ Failed to get dependencies for /Users/desisan/Workspace/enrolment-react/client/package-lock.json
  snyk-test ERROR: Dependency @babel/plugin-transform-runtime was not found in package-lock.json. Your package.json and package-lock.json are probably out of sync. Please run "npm install" and try again.
  snyk-test  +0ms
  snyk-test 
  snyk-test ✗ Failed to get dependencies for /Users/desisan/Workspace/enrolment-react/packages/common/package.json
  snyk-test ERROR: Missing node_modules folder: we can't test without dependencies.
  snyk-test Please run 'npm install' first.
  snyk-test  +78ms
  snyk-test Found 7 projects from 11 detected manifests +944ms
✗ 2/9 potential projects failed to get dependencies. Run with `-d` for debug output.
```
Any ideas on a work around for this?
