### ISSUE TITLE
Failed when using `npm ci`

### ISSUE THREAD

**Issue by Berkmann18** [snyk/snyk#300]
- `node -v`: v11.0.0 (and v6.15.1)
- `npm -v`: 6.4.1 (and 5.7.1)
- `snyk -v`: 1.111.1 (and 1.116.2)
- Command run: `snyk protect`

### Expected behaviour
The command runs smoothly like it normally does.

### Actual behaviour
```bash
Could not detect supported target files in /home/travis/build/Berkmann18/TemplateJS/node_modules.
Please see our documentation for supported languages and target files: https://support.snyk.io/getting-started/languages-support and make sure you are in the right directory.
```

### Steps to reproduce
```bash
npm i -g npm@5.7.1 snyk
npm ci
snyk protect
```

**Comment by lili2311** [comment]
👋 Could you please share the output of `snyk test -d` from your CI neviroment and what is the folder that this is run in + which manifest files are present and send this to us to support@snyk.io?

**Comment by Berkmann18** [comment]
@lili2311 Email sent.

**Comment by lili2311** [comment]
👋 @Berkmann18 Is this still an issue for you?

**Comment by Berkmann18** [comment]
@lili2311 Well, no one responded to my email and it seems to [weirdly fail](https://travis-ci.org/Berkmann18/TemplateJS/jobs/506675167) `node@stable` while working fine on `node@lts/*`.

**Comment by lili2311** [comment]
Oh noes, let me chase this up for you.

**Comment by leongold** [comment]
Hey @Berkmann18, I've forked your repo and am running `protect` in the relevant branch (using the aforementioned versions) and everything seems fine:

```
Leons-MacBook-Pro:TemplateJS leongold$ snyk protect
Successfully applied Snyk patches

Leons-MacBook-Pro:TemplateJS leongold$ pwd
/Users/leongold/git/TemplateJS
Leons-MacBook-Pro:TemplateJS leongold$ git status
On branch npmci
```

However, I am getting a similar error to yours when I'm running `protect` inside `node_modules` (as appears in your error message above):

```
Leons-MacBook-Pro:TemplateJS leongold$ cd node_modules/
Leons-MacBook-Pro:node_modules leongold$ snyk protect
Could not detect supported target files in /Users/leongold/git/TemplateJS/node_modules.
Please see our documentation for supported languages and target files: https://support.snyk.io/getting-started/languages-support and make sure you are in the right directory.
```

Could you please try again outside `node_modules` and let us know if this helps?

**Comment by Berkmann18** [comment]
It seems that `snyk` now works well when using `npm ci` (judging by [this build](https://travis-ci.org/Berkmann18/TemplateJS/builds/507863864))/

@leongold The command wasn't running in `node_modules`.
