### ISSUE TITLE
Unable to test a solution with .NET Core / .NET Standard projects

### ISSUE THREAD

**Issue by alexanderkozlenko** [snyk/snyk#302]
- `node -v`: 11.4.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.116.2
- Command run: `test`

### Expected behaviour

The `test` command is executed successfully.

### Actual behaviour

The `test` command fails.

### Steps to reproduce

The following commands were executed after the solution is successfuly built with `dotnet build` command.

Test 1 (results: [test1.log](https://github.com/snyk/snyk/files/2660051/test1.log)):
```
snyk test --debug --file=global.proj > test1.log 2>&1
```
Test 2 (results: [test2.log](https://github.com/snyk/snyk/files/2660052/test2.log)):
```
snyk test --debug --file=src\Anemonis.JsonRpc.sln > test2.log 2>&1
```
Test 3 (results: [test3.log](https://github.com/snyk/snyk/files/2660053/test3.log)):
```
snyk test --debug --file=obj\Anemonis.JsonRpc\project.assets.json > test3.log 2>&1
```

### Source code

- Project repository: https://github.com/alexanderkozlenko/json-rpc
- Exact commit used for testing: [54c7efdf3947d8a4e19a6e859251cd9ee195c171](https://github.com/alexanderkozlenko/json-rpc/tree/54c7efdf3947d8a4e19a6e859251cd9ee195c171)

**Comment by alexanderkozlenko** [comment]
Any update on this?

**Comment by Kirill89** [comment]
Structure of your project is a bit unexpected for `snyk`.

I your case `obj` folder is in root of the repository and there is no relevant project files. I mean you have `global.proj` but it's only reference to other projects.

I can suggest you hackey but working solution:

```bash
cd src/Anemonis.JsonRpc
mkdir -p obj
cp ../../obj/Anemonis.JsonRpc/project.assets.json ./obj
snyk test
```

Output: `Tested 47 dependencies for known vulnerabilities, found 5 vulnerabilities, 10 vulnerable paths.`.

Does it works for you?

**Comment by alexanderkozlenko** [comment]
@Kirill89 thank you for the response and the provided solution. I checked it and it works for me, so I'm able to get a report.

However, I still think that this is a temporary workaround and the issue is still here since the project structure is not complex - it's just not simple (default). For example, Microsoft CoreFX repository also has `obj` folders in a non-default location.

**Comment by lili2311** [comment]
@alexanderkozlenko 👋 Is this still an issue for you? I see we have auto detection in `obj/` and the same folder as the test is run for `project.assets.json`

**Comment by alexanderkozlenko** [comment]
Hi @lili2311! The provided workaround worked, however, the issue is still here - there is no way to test the solution/project w/o additional actions:

- `node -v`: 11.12.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.140.0

Case 1:

`snyk test --file=src\Anemonis.JsonRpc.sln`
```
super fail Error: No relevant projects found in Solution
    at Object.sln.updateArgs (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\src\lib\sln\index.js:26:11)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:118:9
    at step (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:33:23)
    at Object.next (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:14:53)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:4:12)
    at main (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:154:12)
    at Object.<anonymous> (C:\Users\Alexander\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:143:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
```

Case 2:
`snyk test --file=src\Anemonis.JsonRpc\Anemonis.JsonRpc.csproj`
```
Error: Could not detect package manager for file: src\Anemonis.JsonRpc\Anemonis.JsonRpc.csproj
```

Case 3:
`snyk test --file=obj\Anemonis.JsonRpc\project.assets.json`
```
.csproj file not found in D:\Workspace\json-rpc\obj. Make sure project was built before running `snyk test`
```

**Comment by lili2311** [comment]
Thank you  for through examples, will take a look at what we can do about these 😇

Where could I see the content of the sln file? If it is a private repo could you send it over to support@snyk.io?

**Comment by alexanderkozlenko** [comment]
@lili2311, thank you! This is a public repository: https://github.com/alexanderkozlenko/json-rpc
