### ISSUE TITLE
snyk wizard hangs on node 10.x

### ISSUE THREAD

**Issue by tasadar2** [snyk/snyk#304]
- `node -v`: `v10.14.1`
- `npm -v`: `6.4.1`
- `snyk -v`: `1.116.4`
- Command run: `snyk wizard`

### Expected behaviour
Complete the wizard command after responding to prompts.

### Actual behaviour
The cli hangs indefinitely after responding to certain prompts.

### Steps to reproduce
The scenario I have been testing is:
1. create a `.snyk` file
1. run `snyk wizard`
1. answer `yes` or `no` to `Do you want to revisit your existing policy [y] or only update it [N]?`
1. the cli hangs

Another scenario:
1. ensure no snyk file exists
1. install a package with a known vulnerability, ex. `shelljs@0.8.3`
1. ignore vulnerability for 30 days
1. enter a reason, or don't
1. the cli hangs after resolving all vulnerabilities

### Troubleshooting

This seems to function correctly with node 8.x, but fails with node 10.x. I do not have a large pool of machines to confirm this, but this has been consistent so far.

When debugging, i see the code run through [https://github.com/snyk/snyk/blob/master/src/cli/commands/protect/wizard.js#L121](https://github.com/snyk/snyk/blob/master/src/cli/commands/protect/wizard.js#L121), but it acts like the promise is never resolved.

---

`snyk wizard --debug`
```
  snyk wizard { _: [ [Circular] ], debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder C:\Projects\my-project +0ms
  snyk found package file package-lock.json in C:\Projects\my-project +1ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk sending request to: https://snyk.io/api/v1/verify/token +0ms
  snyk request body size: 46 +1ms
  snyk gzipped request body size: 64 +1ms
  snyk analytics add payloadSize 46 +0ms
  snyk analytics add gzippedPayloadSize 64 +0ms
  snyk not using proxy +1ms
  snyk analytics add inline-auth false +618ms
  snyk not using proxy +618ms

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

? Do you want to revisit your existing policy [y] or only update it [N]? Yes
  snyk analytics add start-over true +3s
```

**Comment by michael-go** [comment]
Hi @tasadar2, thanks for reporting! Did this happen to you also on Mac/Linux or only on Windows?

**Comment by tasadar2** [comment]
@michael-go Windows 10

**Comment by exactlyaron** [comment]
Hello snyk team,

Noticed the same behaviour as well when running locally.

- Windows 10
- node -v 10.14.2
- npm -v 6.5.0
- snyk -v 1.121.0


 

> Querying vulnerabilities database...
> Tested 77 dependencies for known vulnerabilities, found 2 vulnerabilities, 2 vulnerable paths.
>   snyk starting questions +4s
>   snyk getUpdatePrompts +0ms
> 
>   snyk final show SNYK-JS-MPATH-72672 when true +12ms
> ? ✗ High severity vuln found in mpath@0.5.0, introduced via mpath@0.5.0
>     Description: Prototype Pollution
>     Info: https://snyk.io/vuln/SNYK-JS-MPATH-72672
> 
>   Remediation options Skip
> 
>   snyk final show SNYK-JS-SERVEHANDLER-72615 when true +2s
> ? ✗ Medium severity vuln found in serve-handler@5.0.2, introduced via serve-handler@5.0.2
>     Description: Cross-site Scripting (XSS)
>     Info: https://snyk.io/vuln/SNYK-JS-SERVEHANDLER-72615
> 
>   Remediation options Skip
>   snyk getPatchPrompts +2s
>   snyk getIgnorePrompts +0ms



cli hangs there after the final remediation step.

**Comment by joshje** [comment]
Hey, thanks for the multiple reports. We're struggling to reproduce this issue, even on Windows 10. Can you provide us with any more details about the OS (and anything else you think may be relevant). 

My initial hunch is that this is somehow related to file system permissions, so if there's anything non-default about this please let us know.

**Comment by tasadar2** [comment]
I'm running mine in an enterprise environment, so many directories require elevated permissions. But the executing user has full access to the project directory snyk is running from, as well as all child directories.
I did attempt this with an elevated user on the same machine, but with the same results, so I can't blame directory permissions unless snyk is attempting to access something outside of the project or common node directories.

As a company, we have seen this occur on multiple windows machines, and the only commonality that we have seen so far is node 10 vs node < 10. I can see about standing up some VMs to attempt different configurations and narrow the scope.

**Comment by tasadar2** [comment]
I just ran into this on my home machine as well running a simple test. This is running from a user with full admin rights.

#### Versions
- `winver`: `Windows 10 Version 1803 (OS Build 17134.472)`
- `node -v`: `v10.13.0`
- `npm -v`: `6.4.1`
- `npx snyk -v`: `1.121.1`

#### Steps to reproduce
1. Start with an empty directory
1. Run `npm init`
1. Run `npm install shelljs`
1. Run `npm install snyk`
1. Run `npx snyk wizard`
    1. Select `Set to ignore for 30 days (updates policy)`
    1. Click **Enter** for `None given`
    1. Process hangs

**Comment by darmalovan** [comment]
Hey,
We investigate the issue and we were able to reproduce it on windows (using the command prompt, and not bash).
Seems that the issue is happening due to the `inquirer` package, which handles the prompts on the CLI.
To fix it we need to upgrade `inquirer` to a newer version (> 5), which only works from node 6.
We are in the process of removing support for node 4 - once it will happen we could upgrade `inquirer`.

**Comment by vishnuroshan** [comment]
is this issue resolved. I am getting the same error

**Comment by adrukh** [comment]
@vishnuroshan @tasadar2 we just released [1.145.0](https://github.com/snyk/snyk/releases/tag/v1.145.0) with an upgraded `inquirer` dependency. Please give it a try and update here 🙏

**Comment by exactlyaron** [comment]
Working for me @adrukh  👍

**Comment by joseantonio19** [comment]
I had the same problem and now it's working fine. ;)

**Comment by darmalovan** [comment]
Closing the ticket as it seems to be working on the newer version of the Snyk CLI.
