### ISSUE TITLE
Typo in vuln email

### ISSUE THREAD

**Issue by Awk34** [Snyk/snyk#33]
I received an email titled "Vulnerability alert for the awk34 organisation" today.

organisation -> organization

Apologies in advance if this isn't the right place to post this error. I know that this repo is for the CLI, but I didn't see a more relevant place to post this.

**Comment by guypod** [comment]
Thanks for opening the issue! In the future, you can email support@snyk.io

That said, this is actually intentional, as we're using British spelling. A constant topic of conversation, but as we're based in London, we figured we'll give it a go :)
