### ISSUE TITLE
Snyk hangs, add verbose mode (SBT)

### ISSUE THREAD

**Issue by mlushpenko** [snyk/snyk#331]
- `snyk -v`: 1.108.3
- Command run: snyk test

Please add documentation about `--debug` to cli, I only found it here, nowhere on the website or in cli, let me know if I was blind and couldn't see it :) 

### Expected behaviour
Test succeeds or fails.

### Actual behaviour
In some cases command hangs. When expecting what was happening, I could see `sbt dependencyTree` command. Snyk would just hang indefinitely or until timeout was reached in gitlab, but if I ran that command separately, I could see that there was a problem with one of sbt dependencies and sbt was waiting for input: to retry download or cancel.

`snyk test` command didn't show anything, it would be good to add more output about what is happening. I've spent almost two days testing different versions of sbt and snyk only to figure out problem was with dependency.

Small addition, on my local machine everything was going fine, but running from docker was resulting in dependency error. Don't think it is relevant in this case, but sharing just in case. Main point - please add more output to `snyk test` and document `--debug` option

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by mlushpenko** [comment]
To avoid such problems in the future, I am now running the following:

```
sbt dependencyTree
snyk test
```

which will tell me about dependency problems, but I would expect such output from snyk if it hides this  in the background

**Comment by lili2311** [comment]
👋 Please could I verify that the latest version of CLI is also not showing enough information?

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.

**Comment by mlushpenko** [comment]
Sorry, @lili2311,  I was using it at previous work
