### ISSUE TITLE
`docker-entrypoint.sh` puts errors into HTML output if `--json` is not in parameters to snyk

### ISSUE THREAD

**Issue by lfdebrux** [snyk/snyk#332]
- `docker images snyk/snyk-cli`:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
snyk/snyk-cli       npm                 a695054107d0        4 days ago          195MB
```
- Command run:
`docker run -e SNYK_TOKEN=$SNYK_TOKEN -v $(pwd):/project snyk/snyk-cli:npm`

### Expected behaviour

There is a report in the `snyk_report.html` file

### Actual behaviour

The `snyk_report.html` file contains a single line reading `Error: Invalid input JSON format, aborting process.`

### Steps to reproduce

Run the above command in any npm project. I think you will also get the same result with the other Docker images.

**Comment by lfdebrux** [comment]
I think the issue is these two lines

https://github.com/snyk/snyk/blob/master/docker/docker-entrypoint.sh#L85-L86

The rest of the script expects JSON output, but `--json` isn't added to the command line. By comparison, the monitor command at [L106](https://github.com/snyk/snyk/blob/master/docker/docker-entrypoint.sh#L106) does include the `--json` flag

**Comment by darmalovan** [comment]
You are correct, there's a shortcoming in the current implementation that will need to address in more depth.
some context here:
https://github.com/snyk/snyk/pull/164#issuecomment-405617499

In the meanwhile you can overcome this issue by running:
`docker run -e SNYK_TOKEN=$SNYK_TOKEN -v $(pwd):/project snyk/snyk-cli:npm test --json`

**Comment by lili2311** [comment]
👋 @lfdebrux we have released a fix, the images are in the process of re-building but please grab a new one shortly and try again :)

**Comment by lfdebrux** [comment]
Works now! Thanks so much!
