### ISSUE TITLE
Unable to install `snyk` package with npm

### ISSUE THREAD

**Issue by Soul-Master** [snyk/snyk#348]
![image](https://user-images.githubusercontent.com/442046/51818921-1377c080-2303-11e9-8a03-141d933f10f7.png)

`@snyk/gemfile` package was renamed to `gemfile`.
![image](https://user-images.githubusercontent.com/442046/51818956-386c3380-2303-11e9-9568-64a6e6862ad8.png)

**Comment by adrukh** [comment]
@Soul-Master I believe this is a typo in the readme of this repo. Our CLI depends on `@snyk/gemfile` which is a public package, and should not respond with a 404 when installed.

Can you provide more details regarding your env? Which version on `npm`, which OS? Do you have any proxy for `npmjs` or similar?

**Comment by adrukh** [comment]
Correction - this is not a typo :) We are using https://github.com/treycordova/gemfile with some additions of our own. We publish our fork as `@snyk/gemfile`, but have not updated the readme file.

**Comment by Soul-Master** [comment]
I'm sorry. It seems to be an issue of npm about local npmrc & global npm config for private registry.

**Comment by adrukh** [comment]
No harm done! :)

Thanks for pointing this out, closing.
