### ISSUE TITLE
DX issue - missing node_modules

### ISSUE THREAD

**Issue by abtris** [Snyk/snyk#35]
- `node -v`: 0.10.46
- `npm -v`: 2.15.1
- `snyk -v`: 1.17.1
- Command run:

$ snyk test
✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

### Expected behaviour

✓ Missing node_modules folder we can't testing without deps. Please run npm install first.

### Actual behaviour

✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.

### Steps to reproduce

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by guypod** [comment]
@abtris thanks for the report, we'll add the message. 
We used to have a custom message for these cases, but seem to have lost it over time, will put it back in.

**Comment by remy** [comment]
This has been fixed and released in the latest version of the CLI. Thanks.
