### ISSUE TITLE
Add logout command

### ISSUE THREAD

**Issue by omerlh** [snyk/snyk#351]
How can I log out from the CLI after it's authenticated? I want to test functionality when the CLI is not logged-on.
After digging in the code (and reading [Configstore documentation](https://www.npmjs.com/package/configstore)), I was able to do that by cleaning Snyk's config:
```
rm -rf  ~/.config/configstore/snyk.json 
```

**Comment by adrukh** [comment]
That's one way for sure!

Another is to run `snyk config unset api`, which removes the `api` key from the configstore file you mentioned above.

**Comment by omerlh** [comment]
Maybe worth adding something more explicit? `snyk unauth`?

**Comment by adrukh** [comment]
This makes sense!

**Comment by robcresswell** [comment]
`snyk config clear` will remove all of your config too, if you're looking for something like that.
