### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by JeanPerriault** [Snyk/snyk#36]
- `node -v`: 6.2.2
- `npm -v`: 3.10.3
- `snyk -v`: 1.17.1
- Command run: 
* set proxy
* first `snyk test`, following instructions at the end of https://snyk.io/test/ (Test a local project)
* Then `snyk wizard` after a look at https://snyk.io/docs/quick-start/

### Expected behaviour
snyk wizard to be run
snyk test to be run for a local repo, or for a public github project

### Actual behaviour
error message: connect ETIMEDOUT xxx.xxx.xxx.xxx:443, with different IP at each try

### Steps to reproduce
set proxy
run `snyk wizard` or `snyk test` or `snyk test https://github.com/xxx/xxx` being connected to github

**Comment by adrukh** [comment]
@JeanPerriault thanks for reporting this.

Can you elaborate on your network settings, what kind of proxy are you setting, and which IP addresses do you see when failing? Also, run `time snyk test -d` to show the duration of the execution until timeout with more verbose output.

**Comment by JeanPerriault** [comment]
@adrukh 
Regarding network settings: the proxy is the internet proxy of my company, and regarding IP addresses, I can't share them because I don't know if they are internal IPs.. what I can say is that it changes each time I try to run a command, with the same connect ETIMEDOUT 'prefix'

Here is the debug trace:
* For `time snyk test -d`
```
Mon, 18 Jul 2016 14:12:10 GMT snyk test { _: [ [Circular] ], debug: true }
Mon, 18 Jul 2016 14:13:17 GMT snyk checking for cli updates
Mon, 18 Jul 2016 14:13:19 GMT snyk add local true
Mon, 18 Jul 2016 14:13:47 GMT snyk policies found [ 'C:\\Users\\XXX\\Workspace\\private_project' ]
Mon, 18 Jul 2016 14:13:47 GMT snyk add policies 1
Mon, 18 Jul 2016 14:13:47 GMT snyk add packageName private_project
Mon, 18 Jul 2016 14:13:47 GMT snyk add packageVersion 1.0.0
Mon, 18 Jul 2016 14:13:47 GMT snyk add package private_project@1.0.0
Mon, 18 Jul 2016 14:14:08 GMT snyk add error-message connect ETIMEDOUT XX.X.XXX.XX:443
Mon, 18 Jul 2016 14:14:08 GMT snyk add error Error: connect ETIMEDOUT XX.X.XXX.XX:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Mon, 18 Jul 2016 14:14:08 GMT snyk add error-code ETIMEDOUT
Mon, 18 Jul 2016 14:14:08 GMT snyk add command test
Error: connect ETIMEDOUT XX.X.XXX.XX:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Mon, 18 Jul 2016 14:14:08 GMT snyk { command: 'bad-command', args: [ { debug: true } ], metadata: { local: true, policies: 1, packageName: 'private_project', packageVersion: '1.0.0', package: 'private_project@1.0.0', 'error-message': 'connect ETIMEDOUT XX.X.XXX.XX:443', error: 'Error: connect ETIMEDOUT XX.X.XXX.XX:443\n    at Object.exports._errnoException (util.js:1008:11)\n    at exports._exceptionWithHostPort (util.js:1031:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)', 'error-code': 'ETIMEDOUT', command: 'test' }, version: '1.17.1', os: 'Windows 7', nodeVersion: 'v6.2.2', id: 'cba6ffa90f66efa1d7188e5ad23d70bbdb076508', ci: false }
Mon, 18 Jul 2016 14:14:30 GMT snyk Error: connect ETIMEDOUT YYY.YY.Y.YY:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

real    2m21.949s
user    0m0.015s
sys     0m0.045s
```

**Comment by adrukh** [comment]
I suspect your proxy is whitelisting servers for HTTPS access. Please ask to add snyk.io to that list.

The 2m21s timeout supports this - the default `request` timeout is 2m. It take a few seconds to collect the local dependencies data, and then the client is waiting for 2 min with no response from the server before giving up.

A sure way to rule this as a connectivity issue is to run `curl -I https://snyk.io/api/v1/vuln/npm`
You will get an immediate HTTP 501 if network connectivity is ok (GET is not supported by this API endpoint). In case of a connectivity issue, `curl` will hang until killed.

We are not seeing any connectivity issues in our monitoring, hence my suspicion of your network settings.

**Comment by adrukh** [comment]
Closing for now, please reopen if this is not network related.

**Comment by JeanPerriault** [comment]
Ok, I'm surprised because I can access 'https://snyk.io/' via my browser without any warning, but the curl command ends up with a `curl: (7) Failed to connect to snyk.io port 443: Timed out`.
I'll check with IT, I'm not out of the wood because this is a big company with strong IT constraints, I'll let you know.
Thx for your responsiveness and commitement.
