### ISSUE TITLE
snyk test shows different results on CLI and TravisCI

### ISSUE THREAD

**Issue by KharitonOff** [Snyk/snyk#37]
- `node -v`: v0.10.46
- `npm -v`:  2.15.1
- `snyk -v`: 1.17.1
- Command run:
snyk test
### Expected behaviour
common result in CLI and Travis CI

### Actual behaviour
CLI says: ✓ Tested 583 dependencies for known vulnerabilities, no vulnerable paths found.
![bildschirmfoto 2016-07-19 um 09 44 05](https://cloud.githubusercontent.com/assets/8480657/16948823/28faa25c-4db7-11e6-9853-1cc45c3466da.png)

Travis says: Tested 634 dependencies for known vulnerabilities, found 6 vulnerabilities, 8 vulnerable paths.
![bildschirmfoto 2016-07-19 um 09 43 30](https://cloud.githubusercontent.com/assets/8480657/16948777/e24c4fea-4db6-11e6-9cac-d651770359a2.png)

### Steps to reproduce
Nothing special ...

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

snyk test --debug (on CLI)
  snyk test +0ms { _: [ [Circular] ], debug: true }
  snyk checking for cli updates +463ms
  snyk add +64ms local true
  snyk policies found +2s [ '/Users/user/Developer/cla-assistant',
  '/Users/user/Developer/cla-assistant/node_modules/snyk' ]
  snyk add +2ms policies 2
  snyk add +1ms packageName cla-assistant
  snyk add +0ms packageVersion 1.0.0
  snyk add +0ms package cla-assistant@1.0.0
  snyk add +3s vulns-pre-policy 13e...
  snyk add +82ms vulns 0es database...
✓ Tested 583 dependencies for known vulnerabilities, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
  snyk TypeError: Cannot read property 'indexOf' of undefined
    at /Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/lib/analytics.js:99:41
    at Array.reduce (native)
    at getMAC (/Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/lib/analytics.js:98:41)
    at /Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/lib/analytics.js:51:15
    at lib$es6$promise$$internal$$tryCatch (/Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:374:17)
    at /Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:166:11
    at lib$es6$promise$asap$$flush (/Users/user/.nvm/versions/node/v5.7.0/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:119:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11) +3ms

**Comment by adrukh** [comment]
@ KharitonOff

I suspect a difference in the `node_modules` folders between what you have locally, and what exists in your travis run. `snyk test` collects the metadata of all locally installed modules and then compares them with our vulnerabilities database. A difference in results means a difference in input.

Please run `npm install` locally in your project folder, and repeat `snyk test`. I suspect that your local modules are out of date, whereas travis runs `npm install` and gets a fresh set.

A good way to find differences between two sets of dependencies for the same project is to run `npm ls --json` in both locations and then compare the outputs. Doing so with travis is not effortless, but can shed more light on the difference.

Anton

**Comment by KharitonOff** [comment]
@adrukh 
I've run `npm install` and I also deleted my old npm_modules folder and run `npm install` again. Nothing changed on the result of `snyk test ` on CLI. 
I also grabbed the JSONs from CLI and Travis, yes they are on many places different... but how can I fix the travis version?

**Comment by guypod** [comment]
@KharitonOff another possibility is that your globally installed version is running when you run it locally, while your package.json file holds an older version of it. 

Can you please check what's the Snyk version stated in your package.json file, and if it's older update it to be `snyk@^1.17.1`?

**Comment by KharitonOff** [comment]
@guypod ok, I tried it too: I had v1.17.0 in my package.json, so I changed it to 1.17.1, removed my node_modules, reinstalled them, pushed all changes to Travis...
snyk test results are still different: CLI passes, Travis fails

**Comment by guypod** [comment]
@KharitonOff I just noticed, in the CI screenshot, that you're using Node 0.10. 
I'm not sure we still support that version, looking into it now. 

If it's easy, would be great if you could try to reproduce it locally with Node 0.10, or see if you have another CI build that uses a newer version.

**Comment by adrukh** [comment]
@KharitonOff another idea - are you working on the same tag/branch locally as the travis build? I see `v1.1` in travis.

**Comment by KharitonOff** [comment]
@guypod Thanks! That was the point! But this worked so far well for me until snyk updated to v1.17.1 ...
Anyway thank you guys ( @guypod , @adrukh ) for watching in this issue and helping me!
