### ISSUE TITLE
Snyk should not fail on PR's that do not modify package.json

### ISSUE THREAD

**Issue by BerkeleyTrue** [Snyk/snyk#38]
Snyk Github Integration

### Expected behaviour

Should pass on PR's that do not change to package.json
Should run on PR's that do change package.json

### Actual behaviour

Fails PR's without changes to package.json

### Steps to reproduce

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10251
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10200

These two PR's made no changes to the package file, yet Snyk integration reports them as failing. 

In the case of the second one I can verify that the .snyk file is up to date.

According to the docs, the github integration should only run when package.json has changed
![github_integration](https://cloud.githubusercontent.com/assets/6775919/17783435/e46cd6e0-652c-11e6-974a-18576440ec5b.png)

**Comment by johannakoll** [comment]
Thanks for raising this - we are working on sorting this out right now! I'll keep you posted on our progress, aiming to have an improvement out next week.

**Comment by BerkeleyTrue** [comment]
@johannakoll Thanks.

I've disabled Snyk on our project as it was marking every PR as failing. Please let me know as soon as this issue is address.

**Comment by joshje** [comment]
@BerkeleyTrue We're nearly ready to release project settings that will allow you to set PRs to fail only when the PR introduces a vulnerability. Would you like early access to this? We can set you up and would be grateful for feedback. We can enable it on your account, and drop you a line once it's done if you're up for it.

**Comment by BerkeleyTrue** [comment]
Yes I would like that.

**Comment by johannakoll** [comment]
@BerkeleyTrue following up on Josh's message, I've enabled this functionality for you, and also emailed you with some details about how to try it.

**Comment by BerkeleyTrue** [comment]
@johannakoll I'm unable to find a way to re-enable snyk webhook. Is there somewhere in the UI to do this?

**Comment by johannakoll** [comment]
@BerkeleyTrue you should be prompted to give us permissions again when you go to https://snyk.io/add

**Comment by BerkeleyTrue** [comment]
No such luck

**Comment by johannakoll** [comment]
@BerkeleyTrue the other way is to go to the project's settings on snyk.io - if you deactivated watching the repo with GitHub there, you'll see a button labelled "Activate project".

**Comment by BerkeleyTrue** [comment]
No luck again.

No prompt to re-auth.

No webhook added

**Comment by johannakoll** [comment]
@BerkeleyTrue could you report this to support@snyk.io, please? I'll get it looked at in more detail.

**Comment by BerkeleyTrue** [comment]
Done

**Comment by BerkeleyTrue** [comment]
Fixed. Looks like the new settings close this issue. 

Thanks for the help.

Happy Coding.

**Comment by BerkeleyTrue** [comment]
Seems to be working great! 

Thanks for the fix. I really appreciate the hard work you are all doing here. 

Happy Coding!
