### ISSUE TITLE
META: On the frequency of releases

### ISSUE THREAD

**Issue by NicolasCARPi** [snyk/snyk#392]
Hello snyk team,

First I'd like to say that the service you provide is really great and the blog is enjoyable too so thumbs up! :+1: 

I just have a little question: why do you make a new release for nearly every single commit?

You see, I use [Dependabot](https://dependabot.com/) to notify me of a new version of dependencies in my composer.json or package.json, and for snyk it results in nearly 10 PR every month, with sometimes as much as 4 PR in 2 days:

[![2019-03-15-133703_527x547_scrot](https://user-images.githubusercontent.com/3043706/54431731-78f30580-4727-11e9-8878-abd1c9b708e9.png)](https://github.com/elabftw/elabftw/pulls?utf8=%E2%9C%93&q=is%3Apr+snyk)
https://github.com/elabftw/elabftw/pulls?utf8=%E2%9C%93&q=is%3Apr+snyk

I would like to know:

* why did you adopt this model of releasing VERY often? Is it really needed?
* is it feasible to consider maybe releasing less often?

Thanks!

~Nico

**Comment by adrukh** [comment]
Hi @NicolasCARPi !

Thanks for raising this topic! I'd like to briefly explain our philosophy here and open it up for debate.

[Here's a post](https://snyk.io/blog/engineering-and-basketball/) I wrote some 2.5 years ago about what kind of an engineering org we are building. Summing it up, we strive to have the minimal distance possible between an idea we have that adds value to our offering, and this idea being implemented and experienced by all our users. We believe that velocity and quality are achieved both with fast iterations and tight feedback loops.

You are experiencing one specific symptom of this approach, which is noisy upgrade suggestions. I really like [Dependabot](https://dependabot.com/) and think they are doing a great job! However, their premise seems to be rooted in the average slow release rate of OSS packages a project may depend on. When famous and large projects such as [Express](https://expressjs.com/) make just a handful of releases a year, there is a need for a service to basically subscribe to a 'virtual RSS feed' of these releases, turning them into actionable PRs that introduce the upgrades to your project. I believe the future will bring much faster velocity and rate of releases, and I'm sure the fine folks at Dependabot will find a way to adjust their offering to meet this future.

Another advance that contributes to the situation and is still maturing is the use of lockfiles. Prior to lockfiles, using `"express": "^4"` would be a great way to subscribe to newer releases without much hassle, as long as you re-deploy your app regularly to pick them up. I'm expecting some advance in the way lockfiles are used to perhaps allow some flexibility at the expense of the much needed determinism they were originally set to solve. Exciting challenges for everyone involved.

Coming back to the original point, I urge you to subscribe to our view of quick iterations and fast value delivery to our users, empowering the team internally to deliver their best. I admin we won't be slowing down our release rate anytime soon :)

**Comment by NicolasCARPi** [comment]
Hello @adrukh,

The analogy with football/basketball is on point! :)

I understand better now your workflow and the reasons for releasing very often. In fact, it is something I find very positive, and for my project I'm aiming to release as often as possible, but I must first have much more automated testing…

Cheers,
~Nico
