### ISSUE TITLE
Maven module without dependencies is reported as having dependencies

### ISSUE THREAD

**Issue by pkubowicz** [snyk/snyk#396]
- `node -v`: v8.15.1
- `npm -v`: 6.4.1
- `snyk -v`: 1.136.3
- Command run: snyk monitor --org=my-organisation

### Expected behaviour
Snyk assigns the vulnerability report to the root project.

### Actual behaviour
My Maven project structure is:
```
snyk-multi
├── foo-utils
├── reports
└── super-parent
```
but the report at app.snyk.io shows dependencies as:
```
reports
├── foo-utils
├── snyk-multi
└── super-parent
```
and shows the project as `com.example:reports@1.0-SNAPSHOT` which is very confusing, as 'report' project does not define any dependencies.

### Steps to reproduce
Run snyk on https://github.com/pkubowicz/snyk-multi

Logs:
```
  snyk monitor { _: [ [Circular] ], org: 'my-organisation', debug: true } +0ms
  snyk no file specified. Trying to autodetect in base folder /home/piotr-kubowicz/tmp/bugs/snyk-multi +0ms
  snyk found package file pom.xml in /home/piotr-kubowicz/tmp/bugs/snyk-multi +1ms
  snyk found package file pom.xml in /home/piotr-kubowicz/tmp/bugs/snyk-multi +0ms
  snyk analytics add packageManager maven +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/maven +0ms
  snyk request body size: 5981 +0ms
  snyk gzipped request body size: 1108 +0ms
  snyk analytics add payloadSize 5981 +4ms
  snyk analytics add gzippedPayloadSize 1108 +0ms
  snyk not using proxy +1ms
```

**Comment by RyanHavoc** [comment]
@pkubowicz I've reproduced your issue and we're looking into it further. In the meantime, you can delete the project from your org on app.snyk.io and import it through the web interface and you will see the behavior you're expecting. I'll let you know when we've got to the bottom of this.

**Comment by RyanHavoc** [comment]
@pkubowicz OK. So at the moment, our CLI will only monitor the manifest (e.g. `pom.xml`) that you specifically so in this case the `pom.xml` in your root. But we do detect relationships which is why you're seeing this:
```
reports
├── foo-utils
├── snyk-multi
└── super-parent
```
From the CLI you'll need to monitor each manifest individually e.g:
```
snyk monitor --org=my-organisation --file=foo-utils/pom.xml
snyk monitor --org=my-organisation --file=super-parent/pom.xml
snyk monitor --org=my-organisation --file=reports/pom.xml
```
We are working on improving our support for Maven multi-modules through the CLI. I hope this helps.
