### ISSUE TITLE
Snyk 1.138.0 can't find package when testing yarn.lock file

### ISSUE THREAD

**Issue by balderdash** [snyk/snyk#399]
I'm running into an error running snyk against my `yarn.lock` file after upgrading to 1.138.0. It works just fine with 1.137.0.

- `node -v`: v11.5.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.138.0
- Command run: 
`snyk test --file=yarn.lock`

### Expected behaviour
Running snyk in the repo below should produce the output:
`✓ Tested 1 dependencies for known vulnerabilities, no vulnerable paths found.`

### Actual behaviour
Instead, it says:
`The package could not be found or does not exist`

### Steps to reproduce
Install snyk 1.138.0 or above, then:
```
git clone -b add-yarn-lock git@github.com:balderdash/react-native-get-random-values.git test
cd test
snyk test --file=yarn.lock
```

Output from running `snyk test --file=yarn.lock --debug`:
https://gist.github.com/balderdash/32f359a0a39f1211e496d90ea4275c07

**Comment by adrukh** [comment]
👋 thanks for flagging this, the issue is acknowledged and we're working on a fix. I'll update within the hour.

**Comment by adrukh** [comment]
Root cause identified, fix is on it's way to production, next update in 20 min

**Comment by adrukh** [comment]
The fix is now in production, apologies for this interruption (lasted <7h) and thanks for letting us know!

**Comment by adrukh** [comment]
No need to update the CLI, the fix is on our backend.

**Comment by balderdash** [comment]
It's working for me, thanks for the quick fix!
