### ISSUE TITLE
Different results between Node 4.2.2 and 5.0.0 (npm 2.14.7 vs npm 3.3.6)

### ISSUE THREAD

**Issue by ghengeveld** [Snyk/snyk#4]
When running Snyk against my project with Node 5.0.0 and npm 3.3.6, a vulnerability is reported:

```
✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > uglify-js@2.4.24
Upgrade direct dependency uglify-js@2.4.24 to uglify-js@2.5.0
Tested 890 dependencies for known vulnerabilities, found 1 vulnerability.
```

However, when I run it agains Node 4.2.2 with npm 2.14.7, all is fine.

Also, uglify-js is incorrectly reported as being a direct dependency and can be upgraded. I don't have this dependency in my package.json (directly). This must be caused by the new 'flat' structure of node_modules with npm 3, which causes uglify-js to be installed at the root of node_modules.

I'm using Node Version Manager.

**Comment by guypod** [comment]
Thanks for the note, we indeed haven't done enough testing on npm@3, and don't properly track the paths back (hence mistakenly marking it as direct). 

It's possible that this module is pulled in through a devDependency, as by default we don't show issues in devDependencies. Can you try running `snyk test --devDeps=1` and see if the vulnerability does show up? 

If it still doesn't show, can you please either paste here or email us at support@snyk.io your package.json file and/or the output of running `npm ls` on the project? Alternatively, if the project is a public one you can just point us to it.

**Comment by ghengeveld** [comment]
I wasn't aware that devDeps aren't tested by default (makes sense though), I think the documentation is lacking here. Indeed it turns out there's a difference when using --dev.

With node 4 / npm 2:
```
⮀ snyk test
✓ Tested 53 dependencies for known vulnerabilities, no vulnerabilities found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

⮀ snyk test --dev
✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > html-webpack-plugin@1.6.2 > html-minifier@0.7.2 > uglify-js@2.4.24
No direct dependency upgrade can address this issue.
Run `snyk protect -i` to patch this vulnerability
Alternatively, manually upgrade deep dependency html-minifier@0.7.2 to html-minifier@1.0.0 (triggers upgrades to uglify-js@2.5.0)

✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > eslint@1.9.0 > handlebars@4.0.4 > uglify-js@2.4.24
No direct dependency upgrade can address this issue.
Run `snyk protect -i` to patch this vulnerability
Alternatively, manually upgrade deep dependency uglify-js@2.4.24 to uglify-js@2.5.0

Tested 1680 dependencies for known vulnerabilities, found 2 vulnerabilities.
```

With node 5 / npm 3:
```
⮀ snyk test
✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > uglify-js@2.4.24
Upgrade direct dependency uglify-js@2.4.24 to uglify-js@2.5.0

Tested 893 dependencies for known vulnerabilities, found 1 vulnerability.

⮀ snyk test --dev
✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > uglify-js@2.4.24
Upgrade direct dependency uglify-js@2.4.24 to uglify-js@2.5.0

✗ Vulnerability found on uglify-js@2.4.24
Info: https://app.snyk.io/vuln/npm:uglify-js:20151024
From: blaze-hub-skeleton-site@1.0.0 > html-webpack-plugin@1.6.2 > html-minifier@^0.7.2 > uglify-js@2.4.x
No direct dependency upgrade can address this issue.
Run `snyk protect -i` to patch this vulnerability
Alternatively, manually upgrade deep dependency html-minifier@^0.7.2 to html-minifier@1.0.0 (triggers upgrades to uglify-js@2.5.0)

Tested 1026 dependencies for known vulnerabilities, found 2 vulnerabilities.
```

Here's my dependencies:
```
  "dependencies": {
    "babel-runtime": "^5.8.20",
    "blaze-lib-hub-components": "^1.1.1",
    "dotenv": "^1.2.0",
    "keymirror": "^0.1.1",
    "react": "^0.14.2",
    "react-dom": "^0.14.2",
    "react-redux": "^4.0.0",
    "redux": "^3.0.4",
    "redux-actions": "^0.8.0",
    "redux-thunk": "^1.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "babel-core": "^5.8.33",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^5.3.3",
    "babel-plugin-react-transform": "^1.1.1",
    "chai": "^3.4.0",
    "chai-as-promised": "^5.1.0",
    "clean-webpack-plugin": "^0.1.4",
    "css-loader": "^0.21.0",
    "eslint": "^1.8.0",
    "eslint-config-airbnb": "^0.1.0",
    "eslint-plugin-react": "^3.6.3",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^0.9.0",
    "file-loader": "^0.8.4",
    "html-webpack-plugin": "^1.6.2",
    "jscs": "^2.5.0",
    "jsdom": "^7.0.2",
    "json-loader": "^0.5.3",
    "mocha": "^2.3.3",
    "postcss-loader": "^0.7.0",
    "pre-commit": "^1.1.2",
    "precss": "^1.3.0",
    "proxyquire": "^1.7.3",
    "react-a11y": "^0.2.8",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "react-unit": "^1.0.10",
    "redbox-react": "^1.1.1",
    "selenium-standalone": "^4.7.1",
    "sinon": "^1.17.2",
    "snyk": "^1.1.1",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.6",
    "webdriverio": "^3.2.6",
    "webpack": "^1.12.2",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.4.1"
  }
```

It's a private project and we're using Artifactory as an npm proxy and to serve private libraries (blaze-lib-hub-components in this case), but that shouldn't matter.
I'm assuming npm 3 support is fairly high up on your backlog, considering it's only a matter of time before the majority is using it, so I'll just wait for you guys to fix it. Good work so far.

**Comment by boxfoot** [comment]
Snyk looks awesome!

But I'm also finding snyk unusable with NPM@3, different packages but more or less the same scenario described above.  Looking forward to seeing this support eventually added.

**Comment by Eruant** [comment]
Same issue on node v4.2.4 with npm v3.5.4.

**Comment by remy** [comment]
Just to check in to let everyone know, I'm currently working on the npm@3 support. It's going well and hoping to have a new version of snyk out soon enough with complete coverage for npm@3.

Stay tuned!

**Comment by remy** [comment]
I've pushed a development build to npm that you can try out which, I believe should resolve the problem you were seeing. Again, this a dev build, so you should watch out for when we push the stable build too (expected 1.9.0).

If you run `npm install -g snyk@dev` you'll get snyk@1.9.0-alpha3. If you could try that out on your project and let me know how you all get on.

Thanks so much.

**Comment by boxfoot** [comment]
Thanks! Worked for me :smile:

**Comment by IanVS** [comment]
Hmm, I got the following when I attempted to install the latest alpha:

```
> snyk@1.9.0-alpha3 postinstall .nvm/versions/node/v5.3.0/lib/node_modules/snyk
> npm run snyk-protect


> snyk@1.9.0-alpha3 snyk-protect .nvm/versions/node/v5.3.0/lib/node_modules/snyk
> node cli/index.js protect

invalid package name: url, errors: url is a core module name

npm ERR! Darwin 15.2.0
npm ERR! argv ".nvm/versions/node/v5.3.0/bin/node" ".nvm/versions/node/v5.3.0/bin/npm" "run" "snyk-protect"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! snyk@1.9.0-alpha3 snyk-protect: `node cli/index.js protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snyk@1.9.0-alpha3 snyk-protect script 'node cli/index.js protect'.
.
.
.
```

**Comment by remy** [comment]
@IanVS thanks for the report. I know what this is and fix it up for the next dev release.

**Comment by remy** [comment]
@IanVS I've pushed a fix to the package that was causing that error. You will need to re-install snyk@dev to get the updated dependency, but it should succeed now. 

Let me know how you get on.

Cheers again for the report.
