### ISSUE TITLE
Connection Timeout on Snyk Monitor

### ISSUE THREAD

**Issue by DavidMay121** [snyk/snyk#403]
- `node -v`: 8.11.2
- `npm -v`: 5.6.0
- `snyk -v`: 1.143.0
- Command run: snyk monitor --debug --org=<redacted>

### Expected behaviour
snyk receives snapshot and the dashboard updates. 

### Actual behaviour
Connection Timeout errors on CLI. This was working as of yesterday with version 1.83.0 of Snyk and a larger node_modules directory, so not sure what is going on.

### Steps to reproduce
node_modules/ is 335MB and the payload size is ~87MB. Run snyk monitor or node --max_old_space_size=8192 $(which snyk) monitor

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

snyk monitor { _: [ [Circular] ], debug: true, org: '' } +0ms
  snyk no file specified. Trying to autodetect in base folder /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui +0ms
  snyk found package file package-lock.json in /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui +1ms
  snyk found package file package-lock.json in /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui +0ms
  snyk analytics add packageManager npm +0ms
  snyk sending request to: https://snyk.io/api/v1/monitor/npm +0ms
  snyk request body size: 87646053 +0ms
  snyk gzipped request body size: 2091142 +0ms
  snyk analytics add payloadSize 87646053 +2s
  snyk analytics add gzippedPayloadSize 2091142 +0ms
  snyk not using proxy +1ms
  snyk analytics add error-message 
Monitoring /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui...

Connection Timeout +5m
  snyk analytics add error Error: 
Monitoring /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui...

Connection Timeout
    at /var/lib/jenkins/.nvm/versions/node/v8.11.2/lib/node_modules/snyk/src/cli/commands/monitor.js:172:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
  snyk analytics add error-code undefined +0ms
  snyk analytics add command monitor +0ms
Error: 
Monitoring /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui...

Connection Timeout
    at /var/lib/jenkins/.nvm/versions/node/v8.11.2/lib/node_modules/snyk/src/cli/commands/monitor.js:172:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { args: [ { debug: true, org: '' } ],
  command: 'bad-command',
  metadata: 
   { packageManager: 'npm',
     payloadSize: 87646053,
     gzippedPayloadSize: 2091142,
     'error-message': '\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mMonitoring /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\u001b[1m\u001b[31mConnection Timeout\u001b[39m\u001b[22m',
     error: 'Error: \u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37mMonitoring /var/lib/jenkins/workspace/<redacted>/docker/nginx/ui...\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\n\u001b[1m\u001b[37m\u001b[39m\u001b[22m\u001b[1m\u001b[31mConnection Timeout\u001b[39m\u001b[22m\n    at /var/lib/jenkins/.nvm/versions/node/v8.11.2/lib/node_modules/snyk/src/cli/commands/monitor.js:172:17\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': undefined,
     command: 'monitor' },
  version: '1.143.0',
  os: 'Linux 3.10',
  nodeVersion: 'v8.11.2',
  id: 'aebb75909350809e540f76dc924499d2bbe58dee',
  ci: false,
  durationMs: 303130 } +2ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +5m
  snyk request body size: 1132 +0ms
  snyk gzipped request body size: 479 +0ms
  snyk not using proxy +0ms

**Comment by lili2311** [comment]
👋 We have made some improvements to our compression, please could you try upgrading to latest version of CLI and confirm if the issue persists?

We have some ongoing improvement at the moment to handle large payloads better, it would really help if you could share with us the `package.json` & `package-lock.json` for testing purpose while working on these improvements. If they are sensitive please email them to support@snyk.io

**Comment by lili2311** [comment]
👋 @DavidMay121 We have made further changes you can test out this flag if the project size is still an issue https://github.com/snyk/snyk/blob/master/help/help.txt#L55

I will close this for now due to inactivity, please re-open if needed
