### ISSUE TITLE
Snyk PR's should respect new lines at end of file.

### ISSUE THREAD

**Issue by BerkeleyTrue** [Snyk/snyk#41]
### Expected behaviour
Should update snyk version without modifying the rest of package.json file

### Actual behaviour

Removes new line character at the end of the file

### Steps to reproduce

Create a snyk PR using online UI.

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10455/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R168

![_snyk__fix_for_2_vulnerable_dependency_paths_by_snyk-bot_ _pull_request__10455_ _freecodecamp_freecodecamp_](https://cloud.githubusercontent.com/assets/6775919/18226947/48bc27e6-71ca-11e6-84ba-de9313892944.png)

**Comment by BerkeleyTrue** [comment]
Any word on this? Snyk is still removing new lines causing changes to package.json to re-add the new line

**Comment by guypod** [comment]
Sorry for the radio silence - we notice you opened this issue and logged it to be fixed, just haven't gotten around to it yet. 

Will update here once resolved.

**Comment by adrukh** [comment]
@BerkeleyTrue this is now resolved, thanks for your patience :)

![screen shot 2016-09-25 at 13 36 51](https://cloud.githubusercontent.com/assets/1489979/18815157/c5376b6a-8330-11e6-9765-6c53a1c07f54.png)


![screen shot 2016-09-25 at 14 58 55](https://cloud.githubusercontent.com/assets/1489979/18815159/cb0125b8-8330-11e6-8fea-013bc6c4d283.png)

We now keep the original `package.json` whitespace prefix and suffix, if any.

**Comment by BerkeleyTrue** [comment]
Thanks y'all!

**Comment by pksunkara** [comment]
But the tool of `snyk wizard` still has this problem. I am using 1.20.0

**Comment by joshje** [comment]
@pksunkara Thanks for raising this. We will be fixing this issue in an upcoming release. Follow the issue https://github.com/Snyk/snyk/issues/61 to see when it is resolved.
