### ISSUE TITLE
Crash on snyk wizard

### ISSUE THREAD

**Issue by bmiller59** [snyk/snyk#42]
- `node -v`: 4.2.1
- `npm -v`: 2.14.7
- `snyk -v`: 1.19.1
- Command run: snyk wizard
### Expected behaviour

Normal termination of snyk wizard
### Actual behaviour

? Add `snyk protect` as a package.json installation hook to apply chosen patches on in
stall? Yes
Running `npm update`...
Applying patches...
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: ENOENT: no such file or directory, open '/Users/brendanmiller/projects/skch_dsa2/node_modules/jsreport/node_modules/jsreport-core/node_modules/script-manager/node_modules/request/node_modules/hawk/.snyk-npm-hawk-20160119.flag'
    at Error (native)

Also, this has broken my node_modules in ways that seem hard to fix. 
I keep getting "Error: Cannot find module 'nodemon'" even though I have uninstalled and reinstalled nodemon globally, npm cache clean, and rm -rf node_modules and npm install fresh.
### Steps to reproduce

Unknown

**Comment by adrukh** [comment]
When `snyk` patches vulnerable packages, we create a `{vuln_id}.flag` file in the vulnerable package folder. This file indicates the package has been patched, and contains just the timestamp of the action.

Inability to create this file is probably linked to file system issues - maybe your disk is full, or you have a permissions issue in your `node_modules` folder? Your comment regarding `nodemon` seems to support this theory.

Please provide the output of `snyk protect -d` for further analysis.

**Comment by adrukh** [comment]
Closing for now, please reopen if crashes persist.
