### ISSUE TITLE
Snyk test fails wtih error 500

### ISSUE THREAD

**Issue by timelf123** [Snyk/snyk#44]
- `node -v`: 6.6.0
- `npm -v`: 3.10.6
- `snyk -v`: 1.1931
- Command run: 
`snyk test`
### Actual behaviour
```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 500
    at node_modules\snyk\lib\test.js:104:23
    at node_modules\snyk\lib\request.js:64:7
    at lib$es6$promise$$internal$$tryCatch (node_modules\es6-promise\dist\es6-promise.js:362:16)
    at lib$es6$promise$$internal$$invokeCallback (node_modules\es6-promise\dist\es6-promise.js:374:17)
    at lib$es6$promise$$internal$$publish (node_modules\es6-promise\dist\es6-promise.js:345:11)
    at lib$es6$promise$asap$$flush (node_modules\es6-promise\dist\es6-promise.js:119:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```

### Steps to reproduce
Windows if it matters. This error was resolved by re-running snyk-wizard, then snyk test would run again

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@timelf123 thanks for reporting this!

First of all, trying to understand if this was a persistent failure until you ran `snyk wizard`. Can you provide the name of the project as it appears in your `package.json` file so I can look through our logs? Also, a general timeframe of these errors will be helpful.

If this is was not persistent for the same project, it may relate to  some back-end instability we've had for 36 minutes between 11:38am and 12:14pm UTC today. Some clients may have received HTTP 5xx responses during this time. Again, the timeframe of the failure you observed will help me understand if this is related.

**Comment by timelf123** [comment]
I experienced this issue ~10-20 minutes before I posted this issue. The name in the package is shared by other projects "mean"

**Comment by timelf123** [comment]
Seems to be intermittent. I pushed to heroku to test on another env and the initial build failed on the `snyk protect` command with a 503, but I was able to run ` heroku run --app myApp  snyk protect --debug`

my id from the debug is: `c168efccdb0168f67e8cdcedc29b50066f4a3ab3`

**Comment by adrukh** [comment]
This is definitely our back-end acting up. We are monitoring the situation and making improvements as we go. I'll update in a few days.

**Comment by adrukh** [comment]
@timelf123 took longer than planned (for the update), but we've reduced the count of 5xx errors from our services over the past few weeks. Seeing only 0.1% of those now, please let us know if this persists for you.
