### ISSUE TITLE
Patch against uglify-js failed on Windows 10

### ISSUE THREAD

**Issue by rjVapes** [Snyk/snyk#45]
- `node -v`: 6.5.0
- `npm -v`: 3.10.3
- `snyk -v`: 1.19.1
- Command run: snyk protect -d
- OS: Windows 10

### Expected behaviour
Successful patching

### Actual behaviour
Failed to patch uglify:
The patch against "node_modules\swig\node_modules\uglify-js" (npm:uglify-js:20151024) failed.

* Debug output attached

### Steps to reproduce
This happened while running 'npm install' on the linnovate/mean project.  It only seems to happen on windows, as the same process installs fine on MacOS, and I believe linux.

To install that project:
npm install -g mean-cli
mean init <project name>  *This will create a new directory and clone into it
cd into new directory and npm install

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

[snyk-protect-debug.txt](https://github.com/Snyk/snyk/files/496711/snyk-protect-debug.txt)

**Comment by grnd** [comment]
John, thank you for reporting this issue.
What shell environment are you using (native windows command shell, mingw, cygwin)?
Can you please provide the output of the following two commands:
$ patch -v
$ snyk protect -d # please run it in project folder

Thank you!

**Comment by grnd** [comment]
@rjVapes mention - in case you didn't get my response above :)

**Comment by rjVapes** [comment]
The output of snyk protect -d was attached, and run from the project folder.
`C:\dev\projects\meanTest>snyk protect -d > snyk-protect-debug.log`

```
C:\dev\projects\meanTest>patch -v
patch 2.5.9
Copyright (C) 1988 Larry Wall
Copyright (C) 2003 Free Software Foundation, Inc.

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

written by Larry Wall and Paul Eggert
```

**Comment by grnd** [comment]
@rjVapes: Thanks! We managed to reproduce the issue locally. Please uninstall old version of gnu patch, and use official git tools instead (https://git-scm.com/download/win). Make sure to add the bin folder (`C:\Program Files\Git\usr\bin\`) to the PATH.
running `patch -v` should have the following output:
```
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert
```

**Comment by rjVapes** [comment]
@grnd Perfect, we'll just have to make note of the version dependency in our docs etc.  Thanks for the help.
