### ISSUE TITLE
Feature Request: GitHub pull request titles should mention the vulnerable package names.

### ISSUE THREAD

**Issue by TauPan** [snyk/snyk#457]
At least in the case of "1 vulnerable dependencies" it would be helpful to see the name in the PR title right away.

Cves would be nice as well.

**Comment by yuliabaron** [comment]
Since PR title is length-limited, we prefer to add this information into PR description. There's a link for each fixed vulnerability that leads to our site, where a vulnerability's description and CVE can be found

**Comment by TauPan** [comment]
I currently have two pull requests on a project, both have the same title:

"[Snyk] Fix for 1 vulnerable dependencies"

Until I can handle them, I need to open each one of them to get a meaningful overview. Of course I could change the PR title by hand, but I'd need to do that for every pull request I receive from snyk every time.

Currently it looks like it's less work for me to simply disable pull requests from snyk and go via the project overview or the dashboard on the snyk website instead, as it provides a more meaningful overview.

**Comment by yuliabaron** [comment]
I see what you mean. I'll check if the PR length allows us to do smth about it

**Comment by yuliabaron** [comment]
Hi,
We haven't forget about this one, still on our list. Apologies I'm still not able to provide a timeline for when this will be available.

**Comment by lili2311** [comment]
hi @TauPan is this still relevant? Our vulnerability fix PRs do have the package name mentioned in their title along with the versions. I would like to close the issue.

**Comment by TauPan** [comment]
Do they now? I did not use snyk PRs for a while because of that. I might try tomorrow.
