### ISSUE TITLE
publish new npm versions only when there are changes that impact that package

### ISSUE THREAD

**Issue by travi** [snyk/snyk#474]
### Expected behaviour

updates are published when a consumer of the npm package would see actual changes

### Actual behaviour

versions are often published that only list changes to mvn, gradle, etc that create meaningless noise when only consuming through npm. (npm is noisy enough. also dealing with versions that don't have an impact shifts burdens from managing your project to managing my project)

I understand that versioning everything together is a fairly common monorepo strategy, but please recognize that while it may be helpful for you maintaining the project, it does make things harder for consumers. beyond semver not communicating the actual risk of a change per package, i'm getting notifications for changes that have no impact on the way i consume. this is a frustrating approach when everything in a monorepo is consumed the same way, but getting notifications for changes that impact only other languages/package managers is even more frustrating.

**Comment by lili2311** [comment]
HI @travi! 

Snyk cli handles testing any supported project type and thus has each language as a plugin (an npm package with a pinned version in cli), it is important for us to release the changes that have important bug fixes and new features for all of these and it indeed does mean that the main cli gets released as well.

While some users only use `npm` side of the cli, many users have multi language monorepos and use a variety of languages via the cli.

What sort of improvements do you see that can help with the notifications? Would love to hear some ideas and approaches.

**Comment by travi** [comment]
ok. that makes more sense than the assumption i had. i didnt realize that the plugins were actually dependencies of the cli. in that case, i can understand the need to publish the cli as a result of those changing. i assumed (obviously incorrectly) that it was a result of versioning independent tools in a monorepo.

i have seen approaches where a cli is installed as more of a peer to such plugins so that the cli wouldn't require updates when plugins changed, but that would require detecting plugin availability and conditionally loading based on presence. 

however, now understanding the dependency relationship, i retract my objection. i'm a heavy greenkeeper and semantic-release user, so i've trained myself to handle a very active stream of updates. i actually am a fan of frequent releases, so i wouldn't want to encourage lessening the frequency. i have become sensitive to monorepo orgs blasting updates in versions where there are really no changes, but you've clarified that that isn't what is happening here.

thank you for the clarification and sorry for the noise

**Comment by lili2311** [comment]
:) No worries, interesting about peer deps might be something worth exploring
