### ISSUE TITLE
No notification on missing node_modules for snyk monitor

### ISSUE THREAD

**Issue by chesterm8** [snyk/snyk#476]
As per #126, but for snyk monitor.
I did not realise why I was getting no results until I tried running snyk test and saw the error message there.

The comment in #126 stating " if there is a lockfile present we don't look in the node_modules" might suggest a workaround for me - if I run against package-lock.json rather than package.json I assume I will not need the node_modules folder to be present.

**Comment by lili2311** [comment]
👋 You are correct if we detect a lockfile then we have 100% of all information that we need to do a test. What version of the CLI are you using please?

**Comment by chesterm8** [comment]
Using version `1.161.1`.
I was running something like `snyk monitor --file=some/path/package.json --org=myorg --project-name=thename`

I have switched to running against `package-lock.json` which does fix the issue of requiring `node_modules`. I do still suggest that `snyk monitor` produce an error message as `snyk test` does to help others work out what is going on.

**Comment by lili2311** [comment]
Is this still an issue for you on the latest version of cli?

**Comment by lili2311** [comment]
Closing, please re-open if it is still occurring but we believe this should be fixed in later version of cli.
