### ISSUE TITLE
snyk auth doesn't work and gives the error

### ISSUE THREAD

**Issue by sandeepkkv** [snyk/snyk#482]
- `node -v`:
- `npm -v`:
- `snyk -v`:
- Command run:

### Expected behaviour
I'm trying to run snyk auth from the CLI but its not going through and pops out an error saying that its "Unable to get local issuer certificate".
 

### Steps to reproduce
![WhatsApp Image 2019-05-05 at 14 08 20](https://user-images.githubusercontent.com/32559505/57200584-b2373d00-6f42-11e9-8148-4e8b409d577d.jpeg)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 Is this still an issue for you? Could you run the same command with `-d` at the end so we can get more debug information please.
