### ISSUE TITLE
Support GitHub connections without gaining full control over public and private repos

### ISSUE THREAD

**Issue by DinisCruz** [snyk/snyk#49]
The permissions requested are too much

![image](https://cloud.githubusercontent.com/assets/656739/19800173/71b60dda-9cf2-11e6-8474-656af2b48b51.png)

Is there a mode where hooks can be set? (with just privs to update the commit status)

related to: https://twitter.com/DinisCruz/status/791922032686444544

**Comment by johannakoll** [comment]
Hello Dinis! 
Just to let you know that just before the Christmas holidays, we deployed the option to only grant us access to your public repositories. 

This is the first step towards more granular permissions; we plan to use the new GH integrations API to add more options, such as choosing with GH organisation you'd like to give Snyk access to. 

We will still require read/write access when you want to open a pull request with fixes for a vulnerability, but want to find a way to let you test and protect repos with read-access only. 

Would be interested in your feedback on this (if you have any) :-)

**Comment by DinisCruz** [comment]
thx, but still not good enough (sorry)

This is why we really need to figure this out at the Summit http://owaspsummit.org/Working-Sessions/Securing-GitHub-Integrations.html

**Comment by johannakoll** [comment]
@DinisCruz have you looked at the upcoming GH integrations API? https://developer.github.com/early-access/integrations/

We investigated it, and while it isn't ready to use yet, they're putting lots more granularity in place.
