### ISSUE TITLE
No line prefixed with "JSONDEPS " was returned

### ISSUE THREAD

**Issue by Neil-Urwin** [snyk/snyk#491]
- `node -v`: v11.13.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.162.0
- Command run: snyk monitor

### Expected behaviour
Has been working fine until recently and uploaded dependencies to snyk website.

### Actual behaviour
```
===== DEBUG INFORMATION START =====

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.18.0-18-generic amd64


No line prefixed with "JSONDEPS " was returned
===== DEBUG INFORMATION END =====
```

### Steps to reproduce
It's a private repo so I can't share it. I've searched for JSONDEPS but can't find any info. Any help on what that is would be appreciated.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 JSONDEPS is coming from our gradle plugin https://github.com/snyk/snyk-gradle-plugin/blob/6f90fe95c30701b84a7127264e991b790cd5dee2/lib/index.ts#L160

Please confirm this issue persists with latest version of the CLI?
What was the full command you ran?

**Comment by Neil-Urwin** [comment]
I've upgraded to the latest snyk (snyk -v: 1.163.3) and get the same issue:

```
===== DEBUG INFORMATION START =====

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.18.0-18-generic amd64


No line prefixed with "JSONDEPS " was returned
===== DEBUG INFORMATION END =====
```

Full command is 'snyk monitor'.

**Comment by kyegupov** [comment]
Hi Neil,

it looks like our analyzer task is not getting executed. This is very unusual.
Do you have subprojects in your project? Are you running `snyk monitor` from the top-level project? Does running it from sub-project make any difference?

In the meantime, we will try to add more debugging output to the tool to diagnose the problem.

**Comment by Neil-Urwin** [comment]
No sub-projects, and just run from the top-level project directory.

We recently moved from Gradle 4 to Gradle 5. If I can find some time I'll try regressing and see if it starts working again.

**Comment by lili2311** [comment]
👋 We have released a later version of cli with enhanced logging, please could you try using that?  Would you be able to share your gradle files with us at all so we can try replicate the issue locally? If they are sensitive you can share privately via support@snyk.io

**Comment by lili2311** [comment]
Responded via email.

**Comment by lili2311** [comment]
Closing this issue, please re-open if needed.
