### ISSUE TITLE
The Github projects counter shows more projects than Github has when importing all projects

### ISSUE THREAD

**Issue by SeppPenner** [snyk/snyk#492]
### Expected behaviour

The count of imported repositories from Github to Snyk should be the same when importing all.

### Actual behaviour

Github shows me 613 repositories (including forks):
![image](https://user-images.githubusercontent.com/9639361/57374472-3e43a180-719b-11e9-8b19-cc937b405a43.png)

while Snyk shows me 1428 repositories:

![image](https://user-images.githubusercontent.com/9639361/57374488-4a2f6380-719b-11e9-91e7-867ae35625c4.png)

### Steps to reproduce

I'm not completely sure but what happens if I import all projects multiple times? (I pressed `Add selected repositories` with all projects selected once and did this again few days later because I was too lazy to select only those which haven't been selected previously).

Maybe this is related to https://github.com/snyk/snyk/issues/489 where I wrote in the Note:

`... Another strange thing is that snyk shows two package configs (One for 4.7. which is from an older commit I would say and the one for .Net 4.8. which is the current one)`

**Comment by lili2311** [comment]
👋 These are .Net projects? Sounds like you have multiple Target Frameworks configured in them. Each target framework generates a complete different set of dependencies, so we create 1 project per target frameworks from the same set of manifest files. These dependencies can't be merged as Nuget doesn't allow multiple versions of the same dependency in the tree. So by following Nuget resolution rules we have to treat each one as a separate dependency tree.

If you have 3 Target Frameworks in your manifest => this will be 3 projects in Snyk.
I hope this explains what you are seeing?

**Comment by SeppPenner** [comment]
Hi. Yes, these are .Net projects.

I switched from .Net 4.7. to .Net 4.8 with one of the last commits of most of the projects. E.g. https://github.com/SeppPenner/EmguCVZXingBarcodeExample/blob/master/TestBarcode/packages.config --> There I can see two different .Net versions:

![grafik](https://user-images.githubusercontent.com/9639361/57585511-6c054f00-74e9-11e9-8a1c-7dd4e094badc.png)

I assume, Snyk has added the old packages.config file from one commit (https://github.com/SeppPenner/EmguCVZXingBarcodeExample/commit/351c31643cc86652d9e06041e85c95c9c0cb2cfa) and the new one from another (https://github.com/SeppPenner/EmguCVZXingBarcodeExample/commit/dec364dddea6005d9db14d06c2f1db8e1ad97827).

I do not have multiple target frameworks configured: https://github.com/SeppPenner/EmguCVZXingBarcodeExample/blob/master/TestBarcode/TestBarcode.csproj --> `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>`.

Is there anything else I am missing?

**Comment by lili2311** [comment]
👋 Please the explanation I just gave on this issue: https://github.com/snyk/snyk/issues/511#issuecomment-491609783

Each update to a target framework is treated as a new project in our system today, it is a known limitation and we are working towards making this more update dynamically as much as possible.

**Comment by SeppPenner** [comment]
Thank you for the explanation. This is indeed the same issue. I will close this one then :) 👍

**Comment by SeppPenner** [comment]
@lili2311 Sadly, the re-import did not solve the problem for me :(

![grafik](https://user-images.githubusercontent.com/9639361/57586105-35333700-74f1-11e9-863a-3408ce58440a.png)

**Comment by lili2311** [comment]
You will have to manually delete the old project that will no longer be updated unfortunately.

**Comment by SeppPenner** [comment]
Ah okay.
