### ISSUE TITLE
unable to install snyk

### ISSUE THREAD

**Issue by hugofqueiros** [Snyk/snyk#5]
Ubuntu 14.04
nodejs: v0.12.7
npm: 2.11.3

> snyk@1.3.1 postinstall /usr/lib/node_modules/snyk
> node cli/index.js help api-license

/usr/lib/node_modules/snyk/node_modules/configstore/index.js:53
				throw err;
				      ^
Error: EACCES, permission denied '/home/hfq/.config/configstore/snyk.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.create.all.get (/usr/lib/node_modules/snyk/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/lib/node_modules/snyk/node_modules/configstore/index.js:27:44)
    at Object.<anonymous> (/usr/lib/node_modules/snyk/lib/user-config.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by remy** [comment]
Can you confirm how snyk was installed (ie. was it `sudo` or just regular `npm install -g snyk`)?

**Comment by hugofqueiros** [comment]
sudo npm install -g snyk

**Comment by hugofqueiros** [comment]
btw, this happened after an update i did to snyk. I don't know exactly which version I had globally installed but my guess would be v1.1.1.

**Comment by alecha** [comment]
Same issue here

```
Error: EACCES, permission denied '/Users/myuser/.config/configstore/snyk.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.create.all.get (/usr/local/lib/node_modules/snyk/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/snyk/node_modules/configstore/index.js:27:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/lib/user-config.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "snyk-protect"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! snyk@1.9.1 snyk-protect: `node cli/index.js protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snyk@1.9.1 snyk-protect script 'node cli/index.js protect'.
npm ERR! This is most likely a problem with the snyk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/index.js protect
npm ERR! You can get their info via:
npm ERR!     npm owner ls snyk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/snyk/npm-debug.log
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "snyk"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
```

**Comment by remy** [comment]
@alecha can I ask how you were installing snyk? Can I assume this wasn't with sudo?

**Comment by alecha** [comment]
actually it was, `sudo npm install -g snyk`

I guess it something related to node/npm versions I’m running in my machine, is it possible?

**Comment by remy** [comment]
@alecha no, it's actually to do with the user swapping that goes on when you run with `sudo` and when we (snyk) run the `postinstall` process. Can you try without `sudo`? IIRC it's something like the permissions don't read correctly to write to your home directory - which is where your snyk config is saved (containing your API key).

**Comment by kawashimaken** [comment]
I can not install it to my Mac (El Capitan, node.js 4.2.6, npm 2.14.7), neither can I install it withou  `sudo`
`Error: EACCES: permission denied, open '/Users/macbookpro/.config/configstore/snyk.json'
You don't have access to this file.`

**Comment by remy** [comment]
What's the error without sudo?

**Comment by kawashimaken** [comment]
```npm install -g snyk

npm ERR! tar.unpack untar error /Users/macbookpro13/.npm/snyk/1.9.1/package.tgz
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "snyk"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/snyk
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/snyk'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/snyk']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/snyk',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/snyk',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro13/npm-debug.log
```

And of course
into my test folder I **can** install without `-g`
`npm install snyk`

**Comment by remy** [comment]
@kawashimaken from your log (on installing the global method) looks to be a local permissions issue.

In particular: `Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/snyk'`

I believe this should fix the access issue: https://docs.npmjs.com/getting-started/fixing-npm-permissions (includes a useful video with multiple methods to fix).

**Comment by kawashimaken** [comment]
@remy  Thank you for your response, and thank you for the info, I will definitely check it out later.
Just one beginner question, why I can install other packages globally, however I have to fix the access issue to install snyk?

Really believe snyk can help me to figure out if my node application dependencies are alright.

**Comment by remy** [comment]
@kawashimaken hmm, I'm not sure. At first I'd ask if you can install *any* package globally and whether this just affected Snyk, or if there was a handful of packages that worked and others that do not. Is it possible that the directory `/usr/local/lib/node_modules/snyk` already exists (from a previous install attempt)? *That* might also cause the issue...

**Comment by kawashimaken** [comment]
@remy Sorry for being late to response.
Actually I can install other packages globally without any problems. snyk is the first package that I can not install globally so far (till last time).
in my `/usr/local/lib/node_modules/` folder no snyk there,

Today I tried again, and this time is a SUCCESS.
I guess the updated version fixed the issue!
Thank you for your great work!

**Comment by remy** [comment]
This is strange, but shall we close this issue now, or anyone else seeing this still?

**Comment by kawashimaken** [comment]
If others don't report any related issues, I don't mind if you close it.
