### ISSUE TITLE
`snyk test *` and `snyk test c:\path\to\*` don't work on windows

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#50]
- `node -v`: 4.3.0
- `npm -v`: 3.10.9
- `snyk -v`: 1.19.1
- Command run:
X snyk test *
X snyk test .\\*
V snyk test .
X snyk test c:\path\to\\*

### Expected behaviour
Snyk runs on each folder containing a `package.json` and a `node_modules` folder.

### Actual behaviour
```
C:\Users\jhouw\Source\Repos\vsts-snyk-task>snyk test *
The package could not be found or does not exist

C:\Users\jhouw\Source\Repos\vsts-snyk-task>snyk test .\*
invalid package name: .\*, errors: name cannot start with a period
name can only contain URL-friendly characters

C:\Users\jhouw\Source\Repos\vsts-snyk-task>snyk test C:\Users\jhouw\Source\Repos\vsts-snyk-task\*
invalid package name: C:\Users\jhouw\Source\Repos\vsts-snyk-task\*, errors: name can no longer contain capital letters
```

Note, the last two error messages don't show up in red either and Snyk returns `1` instead of a specific error code:
![image](https://cloud.githubusercontent.com/assets/4173387/20445539/b9d19082-add5-11e6-9998-5056a40fe357.png)

### Steps to reproduce
Run snyk on Windows 10

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by jessehouwing** [comment]
Still not working on Windows 10. Is this expected behavior?

**Comment by adrukh** [comment]
👋 @jessehouwing 

The expected behaviour is to support `snyk test path1 path2 path3` and test all 3 paths for relevant projects. I'm not entirely sure, but I think the Windows `cmd` shell doesn't expand `*` to all possible paths? And even if it did, it would perhaps result in `snyk test dir1 dir2 file1 file2`, and we'd fail testing the files?

**Comment by jessehouwing** [comment]
Windows just passes in the * as an argument and expects you to do whatever you want with it :).

**Comment by adrukh** [comment]
Aha! Then we don't have the desired handling for this case.
The `argv` handling is here - https://github.com/snyk/snyk/blob/master/src/cli/args.ts

Can you point us at a CLI that handles Windows better? We'd like to explore :)

**Comment by adrukh** [comment]
Yes, I'm not saying we shouldn't support it! It would be great to do the 'right thing' in this case, and figuring out what this 'right thing' is is a challenge by itself :)

As this issue documents what we can do better, I'm just asking for a point of reference - if there is a nodejs-based CLI that supports `*` arguments in Windows in a way that works for its users, I'd like to learn from it. It can help expedite the solution :)

**Comment by jessehouwing** [comment]
Not that I know of. I'm using node mostly for Azure Devops Pipelines tasks and for those there is a findmatch function (https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/task.ts) which is the standard in Azure devops nowadays.

It's not the same as dos wildcards. Though I don't think you'd need any at this point. * basically means every child-item under current item in most every system.

**Comment by jessehouwing** [comment]
Looks.like you're not alone https://stackoverflow.com/a/41645185/736079
