### ISSUE TITLE
Broken link in README around `SNYK_TOKEN`

### ISSUE THREAD

**Issue by garethr** [snyk/snyk#508]
### Expected behaviour

Instructions to find `SNYK_TOKEN` in README should be correct.

### Actual behaviour

Instructions in GitHub README include a link which returns a 404 error page.

```console
$ curl -I https://snyk.io/account
HTTP/2 404 
content-security-policy: base-uri 'none'; script-src 'self' https: 'nonce-lmxxHQ1hCMvBp0QhTn/V1Q==' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic'; img-src https: data:; object-src 'none'; report-uri http
s://snyk.report-uri.com/r/d/csp/enforce;
x-snyk-version: undefined
content-type: text/html; charset=utf-8
content-length: 24810
etag: W/"60ea-1kMVieEIEH7yxA9Mcd0focTJWbI"
date: Sat, 11 May 2019 12:23:08 GMT
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000; preload
```

I _think_ this should be https://app.snyk.io/account but I wanted to double check before submitting a PR.

### Steps to reproduce

1. View the README on GitHub
2. or view the README on [Docker Hub](https://hub.docker.com/r/snyk/snyk-cli)
3. Note `SNYK_TOKEN - Snyk API token, obtained from https://snyk.io/account.`
4. Visit https://snyk.io/account

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
Indeed, https://app.snyk.io/account is the proper link!

**Comment by adrukh** [comment]
We follow semantic-release commit message notation, please make this one a `docs: ...`
