### ISSUE TITLE
`Snyk protect` can't find profile file when passing path

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#51]
- `node -v`: 4.3.0
- `npm -v`: 3.10.9
- `snyk -v`: 1.19.1
- Command run:
```
X snyk protect c:\path\to\project
X snyk protect c:\path\to\*
X snyk protect .\project
X snyk protect .\* 
X snyk protect project
X snyk protect *
V cd project || snyk protect
```
### Expected behaviour
behavior is similar to `test` and passing in a path just works

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/4173387/20445764/b7f58b8c-add6-11e6-8539-6adb7f4361c9.png)

### Steps to reproduce
Run snyk on windows 10 outside of the project folder.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
Closing this one, as it is very old. Please re-open with new debug info if it is still an issue
