### ISSUE TITLE
Make `snyk test` and `snyk protect` return a specific error code when scanning succeeds but vulnerabilities are found

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#52]
I'd like to be able to offer users of my CI pipeline the ability to only log a warning when vulnerabilities are found. This may be useful for feature branches or development work that isn't being shipped.

Right now it's not possible to check the return code when calling the executable. Parsing the console output may work, but is ugly and prone to breaking.

**Comment by lirantal** [comment]
@jessehouwing I didn't check with `protect` but `snyk test` does yield out error codes if applicable.

For example, with vulnerabilities detected, it returns 1:
![image](https://cloud.githubusercontent.com/assets/316371/20446299/9c389532-ade1-11e6-8aa4-574606b50732.png)

And for a safe scan it returns 0:
![image](https://cloud.githubusercontent.com/assets/316371/20446321/b02dcfbc-ade1-11e6-9b68-c5ebb2764384.png)

**Comment by jessehouwing** [comment]
Not consistently:

```C:\Users\jhouw\Source\Repos\vsts-snyk-task>snyk test .\*
invalid package name: .\*, errors: name cannot start with a period
name can only contain URL-friendly characters

C:\Users\jhouw\Source\Repos\vsts-snyk-task>echo %errorlevel%
1
```

**Comment by lirantal** [comment]
Ahh, so it does return error codes, but mixes them with other unrelated errors. Makes sense now.

**Comment by jessehouwing** [comment]
Hence the request for a "specific" error code. Or maybe ensure that `1` is a consistent error code for "Execution went as planned, yet we detected something" vs "Execution didn't go as planned".

**Comment by jessehouwing** [comment]
That PR doesn't seem to include any fix for this issue...
