### ISSUE TITLE
Snyk can not scan Dockerfile/Image based on distroless/base:latest

### ISSUE THREAD

**Issue by javapapo** [snyk/snyk#522]
- `node -v`: v12.1.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.165.0
- Command run:

```bash
snyk test --docker app:latest  --org=txxxx --file=./Dockerfile --project-name=app-service
```
### Expected behaviour

Get a report

### Actual behaviour
`Failed to detect installed OS packages`

```bash

 snyk Failed to test 1 projects, errors: +0ms
  snyk error: Error: Failed to detect installed OS packages
    at /usr/local/lib/node_modules/snyk/node_modules/snyk-docker-plugin/lib/analyzer/index.ts:31:13
    at processTicksAndRejections (internal/process/task_queues.js:89:5) +11ms
  snyk analytics add error-message
```
The Docker image - is a custom image that is. based on googles distroless

```Dockerfile
FROM gcr.io/distroless/base:latest
+ stuff
```

Is this like expected? Maybe I missed it in the documentation? I technically understand why but is this like by default behavior of snyk?

**Comment by leongold** [comment]
Hey @javapapo, yes, we currently rely on having package manager(s) for dependency scanning, which I'm guessing google's distroless has none of.

We're already working on a more complete, non OS dependant solution.

**Comment by javapapo** [comment]
@leongold  thanks for clarifying. We can close this one I guess..if you already have some in your pipeline

**Comment by Vesli** [comment]
> We're already working on a more complete, non OS dependant solution

Any news on this? I'm developing with Go and I would love to use FROM scratch docker image (as I'm simply copy pasting the binary and running it within the container) without compromising on Snyk.

**Comment by karniwl** [comment]
Hi @Vesli, it is still WIP, and we'll update here when we have more details.
For `scratch` based images, as a temporary workaround, you can use `--file=path/to/dockerfile` flag.
For `distroless` based images, we're releasing soon a change in which we'll stop failing but we still rely on OS package managers and `distroless` support is limited. We'll update here once we have updates in `distroless` and `scratch` images support.
Thanks for your patience!

**Comment by devlinse** [comment]
Any further updates on this?

**Comment by karniwl** [comment]
Hi @devlinse and @Vesli, yes, adding the disclaimer it's still in beta stage, you can use `snyk container test <image>`. This supports both `distroless` and `scratch` images. Please let us know if this is helpful!

**Comment by Vesli** [comment]
Great, we'll give it a try on our side - thanks a lot!

**Comment by karniwl** [comment]
Hi again @devlinse and @Vesli, I'm closing this issue as it should work, please let us know and reopen if you still have issues. Thanks!

**Comment by karniwl** [comment]
Hi again @devlinse and @Vesli, I'm closing this issue as it should work, please let us know and reopen if you still have issues. Thanks!

**Comment by simonkotwicz** [comment]
For scratch-based images, is it possible to detect vulnerabilities in libraries copied from another image, for example:

```
FROM redis:6.0.6-alpine as build

RUN mkdir -p /root_files/lib && \
  cp /lib/ld-musl-x86_64.so.1 /lib/libssl.so.1.1 /lib/libcrypto.so.1.1 /root_files/lib/

FROM scratch

COPY --from=build /root_files /
```
