### ISSUE TITLE
CLI does not return jquery prototype pollution vulnerability when run on package.json

### ISSUE THREAD

**Issue by jason-upchurch** [snyk/snyk#524]
- `node -v`: 10.15.3
- `npm -v`: 6.4.1
- `snyk -v`: 1.165.1
- Command run: `snyk test --file=package.json`

### Expected behaviour
identify that dependency `"query": "^3.2.1"` yields a prototype pollution error and that remediation is to upgrade to `jquery@3.4.0`.

### Actual behaviour
CLI: no vulnerabilities
Web interface: advise to upgrade to `jquery@3.4.0`

### Steps to reproduce
- [ ] include `"jquery": "^3.2.1"` in dependency in `package.json`
- [ ] run `snyk test --file=package.json`

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by jason-upchurch** [comment]
additional test: run `snyk test jquery@3.2.1` to verify the prototype pollution warning.

**Comment by AndreDalcher** [comment]
Can you check in your `package-lock.json` to see what version of jquery has been installed in your project?

If I run `npm install` with "jquery": "^3.2.1" in my `package.json` it actually resolves to 3.4.1 as the latest version which satisfies the dependency, which does not contain the vulnerability.

**Comment by jason-upchurch** [comment]
Thank you @AndreDalcher! Mine resolves to 3.4.1 in `package-lock.json` as well. Much appreciated 👍
