### ISSUE TITLE
Detect GitHub projects that don't have a `package.json` in the root folder

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#54]
For my VSTS extensions I'm using node packages, an extension can contain multiple UI extensions or Build tasks. Each lives in their own subfolder of the project and has its own `package.json`. These projects are detected as `Typescript` by GitHub. It'd be nice if you'd offer me the ability to do a deep scan on demand or to pick-up the GitHub uri when I'm calling `snyk monitor` as the package gets registered over at snyk.io.

**Comment by darscan** [comment]
Hi @jessehouwing . Thanks for reporting. This is something we are investigating. I post back with any updates.

**Comment by adrukh** [comment]
@jessehouwing we released full support for nested projects in GitHub repositories (sometimes referred to as monorepos).

Go to [snyk.io/add](snyk.io/add) and choose any repo with any custom path from the dropdown menu at the bottom of the page:
![screen shot 2017-04-19 at 10 03 47](https://cloud.githubusercontent.com/assets/1489979/25167267/86be4ae4-24e7-11e7-978a-3468f276c509.png)

Web support only for now.
