### ISSUE TITLE
Support for NuGet repositories

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#55]
Right now there is no service that supports reporting unsafe packages or package dependencies for nuget.org. With .NET Core being cross platform and picking up momentum, it'd be a nice place to extend into.

**Comment by maban** [comment]
@jessehouwing Hi! I know it's been a while but we are now working on support for Nuget! Would you like to try our beta? If you email us at support@snyk.io, we'll get you set up. 😄
