### ISSUE TITLE
Offer OAuth workflow for API-key registration

### ISSUE THREAD

**Issue by jessehouwing** [snyk/snyk#56]
Services like VSTS offer a "Authorize" button in the service registration window. It'd be nice when snyk.io would offer a compatible API so I don't have to go to the website to `https://snyk.io/account/` to copy my API key, I could just click the button, walk through the OAuth (or similar) workflow by logging on and automatically have my API key stored inside VSTS.

It's similar to [how you can setup a GitHub authorization](https://www.visualstudio.com/en-us/docs/build/define/repository#github).

**Comment by lili2311** [comment]
Closing this one as it is super old! This has been implemented since
