### ISSUE TITLE
Expose CLI parameters as environment variables

### ISSUE THREAD

**Issue by iwan41** [snyk/snyk#568]
It would be very handy to have parameters from CLI exposed as environment variables (the same way as SNYK_TOKEN).
E.g.
SNYK_ORG -> could save a lot of boilerplate code in CI (especially with more advanced projects) -> same as `--org=`

SNYK_FILE -> `--file=`
SNYK_PROJECT_NAME -> `--project-name=`

Maybe: SNYK_ADDITIONAL_PROPERTIES

**Comment by lili2311** [comment]
Thank you for this request, I think this would be a great candidate for a small external contribution if you are keen?

**Comment by sbinlondon** [comment]
@lili2311 I’m happy to give this a shot if that’s ok?

**Comment by lili2311** [comment]
@sbinlondon Thats great, assigned to you :)

**Comment by sbinlondon** [comment]
@lili2311 Do y'all have contributors' guidelines in your documentation or somewhere else? I couldn't find anything.

**Comment by sbinlondon** [comment]
@lili2311 Is there a PR you can think of that has also dealt with CLI parameters? It would be helpful to be able to look at that and use it as a starting point 😊

**Comment by adrukh** [comment]
👋 @sbinlondon !

You can trace the way the `SNYK_TOKEN` env var gets converted to `config.TOKEN` over here - https://github.com/snyk/snyk/blob/master/src/lib/api-token.ts#L8

There is some automated env parsing in place that _may_ convert every `SNYK_FOO` env var into `config.FOO` or similar. Check out if this works (I'm not fully sure).

Also, see https://github.com/snyk/snyk/blob/master/src/lib/config.ts as it merges config values stored by `snyk config set foo=bar` with env vars such as `SNYK_FOO`. This is the entry point to add new config values that can either be set via the CLI, or provided as env vars.

Please ask further questions as you have them :)

**Comment by sbinlondon** [comment]
@adrukh Perfect, thank you so much! 🙌

**Comment by lili2311** [comment]
👋@sbinlondon, just wanted to check-in see how you are getting on? Please let me know if we can help in any way :)

**Comment by JackuB** [comment]
Hey, this is now possible with `SNYK_CFG_` flags, that were implemented in #1332
Documentation on how they map to flags will be added to readme
