### ISSUE TITLE
Allowed multiple path in snyk-path

### ISSUE THREAD

**Issue by mn3m0nic** [snyk/snyk#589]
Recently we detect in Web UI and in JSON file report contains multiple number of possible 'path'-es and it cause that single detected vulnerability, for example, in vulnerable module "set-value" was introduced via >~ 5000 paths which makes result JSON file grows from 5K to 50M and brakes 'issue to JIRA' functionality which require SNYK-ID and SNYK-PATH should be unique for each JIRA ticket.
In this case your offical SNYKtoJIRA shell script will create ~ 5000 JIRA tickets - which have no sense as all these vulns are related with very atomic NPM library.
Please return back JSON creation functionality or make it backwards compatible to see only 1 possible path and not N*M*K possible - which have no practical sense IFAIK.

- `node -v`:
v8.14.1
- `npm -v`:
6.4.1
- `snyk -v`:
1.180.0

- Command run:

```
snyk test --json  > report20190621-1.json
```

### Expected behavior

JSON file is generated for only real unique issue/vulnerability + one possible path, but not for every theoretical possible path-es - as this have no use cases. 

### Actual behavior

Generated report in JSON or in Web UI contains all possible theoretical path-es which makes Web UI very slow (page renders several minutes) and required to pass JSON through JQ filter which return 5K usefull data from ~50M  

### Steps to reproduce

1. Run "snyk test --json" for JS code;
2. Check count of issues in JSON;

```
snyk auth $TOKEN
snyk test --json > report20190621-1.json
cat report20190621-1.json | jq '.["vulnerabilities"][]["id"]' | sort | uniq -c | sort -nr | awk '{if ($1 > 1000) print $0}' 
   4700 "SNYK-JS-XXX1"
   2350 "SNYK-JS-XXX2"
```

**Comment by lili2311** [comment]
@mn3m0nic would this `summary` report be suitable for you to cover this issue? https://github.com/snyk/snyk-to-html/issues/22

**Comment by lili2311** [comment]
@mn3m0nic did you get a chance to review the linked issue? We have a PR in the works too, would love to know if this is what you are after.

**Comment by lili2311** [comment]
Closing as we have not heard back from you for a little while, please re-open if there is anything further
