### ISSUE TITLE
Snyk checking optional dependencies

### ISSUE THREAD

**Issue by hugofqueiros** [Snyk/snyk#6]
I am using deps, devdeps and optional deps on my package.json.
Snyk only checks the dependencies, not the dev deps, but it seems it is checking the optional dependencies too.

**Comment by johannakoll** [comment]
Yes, this is the case for your local projects, snyk does include the optional dependencies. We exclude optional dependencies if you test a public package, but are looking into adding checking optional dependencies there as well.
If you want to test the dev deps, by default, both wizard and test ignore devDependencies. To test those, add the --dev flag.

**Comment by hugofqueiros** [comment]
Thanks for the quick reply.
No I was looking into why it was checking optional deps, but it makes sense.
