### ISSUE TITLE
Daemonless docker scanning inside the snyk:docker image with podman?

### ISSUE THREAD

**Issue by orf** [snyk/snyk#622]
Right now the `snyk:docker` image is quite annoying as it requires the docker daemon to be running to function at all. In some situations mounting the docker socket inside a container is  a big no-no.

So, why not look into [podman?](https://github.com/containers/libpod). It's a pretty mature project (and part of the much wider [containers organization](https://github.com/containers)) that allows you to run containers without the daemon. As far as I can tell the current docker plugin is fairly simple: it pulls the image and runs some commands to extract information from within the container. This is easily covered by podman and can be fully done using podman without needing a daemon. 

`podman pull your-image && podman run your-image ..xyz`.

This would lower the barrier to use `snyk:docker` and make it more secure. Plus [the installation is pretty simple](https://github.com/containers/libpod/blob/master/install.md) and should work with the `node:8` image currently used.

One annoyance we've seen after using this in production is you need to specify `--storage-driver=vfs` on every call, but other than that it's a pretty drop-in replacement.

**Comment by lili2311** [comment]
👋 @orf we are closing this issue since we have not heard back, please re-open if you need any further help.
