### ISSUE TITLE
dockerhub image `snyk/snyk-cli:composer` is not up-to-date

### ISSUE THREAD

**Issue by HannesBBR** [snyk/snyk#628]
### Expected behaviour
`snyk/snyk-cli:composer` is the latest snyk-cli composer image.

### Actual behaviour
`snyk/snyk-cli:composer` is an older version which hasn't been updated in a few months. The newest version is `snyk/snyk-cli:1.188.0-composer`, but this is not tagged as `snyk/snyk-cli:composer`.

`snyk --version` results in `1.163.0`

### Steps to reproduce

1. `docker pull snyk/snyk-cli:composer`
2. `docker run --rm -it --entrypoint=/bin/bash snyk/snyk-cli:composer`
3. `snyk --version`

### Fix
When building the new images, tag the latest  `snyk-cli:1.xxx-composer` to `snyk-cli:composer`

**Comment by miiila** [comment]
Hi @HannesBBR,

thank you very much for spotting this!  Tagging the lastest version as a general one is exactly what we had, but when we did some changes composer was overlooked.

I updated our build process of docker images to fix this, so as soon as there will be new version, actual snyk-cli:composer will be created.

Thank you again for this help.

**Comment by HannesBBR** [comment]
Perfect, thanks!
