### ISSUE TITLE
Removing `snyk test/monitor` outside of the a "test" folder to support default .yarnclean

### ISSUE THREAD

**Issue by SxMShaDoW** [Snyk/snyk#64]
- `node -v`: 6.2.2
- `npm -v`: NA
- `yarn -v` 0.17.10
- `snyk -v`: 1.22.1
- Command run: `snyk test or snyk monitor`

### Expected behaviour
To work with yarn's default .yarnclean

### Actual behaviour
Currently .yarnclean wipes out "test" folders on dependencies to reduce size

``` 
Error: Cannot find module './test'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/.../node_modules/snyk/lib/index.js:52:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
error Command failed with exit code 1.

```

### Steps to reproduce
install yarn
yarn add snyk -dev
yarn clean
add snyk test / snyk monitor to package.json
yarn run snyk

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by BradlySharpe** [comment]
Removing the `.yarnclean` file and installing the packages again worked for me

**Comment by SxMShaDoW** [comment]
@BradlySharpe - Yes removing the .yarnclean file and installing works. This would be a feature request because I want to keep my .yarnclean for various other reasons.

**Comment by darscan** [comment]
Hi @SxMShaDoW 

It seems `yarn clean` is a bit aggressive. I added a `.yarnclean` file inside a sample app to `node_modules/snyk` and ran `yarn clean` on the sample with interesting results..

On the first run yarn respects the `.yarnclean` file and leaves the `snyk/lib/test` folder alone.. but it also deletes the `.yarnclean` file! So, on the second run yarn ends up deleting `node_modules/snyk/lib/test` as before.

Other libs are having the same [problem](https://github.com/yarnpkg/yarn/issues/2331).

Will look into options and get back to you.

**Comment by SxMShaDoW** [comment]
@darscan - I guess it seems a little weird to have the library called "test" as most people in the community have that folder to _store_ tests and not execute code. The idea behind `yarn clean` is to be able to clean and minimize other node modules (i.e. i don't need to store someone's tests when I run yarn on my code)

**Comment by darscan** [comment]
@SxMShaDoW - yup, agreed, it's a bad name!

**Comment by darscan** [comment]
Hi @SxMShaDoW 

Can you try out the latest [release](https://github.com/Snyk/snyk/releases/tag/v1.23.4) and ensure it's playing nicely with `yarn clean`. Thanks.

**Comment by FJunior225** [comment]
@darscan I'm working with @SxMShaDoW and that release seemed to do the trick. Thank you!

**Comment by darscan** [comment]
Great stuff! Thanks
