### ISSUE TITLE
snyk alpine binary fails for official python3 docker

### ISSUE THREAD

**Issue by chrisdlangton** [snyk/snyk#642]
Using simple Docerfile;

```Dockerfie
FROM python:3-alpine

ARG SNYK_TOKEN
ENV SNYK_TOKEN ${SNYK_TOKEN}

WORKDIR /snyk
RUN $(which python3) -m pip install requests -q
RUN $(which python3) -m pip freeze > requirements.txt
COPY get-snyk.sh .
ENTRYPOINT [ "/bin/sh" ]
CMD ["get-snyk.sh"]
```
And the `get-snyk.sh` file;

```bash
#!/usr/bin/env sh

python --version
pip --version

echo "Checking GitHub Releases version"
version=$(wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep alpine | head -n1 | sed "s/^.*v\([^\/]*\).*/\1/")
echo "Version: ${version}"

echo "Downloading snyk-alpine-${version}"
wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep snyk-alpine |cut -d : -f 2,3 | tr -d \" | xargs wget -cq

if ! echo "$(cat snyk-alpine.sha256)" | sha256sum -c -; then
    echo "Checksum failed" >&2
    exit 1
fi
chmod +x snyk-alpine

./snyk-alpine auth
./snyk-alpine monitor --file=requirements.txt --project-name=snyk-deploy-qa-pip
./snyk-alpine test --file=requirements.txt
```

Produces;

```
Python 3.7.3
pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Checking GitHub Releases version
Verson: 1.192.3
Downloading snyk-alpine-1.192.3
snyk-alpine: OK
Error loading shared library libstdc++.so.6: No such file or directory (needed by ./snyk-alpine)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./snyk-alpine)
```

Plus a few hundred `symbol not found` lines of errors too.

**Comment by chrisdlangton** [comment]
I realise the fix (for now) is to just `apk add gcc` however I am concerned the _binary_ has a dependency at all, is that intentional?

**Comment by adrukh** [comment]
👋 @chrisdlangton 

Thanks for this issue! We are using [pkg](https://github.com/zeit/pkg) to build the standalone binaries. `pkg`'s node runtime for alpine is compiled against `libstdc++`, so `apk add libstdc++` should do the trick.

This is indeed a known issue, see https://github.com/zeit/pkg/issues/726

**Comment by chrisdlangton** [comment]
@adrukh are you saying users must ensure environments must install _prerequisites_ to use the _binary_ ? that is defeating the entire purpose of there being a binary release..

I.e. until the _binary_ release is working stnadalone as designed, we cannot use snyk at all

**Comment by adrukh** [comment]
I was surprised by this as well. Please help promote this on the zeit/pkg repo, it would be great to have a musl-based node runtime that requires no additional dependencies on a barebone alpine.

**Comment by lili2311** [comment]
👋 @chrisdlangton is this still a problem for you with the latest version?
