### ISSUE TITLE
Snyk binary does not support PHP composer

### ISSUE THREAD

**Issue by chrisdlangton** [snyk/snyk#643]
Using official PHP in docker

```Dockerfile
FROM php:7-alpine

ARG SNYK_TOKEN
ENV SNYK_TOKEN ${SNYK_TOKEN}

RUN apk add gcc git zip && \
    curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /home/www-data

RUN composer init -q -n
RUN composer require paragonie/sodium_compat -q
COPY get-snyk.sh .
ENTRYPOINT [ "/bin/sh" ]
CMD ["get-snyk.sh"]
```

**Note:** we needed to add `gcc` dependency or the snyk binary also fails.

the `get-snyk.sh` content;

```bash
#!/usr/bin/env sh

php --version
composer --version

echo "Checking GitHub Releases version"
version=$(wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep alpine | head -n1 | sed "s/^.*v\([^\/]*\).*/\1/")
echo "Version: ${version}"

echo "Downloading snyk-alpine-${version}"
wget -q -O - https://api.github.com/repos/snyk/snyk/releases/latest | grep browser_download_url | grep snyk-alpine |cut -d : -f 2,3 | tr -d \" | xargs wget -cq

if ! echo "$(cat snyk-alpine.sha256)" | sha256sum -c -; then
    echo "Checksum failed" >&2
    exit 1
fi
chmod +x snyk-alpine

./snyk-alpine auth
./snyk-alpine monitor --file=composer.json --project-name=snyk-deploy-qa-composer
./snyk-alpine test --file=composer.json
```

produces;

```
PHP 7.3.6 (cli) (built: Jun 28 2019 02:06:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.8.6 2019-06-11 15:03:05
Checking GitHub Releases version
Version: 1.192.3
Downloading snyk-alpine-1.192.3
snyk-alpine: OK

Now redirecting you to our auth page, go ahead and log in,
and once the auth is complete, return to this prompt and you'll
be ready to start using snyk.

Monitoring /home/www-data...

Could not detect package manager for file: composer.json

Testing /home/www-data...

Error: Could not detect package manager for file: composer.json

snyk failed with code 2
```

**Comment by adrukh** [comment]
Hmmm... When the project file is stated explicitly with a `--file` arg, we need to see `composer.lock` to detect a PHP project. This is documented [here](https://support.snyk.io/hc/en-us/articles/360000911957-Language-support) and appears [here](https://github.com/snyk/snyk/blob/77a80fcb43e74654b53ce186860187ae5ff5eb70/src/lib/detect.ts#L55)

@lili2311 seems like adding `composer.json` to our detection list would be a nice usability improvement? That is, only if we fail gracefully when `composer.lock` is not found :)

**Comment by chrisdlangton** [comment]
seems you dd not run the code.. `composer.lock` exists.
All your feedback is void. can you try and take a look? seems to be a new unknown issue

**Comment by adrukh** [comment]
@chrisdlangton please change these lines:
```
./snyk-alpine monitor --file=composer.json --project-name=snyk-deploy-qa-composer
./snyk-alpine test --file=composer.json
```

to these lines:
```
./snyk-alpine monitor --file=composer.lock --project-name=snyk-deploy-qa-composer
./snyk-alpine test --file=composer.lock
```

and tell me what you see.

**Comment by chrisdlangton** [comment]
@adrukh of course that works, but composer.lock is not always present however the main package manager file `composer.json` is the main file distributed by project repo's.

Based on the existing documentation you linked, even when `composer.lock` exists, we should not see this bug.

Also, this raises the question _why_ snyk enforces the existence of `composer.lock` when `composer.json` is the standard file.

I guess feel free to close this "will not fix" is Snyk will be Dogmatic about requiring `composer.lock`

**Comment by adrukh** [comment]
We require `composer.lock` to be present to perform the scan. It contains the dependency graph structure collected by `composer`, which we rely on in our analysis.

**Comment by chrisdlangton** [comment]
and i guess because snyk do not actually interact with the package managers (or in this case scan the packages directory) then yeah i see, this is a requirement. not the most intuitive based on how historical usage was done but makes sense for more up-to-date or active projects.
