### ISSUE TITLE
automatically added npm run snyk-protect; to npm prepare script doesn't run on windows in git bash

### ISSUE THREAD

**Issue by sn0wcat** [snyk/snyk#646]
- `node -v`:
v10.15.0
- `npm -v`:
6.10.0
- `snyk -v`:
1.192.3

- Command run:

The snyk bot added following changes to my package.json:

`
 "prepare": "npm run snyk-protect; rimraf dist/ && tsc -p ./ --outDir dist/",
`

### Expected behaviour

The script works.

### Actual behaviour

```bash
$ npm run prepare

> @mindconnect/mindconnect-nodejs@3.6.0-6 prepare C:\git\github\mindconnect-nodejs
> npm run snyk-protect; rimraf dist/ && tsc -p ./ --outDir dist/

npm ERR! missing script: snyk-protect;
npm ERR!
npm ERR! Did you mean this?
npm ERR!     snyk-protect
```

### Steps to reproduce

Run npm install or npm prepare with that command on windows in git shell.

---

The reason for this is that the ; is not properly escaped on windows when running in git bash.

This works:

`
"prepare": "npm run snyk-protect && rimraf dist/ && tsc -p ./ --outDir dist/",
`

Proposal use `&&` instead of ';' when adding npm run snyk-protect to prepare step.

**Comment by lili2311** [comment]
Could you share the whole scripts tag please? Do you not have a snyk-protect entry? Please confirm how you use fix with snyk cli or fix PR?

**Comment by sn0wcat** [comment]
```json
  "scripts": {
    "clean": "rimraf starterts/ && rimraf starterjs/ && rimraf dist/",
    "prepare": "npm run snyk-protect; rimraf dist/ && tsc -p ./ --outDir dist/",
    "test": "npm run ts:build && mocha --colors --timeout=0",
    "test-dev": "npm run ts:build && cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 mocha --reporter=list --timeout=0",
    "mocha-run": "mocha --colors --timeout=0",
    "test-jenkins": "npm run ts:build && cross-env JUNIT_REPORT_PATH=./report.xml mocha --colors --reporter mocha-jenkins-reporter --timeout=0",
    "buildnodewin": "docker build -t sn0wcat/mc-nodetest -f Dockerfile .",
    "testnodewin": "powershell -Command \"docker run --rm  -it  -v c:\\Users\\z001ythk\\.mc:/root/.mc -v c:\\Users\\z001ythk\\.mc:/usr/src/app/.mc  sn0wcat/mc-nodetest \"",
    "ts:build": "tsc",
    "ts:watch": "tsc -w",
    "lint": "tslint ./src/**.ts && tslint ./test/**/*.ts",
    "test:watch": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 mocha --watch test/ --growl --reporter=spec --inspect --timeout=0",
    "start-dev": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 cross-env DEBUG=http,mindconnect* concurrently --raw \"npm run ts:watch\" \"npm run test:watch\" ",
    "dev": "npm run ts:build && cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 concurrently --raw \"npm run ts:watch\" \"npm run test:watch\" ",
    "start-agent-dev": "npm run ts:build && cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 cross-env DEBUG=http,mindconnect-agent,mindconnect-fileencoder node ./src/demoagent/test-agent.js ",
    "doc": "compodoc -p tsconfig.json --output docs --name \"@mindconnect/mindconnect-nodejs\" --theme material && cp -r images/ docs/ ",
    "createkey": "openssl genrsa -out private.key 3072",
    "license": "license-checker --csv --onlyAllow \"Apache-2.0; Apache*; BSD; BSD-2-Clause; BSD-3-Clause; ISC; MIT; Unlicense; WTFPL; CC-BY-3.0; CC0-1.0\" --production",
    "license:summary": "license-checker --summary --onlyAllow \"Apache-2.0; Apache*; BSD; BSD-2-Clause; BSD-3-Clause; ISC; MIT; Unlicense; WTFPL; CC-BY-3.0; CC0-1.0\" --production",
    "snyk-protect": "snyk protect"
  },
```

https://github.com/mindsphere/mindconnect-nodejs/blob/master/package.json

This is what the merge request proposed. The `;` just doesn't work as separator on windows.

**Comment by sn0wcat** [comment]
git bash:
![image](https://user-images.githubusercontent.com/1426617/60793442-068bb280-a168-11e9-90f3-7b273f8ea8a6.png)

cmd:

![image](https://user-images.githubusercontent.com/1426617/60793550-33d86080-a168-11e9-8574-372e60125fc5.png)

**Comment by sn0wcat** [comment]
fix PR:

https://github.com/mindsphere/mindconnect-nodejs/pull/62/files

**Comment by lili2311** [comment]
Thanks @sn0wcat, do you think there is something we can use to identify the project as `Windows` or not so we can use `&&` instead of `;`?

**Comment by sn0wcat** [comment]
This is not really about `windows` projects but `nodejs` projects which *sometimes* run on windows machines so that there is no point in trying to recognize anything.  My CI/CD pipeline runs on Linux and we also have some devs with MacOS. 

Instead of recognizing the platform , you should just use the double ampersand `&&` for  everything. This behaves agnostic on all platforms and also has the advantage that the commands are executed in order from left to right, which is probably what you want to do anyway.

https://unix.stackexchange.com/questions/187145/whats-the-difference-between-semicolon-and-double-ampersand

**Comment by lili2311** [comment]
👋 We have released a change that uses `&&` instead, please confirm once you have another PR with patches that this is now all working for you

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/issues/646

**Comment by lili2311** [comment]
Fix is now merged & deployed. Please close this once you had a chance to verify it is all OK for you now?
