### ISSUE TITLE
Vulnerability issue: Memory Leak in inquirer@5.2.0

### ISSUE THREAD

**Issue by VlkaFenryka** [snyk/snyk#647]
**What operating system, Node.js, and npm version?**
OS: Win 10 x64 build 1809
Node: 10.16.0
NPM: 6.9.0
snyk: 1.192.3

**The Problem**
https://www.sourceclear.com/vulnerability-database/security/memory-leak/javascript/sid-20567

**Solution**
update to inquirer >= 6.4.0
https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%406.4.0

**Comment by lili2311** [comment]
hi @VlkaFenryka, thank you for reaching out on this please could I ask you to report this via our Vulnerability Disclosure form located here: https://snyk.io/vulnerability-disclosure/ so we can action this via our usual flow.
