### ISSUE TITLE
Feature/documentation: undocumented programmatic api

### ISSUE THREAD

**Issue by doug-wade** [snyk/snyk#65]
Hello friends!  I hope you're not too upset that I disregarded your issue template; I'm not reporting a bug, so it doesn't really seem to apply.

While developing gulp-snyk, I discovered there is a [main module exported by snyk](https://github.com/Snyk/snyk/blob/master/package.json#L4), and that main module has a `test` method.  I found this delightful, and it made writing the [test branch](https://github.com/doug-wade/gulp-snyk/blob/master/index.js#L17) of my plugin much more elegant than the [other branches](https://github.com/doug-wade/gulp-snyk/blob/master/index.js#L17), which just shell out.

However, the programmatic api is undocumented, at least as far as I can tell, which makes me feel like it might change unexpectedly.   I was wondering if you'd take a pr to document the extant programmatic api, or possibly even prs to extend it to other commands (I mostly want `protect`, though I guess `auth` will be helpful too, once its required before running `test`), or if I should refactor to always shell out for all commands.

**Comment by darscan** [comment]
Hello @doug-wade ! Thanks for getting in touch. You are correct, the api is undocumented, and while it is fairly stable it might change a bit in the near future. The line is currently a bit blurry between `cli/*` and `lib/*` responsibility-wise. We're hoping to nail this down soon, and once that's down we'll properly document it.

**Comment by lili2311** [comment]
👋 This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.

FIY: We planning an overhaul of the CLI and can’t commit to internal APIs at this point, but please do stay tuned for more developments.
