### ISSUE TITLE
Snyk does not find all pom files in multi-module maven project

### ISSUE THREAD

**Issue by mstepniak** [snyk/snyk#654]
- `node -v`: v10.16.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.192.6
- Command run:
snyk monitor --org=my_org --project-name=my_project
snyk test --org=my_org --project-name=my_project

### Expected behaviour
After running this command on multi-module maven project, all pom files are tested

snyk@1.158.0
✓ Tested 172 dependencies for known issues, no vulnerable paths found.

### Actual behaviour
Only one pom file is tested against vulnerabilities
snyk@1.160.0
✓ Tested 1 dependencies for known issues, no vulnerable paths found.
For any newer version there is the same behaviour

### Steps to reproduce
Have multi-module maven project with multiple pom files
Run command for testing
Result: only one pom file is checked

Output of debug command run locally:
```
michal.stepniak$ snyk test --org=myorg --project-name=name --debug
  snyk test { _: [ [Circular] ],
  org: 'org',
  'project-name': 'name',
  debug: true } +0ms
  snyk policies found [ '/Users/michal.stepniak/IdeaProjects/project' ] +0ms
  snyk converting dep-tree to dep-graph { name: 'name-parent',
  targetFile: 'pom.xml' } +3ms
  snyk done converting dep-tree to dep-graph { uniquePkgsCount: 2 } +5ms
  snyk sending request to: https://snyk.io/api/v1/test-dep-graph +0ms
  snyk request body size: 725 +0ms
  snyk gzipped request body size: 246 +0ms
  snyk not using proxy +1ms

Testing /Users/michal.stepniak/IdeaProjects/name...

Organisation:     org
Package manager:   maven
Target file:       pom.xml
Open source:       no
Project path:      /Users/michal.stepniak/IdeaProjects/name
Licenses:          enabled

✓ Tested 1 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run snyk monitor to be notified about new related vulnerabilities.
- Run snyk test as part of your CI/test.
  snyk analytics { args:
   [ { org: 'org',
       'project-name': 'name',
       debug: true,
       showVulnPaths: true } ],
  command: 'test',
  metadata:
   { local: true,
     pluginName: 'bundled:maven',
     policies: 1,
     packageManager: 'maven',
     packageName: 'com.name-parent',
     packageVersion: '1.0-SNAPSHOT',
     package: 'com.name-parent@1.0-SNAPSHOT',
     depGraph: true,
     isDocker: false,
     payloadSize: 725,
     gzippedPayloadSize: 246,
     'vulns-pre-policy': 0,
     vulns: 0 },
  version: '1.192.6',
  os: 'macOS Mojave',
  nodeVersion: 'v10.16.0',
  id: '123.....890',
  ci: false,
  durationMs: 5800 } +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +2s
  snyk request body size: 617 +0ms
  snyk gzipped request body size: 379 +1ms
  snyk not using proxy +0ms
```

**Comment by lili2311** [comment]
Hi @mstepniak 👋 Would you be able to share an example project with us to test on? Are you saying the behaviour changed between those 2 version of the CLI? Just took a look and I don't see any such large changes, so would really like to replicate this.

**Comment by mstepniak** [comment]
Hi @lili2311 thanks for the answer, here is sample project that has maven configuration similar to our project:
https://github.com/mstepniak/mvn-sample

Here are logs for this sample that I am getting:

```
MP29721:mvn-sample michal.stepniak$ snyk -v
1.193.2

MP29721:mvn-sample michal.stepniak$ snyk test

Testing /Users/michal.stepniak/IdeaProjects/mvn-sample...

Organisation:      my-org
Package manager:   maven
Target file:       pom.xml
Open source:       no
Project path:      /Users/michal.stepniak/IdeaProjects/mvn-sample
Licenses:          enabled

✓ Tested 1 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

MP29721:mvn-sample michal.stepniak$ sudo npm -g install snyk@1.158.0
Password:
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.158.0
added 1 package, removed 19 packages and updated 12 packages in 15.73s
MP29721:mvn-sample michal.stepniak$ snyk -v
1.158.0

MP29721:mvn-sample michal.stepniak$ snyk test

Testing /Users/michal.stepniak/IdeaProjects/mvn-sample...

Organisation:      my-org
Package manager:   maven
Target file:       pom.xml
Open source:       no
Project path:      /Users/michal.stepniak/IdeaProjects/mvn-sample
Licenses:          enabled

✓ Tested 3 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

```

**Comment by lili2311** [comment]
Just an update here: we have some work that will auto detect and scan all `pom.xml` and other languages in the repo, this is planned shortly and some sort of Beta will be available this quarter :) I will update here once there is something to try as it will help grab everything here that is relevant and scan it all at once + monitor

**Comment by lili2311** [comment]
@mstepniak we have just released in Beta 🎏 a new feature that allows to auto detect and scan multiple project & project types, it is available from version `1.275.0` and help text can be found here: https://github.com/snyk/snyk/pull/945/files.

It at the moment support `npm`, `yarn`, `rubygems`, `maven` and .Net is being released next. Please give it a try and share any feedback you may have. `snyk test --all-projects --detection-level=2` for example to look 2 directories deep (current and 1 more). Both `test` & `monitor` are supported.

**Comment by lili2311** [comment]
`.Net` has now also been added and released https://github.com/snyk/snyk/releases/tag/v1.278.0

**Comment by lili2311** [comment]
@mstepniak please confirm if this issue can now be closed and the feature above meets your needs?

**Comment by lili2311** [comment]
Closing this since the feature is released, please re-open if you have further feedback.

**Comment by nasifimtiazohi** [comment]
Is this possible to get an aggregated report for multi-module maven projects? 

When a project contains multiple child modules who all share some vulnerable dependency, the snyk reports presents one alert for each module. However, another desired way would be to get an aggregated report for the project with only distinct alerts.

**Comment by nasifimtiazohi** [comment]
hi @lili2311 , 

> Are you using the output of snyk test or using something like snyk-to-html?

I am using `snyk test`.

> Are you suggesting something like:
> snyk test --unique-vulns-only to only display each vulnerability once?

Yes.
