### ISSUE TITLE
There is no synk.json file for the project

### ISSUE THREAD

**Issue by ChiragGL** [snyk/snyk#658]
**node -v:** 10.16.0
**npm -v:** 6.9.0

Whenever I am trying to run any of the synk CLI commands to monitor and test my Node.js package for vulnerabilities, I keep on getting the error: "There is no synk.json file for the project in [Current-Directory Path]. Create one now? type 'yes' or 'no'." And even if I enter yes, it does nothing and shows the same message when ran again.

**Comment by adrukh** [comment]
:wave:

It seems that you are running `synk` instead of `snyk` :)

**Comment by ChiragGL** [comment]
Oh, That was really a terrible mistake. It consumed my complete day and a couple of hours. Thanks for the response. I shall close this Issue.

**Comment by subhnet** [comment]
> 
> 
> 👋
> 
> It seems that you are running `synk` instead of `snyk` :)

Same here mate 😂

**Comment by ankit-1729** [comment]
Same here as well

**Comment by deepaktatineni** [comment]
wasted 4 hours :octocat:

**Comment by Just-Hussain** [comment]
i feel stupid 🩴

**Comment by atish53481** [comment]
Same for me

**Comment by ezebinker** [comment]
Same 🤣

**Comment by Nabeelaron** [comment]
same bro
