### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by doug-wade** [snyk/snyk#67]
- `node -v`: 6.9.5
- `npm -v`: 3.10.10
- `snyk -v`: ^1.14.3
- Command run: `snyk test`

### Expected behaviour
My dependencies are audited

### Actual behaviour
My dependencies are not audited

### Steps to reproduce
- Create two lerna open-source repositories
- Set up both to be tested by snyk using snyk test
- Note that both must be authenticated, and both are considered private

### The actual bug report
Recently, Snyk has changed the way that projects are considered open vs closed source.  All projects that use the CLI are considered to be "private," regardless of whether the project is private or not.  Unfortunately, the Snyk github plugin only considers the root package.json when auditing dependencies, so I need to use the Snyk cli to audit all of my packages.  However, my one "free" slot for a cli-tested application is "used up" by [gulp-snyk](https://github.com/doug-wade/gulp-snyk), so I'm no longer able to audit the dependencies for my projects.  Although I'd much prefer you allow me to continue to use the cli to audit dependencies, and check whether the project is open-source using the [repository field](https://docs.npmjs.com/files/package.json#repository), I presume there are business reasons for not doing that, and instead I'm requesting first-class support for [Lerna](https://github.com/lerna/lerna) projects.

**Comment by adrukh** [comment]
@doug-wade thanks for reporting this!

Support for monorepos is on our roadmap, let me check internally and update on this issue with expected timeline. Not promising anything concrete, but will update with whatever I have :)

**Comment by adrukh** [comment]
@doug-wade we recently changed our pricing model. Long story short - all projects are free :) More details - https://snyk.io/blog/snyk-projects-now-free/

You can also let us know that a project monitored via the cli is actually open-source. Just go to the project settings page and update the open source git URI of your repo. We support GitHub, BitBucket and Gitlab URIs.

**Comment by mennovandiermen** [comment]
Any update on this? I'm taking another quick look at snyk since last evaluating it in a hurry 6 months ago, and setting up the monitoring on multiple manifest files within a repo doesn't seem to be possible while also setting them as open source. Our monorepo only has a `.git` at its root, but there are multiple packages one and two levels deep that I would like to test, but I cannot figure out how to register/monitor them to not be considered private.

**Comment by flo-sch** [comment]
I guess this one is the recommended approach?
https://support.snyk.io/hc/en-us/articles/360000910577-Does-the-Snyk-CLI-support-monorepos-or-multiple-manifest-files-

I have not tested it yet, but I will be able to confirm it soon hopefully
