### ISSUE TITLE
Heap out of memory

### ISSUE THREAD

**Issue by ThomasVdBerge** [snyk/snyk#678]
- `node -v`: v10.16.0
- `npm -v`: 6.9.0
- `snyk -v`: 1.196.0
- Command run: snyk test --max-old-space-size=16384 --file=package.json

### Expected behaviour
Snyk completes it run and tells me if there are any security issues

### Actual behaviour
Snyk crashes, does not matter how high I set max-old-space-size.

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### Steps to reproduce
Run snyk test --max-old-space-size=16384 --file=package.json with the following [packages.json](https://gist.github.com/ThomasVdBerge/77941bd96ae357bb81fc101b9eac1c44)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@ThomasVdBerge 👋 

The `--max-old-space-size` is indeed the right argument to fix this, but needs to be supplied to the nodejs runtime, and not our CLI.

A good way of doing so is to define the `NODE_OPTIONS` env var, see https://github.com/npm/npm/issues/12238#issuecomment-367147962 for example.

Please try this out and tell us how this goes, there are other ways of reducing the memory consumption when testing projects with Snyk!
