### ISSUE TITLE
Is snyk auth required for snyk test?

### ISSUE THREAD

**Issue by petermbenjamin** [snyk/snyk#68]
Hello Snyk Team,

I am wondering why is it that the CLI tool needs to auth in order to perform `snyk test` compared to `nsp check`, which doesn't require any authentication to compare `package.json` against a public advisory/vuln database.

I am aware that on my local machine, `snyk auth` is only required once and `snyk test` would work thereafter without having to `snyk auth` everytime.

Therein lies my problem, if I set up my node project to perform `snyk test` as my `npm test` command, it works on my machine, but fails on the CI platform (e.g. Travis).

I am also aware that I can use the `$SNYK_TOKEN` environment variable on the CI server and modify my `npm test` command to perform `snyk auth $SNYK_TOKEN && snyk test`, which I am fine with, but every time I run this on my machine, the snyk auth command opens a web page in my browser, which becomes annoying after the first time.

This is all to say that I propose one of two things:
1. I presume that `auth` is needed more so for `wizard` command (for auto patching capabilities) than for `test` (which is essentially a one-time test). If this is the case, then `snyk test` should work  without having to authenticate.
    - This would simplify running `snyk test` on CI servers as users wouldn't have to do additional configuration/setup to export `SNYK_TOKEN` environment variables.
1. Alternatively, if `auth` is required for `test`, then simply authenticate without opening a browser window, unless specified with a flag (e.g. `-g` or `--gui`)

**Comment by joshje** [comment]
Hi @petermbenjamin, these are very good points you raise.

We do require auth in order to run `snyk test`, however we're revising our documentation as a result of this issue you've raised, and recommend the following for working with CI environments:

- Set the environment variable `SNYK_TOKEN` to your API token (found at [https://snyk.io/account](https://snyk.io/account))
- Now any `snyk` commands you run (including `snyk test`) will use that token automatically

There is no need to run `snyk auth` if you follow those steps. Let me know how you get on.

**Comment by KharitonOff** [comment]
since two weeks (14 days) we are facing the same issue in our repo cla-assistant/cla-assistant
All builds for pull requests fail with error "snyk test requires an authenticated account. Please run `snyk auth` and try again.". We have stored SNYK_TOKEN and it works for brunch-builds but fails for PR-builds.
e.g.
https://travis-ci.org/cla-assistant/cla-assistant/builds/308060825

Everything worked fine 15 days ago

**Comment by maban** [comment]
Hi @KharitonOff, Travis doesn't make tokens available on PRs sent from forked repos. There's a bit more information about that here: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions – it also contains a workaround.

Let us know how you get on!

**Comment by KharitonOff** [comment]
@maban thank you for your response! The workaround works 👍

**Comment by evanjmg** [comment]
I've set the environment variable in circle ci and it doesn't work 👎

**Comment by evanjmg** [comment]
https://snyk.io/blog/requiring-authentication/ so do we do it this way? This way gives me an error as well

**Comment by adrukh** [comment]
@evanjmg indeed so! Having your token allows us to match the test against your organisation, and apply whatever settings you choose. ~See https://snyk.io/blog/requiring-authentication/ for more details.~ you just did that :)

The proper way to authenticate in a CI environment is any of these two options:
- set the `SNYK_TOKEN` env var to the value of your token
- run `snyk auth <your-token>` before running `snyk test`

**Comment by evanjmg** [comment]
I've done this (snyk auth ${SNYK_TOKEN} && snyk test and it doesn't work. I get the error: noAuthInCi

**Comment by evanjmg** [comment]
> snyk auth ${SNYK_TOKEN} && snyk test

An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: noAuthInCI
    at githubAuth (/home/circleci/project/node_modules/snyk/cli/commands/auth.js:46:17)
    at auth (/home/circleci/project/node_modules/snyk/cli/commands/auth.js:150:15)
    at /home/circleci/project/node_modules/snyk/lib/hotload.js:16:21
    at Object.<anonymous> (/home/circleci/project/node_modules/snyk/cli/index.js:15:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)

**Comment by evanjmg** [comment]
**I got it working finally. set the SNYK_TOKEN env var to the value of your token is the correct solution.**

**Comment by adrukh** [comment]
Thanks for updating!

`noAuthInCI` on `snyk auth ${SNYK_TOKEN}` usually points to `SNYK_TOKEN` not being set, resulting in `snyk auth` being executed, which relies on user interaction, and bails out if in CI mode.

Glad you got this working eventually!
