### ISSUE TITLE
Snyk autopatch breaks Windows compatibility

### ISSUE THREAD

**Issue by saschanaz** [snyk/snyk#683]
- `node -v`: 12.7.0
- `npm -v`: 6.10.2
- `snyk -v`: 1.199.0

The snyk bot modified `prepare` script to be `"prepare": "npm run snyk-protect; npm run build:components"` in our package.json: https://github.com/w3c/respec/pull/2410 and this causes failure on Windows:

```
> respec@24.27.1 prepare C:\Users\sasch\Documents\GitHub\respec
> npm run snyk-protect; npm run build:components

npm ERR! missing script: snyk-protect;
npm ERR!
npm ERR! Did you mean this?
npm ERR!     snyk-protect

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sasch\AppData\Roaming\npm-cache\_logs\2019-07-25T02_25_35_640Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! respec@24.27.1 prepare: `npm run snyk-protect; npm run build:components`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the respec@24.27.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sasch\AppData\Roaming\npm-cache\_logs\2019-07-25T02_25_35_727Z-debug.log
```

Replacing `;` with `&&` fixes the problem. It seems npm on Windows only supports `&&`.

**Comment by lili2311** [comment]
Relevant: https://github.com/snyk/snyk/issues/646

**Comment by lili2311** [comment]
Fix is now merged & deployed. Please close this once you had a chance to verify it is all OK for you now?

**Comment by saschanaz** [comment]
Great! How can I verify whether it works?

**Comment by lili2311** [comment]
You can try:
- open a PR on a repo that needs patching via Snyk UI
- or run `snyk wizard` 

This change only affects projects where there is already something in `prepare` script. On the PR you mentioned you could manually change it to `&&` of course to fix that one.

This will take effect only on new PRs & wizard runs from now on.

**Comment by lili2311** [comment]
Did you get a chance to try this out? Is the issue resolved for you?

**Comment by saschanaz** [comment]
Oops, sorry for no response! I just tried the wizard way `npx snyk wizard` with my package.json `"prepare": "npm run build:components"` but it just adds `"test": "snyk test"` and nothing else. Any idea?

**Comment by lili2311** [comment]
Hi! Do you have the example file or perhaps you can share this to `support@snyk.io` if it is private so we can take a peek?

**Comment by saschanaz** [comment]
Retried and it works 👍 Thanks!
