### ISSUE TITLE
Misdetection of vuln path when dependencies originate on a git url

### ISSUE THREAD

**Issue by adrukh** [snyk/snyk#70]
- `node -v`: 6.5.0
- `npm -v`: 3.10.0
- `snyk -v`: 1.25.2
- Command run: `npm i && snyk test` in a clone of https://github.com/optimizely/snyk-test

### Expected behaviour
No vulnerabilities should be detected, as the vulnerable paths originate from `grunt-jsdoc-to-markdown@0.4.3`, which is a dev dependency.

### Actual behaviour
Vuln `npm:marked:20170112` is detected on the path `snyk-test@1.0.0 > jsdoc@3.3.0-dev > marked@0.3.6`.

This is wrong in two ways:
- The vuln exists on a dev dependency and should be ignored by `snyk test`, only detectable with `snyk test --dev`
- The path is incorrect, as `jsdoc@3.3.0-dev` is not a direct dependency of the project.

### Steps to reproduce
- `npm i grunt-jsdoc-to-markdown@0.4.3`
- `snyk test`

The broken vuln path of `npm:marked:20170112` is shown, and is most likely a result of the fact `jsdoc@3.3.0-dev` originates from `git+https://github.com/jsdoc3/jsdoc.git#b5653b838ce7b96f97322c77e65f74c3086bd3d1`.
Running `npm ls` clearly shows the correct path.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by gablaxian** [comment]
This issue has since been fixed. Following the steps above, we get the expected behaviour.
