### ISSUE TITLE
Feature Request: snyk watch in the CLI app

### ISSUE THREAD

**Issue by petermbenjamin** [snyk/snyk#71]
It would be great if users can watch github repositories on snyk.io from the terminal rather than having to do it through the web app (see example below).

Potential questions and solutions:
- What if user has multiple organizations? How would snyk determine which organization to watch this repo for?
  - Maybe, default to the primary/default org if no org is specified (e.g. `$ snyk watch [org]`)

Example:
```sh
Usage:

  $ snyk [options] [command] [package]

Commands:

  auth [api-token] ... 
  test ............... 
  wizard ............. 
  watch [org] ........ Watch repository on snyk.io
  protect ............ 
  monitor ............ 
  policy ............. 
```

**Comment by petermbenjamin** [comment]
I just saw that `--org` already exists and works with `monitor` command.
So, maybe it can be extended to work with `watch` command, with the default org being the primary/default one if no `--org` is provided.

Example:
`$ snyk watch [--org=<my-org>]`

**Comment by johannakoll** [comment]
Thanks for the request, Peter. We are aware of this product gap, but don't plan to address it in the near future. We will look into this again after current work on our API and GitHub integration has been completed.
