### ISSUE TITLE
 Cannot install on Node >7

### ISSUE THREAD

**Issue by simlevesque** [snyk/snyk#74]
- `node -v`: 7.6.0
- `npm -v`: 4.4.1
- `snyk -v`: not installed yet
- Command run: npm i --save-dev snyk

### Expected behaviour
Snyk is installed and added to my dev dependencies.

### Actual behaviour
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"7.6.0","npm":"4.4.1"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"4.4.1","node":"7.6.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deagle/.npm/_logs/2017-03-15T15_50_04_896Z-debug.log

### Steps to reproduce
A simple npm install on my versions of npm and node should do the trick.

**Comment by adrukh** [comment]
@simlevesque seems like your project's installed deps are playing a role here, as `npm i -g snyk` on  node 7.x works (7.7.3 just worked fine for me).

I can suggest adding `snyk` to your devDeps and running `rm -fr node_modules; npm i` to see if this can work out.

**Comment by lirantal** [comment]
Works fine for me on 7.7.4 with yarn v0.18.1 as a global install.

**Comment by adrukh** [comment]
Closing for now, please reopen if you have more info.

**Comment by nebirhos** [comment]
Hi @adrukh!

While upgrading our app to the latest version of node (v9.4.0) I encountered the same issue described by @simlevesque.

`snyk-resolve-deps` has `clite@0.3.0` among its dependencies, which is a 2 years old release (and therefore carries outdated dependencies, like `got@5.7.1`).

If you set `engine-strict=true` for npm, `snyk` refuses to install, both globally and locally:

```
$ echo 'engine-strict=true' >> ~/.npmrc
$ npm i -g snyk

npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"9.4.0","npm":"5.6.0"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"5.6.0","node":"9.4.0"}

npm ERR! A complete log of this run can be found in:
...
```

Installation works fine without the `engine-strict` option, but this is not desirable for our use case.

**Comment by adrukh** [comment]
@nebirhos thanks for pointing this out!
We are in the process of properly retiring Node.js 0.12 support, after which we can introduce breaking changes that will move our dependencies forward. No specific timeline right now, but knowing that we are not Node.js 9 compatible will definitely speed this up, so thanks for your comment.

👋 @remy
Will you be interested in receiving a PR to https://github.com/remy/clite that drops Node.js 0.12 support in favour of letting the future in? :)
