### ISSUE TITLE
Snyk introduces a vulnerability through itself

### ISSUE THREAD

**Issue by JimNero009** [snyk/snyk#744]
I am currently seeing a vulnerability introduced through the dependency tree:
snyk@1.217.3 › snyk-resolve-deps@4.3.0 › @types/package-json@5.0.1 › package-json@4.0.1 › registry-url@3.1.0 › rc@1.0.3 › deep-extend@0.2.11

The vulnerability is around prototype pollution in the deep-extend library. Obviously, it is quite frustrating to have a vulnerability library itself have a vulnerability -- could you fix/advise?

Cheers,
Jim

**Comment by dkontorovskyy** [comment]
Hi @JimNero009.
Thanks for submitting the issue.
Could you provide such data for more accurate debugging:
1. Your snyk version. (run `snyk -v`)
2. Your `package-lock.json` or zipped `node_modules`.

Cos it's what I am not seeing such path in `snyk@1.217.3`.

**Comment by JimNero009** [comment]
Yep, sorry -- seems to be some issue with lockfiles across projects that is mistakenly pulling in 'bad' versions. Closing as no-op.

**Comment by dkontorovskyy** [comment]
@JimNero009, no worries and thanks again for reaching out :)
