### ISSUE TITLE
Add JWT support

### ISSUE THREAD

**Issue by timbru31** [snyk/snyk#75]
### The issue
Snyk requires auth, which is just fine. However when snyk is run in a CI environment like TravisCI the secure variables defined in the TravisCI settings are **not** available for forks due to [security reasons](https://docs.travis-ci.com/user/pull-requests/).

That leads to two options:
- Skipping snyk auth for pull requests from forks. *Bad idea, since often PRs are updating or introducing new dependencies*
- Add synk auth token to the version control. *Bad idea, too*

### The solution
[JWT (JSON Web token)](https://jwt.io/) offer the possibility to securely share information between two parties. TravisCI supports JWT to pass the secret/secured environment variables to the third party tools: https://docs.travis-ci.com/user/jwt

There is a npm module for JWT in NodeJS: https://github.com/auth0/node-jsonwebtoken

By adding a listener for JWT, snyk could be executed safely in a pull request.

**Comment by maban** [comment]
Hi @timbru31 – this is a really nice idea, thanks for suggesting it! We're looking into this.

**Comment by lili2311** [comment]
:wave: This issue has not had a lot of activity for a while, we are closing. Please re-open if there is anything else further.
