### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Hongbo-Miao** [snyk/snyk#754]
- `node -v`: 10.16.1
- `npm -v`: 6.11.1
- `snyk -v`: 1.221.1
- Command run: `yarn install`

### Expected behaviour

I got an auto fix pull request from Snyk at https://github.com/Hongbo-Miao/hongbomiao.com/pull/169.
I expect it has no error when `yarn install`.

### Actual behaviour

It shows error

![image](https://user-images.githubusercontent.com/3375461/63893572-64d25600-c99f-11e9-92dd-fed24fe9d14b.png)

> ...
> $ npm run snyk-protect
> npm WARN lifecycle The node binary used for scripts is /var/folders/58/3k2xhtfd19z23n5pynnhf2rc0000gn/T/yarn--1567027127845-0.7697854065469152/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > hongbomiao.com@0.1.0 snyk-protect /Users/hongbo-miao/Clouds/Git/hongbomiao.com
> > snyk protect
> 
> 
> <--- Last few GCs --->
> 
> [19117:0x10280c000]    88313 ms: Mark-sweep 1286.8 (1442.2) -> 1286.6 (1434.7) MB, 237.6 / 0.0 ms  (average mu = 0.215, current mu = 0.130) allocation failure GC in old space requested
> [19117:0x10280c000]    88569 ms: Mark-sweep 1286.6 (1434.7) -> 1285.3 (1429.7) MB, 256.7 / 0.0 ms  (average mu = 0.114, current mu = 0.000) allocation failure GC in old space requested
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 0x4449dfdbe3d]
> Security context: 0x22012d29e6e9 <JSObject>
>     1: fromString(aka fromString) [0x2201dbf13581] [buffer.js:340] [bytecode=0x2201cb1e00f1 offset=53](this=0x2201d45826f1 <undefined>,string=0x2201581d5f21 <Very long string[252451039]>,encoding=0x22012d2be961 <String[4]: utf8>)
>     2: from [0x2201f0ca03a9] [buffer.js:201] [bytecode=0x2201cb1dfc71 offset=11](this=0x2201865532b1 <JSFunction Buffer (sfi = 0x22...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 0x10003cff5 node::Abort() [/usr/local/bin/node]
>  2: 0x10003d1ff node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
>  3: 0x1001b8265 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
>  4: 0x1005861c2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
>  5: 0x100588c95 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
>  6: 0x100584b3f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
>  7: 0x100582d14 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
>  8: 0x100583215 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
>  9: 0x10058f681 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
> 10: 0x1005614b4 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
> 11: 0x100693029 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
> 12: 0x1001d5ffd v8::String::Utf8Length() const [/usr/local/bin/node]
> 13: 0x100051057 node::Buffer::(anonymous namespace)::ByteLengthUtf8(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
> 14: 0x1002435bf v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
> 15: 0x100242b01 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
> 16: 0x1002421a0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
> 17: 0x4449dfdbe3d
> 18: 0x4449df918d5
> error Command failed with signal "SIGABRT".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Steps to reproduce

1. Pull this branch https://github.com/Hongbo-Miao/hongbomiao.com/pull/169
2. Run `yarn install`

**Comment by dkontorovskyy** [comment]
Duplicate #564

**Comment by dkontorovskyy** [comment]
We are working on improving out protect flow.
Problem that we are heaving here is a big dependency tree issue.
I referenced your issue to the first one occurred, so whenever we solve it, you'll be notified

**Comment by Hongbo-Miao** [comment]
Thanks @dkontorovskyy , will track there!
