### ISSUE TITLE
Snyk test shows vulns from devDependencies

### ISSUE THREAD

**Issue by lirantal** [snyk/snyk#76]
- `node -v`:
v7.7.4
- `npm -v`:
4.1.2
- `snyk -v`:
1.28.1
- `yarn --version`:
0.18.1
- Command run:
snyk test
### Expected behaviour
Shouldn't show eslint and standardjs in the vuln report when running snyk test

Didn't expect eslint and standardjs packages to show up in the report as they are placed in `devDependencies` and the vuln report shows them as direct descendants of the project itself.

### Actual behaviour

```
Error: ✗ High severity vulnerability found on shelljs@0.6.1
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
- from: project1.0.0 > eslint@2.10.2 > shelljs@0.6.1
Fix: None available. Consider removing this dependency.

✗ High severity vulnerability found on shelljs@0.6.1
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
- from: project1.0.0 > standard@7.1.2 > eslint@2.10.2 > shelljs@0.6.1
Fix: None available. Consider removing this dependency.
```

### Steps to reproduce

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@lirantal thanks for reporting!

Can you share both `package.json` and `yarn.lock` for this project?  Maybe through support@snyk.io if you don't want to expose them publicly?

**Comment by lirantal** [comment]
Will do, thanks.

**Comment by lirantal** [comment]
@adrukh I deleted the yarn.lock file and re-installed and now I don't get the eslint and standardjs packages reported. I would say this is possibly related to how snyk reads and parses yarn.lock maybe (if it does that at all)?
