### ISSUE TITLE
sqlite3 inconsistent vulns offline vs. web site

### ISSUE THREAD

**Issue by remy** [snyk/snyk#77]
- `node -v`: v7.8.0
- `npm -v`: 4.2.0
- `snyk -v`: 1.29.0
- Command run: 

```
$ snyk test sqlite@latest # 👍 passes
$ snyk test # 👎 fails (against attached package.json)
```

package.json:

```json
{
  "main": "index.js",
  "dependencies": {
    "sqlite3": "^3.1.8"
  }
}
```

### Expected behaviour

For web site (or remote test) to also fail. It's actually because (I've just spotted), sqlite3 includes node-pre-gyp as a bundled dep (see reduced package.json from sqlite3):

```json
{
  "bundleDependencies": [
    "node-pre-gyp"
  ],
  "dependencies": {
    "nan": "~2.4.0",
    "node-pre-gyp": "~0.6.31"
  },
  "version": "3.1.8"
}
```

I'm guessing that Snyk online isn't (able to?) look at bundled deps. I only spotted this because I tried the wizard (rather than my original attempt to continuously upgrade).

Maybe if the dep fails during a local test, and you can see it's a bundled dep, it can say that on the test result - it took me a while to work out why just `npm install sqlite3@latest` wouldn't work when it looked fine online.

### Steps to reproduce

Use attached package and run `snyk test` - should fail as:

<img width="1036" alt="screen shot 2017-04-21 at 16 03 24" src="https://cloud.githubusercontent.com/assets/13700/25283708/9104fb6c-26ac-11e7-839c-5ac3bb4cfa84.png">

✌️ 

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by tkadlec** [comment]
Hey @remy! Sorry for the radio silence.

You're right—it's the bundled dependency that's the issue here. It's a known issue on our end. We'll update here when we get a fix out.
