### ISSUE TITLE
Unable to use snyk-cli:python3 with Pipfile-based projects.

### ISSUE THREAD

**Issue by jonapich** [snyk/snyk#786]
I have a project with a `Pipfile` and a `Pipfile.lock`. It is correctly detected and analyzed with `snyk test` or `snyk monitor` commands from the root of my repo.

But the following won't work:
```
docker run -e SNYK_TOKEN=<redacted> -v $PWD:/project snyk/snyk-cli:python-3 test
```
It will say: `ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/project/requirements.txt'`

I tried to specify `--file=Pipfile` and the process will exit with a `please run pipenv update` message...

I was able to work around the issue by providing a requirements.txt instead, for the time being.

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/pull/925

**Comment by lili2311** [comment]
👋 @jonapich we have released the Pipfile support now, the images are currently building and will be available for download shortly. Please give it a try and let me know if I can close this
