### ISSUE TITLE
Add a deprecation notice for Node 6 if user is using 6

### ISSUE THREAD

**Issue by lili2311** [snyk/snyk#787]
- `node -v`:
- `npm -v`:
- `snyk -v`:
- Command run:

### Expected behaviour
Node 6 is EOL, add a warning at the end of each command to let the user know that this will soon be deprecated.

'Node.js 6 is approaching End-of-Life please upgrade your version. We will soon be dropping support for it.' (TODO: wording may change)

An external contribution for this would be amazing! This is a small task that can be done standalone.

**Comment by YashdalfTheGray** [comment]
@lili2311 I can take this on. Can you assign this to me?

**Comment by lili2311** [comment]
Great thank you :)
