### ISSUE TITLE
snyk wizard includes devDependencies

### ISSUE THREAD

**Issue by edrpls** [snyk/snyk#79]
- `node -v`: v6.10.2
- `npm -v`: 3.10.10
- `yarn version`: 0.19.1
- `snyk -v`: 1.29.0
- Command run: snyk wizard

### Expected behaviour
Snyk should only include vulnerabilities for dependencies listed on the "dependencies" configuration of package.json, not the ones on "devDependencies"

### Actual behaviour
Snyk includes vulnerabilities from devDependencies, when trying to fix these automatically, yarn returns the error: `error This module isn't specified in a manifest.`

    // package.json
      "dependencies": {
        "body-parser": "1.17.1",
        "clean-css": "^4.0.7",
        "connect-busboy": "^0.0.2",
        "epilogue": "^0.7.0",
        "express": "4.15.2",
        "express-jwt": "^5.0.0",
        "image-size": "^0.5.0",
        "multer": "^1.2.0",
        "snyk": "^1.29.0"
      },
      "devDependencies": {
           "nyc": "^10.0.0",
           "babel-plugin-istanbul": "^4.0.0"
      }

     // snyk wizard output
    ? Medium severity vuln found in brace-expansion@1.1.6, introduced via istanbul-lib-report@1.0.0-alpha.3
    - desc: Regular Expression Denial of Service (ReDoS)
    - info: https://snyk.io/vuln/npm:brace-expansion:20170302
    - from: istanbul-lib-report@1.0.0-alpha.3 > rimraf@2.5.4 > glob@7.1.1 > minimatch@3.0.3 > brace-expansion@1.1.6
      Remediation options Ignore
    ? [audit] Reason for ignoring vulnerability? Test dep

    ? Medium severity vuln found in brace-expansion@1.1.6, introduced via istanbul-lib-source-maps@1.1.0
    - desc: Regular Expression Denial of Service (ReDoS)
    - info: https://snyk.io/vuln/npm:brace-expansion:20170302
    - from: istanbul-lib-source-maps@1.1.0 > rimraf@2.5.4 > glob@7.1.1 > minimatch@3.0.3 > brace-expansion@1.1.6
      Remediation options Ignore
    ? [audit] Reason for ignoring vulnerability? Test dep

    ? Medium severity vuln found in brace-expansion@1.1.6, introduced via spawn-wrap@1.2.4
    - desc: Regular Expression Denial of Service (ReDoS)
    - info: https://snyk.io/vuln/npm:brace-expansion:20170302
    - from: spawn-wrap@1.2.4 > rimraf@2.5.4 > glob@7.1.1 > minimatch@3.0.3 > brace-expansion@1.1.6
      Remediation options Ignore
    ? [audit] Reason for ignoring vulnerability? (Non prod dep)

    // npm list istanbul-lib-report
       ├── istanbul-lib-report@1.0.0-alpha.3  extraneous
       └─┬ nyc@10.1.2
            └── istanbul-lib-report@1.0.0-alpha.3

    // npm list istanbul-lib-source-maps
      ├── istanbul-lib-source-maps@1.1.0  extraneous
      └─┬ nyc@10.1.2
           └── istanbul-lib-source-maps@1.1.0

    // npm list spawn-wrap
     ├─┬ nyc@10.1.2
     │ └── spawn-wrap@1.2.4
     └── spawn-wrap@1.2.4  extraneous

### Steps to reproduce
run `snyk wizard` with nyc as a devDependency?

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by deebugger** [comment]
This issue has been resolved in version 1.31.1 of the Snyk CLI tool.
To upgrade, simply run 'npm install -f snyk'.

**Comment by adrukh** [comment]
@edrpls in addition to the fix mentioned above, please note that extraneous dependencies may not play nicely with `snyk wizard` right now. See #86 for more details. The short story is to run `npm prune` to get rid of extraneous dependencies, or `yarn add dep-name` to add them as first-class citizens of your `package.json` file.

**Comment by adrukh** [comment]
A fix has been released with snyk@1.33.1, see #86 

I'm closing this issue for now, please comment on #86 with further input.
