### ISSUE TITLE
Can't install the latest version of snyk

### ISSUE THREAD

**Issue by IgorSasovets** [snyk/snyk#796]
- `node -v`: v8.11.3
- `npm -v`: 6.11.3
- `snyk -v`: 1.230.5
- Command run: npm install snyk --save

### Expected behaviour
snyk is successfully installed

### Actual behaviour
installation error. Error stack trace is listed below:
```
npm install snyk --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm ERR! 404 
npm ERR! 404  'https-proxy-agent-snyk-fork@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'proxy-agent'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

### Steps to reproduce
Please run the following command:
```
npm install snyk --save
```

---

debug info
```
 http fetch GET 304 https://registry.npmjs.org/http-proxy-agent 77ms (from cache)
npm http fetch GET 404 https://registry.npmjs.org/https-proxy-agent-snyk-fork 1074ms
npm http fetch GET 404 https://registry.npmjs.org/https-proxy-agent-snyk-fork 844ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 9189ms
npm verb stack Error: 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm verb stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
npm verb stack     at <anonymous>
npm verb stack     at process._tickCallback (internal/process/next_tick.js:188:7)
npm verb statusCode 404
npm verb pkgid https-proxy-agent-snyk-fork@*
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "snyk" "--save" "--verbose"
npm verb node v8.11.3
npm verb npm  v6.11.3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm ERR! 404 
npm ERR! 404  'https-proxy-agent-snyk-fork@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'proxy-agent'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
npm timing npm Completed in 10074ms
```

**Comment by lili2311** [comment]
👋 We have a fix ready to go out very shortly, will post an update once it's out.

**Comment by IgorSasovets** [comment]
Hello, @lili2311 ! Thank you for the updates!)

**Comment by lili2311** [comment]
Issue is now resolved, please try the latest version of the cli 1.230.6

**Comment by andyjk15** [comment]
Can confirm this is working for me

**Comment by IgorSasovets** [comment]
@lili2311 , now it works without any errors. Thank you!

**Comment by nothingrandom** [comment]
Not sure if this ought to be this issue or a new one, but I can't currently upgrade snyk globally or in any of my repos.

```
yarn global upgrade snyk
yarn global v1.17.3
[1/4] 🔍  Resolving packages...
error "proxy-agent-3.1.0.tgz": Tarball is not in network and can not be located in cache (["/Users/benjamin/.config/yarn/global/proxy-agent-3.1.0.tgz","/Users/benjamin/Library/Caches/Yarn/v4/.tmp/1cb65d53db120924735197f89834781e/.yarn-tarball.tgz"])
```

**Comment by lili2311** [comment]
> Not sure if this ought to be this issue or a new one, but I can't currently upgrade snyk globally or in any of my repos.
> 
> ```
> yarn global upgrade snyk
> yarn global v1.17.3
> [1/4] 🔍  Resolving packages...
> error "proxy-agent-3.1.0.tgz": Tarball is not in network and can not be located in cache (["/Users/benjamin/.config/yarn/global/proxy-agent-3.1.0.tgz","/Users/benjamin/Library/Caches/Yarn/v4/.tmp/1cb65d53db120924735197f89834781e/.yarn-tarball.tgz"])
> ```

@nothingrandom  do you know what version it is trying to grab? What OS is this on as well please?

**Comment by lili2311** [comment]
Seems related https://github.com/yarnpkg/yarn/issues/6108

**Comment by nothingrandom** [comment]
Trying to get the latest version. macOS Mojave. I will see if it is related to that other issue now :)

**Comment by lili2311** [comment]
I'm also looking why yarn is not happy with the bundledDependencies

**Comment by UlanaXY** [comment]
> 
> 
> Not sure if this ought to be this issue or a new one, but I can't currently upgrade snyk globally or in any of my repos.
> 
> ```
> yarn global upgrade snyk
> yarn global v1.17.3
> [1/4] 🔍  Resolving packages...
> error "proxy-agent-3.1.0.tgz": Tarball is not in network and can not be located in cache (["/Users/benjamin/.config/yarn/global/proxy-agent-3.1.0.tgz","/Users/benjamin/Library/Caches/Yarn/v4/.tmp/1cb65d53db120924735197f89834781e/.yarn-tarball.tgz"])
> ```

I have the same issue on Windows 10 using yarn, npm seems to work fine.

**Comment by lili2311** [comment]
@UlanaXY @nothingrandom please can you try `yarn add snyk@1.230.6-rc4`, works for me on `npm` & `yarn` so will be releasing as a version shortly

**Comment by JoaoBGusmao** [comment]
install using yarn working again.

**Comment by lili2311** [comment]
Thank you everyone for confirming, I would like to give an update to what happened:

`A vulnerability was discovered in one of our CLI’s transitive dependencies, which did not have an available fix. We manually patched the dependency in question, however the way we consumed the patched version caused install issues in some customer environments. We have now bundled the patch directly into our CLI, which addresses the issues.

Version 1.230.7 is available now from https://www.npmjs.com/package/snyk and https://github.com/snyk/snyk/releases/tag/v1.230.7`

**Comment by UlanaXY** [comment]
@lili2311 `snyk@1.230.6-rc4` solved the problem for me.

**Comment by nothingrandom** [comment]
Fantastic, that's sorted the issue for me!

**Comment by ebaioni** [comment]
I'm getting the following error:
npm install
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for https-proxy-agent-snyk-fork

**Comment by lili2311** [comment]
@ebaioni is the lates version of snyk not fixed for you? Please can you verify the command you run and what version of snyk you are trying to install?

**Comment by rbjoshi** [comment]
@lili2311 
I am getting the above error:

> npm ERR! code ENOVERSIONS
> npm ERR! No valid versions available for https-proxy-agent-snyk-fork
> 

and the log file contains

> 2 info using npm@6.9.0
> 3 info using node@v10.16.2
> 4 verbose npm-session e3c0274ec2b05b1f
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 304 http://registry.npmjs.org/https-proxy-agent-snyk-fork 135ms (from cache)
> 8 silly fetchPackageMetaData error for https-proxy-agent-snyk-fork@latest No valid versions available for https-proxy-agent-snyk-fork
> 9 timing stage:rollbackFailedOptional Completed in 1ms
> 10 timing stage:runTopLevelLifecycles Completed in 1605ms
> 11 verbose type tag
> 12 verbose stack https-proxy-agent-snyk-fork: No valid versions available for https-proxy-agent-snyk-fork

**Comment by joeholdcroft** [comment]
@rbjoshi Could you try upgrading to the latest version of `snyk` (1.237.0) and see if this fixes your issue?
