### ISSUE TITLE
missing node_modules directory

### ISSUE THREAD

**Issue by dottodot** [Snyk/snyk#8]
Just tried to use this on a sailsjs app and I get the following error when running `snyk wizard`

```
This directory looks like a node project, but is missing the contents of the node_modules directory.
Please run `npm install` and re-run your snyk command.
```

However there is a node_modules directory

**Comment by remy** [comment]
Thanks for the feedback. There's some tests we run to try to work out how to traverse the project.

If you're happy to post the details, can you post up the output of `find .` in the working directory, or you can email me directly at support@snyk.io - and possibly include your `package.json` file.

– Remy

**Comment by remy** [comment]
Hi, I realise this was raised last week, but I think I've finally found the source of the bug. I'm pushing a release in the next few business days to the CLI that refactors the logic around package resolution, and this specific issue should also be solved (I couldn't replicate from your package, but I was able to replicate today with a different environment and had the exact same issue).

**Comment by remy** [comment]
I've pushed a development build to npm that you can try out which, I believe should resolve the problem you were seeing. Again, this a dev build, so you should watch out for when we push the stable build too (expected 1.9.0).

If you run `npm install -g snyk@dev` you'll get snyk@1.9.0-alpha3. If you could try that out on your project and let me know how you get on.

Thanks so much.

**Comment by vlinder** [comment]
The snyk@1.9.0-alpha3 release works for me. The regular npm release didn't. Thanks! :)

**Comment by dottodot** [comment]
snyk@1.9.0-alpha3 is working for me too. Thanks

**Comment by remy** [comment]
This is all live on snyk@1.9.x now (outside of the dev release). Thanks all for the feedback.
