### ISSUE TITLE
local project config

### ISSUE THREAD

**Issue by scoch** [snyk/snyk#80]
Hi,

Is there any way to share some common config on a local project level, much like .eslint, config.js, etc?

I'd like to share the below throughout the team without having to rely on a per person basis and contain it to just the selected projects:

    	"disable-analytics": "1"

.snyk only seems to contain policy content and I wasn't sure of the impact it would have messing about with it.

Thanks,
Steven

**Comment by adrukh** [comment]
@scoch as you pointed out, the `.snyk` policy file is indeed for security policy purposes.

The `snyk` cli keeps its config in `~/.config/configstore/snyk.json`, where you can specify settings such as `"disable-analytics": "1"`. This is not being set per project right now, and may change in the future.

I'll pass this on to our product folks as an idea for more granular control of our cli.

**Comment by scoch** [comment]
Thanks for the reply and suggestion @adrukh. Apologies for the late reply too.
