### ISSUE TITLE
Change `prepublish` to `prepare`

### ISSUE THREAD

**Issue by AnandChowdhary** [snyk/snyk#801]
- `node -v`: 10.16.3
- `npm -v`: 6.9.0
- `snyk -v`: 1.228.5
- Command run: `npm publish` calls `prepublish`

### Expected behaviour
No warning

### Actual behaviour
npm shows a warning telling us that `prepublish` scripts are deprecated and we should use `prepare` instead.

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

Perhaps Snyk should append a `prepare` script instead of `prepublish` for `snyk protect`?

### Steps to reproduce
- Publish a package using npm v5+

**Comment by lili2311** [comment]
👋 Please could you confirm if your file already had a script before you run snyk-protect? We currently preserve whatever user is using but the default is indeed `prepare` https://github.com/snyk/add-to-package/blob/be91a3233ba333788d0252c856ceaa1e38ba16c6/lib/index.js#L85

we can look into migrating user scripts to `prepare` if we find `prepublish` but it may be suprising

**Comment by AnandChowdhary** [comment]
I'm closing this in light of your link. Perhaps I had a `prepublish` script before. If I'm able to reproduce this, I'll reopen this issue. Thanks for your help!
