### ISSUE TITLE
snyk >= 1.230 breaks code inside project, project unit tests fail

### ISSUE THREAD

**Issue by ericblade** [snyk/snyk#802]
- `node -v`: 12.0.0
- `npm -v`: 6.9.0
- `snyk -v`:
- Command run: npm run test

### Expected behaviour
Tests in project should complete

### Actual behaviour
Tests in project fail to run

### Steps to reproduce
```
git clone https://github.com/ericblade/quagga2.git
cd quagga2
npm install
npm build
npm run test
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

Something that 1.230+ does to the code is causing most of the tests to fail. Pinning to 1.229.0.

**Comment by lili2311** [comment]
👋 Please take a 👁 here: https://github.com/snyk/snyk/issues/796 and try the suggested Snyk version

**Comment by rowanbeentje** [comment]
Could you try updating `npm` and see if that also fixes it for you? I've been trying to track down some failed installs with recent versions of Snyk - 1.232.0 now in our case - and it seems the projects failing are using an old Lambda setup of node@8.10 and npm@5.6.0.  We get all sorts of weird install failures there now where installing once seems to work, but generates either invalid package locks (shrinkwraps in those days!) which then break subsequent installs, or complain about:

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for https-proxy-agent-snyk-fork
```

Using a more modern version of npm seems to work.

[Snyk's `engines` notation](https://github.com/snyk/snyk/blob/master/package.json#L22) is `"node": ">=6"` - is this still intended to be the case?

In this case we'll try fixing by moving onto some more recent lambda setups, but that wasn't expected right now :)

**Comment by lili2311** [comment]
`Snyk's engines notation is "node": ">=6" - is this still intended to be the case?` we will be sunsetting Node 6 support soon as it is EOL

**Comment by rowanbeentje** [comment]
@lili2311 Just to clarify we are on node@8, but I think it's the initial npm@5.6.0 that came with that which is breaking the install, and "engines" doesn't specify a `npm` requirement :)

**Comment by lili2311** [comment]
`(git+commit hash URLs were particularly flaky in the npm@5 series but even quite a bit through 6, and I bet that's it)
` could be that it is indeed causing some other issues too :(

**Comment by ericblade** [comment]
Not having installation problems. It's literally breaking the code.  The package builds just fine, but it doesn't work right.

**Comment by rowanbeentje** [comment]
I understand - sorry, I thought it was the patching process that was at fault here and that it might be related to some of the node_modules file loss I was seeing. Will split that out to a separate ticket.

**Comment by ericblade** [comment]
I updated the title to be more clear, sorry. :-)

**Comment by ericblade** [comment]
1.231 and 1.232 also fail, greenkeeper i believe will continue to attempt to update it every release until it succeeds.

https://github.com/ericblade/quagga2/pull/51

**Comment by lili2311** [comment]
We are waiting for these 2 PRs to go in so we can go back to not bundling the dependency, this should revert back to old behaviour.

https://github.com/TooTallNate/node-pac-proxy-agent/pull/22
https://github.com/TooTallNate/node-proxy-agent/pull/47

**Comment by lili2311** [comment]
Prs merged, waiting for the release of those packages

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by lili2311** [comment]
```npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for https-proxy-agent-snyk-fork```

Should be fixed in latest version. 

I am not sure how you are using snyk for it to affect the tests 🤔 This is the change between those two versions: https://github.com/snyk/snyk/commit/7802663a8dbe9a6e1e113aec4a806a04a582da87

I don't see anything that could be responsible, very strange!

**Comment by ericblade** [comment]
I'm not having a package installation issue.  It appears that something in the Snyk applied patches is causing the code to break.

**Comment by lili2311** [comment]
I see! What happens if you try:
- remove this https://github.com/ericblade/quagga2/blob/7e4be307acfd4560ab937a89fdcdb02a660625e5/package.json#L60
- trash `node_modules`
- reinstall

Do the tests pass?

(essentially disabling `snyk protect`) This will give a clue as to whether it is something to do with that or now

**Comment by ericblade** [comment]
@lili2311 test results https://github.com/ericblade/quagga2/pull/55 .. everything passes.

**Comment by ericblade** [comment]
Just letting you know, with 3 weeks of consistent failure to fix a problem where snyk is actively altering code into a non-functional state, I have decided to remove it from my projects. Once I commit that removal from the quagga2 project, autobuilds when snyk updates will no longer occur.  If you come up with a change that might solve the problem, I might be able to restore it's use in a test-build, but i'm probably not likely to return to using snyk across the board in my projects.

**Comment by lili2311** [comment]
Hi @ericblade this issue is tracked in our internal issue tracker, we are continuing to investigate further to help identify the problem. Unfortunately we have not yet been able to identify what could be causing this issue you are seeing, please stay tuned for updates. Sorry that you had to remove snyk from the project :( Hopefully we can get to the bottom of this soon.

**Comment by jjmschofield** [comment]
We’re sorry we haven’t been able to get back to you with any fixes sooner. We are actively working on this and have been struggling to replicate your experiences on our side. 

When we set the version of snyk to 1.231.1 as in your PR https://github.com/ericblade/quagga2/pull/51 we do begin to receive test failures.

I notice that when running under the latest version (1.239.5) that all tests pass successfully. I'm hopeful that updating to this version will solve your issue.

Additionally I notice that there is a patch for loadash in your `.snyk` policy which is likely no-longer needed having looked at your production dependencies.

I would suggest re-running `snyk wizard` from the CLI to regenerate the policy for you project.

You can do this as follows:

```
 $ rm .snyk 
$ npx snyk wizard 
```

**Comment by justshiv** [comment]
@ericblade we've created a PR to illustrate our findings here https://github.com/ericblade/quagga2/pull/56 

We have tested this out locally and now in the PR your tests pass for us as expected. 

We also looked into the greenkeeper PR you referenced and while it suggests the new versions to you, it does not appear to apply them if you don't explicitly agree to. This could be why it looked like the new versions of `snyk` were also failing your CI.

**Comment by ericblade** [comment]
Greenkeeper's PRs update the version information, and then the tests run via github.  

So, snyk at one point installed a fix, and should've removed it after the package got updated, it seems?  yeah i think i'm going to carry on without it, but I do really appreciate the help.
