### ISSUE TITLE
npm audit broken

### ISSUE THREAD

**Issue by vfedyk-lohika** [snyk/snyk#804]
- `node -v`: v10.16.3
- `npm -v`: 6.11.3
- `snyk -v`: 1.231.1
- Command run: npm audit

### Expected behaviour
Expecting report of npm audit subcommand.	

### Actual behaviour
npm throws an error like this:
```
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
npm ERR! audit The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2019-10-07T13_52_43_557Z-debug.log
```

### Steps to reproduce
```sh
cd /tmp && mkdir some-project && cd some-project && npm init -y
npm i snyk@latest
npm audit
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lwywoo** [comment]
Hi @vfedyk-lohika,

Thank you for letting us know. We are looking into the issue and will update here once we have more information.

Cheers,

Laura

**Comment by vfedyk-lohika** [comment]
@lwywoo how are you doing? What is the progress on that issue?

**Comment by lili2311** [comment]
@vfedyk-lohika 👋 One of the upstream libraries now has a patch, we are waiting on 2 more bumped versions from the libraries that consume it and can then revert back to using the patched library directly. npm audit seems to not be happy when using bundled deps :(

**Comment by lili2311** [comment]
https://github.com/TooTallNate/node-proxy-agent/pull/47
https://github.com/TooTallNate/node-pac-proxy-agent/pull/22

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by vfedyk-lohika** [comment]
@lili2311 it works now. Tested with 1.237.1.
Thanks!
