### ISSUE TITLE
snyk >=1.230.5 no longer works with npm 5.6.0

### ISSUE THREAD

**Issue by rowanbeentje** [snyk/snyk#805]
- `node -v`: 8.10.0
- `npm -v`: 5.6.0
- `snyk -v`: 1.232.0
- Command run: `npm i`

This is a slight variant of https://github.com/snyk/snyk/issues/796 . 1.230.5 breaks installs as described there; on more recent versions including 1.232.0, snyk appears to be installed correctly, but the *next* time a `npm install`-type command is run, the node_modules structure is broken including missing proxy-agent files and snyk itself refusing to execute because it can't find proxy-agent.

This is without running `snyk protect`, so I'm not sure at what stage it's breaking.

We found this when using a node 8 lambda image on circleci, which uses npm 5.6.0.  Updating to the most recent version of npm avoids this problem, so there's an obvious workaround! Also reproduced locally with a downgrade to npm@5.6.0 (and also npm@5.8; works with npm@5.10 and above).

### Expected behaviour
Running `npm i` multiple times under supported npm versions should produce a node_modules installation unaffected by snyk.

### Actual behaviour
Running `npm i` multiple times in npm 5.6.0 results in a broken node_modules on the second run.

### Steps to reproduce
(Using nvm or global installs to get npm@5.6.0, then...)
1) In an empty folder, `npm init` with defaults
2) `npm install --save snyk@1.232.0`
3) `npm install`
This results in an error.

**Comment by rowanbeentje** [comment]
(I initially wrongly thought this was similar of https://github.com/snyk/snyk/issues/802 but it appears to be different, so have split it out from comments there!)

**Comment by lili2311** [comment]
We are waiting for these 2 PRs to go in so we can go back to not bundling the dependency, this should revert back to old behaviour.

https://github.com/TooTallNate/node-pac-proxy-agent/pull/22
https://github.com/TooTallNate/node-proxy-agent/pull/47

**Comment by lili2311** [comment]
The PRs have been merged, waiting for a new release

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by lili2311** [comment]
Haven't heard back from you for a little while, going to close this issue as it is working for everyone else. But please do re-open if you see any issues.
