### ISSUE TITLE
npm install fails with: "ENOENT: no such file or directory, rename"

### ISSUE THREAD

**Issue by spilliton** [snyk/snyk#818]
- `node -v`: `v8.10.0`
- `npm -v`: `5.6.0`
- `snyk -v`: `1.234.2`
- Command run: `npm install`

### Expected behaviour

That npm install works after initial install of the snyk package.

### Actual behaviour

Installing `snyk` works, but the next time I run `npm install` in a fresh project it explodes with:

```
npm ERR! path /Users/zac/code/testsnyk/node_modules/snyk/node_modules/proxy-agent/node_modules/ast-types
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/zac/code/testsnyk/node_modules/snyk/node_modules/proxy-agent/node_modules/ast-types' -> '/Users/zac/code/testsnyk/node_modules/snyk/node_modules/proxy-agent/node_modules/.ast-types.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zac/.npm/_logs/2019-10-11T22_12_43_780Z-debug.log
```

In addition, when looking at the `package-lock.json` for snyk it has a really weird looking entry for `proxy-agent`:

```
"proxy-agent": "file:../../../../home/travis/build/snyk/snyk/proxy-agent-3.1.0.tgz",
```

### Steps to reproduce

```
mkdir testsnyk
cd testsnyk
npm init -f
npm install snyk
npm install
```

**Comment by lili2311** [comment]
Linked:
https://github.com/TooTallNate/node-pac-proxy-agent/pull/22
https://github.com/snyk/snyk/issues/802
https://github.com/snyk/snyk/issues/805

**Comment by lili2311** [comment]
The PRs have been merged, waiting for a new release

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by spilliton** [comment]
LGTM!  Thanks for fixing :)
