### ISSUE TITLE
Add gradle support

### ISSUE THREAD

**Issue by schwer** [snyk/snyk#82]
I'd really like to see gradle support. The project I'm working on has both nodejs and java dependencies, and converting to a pom.xml is not easily done.

**Comment by adrukh** [comment]
@schwer we are actively working on gradle support, will update once we have something viable!

In the meantime, the shortest path from build.gradle to pom.xml that we found is documented here - https://snyk.io/docs/snyk-for-java#using-snyk-with-gradle-managed-projects

**Comment by deebugger** [comment]
Hi @schwer - we have just released our support for Gradle projects in the Snyk CLI. If you update the Snyk CLI tool (just run 'npm install -g snyk'), you'll be able to test and monitor Gradle projects.

Let us know how it goes!

**Comment by partyzan** [comment]
With regards to Gradle support, I notices it only uses dependencies from build.gradle in the current folder. In our case there are multiple sub projects each with their own dependencies, is it possible to run snyk recursively on all sub projects  ?

**Comment by adrukh** [comment]
@partyzan you can specify which file to test either by running `snyk test --file=path/to/build.gradle`, or by running `snyk test` in the path of the `gradle.build` file you want to test.
