### ISSUE TITLE
RHEL OS Support, not for RHEL7.7 yet?

### ISSUE THREAD

**Issue by endwall** [snyk/snyk#823]
Does snyk support RHEL 7.7 yet? Is it a concern for snyk to test against RHEL7.7 docker image?

- `node -v`: 6.10.2
- `npm -v`: 3.10.10
- `snyk -v`: 1.235.1
- Command run:
snyk test
So it is run against a RHEL 7.7 base docker image. 
### Expected behaviour
Vulnerabilities are reported as normal, however there is one extra message

### Actual behaviour
The extra message is "We do not yet support your target OS version (rhel:7.7), but will in the future." 

### Steps to reproduce
snyk test against any RHEL 7.7 base image

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by ivanstanev** [comment]
Hi @endwall!
Snyk does not currently support RHEL (the enterprise version), we have vulnerability information for RPM package manager distros like RHOS (the open-source version). We are also looking to add more support for CentOS and Fedora in the near future.

Like the message "we do not yet support your target OS version" suggest, I would advise not to trust any vulnerability information reported for RHEL as RHEL is not yet supported!

**Comment by karniwl** [comment]
Hi @endwall thanks for raising this issue, it's currently being fixed. Can you share the specific image name you tested and a few of the vulnerabilities from the output?

**Comment by karniwl** [comment]
@endwall glad to update we now fully support `RHEL` OS for `RHEL:8`, `RHEL 7`, `RHEL 6`, `RHEL 5`. I'm closing the issue now, please reopen it if needed. Thank you!
