### ISSUE TITLE
Security Vulnerability detected

### ISSUE THREAD

**Issue by abhisekpaul** [snyk/snyk#824]
- `node -v`:
- `npm -v`:
- `snyk -v`:
- Command run: npm audit

### Expected behaviour
0 vulnerabilities

### Actual behaviour
                      === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Machine-In-The-Middle                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ snyk                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ snyk > proxy-agent > https-proxy-agent                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1184                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Machine-In-The-Middle                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ snyk                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ snyk > proxy-agent > pac-proxy-agent > https-proxy-agent     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1184                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

### Steps to reproduce
run "npm audit"
there are 2 high severity vulnerabilities in there.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by matthew1534** [comment]
This is now fixed for us 🎉 Thanks 👍

**Comment by abhisekpaul** [comment]
yep, looks good. thanks.
