### ISSUE TITLE
npm install fails with: "ENOVERSIONS: No valid versions available for https-proxy-agent-snyk-fork"

### ISSUE THREAD

**Issue by flymecca** [snyk/snyk#827]
- `node -v`: `8.9.3`
- `npm -v`: `5.6.0`
- `snyk -v`: (package.json "^1.231.0" resolves to: `1.236.1`)
- `OS` - `Windows 10`
- Command run:
`npm install`

### Expected behaviour 
npm install correctly installs the snyk package and all dependencies.

### Actual behaviour
Install fails with:
````
error	21-Oct-2019 21:09:25	npm ERR! code ENOVERSIONS
error	21-Oct-2019 21:09:25	npm ERR! No valid versions available for https-proxy-agent-snyk-fork
````

### Steps to reproduce
package.json: `"snyk": "^1.231.0"`
_(example as in "requires" block of "@sentry/cli")_

Run the following command  
`npm install`

This appears to be the same issue reported as an unaddressed comment of [Issue #796 ](https://github.com/snyk/snyk/issues/796#issuecomment-541314867)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by joeholdcroft** [comment]
Hi @flymecca,

I'm having some trouble replicating this using the same environment and steps as you, but I suspect this is either something in your lockfile and/or local npm cache. Can you try the following steps for me:

1. Run `npm cache verify`
2. In your project directory, re-install the latest version of `snyk` by running `npm install snyk --save`

If this doesn't work, I'd suggest upgrading node & npm. Long term support for Node 8 ended at the start of this year, and it will reach end of life at the end of this year.

Please let me know if these steps solve the problem for you or not.

**Comment by flymecca** [comment]
Hi @joeholdcroft 

Thank you for responding.  cache verify did not change the result.  Unfortunately as these servers are shared across departments I don't have the luxury of updating without going through some channels so it's not an option at the moment.  I also don't have control over which of the servers will run the build during deployments, so any solution will ideally be controlled via the package which is pushed to these builds.

From one of the servers, I ran this command and saw this result which seems significant - perhaps this can give more confirmation of the problem:

`npm show https-proxy-agent-snyk-fork@* version
npm ERR! code E404
npm ERR! 404 Unpublished by omrilotan on 2019-10-04T12:03:24.174Z
npm ERR! 404
npm ERR! 404  'https-proxy-agent-snyk-fork' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

Do you get different results from that command?

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI 1.237.0?

**Comment by flymecca** [comment]
Excellent that did the trick!  Thanks for pointing out the new version.
