### ISSUE TITLE
npm dependency tree errors with snyk v1.236.1

### ISSUE THREAD

**Issue by pfefferf** [snyk/snyk#828]
- `node -v`: 10.16.0
- `npm -v`: 6.12.0
- `snyk -v`: 1.236.1

### Expected behaviour
No npm dependency tree errors.

### Actual behaviour
Using snyk v1.236.1 following npm dependency tree errors occur when executing "npm list":
_npm ERR! extraneous: esprima@4.0.1 C:\Users\user\Desktop\tmp_snyk\node_modules\snyk\node_modules\esprima
npm ERR! extraneous: inherits@2.0.4 C:\Users\user\Desktop\tmp_snyk\node_modules\snyk\node_modules\inherits
npm ERR! extraneous: type-check@0.3.2 C:\Users\user\Desktop\tmp_snyk\node_modules\snyk\node_modules\type-check_

This dependency errors leads to follow up problems, e.g. npm audit cannot be executed anymore, because it reports back that the dependency tree is not correct.

### Steps to reproduce
1) Create a package json with following content:
`{
    "version": "0.0.1",
    "devDependencies": {
        "snyk": "^1.236.1"
    }
}`

2) npm install

3) npm list 
=> error

4) npm audit --registry=https://registry.npmjs.org 
=> error

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
https://github.com/snyk/snyk/pull/829

**Comment by lili2311** [comment]
👋 Please could you try again with the latest version of the CLI `1.237.0`?

**Comment by pfefferf** [comment]
Thanks. Works fine.
