### ISSUE TITLE
ReDos

### ISSUE THREAD

**Issue by svipben** [snyk/snyk#83]
Hello,

snyk (https://snyk.io/test/npm/snyk) have 1 vulnerability which is `ms` package. In detailed paths it says `ms` version is `0.7.3`. When you go to the https://snyk.io/vuln/npm:ms:20151024 it says `ms` package have ReDos only with `0.7.0` version or below. How to understand this? Snyk have `0.7.3` version, not `0.7.0` or below :smile: 

This also happens to my own package which is using another lib which is using `ms`, but version are also higher than `0.7.0`.

**Comment by maban** [comment]
Hi! Thanks for reporting this 😀 
We're just looking into this at the moment and will get back to you when we have an update.

**Comment by adrukh** [comment]
Closing now that `ms@2.0.0` has propagated to all of our dependencies. https://snyk.io/test/npm/snyk is squeaky-clean!
