### ISSUE TITLE
Error "Cannot convert undefined or null to object" for empty .net project

### ISSUE THREAD

**Issue by IvanovNiko** [snyk/snyk#832]
- `node -v`: 8.12.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.237.1
- Command run:
snyk test --file=c:\Users\ivano\Source\Repos\ClassLibrary1.sln

### Expected behaviour
solution analyzed without errors

### Actual behaviour
Cannot convert undefined or null to object

### Steps to reproduce
1. Create empty .NET Framework class library project 
2. Build the project
3. Snyk run

Error: 
Testing c:\Users\ivano\Source\Repos\ClassLibrary1...

Cannot convert undefined or null to object
    at C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test\index.ts:197:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test\index.js:6:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3 

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by orkamara** [comment]
Hi @IvanovNiko - thanks for reaching out!!!!

Just to get some context - 2 questions:
1. Does this bug block you right now from using `snyk test`?
2. Does it happen only with an empty SLN file?

Thanks,
Or

**Comment by IvanovNiko** [comment]
Hi.

1. No, but i cann't to fully analuzy my production solution.
2. No. Solution is not empty and contains only one project with on empty class (no methods, properties, etc). I attached the test solution to bug before (see Repos.zip). It's a demo solution for reprodice the issue.
3. It's a very simple demo solution for reprodice the issue.

**Comment by orkamara** [comment]
Hi @IvanovNiko,

We fixed the problem on our new version (https://github.com/snyk/snyk/releases/tag/v1.239.4).
Please try and let us know :)

OrKa

**Comment by IvanovNiko** [comment]
Hi @orkamara.
The issue was fixed. 
Thank you.
But i have a new problem with message ### Cannot read property 'dependencies' of undefined
I am working wity making a simple sample to reproduce the issue.

**Comment by orkamara** [comment]
Hi @IvanovNiko,
Thanks so much for helping us!
Can we close this ticket right now? you can create a new issue when you have an example of how to recreate the problem...
