### ISSUE TITLE
"Error: Could not detect package manager for file" for empty .NET Framework project

### ISSUE THREAD

**Issue by IvanovNiko** [snyk/snyk#833]
- `node -v`:8.12.0
- `npm -v`:6.4.1
- `snyk -v`:1.237.1
- Command run:
snyk test --file=c:\Users\ivano\Source\Repos\ClassLibrary1\ClassLibrary1.csproj -d
### Expected behaviour
no errors

### Actual behaviour
C:\Users\ivano\Source\Repos>snyk test --file=c:\Users\ivano\Source\Repos\ClassLibrary1\ClassLibrary1.csproj -d
  snyk test { _: [ [Circular] ],
  file: 'c:\\Users\\ivano\\Source\\Repos\\ClassLibrary1\\ClassLibrary1.csproj',
  debug: true } +0ms
  snyk Failed to test 1 projects, errors: +0ms
  snyk error: Error: Error: Could not detect package manager for file: c:\Users\ivano\Source\Repos\ClassLibrary1\ClassLibrary1.csproj
    at C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test\index.ts:97:15
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test\index.js:6:65)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3 +23ms
Error:
Testing C:\Users\ivano\Source\Repos...

Error: Could not detect package manager for file: c:\Users\ivano\Source\Repos\ClassLibrary1\ClassLibrary1.csproj
    at C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\cli\commands\test\index.ts:197:19
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\commands\test\index.js:6:65)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  snyk analytics { args:
   [ { file: 'c:\\Users\\ivano\\Source\\Repos\\ClassLibrary1\\ClassLibrary1.csproj',
       debug: true,
       org: undefined,
       showVulnPaths: 'some' } ],
  command: 'bad-command',
  metadata:
   { 'error-message': '\nTesting C:\\Users\\ivano\\Source\\Repos...\n\nError: Could not detect package manager for file: c:\\Users\\ivano\\Source\\Repos\\ClassLibrary1\\ClassLibrary1.csproj',
     error: 'Error: \nTesting C:\\Users\\ivano\\Source\\Repos...\n\nError: Could not detect package manager for file: c:\\Users\\ivano\\Source\\Repos\\ClassLibrary1\\ClassLibrary1.csproj\n    at C:\\Users\\ivano\\AppData\\Roaming\\npm\\node_modules\\snyk\\src\\cli\\commands\\test\\index.ts:197:19\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\ivano\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\commands\\test\\index.js:6:65)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:122:5)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/next_tick.js:181:9)\n    at Function.Module.runMain (module.js:696:11)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3',
     'error-code': undefined,
     command: 'test' },
  version: '1.237.1',
  os: 'Windows 10',
  nodeVersion: 'v8.12.0',
  id: 'e0d28ffe7919129d4c048ae8140b6759f9b1e2f9',
  ci: false,
  durationMs: 144 } +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 1316 +1ms
  snyk gzipped request body size: 572 +0ms
  snyk not using proxy +1ms

### Steps to reproduce
Create empty .NET Framework class library project (sample attached)
Build the project
Snyk run

[Repos.zip](https://github.com/snyk/snyk/files/3766845/Repos.zip)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 We currently do no scan the project files in the CLI. Please see the list of supported manifests here: https://snyk.io/docs/cli-test/

You should be able to run `snyk test` and let it auto detect or if you have an `sln` file or `obj/project.assets.json` then point to those.

**Comment by IvanovNiko** [comment]
Hi, @lili2311.

I read your mainfest and see following: "The CLI does not currently auto-detect .sln files, so for .NET and .NET Core projects you can specify in the --file parameter the location of the solution file and the CLI will run on all the projects it finds inside."

I passed my sln file in --file parameter and gave the issue described in this ticket.

**Comment by orkamara** [comment]
Hi @IvanovNiko,

As mentioned above, using --file, it's not possible to test a csproj, only sln file.
So you cannot run `snyk test --file=c:\Users\ivano\Source\Repos\ClassLibrary1\ClassLibrary1.csproj -d` but you can run `snyk test --file=c:\Users\ivano\Source\Repos\ClassLibrary1.sln`.

If your'e doing the second one, how is that different from https://github.com/snyk/snyk/issues/832?

Thanks,
Or

**Comment by IvanovNiko** [comment]
Hi @orkamara,
yes, if i will pass sln file instead of csproj it is no difference from  #832

**Comment by orkamara** [comment]
Great! closing this issue for now :)
