### ISSUE TITLE
CustomError: Could not detect supported target files in SnykDemoWinForm\SnykDemoWinForm.csproj

### ISSUE THREAD

**Issue by IvanovNiko** [snyk/snyk#841]
- `node -v`:8.12
- `npm -v`:6.4.1
- `snyk -v`:1.239.5
- Command run:
snyk test --file=SnykDemo.sln --json

### Expected behaviour
No errors. Success analyzing.

### Actual behaviour
CustomError: Could not detect supported target files in SnykDemoWinForm\SnykDemoWinForm.csproj.
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.
    at Object.NoSupportedManifestsFoundError (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\lib\errors\no-supported-manifests-found.ts:16:17)
    at Object.exports.updateArgs (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\lib\sln\index.ts:62:11)
    at C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:162:11
    at Generator.next (<anonymous>)
    at C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:5:12)
    at main (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js:147:12)
    at Object.<anonymous> (C:\Users\ivano\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:190:13)
    at Module._compile (module.js:653:30)

### Steps to reproduce
1. Unpack attached sample
2. in command line run: **snyk test --file=SnykDemo.sln --json**

Example attached 
[SnykDemo.zip](https://github.com/snyk/snyk/files/3788268/SnykDemo.zip)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by dkontorovskyy** [comment]
Hi @IvanovNiko.

This is error, cos we fail to find any suitable manifest files in project you specified. In order to show this error, cos maybe you specified something wrong we throw an error.
If you look into the link that @orsagie shared, `*.csproj` files are supported through importing your project from SCM (github, gitlab etc.)

Hope that helped.

**Comment by dkontorovskyy** [comment]
Can I close this issue or you need more help from us or maybe you have any suggestions?

**Comment by IvanovNiko** [comment]
Hi @dkontorovskyy.
My suggestion is show warning message and not failing the analyzing process. For example for that csproj will be empty results, because project is valid, but manifest is absent.

**Comment by lili2311** [comment]
@IvanovNiko we have just released in Beta 🎏 a new feature that allows to auto detect and scan multiple project & project types, it is available from version 1.275.0 and help text can be found here: https://github.com/snyk/snyk/pull/945/files.

It at the moment support npm, yarn, rubygems, maven and .Net is being released next. Please give it a try and share any feedback you may have. snyk test --all-projects --detection-level=2 for example to look 2 directories deep (current and 1 more). Both test & monitor are supported.

If 1 project fails it will keep going and scan the rest.

**Comment by lili2311** [comment]
@IvanovNiko  please confirm if this issue can now be closed and the feature above meets your needs?

**Comment by lili2311** [comment]
Closing as we have not heard back from you, please re-open if you would like to continue chatting on this.
