### ISSUE TITLE
Feature Request - Add JSON Output Support to Snyk Test

### ISSUE THREAD

**Issue by TommyJ1994** [snyk/snyk#85]
As per the title, this allows the results of vulnerability scans to be used in programs or consumed by applications like an issue tracker.

**Comment by tkadlec** [comment]
Hey @TommyJ1994! Actually, you're in luck—we already have JSON output support. If you run `snyk test --json`, you'll get the test results outputted in JSON format. I see that's missing from the documentation, so I'll make sure we get it added there.

**Comment by TommyJ1994** [comment]
![](https://media.giphy.com/media/xB1RqLGoBNh3W/giphy.gif)
