### ISSUE TITLE
core-js places advertisements on CLI

### ISSUE THREAD

**Issue by ebickle** [snyk/snyk#855]
- `node -v`: v10.17.0
- `npm -v`: 6.11.3
- `snyk -v`: 1.242.0
- Command run: `npm i -g snyk`

### Expected behaviour
Normal output from NPM during Snyk installation.

### Actual behaviour
Snyk CLI takes a dependency on the `core-js` library. During installation core-js places advertisements/spam asking for money onto the command line output. Consider dropping core-js in favor of alternatives. 

### Steps to reproduce
Install Snyk.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by dkontorovskyy** [comment]
Hey, @ebickle. 

I can give you a small workaround that might help you. `npm i --loglevel silent` that has been taken from https://github.com/zloirock/core-js/issues/548#issuecomment-493851570.

Hope that helped
