### ISSUE TITLE
Support Go modules on GitHub

### ISSUE THREAD

**Issue by stone-z** [snyk/snyk#866]
Hey Snyk, I would like to be able to use Snyk for Go module projects directly through your GitHub integration. I see in [this previous issue](https://github.com/snyk/snyk/issues/354) that there is interest, but I can't find whether this made it onto your roadmap. Do you have any plan/timeline to support this?

**Comment by gablaxian** [comment]
Hi @stone-z 

Go modules via SCM is on our roadmap, but we can't comment on when exactly it will be released as there are a few hurdles to overcome first. We are keeping a track of these requests and will let you know once it becomes available.

Thank you for your interest!

**Comment by ryancurrah** [comment]
Shouldn't this issue stay open until this is resolved? Would like to track this feature.

**Comment by jdbranham** [comment]
I _think_ this means it's supported now -  

https://support.snyk.io/hc/en-us/articles/360003817417-Snyk-for-Golang

**Comment by cooomma** [comment]
Um... probably there's something wrong with supporting Go module with the VSCode plugin.

VSCode Verison: 1.62.3 (Universal)
VSCode Plug-in Snyk Version: v1.2.1
OS: macOS Big Sur 11.6

Here is my VSCode Debug information:
```
[Info] Starting full scan
[Info] Snyk CLI version is up-to-date.
[Info] Open Source Security test started.
[Info] Running "/Users/paytonchan/.vscode/extensions/snyk-security.snyk-vulnerability-scanner-1.2.1/snyk-macos test /Volumes/workspace/some-api --json".
[Error] Open Source Security test failed for "/Volumes/workspace/some-api". Failed to test go modules project
```

But, it's normal when I am using the cli installed from brew:

```
/Volumes/workspace/some-api on  master ⌚ 15:44:12
$ snyk test . --json
{
  "vulnerabilities": [
    {
      "CVSSv3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "alternativeIds": [],
      "creationTime": "2020-07-30T13:33:31.283115Z",
      "credit": [
        "christopher-wong"
      ],
      "cvssScore": 7.5,
.....
}
```
