### ISSUE TITLE
Dependency issue in latest version

### ISSUE THREAD

**Issue by philkunz** [snyk/snyk#870]
Error: Cannot find module 'request'
54 Require stack:
55 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/request-promise-native/lib/rp.js
56 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/snyk-mvn-plugin/dist/jar.js
57 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/snyk-mvn-plugin/dist/index.js
58 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/lib/plugins/index.js
59 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/lib/snyk-test/run-test.js
60 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/lib/snyk-test/index.js
61 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/lib/index.js
62 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/lib/analytics.js
63 - /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/dist/cli/index.js
64     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
65     at Function.Module._load (internal/modules/cjs/loader.js:618:27)
66     at Module.require (internal/modules/cjs/loader.js:771:19)
67     at require (internal/modules/cjs/helpers.js:68:18)
68     at /usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/request-promise-native/lib/rp.js:8:12
69     at module.exports (/usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/stealthy-require/lib/index.js:62:23)
70     at Object.<anonymous> (/usr/local/nvm/versions/node/v12.8.1/lib/node_modules/snyk/node_modules/request-promise-native/lib/rp.js:7:15)
71     at Module._compile (internal/modules/cjs/loader.js:868:30)
72     at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
73     at Module.load (internal/modules/cjs/loader.js:731:32)
74   WARN ->  Something went wrong! Exit Code: 1

**Comment by lad475** [comment]
Seconded- also having this issue after installing the latest version

**Comment by Burnett2k** [comment]
Having the same problem at my workplace.  Causing lots of problems with our builds. Please let me know once this is resolved.

**Comment by dkontorovskyy** [comment]
@philkunz @lad475 @Burnett2k fix is on his way. Around 15 mins and fix will be released!

**Comment by philkunz** [comment]
It is the irony of life: The tool that is supposed to keep dependencies secure has a dependency issue...

btw. I just looked at snyk's dependency tree: http://npm.broofa.com/?q=snyk

It looks kinda bloated for what it does (tbh imho)...

**Comment by dkontorovskyy** [comment]
@philkunz @lad475 @Burnett2k Fix is released. Thanks for reporting and sorry for inconvenience  

https://github.com/snyk/snyk/pull/873#issuecomment-555628584

**Comment by tasadar2** [comment]
Will the docker images be updated soon as well? Namely `snyk/snyk-cli:nuget`.

**Comment by dkontorovskyy** [comment]
@tasadar2 we are currently working on that. I will update you ASAP

**Comment by Burnett2k** [comment]
thanks @dkontorovskyy . Just verified scans are working again.

**Comment by lili2311** [comment]
@tasadar2 please can you try the latest `snyk/snyk-cli:nuget` image?

**Comment by tasadar2** [comment]
@lili2311 Looks good now, thanks.
