### ISSUE TITLE
Request - Support for JSPM

### ISSUE THREAD

**Issue by TomFoyster** [snyk/snyk#88]
- `node -v`: v6.10.1
- `npm -v`: 3.10.10
- `snyk -v`: 1.34.3

### Expected behaviour
It would be excellent if Snyk could also check JSPM packages. These are managed via `jspm` commands rather than `npm`, but the dependency information is stored with `package.json` along with NPM's. 

The format is as so;

    {
       "name": "normal-contents",
       //etc
      "devDependencies": {
          "normal-dev-dependencies": "1.0.0"
      },
      "jspm": {
           "dependencies": {
               "list-of-jspm-deps": "npm:bar-foo@1.0.0"
           },
           "devDependencies": {
                "list-of-jspm-dev-dependencies": "github:bar-baz@1.0.0"
            }
        },
        "dependencies": {}
    }

Is it possible for Snyk to also work through these dependencies too? 

The format of the package name in the `devDependencies` and `dependencies` objects are as follows;

` "local-package-name": "registry:package-name@version"`

- `local-package-name` is of no concern to Snyk
- `registry` is the registry that contain this package. This is normally NPM or Github , but custom registries can be added in JSPM. In my opinion it's acceptable for Snyk only to check the most common registries.
- `package-name` is self explanatory
- `version` is also self explanatory

### Actual behaviour
N/A

### Steps to reproduce
N/A

**Comment by JackuB** [comment]
Hi, we are currently not planning to support JSPM in Snyk CLI and I'll be closing this issue. JSPM CLI was [sunset in June 2020](https://jspm.org/jspm-dev-release#sunsetting-the-cli), and by effect deprecating this "jspm" field approach.

> [Modules are resolved as URLs, with the package.json "dependencies" field used to determine version ranges of package dependencies. Node.js builtin imports like util are replaced with optimized Browserify library references.](https://jspm.org/#universal-module-semantics)
