### ISSUE TITLE
Override config at runtime

### ISSUE THREAD

**Issue by garethr** [snyk/snyk#880]
### Expected behaviour

Able to, for instance, specify `disableSuggestions` without needing to call a separate command first.

A good use case for this is described in https://github.com/snyk/actions/issues/3.

A common pattern for configuration like this in higher-level CLI frameworks is to support configuration loading from:

1. A global file
2. A local file
3. An ENV
4. a flag

Basically in order of increasing precedence.

### Actual behaviour

Everything relies on a file on disk, which can be manipulated by the `snyk config` commands or written by hand.

```console
$ cat ~/.config//configstore/snyk.json
{
        "disableSuggestions": "true"
}
```

**Comment by silvin-lubecki** [comment]
@garethr do you think you could prioritize this issue? I'd like to be able to disable the hints using env var, without tempering with the snyk config file. ping @nebuk89

**Comment by garethr** [comment]
@silvin-lubecki 👋  I'll ping the relevant team internally.

**Comment by garethr** [comment]
Looks like this is now supported as of https://github.com/snyk/snyk/pull/1332

@mladkau is this complete? If so we can probably close this issue.

**Comment by mladkau** [comment]
@garethr you are correct. From CLI version 1.376.0 onwards it is now possible to override any configstore value with an appropriate environment variable. For `disableSuggestions` it should be:

```
$ SNYK_CFG_DISABLESUGGESTIONS=true snyk test
```
