### ISSUE TITLE
snyk monitor --all-sub-projects does not monitor sub-projects

### ISSUE THREAD

**Issue by pkspks** [snyk/snyk#890]
- `node -v`: v12.12.0
- `npm -v`: 6.12.1
- `snyk -v`: 1.254.0
- `gradlew --version`: Gradle 5.0, Kotlin DSL:   1.0.4
- Command run:
`snyk monitor --all-sub-projects`
### Expected behaviour
Should upload for all subprojects.

### Actual behaviour
Only uploads for root. This is regression issue as it works on 1.251.0

### Steps to reproduce
1. Have a multi module gradle project.
2. `snyk auth`
3. `snyk test --all-sub-projects` . This actually tests all submodules and displays a report for each project
4. `snyk monitor --all-sub-projects` . This only uploads root project. Consequently no vulnerabilities are reported for sub projects.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by ivanstanev** [comment]
Thank you for raising this, we are looking into what caused the regression and will be releasing a fix soon!

**Comment by ivanstanev** [comment]
@pkspks Could you please try the newly released Snyk CLI https://github.com/snyk/snyk/releases/tag/v1.255.0 and let us know if that resolves your issue!

**Comment by pkspks** [comment]
@ivanstanev , can confirm it works 👍 This can be closed.
