### ISSUE TITLE
Failed authentication when installing Snyk through the CLI.

### ISSUE THREAD

**Issue by Neonz27** [snyk/snyk#898]
- Command ran: `snyk auth`

### Expected Behaviour
Authenticates the use of my Snyk account with the Snyk CLI.

### Actual Behaviour
Console prints out: "Authentication failed. Please check the API token on [https://snyk.io](https://snyk.io)"

### Steps To Reproduce
npm install -g snyk
snyk auth
*Click the authenticate button the website that the command links you to.*

----------------------------

Please note that I am using the newest LTS version of NodeJS and NPM installed on a Windows 10 machine. I have already upgraded and updated all packages to make sure that the problem was not on my end or due to any packages I may have installed on my machine. Also, I already have an account on Snyk that I made previously on the website if that information is of any importance to the developers or community working on this project.

**Comment by gitphill** [comment]
Hi, do you get presented with browser login page? CLI will also print a link like https://snyk.io/login?token=... that you can use if a browser window doesn't pop up automatically

**Comment by kyegupov** [comment]
Hi @Neonz27 ,
we are currently looking into the issue. Our current best guess is that your client IP address is different for the CLI and the browser page. This can be due to having IPv6 support in your internet connection. As a temporary workaround, please see if disabling IPv6 resolves the issue? https://medium.com/@JockDaRock/disabling-ipv6-on-network-adapter-windows-10-5fad010bca75

**Comment by odinn1984** [comment]
Hi @Neonz27 while we are looking into this issue I can suggest to try a workaround, you can supply the API  KEY through an environment variable, something like `SNYK_TOKEN=1234 snyk test` and when u define this environment variable it will use this as the API TOKEN.

You can get the API TOKEN itself from your account at snyk.io in the use profile settings.

Please try this as a workaround and tell me if that worked for you.

Also, did you try to run this on different machines or different versions of node? I ran it on my Mac OS X with LTS v12.13.0 and it worked fine... Do you have some sort of proxy configured on the browser maybe? Any additional information that you can provide about the environment you are running on will help a lot :)

Thank you!

**Comment by Neonz27** [comment]
The CLI did open a webpage, but it was not the login page. It was asking for permission to authenticate using my account information. I did try recreating the issue in a virtual machine. Unfortunately, I was not able to find any other versions of Node/NPM to try it with as all of my machines were already updated. The Linux version worked just fine, to begin with, but the Windows 10 VM did the exact same thing that my real machine did. I disabled IPV6 on my network adapter like **_kyegupov_** said, and it worked just fine afterward. My question now is should I leave IPV6 off? If I do what will it affect? I am using this network for web hosting, media transferring, and operating system virtualization.

**Comment by odinn1984** [comment]
@Neonz27 Hi, thanks for the reply! In general if you don't have any usage of IPv6 for internal networking or accessing sites that only support IPv6 (which I'm not sure that there are any today) it shouldn't affect anything. I will however open an issue with our dev team that is responsible for this product.

**Comment by mockupsjar** [comment]
+1

**Comment by nasifimtiazohi** [comment]
I am also running into the same issue. The CLI opened a page with an `authenticate` button but without any log in procedure. If I click the button it says authentication is successful on the webpage but the terminal gives error message that the authentication has failed.

I was able to run the `snyk tes`t through setting the `SNYK_TOKEN` environment variable though.

**Comment by dkontorovskyy** [comment]
From the version of CLI 1.330.0 (#1116) this should happen again

**Comment by konlanz** [comment]
> Hi @Neonz27 while we are looking into this issue I can suggest to try a workaround, you can supply the API KEY through an environment variable, something like `SNYK_TOKEN=1234 snyk test` and when u define this environment variable it will use this as the API TOKEN.
> 
> You can get the API TOKEN itself from your account at snyk.io in the use profile settings.
> 
> Please try this as a workaround and tell me if that worked for you.
> 
> Also, did you try to run this on different machines or different versions of node? I ran it on my Mac OS X with LTS v12.13.0 and it worked fine... Do you have some sort of proxy configured on the browser maybe? Any additional information that you can provide about the environment you are running on will help a lot :)
> 
> Thank you!

this worked for me thank you

**Comment by VitalyPanteleev** [comment]
To solve this trouble just make the authorization `docker --login --token "YOUR_SNYK_API_TOKEN"` before using `docker scan IMAGE_NAME` command. That token you can get from [Snyk account settings page](https://app.snyk.io/account). It works.

**Comment by digitalbalanceltd** [comment]
For anyone still having issues here, you can also generate an API key from your profile page on https://app.snyk.io/account, then run ```snyk auth <API_TOKEN>``` to authenticate without needing to login via the link.

Ref: https://support.snyk.io/hc/en-us/articles/360003812578-CLI-reference

**Comment by thomaswoj** [comment]
For anyone still having issues here, you can also generate an API key from your profile page on https://app.snyk.io/account, then run ```snyk auth <API_TOKEN>``` to authenticate without needing to login via the link.

Ref: https://support.snyk.io/hc/en-us/articles/360003812578-CLI-reference

**Comment by AntonDykyi** [comment]
> To solve this trouble just make the authorization `docker --login --token "YOUR_SNYK_API_TOKEN"` before using `docker scan IMAGE_NAME` command. That token you can get from [Snyk account settings page](https://app.snyk.io/account). It works.

This worked like a charm. Thanks!

**Comment by yejuns** [comment]
I also encountered the same problem, and then closed my proxy tool, and the authorization was successful.

**Comment by jeanjoe** [comment]
After reading this, I solved it by disabling my VPN from the browser

> Hi @Neonz27 ,
> we are currently looking into the issue. Our current best guess is that your client IP address is different for the CLI and the browser page. This can be due to having IPv6 support in your internet connection. As a temporary workaround, please see if disabling IPv6 resolves the issue? https://medium.com/@JockDaRock/disabling-ipv6-on-network-adapter-windows-10-5fad010bca75

**Comment by jeremy-chua** [comment]
i'm facing the same issue with vscode dev container.

I used  "snyk auth <API TOKEN> as a workaround

**Comment by katebygrace** [comment]
Seeing the same issue over here. Auth token was generated and pasted correctly

**Comment by endrelovas** [comment]
> To solve this trouble just make the authorization `docker --login --token "YOUR_SNYK_API_TOKEN"` before using `docker scan IMAGE_NAME` command. That token you can get from [Snyk account settings page](https://app.snyk.io/account). It works.

`docker scan --login --token "YOUR_SNYK_API_TOKEN"
`
Don't forget the scan

**Comment by MrBenGriffin** [comment]
CustomError: Not authorised at Object.AuthFailedError (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/errors/authentication-failed-error.ts:9:17) at Object.hasFeatureFlag (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/feature-flags/index.ts:37:11) at processTicksAndRejections (node:internal/process/task_queues:96:5) at test (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:62:8) at runCommand (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:51:25) at main (/snapshot/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:293:11) at /snapshot/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3 at Object.callHandlingUnexpectedErrors (/snapshot/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)

This was over PyCharm on MacOS 12.5

app.snyk.io stated "Your account has been authenticated. Snyk is now ready to be used."

**Comment by kobethuwis** [comment]
> @Neonz27 Hi, thanks for the reply! In general if you don't have any usage of IPv6 for internal networking or accessing sites that only support IPv6 (which I'm not sure that there are any today) it shouldn't affect anything. I will however open an issue with our dev team that is responsible for this product.



> I apologize for replying to you guys so late. I have been busy lately. The CLI did open a webpage, but it was not the login page. It was asking for permission to authenticate using my account information. I did try recreating the issue in a virtual machine. Unfortunately, I was not able to find any other versions of Node/NPM to try it with as all of my machines were already updated. The Linux version worked just fine, to begin with, but the Windows 10 VM did the exact same thing that my real machine did. I disabled IPV6 on my network adapter like **_kyegupov_** said, and it worked just fine afterward. My question now is should I leave IPV6 off? If I do what will it affect? I am using this network for web hosting, media transferring, and operating system virtualization.

Disabled IPV6 on the network adapter of my Windows 11 host and the authentication worked instantly for the WSL2 CLI in VS Code. Thanks @kyegupov
