### ISSUE TITLE
`docker-entrypoint.sh` outputs a parse error if the --json option is not present

### ISSUE THREAD

**Issue by raphiz** [snyk/snyk#899]
- `node -v`: v10.16.3
- `npm -v`: 6.9.0
- `snyk -v`: 1.230.0
- docker image: `snyk/snyk-cli:docker` (image id: `dd98a65b6b0a`)
- Command run: `docker run --rm -e SNYK_TOKEN=**** -v $PWD:/project snyk/snyk-cli:docker test --org=*** --docker myImage:version --file=Dockerfile`

### Expected behaviour

The same human readable output as when running the snyk cli outside of a docker container  (`snyk test --org=*** --docker myImage:version --file=Dockerfile`), for example:

```bash
Testing myImage:version...

Organization:      ***
Package manager:   rpm
Target file:       Dockerfile
Docker image:      myImage:version
Base image:        baseImage:version
Licenses:          enabled

✓ Tested 42 dependencies for known issues, no vulnerable paths found.
```

### Actual behaviour

Before the human readable output, a parse error from jq is printed. The script ends normally with an exit code 0.

```bash
parse error: Invalid numeric literal at line 2, column 8

Testing myImage:version...

Organization:      ***
Package manager:   rpm
Target file:       Dockerfile
Docker image:      myImage:version
Base image:        baseImage:version
Licenses:          enabled

✓ Tested 42 dependencies for known issues, no vulnerable paths found.
```

### Steps to reproduce

Run the command mentioned above using any docker image and version `docker run --rm -e SNYK_TOKEN=**** -v $PWD:/project snyk/snyk-cli:docker test --org=*** --docker myImage:version --file=Dockerfile`. The same happens when running `monitor` instead of `test` inside the docker container. The issue does only occur when using one of the docker images.

### Suspected Cause

The problem is probably in the [`docker-entrypoint.sh` script](https://github.com/snyk/snyk/blob/master/docker/docker-entrypoint.sh#L83) where the output of the synk command is forwarded into the `OUTPUT_FILE` (`snyk-result.json`). Later in the script, jq is used to parse data from that file. If the `--json` option is missing, that file contains non-json data resulting in the parse error.
It might be a good idea to [`set  -euo pipefail`](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/) in the bash script to prevent such "silent" failures in the future.

**Comment by odinn1984** [comment]
Hello! Thanks for submitting this bug report.
The images you are using were created mainly for an older version of our jenkins plugin and are meant to work with json output I apologise if that's unclear from our documentation.

However! we are developing a new set of images at https://github.com/snyk/snyk-images which are currently experimental and quite new, but it would be great if using the new set of images can solve the issues you are having with the current docker files.

Please let us know if that is a good solution for you or if you have any other questions.

**Comment by raphiz** [comment]
Hi, thanks for the update! I did not realize that the images were meant to work with json only, but apart from this error they do the job just fine :smile: .
I did try out the new images and for my case, it's working flawlessly. However, it would be great if they were stable and published on Docker Hub. Do you have a rough estimation when that might be?

**Comment by odinn1984** [comment]
@raphiz Good to hear that the new images are working fine for you! we are going to have a session about bringing those images to production early next month unfortunately I don't have a timeline of when we are going to make them official and publish them.

I will however pass the feedback to the product manager responsible for this and hopefully we will do it soon so that all of our users can enjoy a better experience!

Is there anything else we can help you with regarding this topic?

**Comment by raphiz** [comment]
Thank you, that sounds good to me. I suppose there is nothing else you can do for now regarding this topic.
