### ISSUE TITLE
exit status is 1 if there are no dependencies

### ISSUE THREAD

**Issue by libreninja** [Snyk/snyk#9]
We are trying to use snyk in our npm test scripts.  One of our projects does not, as of yet, have any dependencies in the package.json but our build still fails because snyk returns a non zero exit status.  We would like to see a fix for this, or at least an option to suppress this specific non-error error.

**Comment by remy** [comment]
Are you able to share the output from the snyk test? Or is it finding a vulnerable package in your deps?

**Comment by libreninja** [comment]
We are getting the tryDevDeps error: 'Snyk only tests production dependencies by default (**which this project had none**). Try re-running with the `--dev` flag.'

This happens because there currently are no dependencies.  Until one is added, there isn't even a "dependencies" property in our package.json.  However we proactively check for vulnerabilities during builds, as dependencies will surely be added in the future.

**Comment by remy** [comment]
Right, I see. This should actually be a warning, and in retrospect *not* exit(1). There's an update being released to the snyk cli in the next couple of working days, I believe this will already be addressed, but I'll make a specific test for this too.

Thanks for the feedback, and I'll post back here when it's live.

**Comment by libreninja** [comment]
Thanks!

**Comment by remy** [comment]
Just to let you know, I had intended to address this specifically, but somehow I managed to land a fix where if there are no production deps, then `snyk test` *does not* exit with an error code. So you should be all good now.

Thanks again for the report.
