### ISSUE TITLE
Snyk protect hangs and runs out of memory

### ISSUE THREAD

**Issue by tevko** [snyk/snyk#913]
- `node -v`: 8.11.3
- `npm -v`: 5.6.0
- `snyk -v`:  1.261.0
- Command run: snyk protect

### Expected behaviour
Snyk protect runs successfully

### Actual behaviour
Snyk fails with following error:

```
> snyk protect


<--- Last few GCs --->

[71394:0x102800c00]   125259 ms: Mark-sweep 1445.9 (1592.4) -> 1445.8 (1594.4) MB, 590.2 / 0.0 ms  allocation failure GC in old space requested
[71394:0x102800c00]   125996 ms: Mark-sweep 1445.8 (1594.4) -> 1445.7 (1538.4) MB, 737.0 / 0.0 ms  last resort GC in old space requested
[71394:0x102800c00]   126860 ms: Mark-sweep 1445.7 (1538.4) -> 1445.7 (1525.9) MB, 863.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3625803a5879 <JSObject>
    1: fromString(aka fromString) [buffer.js:314] [bytecode=0x3625e26d1fe1 offset=164](this=0x3625a2a822d1 <undefined>,string=0x362512e79369 <Very longstring[286506116]>,encoding=0x3625803b58e9 <String[4]: utf8>)
    2: from [buffer.js:177] [bytecode=0x3625e26d1ae9 offset=11](this=0x3625c40364f1 <JSFunction Buffer (sfi = 0x3625803fc461)>,value=0x362512e79369 <Very long string[286506116]>,encodi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out ofmemory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::(anonymous namespace)::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
12: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x1fa7108842fd
14: 0x1fa71093d1d6
✨  Done in 128.55s.
```

### Steps to reproduce

run `snyk protect`
---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
Hi @tevko! Sorry to hear you are having this issue, would you be able to share your package.json & lockfile please so we can investigate further? If this information is sensitive please email us the files to support@snyk.io.

**Comment by tevko** [comment]
Sending email now!

**Comment by heiditeq** [comment]
Seems like it could be the same as #603 #445 and also maybe #564 . I heard a fix was in progress last October (to migrate fix for #603 to snyk wizard to snyk protect). Can we get an update on that? Can't update react-scripts to get the latest security fixes because then I wouldn't be able to use snyk anymore...

**Comment by rberrelleza** [comment]
The same thing is happening to me in a go project that uses `go.mod` with no vendored dependencies (https://github.com/oketo/okteto).

**Comment by ahmedsajid** [comment]
@rberrelleza were you run `snyk monitor` since then?
I'm having the same issue with go project.

**Comment by rberrelleza** [comment]
@ahmedsajid I keep seeing the same issue on 1.305.0

**Comment by ahmedsajid** [comment]
@rberrelleza I tried the suggestion here https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory which worked for me.
`export NODE_OPTIONS=--max-old-space-size=8192`

**Comment by rberrelleza** [comment]
> export NODE_OPTIONS=--max-old-space-size=8192

@ahmedsajid I ran it with that and got a bunch of `Pkg: FLAGS_MISMATCH` errors, and then monitor failed with `413` error. `snyk test` seems to work though.

**Comment by ahmedsajid** [comment]
Try with ` --prune-repeated-subdependencies`
https://support.snyk.io/hc/en-us/articles/360001889797-Snyk-monitor-is-failing

**Comment by lili2311** [comment]
@tevko is this still an issue for you?

**Comment by lili2311** [comment]
@tevko 👋 did you get a chance to confirm if this is still an issue?

**Comment by tevko** [comment]
@lili2311 haven't noticed it lately, thanks for following up!

**Comment by lili2311** [comment]
Thanks @tevko I will close this issue, please raise again if it occurs.

**Comment by jpruiz114** [comment]
@lili2311, @tevko:

This is happening to one of my projects. We have used both the extra heap memory flag and the prune option, and it doesn't seem to be doing the trick.

```
export NODE_OPTIONS=--max-old-space-size=16384

snyk monitor --org=the-org-id --file="$package_json_file" --remote-repo-url="$repo_name" --project-name="$project_name" --prune-repeated-subdependencies --debug
```

Is there a documented workaround for this?

Thanks.
