### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by joelchen** [snyk/snyk#92]
- `node -v`: v8.1.2
- `npm -v`: 5.0.3
- `snyk -v`: 1.36.0
- Command run:
`snyk test --json > results.json`
### Expected behaviour
JSON of test results generated.

### Actual behaviour
```
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: 413
    at /usr/local/lib/node_modules/snyk/lib/snyk-test/npm/index.js:107:23
    at /usr/local/lib/node_modules/snyk/lib/request/index.js:12:7
    at tryCatch (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

### Steps to reproduce
As command run above.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.
```
  snyk test { _: [ [Circular] ], debug: true, json: true } +0ms
  snyk checking for cli updates +307ms
  snyk add local true +42ms
  snyk policies found [ '/Users/joel/Documents/web/Provider' ] +2m
  snyk add policies 1 +2ms
  snyk add packageManager npm +1ms
  snyk add packageName web-provider +0ms
  snyk add packageVersion 0.9.0 +0ms
  snyk add package web-provider@0.9.0 +0ms
  snyk add error-message 413 +2s
  snyk add error Error: 413
    at /usr/local/lib/node_modules/snyk/lib/snyk-test/npm/index.js:107:23
    at /usr/local/lib/node_modules/snyk/lib/request/index.js:12:7
    at tryCatch (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9) +1ms
  snyk add error-code 413 +0ms
  snyk add command test +0ms
  snyk { command: 'bad-command',
  snyk   args: [ { debug: true, json: true, packageManager: 'npm' } ],
  snyk   metadata:
  snyk    { local: true,
  snyk      policies: 1,
  snyk      packageManager: 'npm',
  snyk      packageName: 'web-provider',
  snyk      packageVersion: '0.9.0',
  snyk      package: 'web-provider@0.9.0',
  snyk      'error-message': '413',
  snyk      error: 'Error: 413\n    at /usr/local/lib/node_modules/snyk/lib/snyk-test/npm/index.js:107:23\n    at /usr/local/lib/node_modules/snyk/lib/request/index.js:12:7\n    at tryCatch (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:410:12)\n    at invokeCallback (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:425:13)\n    at publish (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:393:7)\n    at flush (/usr/local/lib/node_modules/snyk/node_modules/es6-promise/dist/es6-promise.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:95:7)\n    at process._tickCallback (internal/process/next_tick.js:161:9)',
  snyk      'error-code': 413,
  snyk      command: 'test' },
  snyk   version: '1.36.0',
  snyk   os: 'OS X',
  snyk   nodeVersion: 'v8.1.2',
  snyk   id: '4f78ed1cb02f2ca4fbd445b036893aa0eddcfbd7',
  snyk   ci: false } +11ms
```

**Comment by adrukh** [comment]
@joelchen thanks for reporting this!

The `413` code most likely means that the payload generated for our API is too large for our limits. Can you please share the output of `npm ls --json` as a gist or similar for us to inspect?

**Comment by joelchen** [comment]
@adrukh After removing node_modules and doing a `npm install`, I was able to run the command successfully. Since it is a different set of node_modules, I do not think running `npm ls --json` can get the problematic output now.

**Comment by adrukh** [comment]
Indeed... Thanks for updating!

**Comment by lebaz20** [comment]
I had the same issue, because i was using dependencies that already use snyk also,
So response was indeed massive,
The solution was using `--trust-policies` option,
As it avoids checking those dependencies, minimizing response size and fixing the 413 error

**Comment by outNapGnaw** [comment]
I had the same issue, because i was using 'cnpm' packageManager to install my work.
this is my node_modules folder list.
<img width="308" alt="wx20171228-094822 2x" src="https://user-images.githubusercontent.com/13870052/34397841-6ad6b3e0-ebb4-11e7-80cf-a55a534b49fc.png">
The total is 1,756. But half of them is **_shortcut_**.
<img width="214" alt="wx20171228-095525 2x" src="https://user-images.githubusercontent.com/13870052/34397931-40d47f90-ebb5-11e7-9aaa-a4ae5e5127a8.png">

How to solve this problem?

**Comment by adrukh** [comment]
@outNapGnaw make sure your `node_modules` folder contains the bare minimum (deleting and reinstalling is a common practice), and see if this reduces the payload size sufficiently.

**Comment by outNapGnaw** [comment]
@adrukh 
The file in the folder can not be deleted, and it will not be possible after reloading. Because of our country's network, in order to ensure the complete installation, I can only use the 'cnpm' to install my work. This is the result in the folder after  installed. So, I'd like to have a configuration that lets me ignore some folders .just like the folder's name contains `_@` .So, do you have this configuration?
