### ISSUE TITLE
Snyk should support maven wrapper mvnw

### ISSUE THREAD

**Issue by eddiewebb** [snyk/snyk#957]
- node -v
v10.18.0
- npm -v
6.13.4
- snyk -v
1.278.0
- Command run:
snyk test

### Expected behaviour
This maven project uses a pattern of embeddeding a  [maven wrapper](https://www.baeldung.com/maven-wrapper) pinned at a specific version in the repo instead of trusting each user to have mvn installed.  THis is dues a history of sharp API breaking changes in maven's life.  This is especially popular in the Spring community.

So instead of `mvn test` etc, we (or our CI) runs `./mwn test` etc.   Any everyone and all our machines work the same way ...  Dig?

I would expect a way to instruct snyk to use the same maven the rest of my build process does.

### Actual behaviour
`/bin/sh: 1: mvn: not found`

### Steps to reproduce

Run `snyk test` on a Maven project using the [maven wrapper](https://www.baeldung.com/maven-wrapper)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by eddiewebb** [comment]
As a workaround I just `ln -s mvnw /usr/local/bin/` so that `mvn` was found on the path. Perhaps that's well enough.

**Comment by orsagie** [comment]
Hi @eddiewebb version 1.292.0 supports mvnw, thanks to @sfat 🙏. Please give it a try and let us know of any feedback you have!
