### ISSUE TITLE
`snyk wizard` (arrow) keys don't work

### ISSUE THREAD

**Issue by fhemberger** [snyk/snyk#96]
- `node -v`: v8.1.0
- `npm -v`: 5.1.0
- `snyk -v`: 1.36.2
- Command run: `snyk wizard`

### Expected behaviour

Select action to take with cursor keys

### Actual behaviour

Arrow keys are not working, can't terminate process using Ctrl-C as well. Have to close terminal to end process. Tested in both zsh and bash on iTerm2 and macOS Terminal.

### Steps to reproduce

Execute command.

**Comment by darscan** [comment]
Hi @fhemberger 

I tried to reproduce the issue using the same versions listed above to no avail. I tested in `bash` using:

- iTerm2 Build 3.0.15
- macOS Sierra 10.12.5

(I didn't test in `zsh`)

Do you have any other Node-based interactive CLI tools you could try out in your environment?

**Comment by fhemberger** [comment]
I can use `n` or `npm-check` without any issues, they use keyboard navigation as well.

**Comment by JackuB** [comment]
Hi, this is an older issue, but I was unsuccessful replicating it with the latest Snyk CLI version, iTerm2 and ohmyzsh. I'm going to close this issue - if this is still occurring, please open a new one.
