### ISSUE TITLE
documentation error with Snyk CLI v1.278.1 help page

### ISSUE THREAD

**Issue by pierre-ernst** [snyk/snyk#967]
- `snyk -v`: 1.278.1
- Command run: snyk help file

### Actual behaviour
the help output seems to indicate that the file option is only available for the test command, whereas it seems to work for the monitor command as well.

### Expected behaviour
maybe show examples of both usage (test/monitor) in the help output

**Comment by aviadhahami** [comment]
@pierre-ernst Thank you for reporting this! :pray: 
Fixed in https://github.com/snyk/snyk/pull/968
