### ISSUE TITLE
Snyk vulnerability libraries

### ISSUE THREAD

**Issue by prasanthmeenapalli** [snyk/snyk#98]
Hi Team,

We are using synk vulnerability scans in our project. Recently we have encountered errors with snyk modules. PFB the paths which has vulnerability with npm modules used in snyk. Can you please provide the fix for the same.

snyk@1.36.2 > snyk-policy@1.7.1 > snyk-module@1.8.1 > debug@2.6.1 > ms@0.7.2

snyk@1.36.2 > snyk-policy@1.7.1 > snyk-resolve@1.0.0 > debug@2.6.1 > ms@0.7.2

snyk@1.36.2 > request@2.79.0 > tunnel-agent@0.4.3

Thanks in advance.

Regards
Prasanth.

**Comment by karenyavine** [comment]
Hey there,

Sorry for the delay in responding. 
This issue has since been fixed, closing.
