### ISSUE TITLE
Snyk release v1.290.1 breaks update check

### ISSUE THREAD

**Issue by ralish** [snyk/snyk#991]
- `node -v`: v12.14.1
- `npm -v`: 6.13.7
- `snyk -v`: 1.290.1
- Command run: `snyk`

### Expected behaviour
Update check is successfully performed.

### Actual behaviour
```
┌──────────────────────────────────────────────────────────┐
│                 snyk update check failed                 │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\xxx\.config │
└──────────────────────────────────────────────────────────┘
```

### Steps to reproduce
Just run `snyk`. Only tested on Windows but I expect it affects all platforms.

### Additional details
Appears to have been introduced by [v1.290.1](https://github.com/snyk/snyk/releases/tag/v1.290.1) which changed package dependencies to use the Snyk forks of `configstore` and `update-notifier`. The error returned per *Actual behaviour* is misleading.

The actual error being caught is:
```
Error: Cannot find module 'configstore'
Require stack:
- C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\node_modules\@snyk\update-notifier\index.js
- C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\dist\lib\updater.js
- C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\dist\cli\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at lazy (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\node_modules\import-lazy\index.js:2:51)
    at C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\node_modules\import-lazy\index.js:10:11
    at new UpdateNotifier (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\node_modules\@snyk\update-notifier\index.js:47:25)
    at module.exports (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\node_modules\@snyk\update-notifier\index.js:151:25)
    at Object.updateCheck (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\src\lib\updater.ts:29:20)
    at C:\Users\<redacted>\AppData\Roaming\npm\node_modules\snyk\src\cli\index.ts:153:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\<redacted>\\AppData\\Roaming\\npm\\node_modules\\snyk\\node_modules\\@snyk\\update-notifier\\index.js',
    'C:\\Users\\<redacted>\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\lib\\updater.js',
    'C:\\Users\\<redacted>\\AppData\\Roaming\\npm\\node_modules\\snyk\\dist\\cli\\index.js'
  ]
}
```

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by ralish** [comment]
Can confirm by downgrading to v1.290.0 the issue is no longer seen.

**Comment by orkamara** [comment]
:wave: @ralish - Thanks for reaching out. We're taking a look on that.

**Comment by orkamara** [comment]
@ralish - please try to reinstall snyk - that's suppose to fix the issue :)

**Comment by ralish** [comment]
@orkamara Not the case for me. It may be relevant that this is in the case of `snyk` being installed globally (i.e. via `npm i -g snyk`). Completely removing `snyk` using `npm un -g snyk`, then reinstalling still shows the issue. I've verified the `$APPDATA\npm\node_modules\snyk` folder has been removed prior to reinstalling.

**Comment by orkamara** [comment]
@ralish - thanks for the fast response - according to the logs seems like the `node_modules` folder is `C:\\Users\\<redacted>\\AppData\\Roaming\\npm\\node_modules` (not `$APPDATA\npm\node_modules\snyk`) - can you verify that this folder has been removed prior to reinstalling.

**Comment by ralish** [comment]
@orkamara I meant `$APPDATA` as equivalent to the `APPDATA` environment variable, so we're talking about the same location. I'm certain the folder was removed during earlier testing, but on testing again now I can't reproduce the issue. So I'm not sure what's going on ...

Happy to close this issue and I'll perform further testing if it resurfaces.

Cheers!

**Comment by orkamara** [comment]
Amazing :) Let us know if there are any more issues!
